### ISSUE TITLE
Running on Next.js 14 with App Router doesn't seem to allow for path based URLs

### ISSUE THREAD

**Issue by yoitsro** [marmelab/react-admin#10116]
**What you were expecting:**

As mentioned on https://marmelab.com/react-admin/Routing.html#using-a-custom-router, it should be possible to use a `BrowserRouter` when rendering server side pages.

react-admin should detect that we're already within a Router context and not try to implement the Hash router.

**What happened instead:**

Instead, the hash router is still used. So for instance, if I wanted to go to the users list, when I click the Users button in the menu, I get taken the `#/users`.

In the same way, when I go to `/users`, the URL changes to `/users#/users`.

**Steps to reproduce:**

1. Create a Next app as described on https://marmelab.com/react-admin/NextJs.html
2. Use the App router
3. Try to setup the app as per https://marmelab.com/react-admin/Admin.html#using-a-custom-router

**Environment**

* React-admin version: 5.1.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18
* Browser: Brave
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Unfortunately, react-admin isn't compatible with Next.js's AppRouter, and it can't be. This is because react-admin uses react-router, which itself isn't compatible with the Next router. That's why you have to use the HashRouter hen using Next.js. 

If you want to support server-side routing, you'll have to use Remix.
