### ISSUE TITLE
Feature Request: Allow Data Providers to return pre-fetched related records

### ISSUE THREAD

**Issue by athrawes** [marmelab/react-admin#10265]
**Is your feature request related to a problem? Please describe.**

Hello, I'm using a [JSON:API](https://jsonapi.org/) based backend. Quite frequently, this backend eagerly returns additional records related to the current request, anticipating that I might want to use these additional records immediately. However, there's not currently a way for my Data Provider to return these to the application, so these records are discarded only to be immediately re-fetched.

This feels like a wasted opportunity, where if I could return these related records from my data provider I could save several round trips to the API in some contexts (e.g. List pages with referenced records), as well as speeding up the render of many pages.

**Describe the solution you'd like**

Would it be possible to add an optional field to the Data Provider's return value? Ideally, something like the following:

```ts
getList(resource, params) {
  // ...

  const related = {
    articles: [ { id: 1, title: 'foo' }],
    authors: [
      { id: 2, name: 'Alice' },
      { id: 10, name: 'Bob' }
    ]
  }

  return { data, related, ... };
}
```

Ideally, this data would just go into the usual cache for use in optimistic rendering.

**Describe alternatives you've considered**

I'm currently using a local cache inside my Data Provider. This has problems of its own, namely around cache invalidation and timing, where I need to keep the local cache long enough to return data for the immediate next requests, but not long enough to where if a user navigates to that record the user gets a stale record.

And it's not as if the current system doesn't work, it just misses an opportunity to reduce the number of required calls to the backend.

**Comment by fzaninotto** [comment]
Hi,

And thanks for your suggestion. 

You can already pass optional fields in the `getList` return value, see https://marmelab.com/react-admin/useGetList.html#accessing-response-metadata. This data is available in the `ListContext` under the `meta` key, so you can read it in a React hook and place it in the QueryClient cache. 

https://marmelab.com/react-admin/List.html#accessing-extra-response-data

Since this is doable in user land, we're not considering a change in react-admin to accommodate this.
