### ISSUE TITLE
base route to first resource redirect prevents going back in history

### ISSUE THREAD

**Issue by justin-hackin** [marmelab/react-admin#10262]
**What you were expecting:**
When I navigate from non-RA part of my app to the base path for the admin panel, I should be able to navigate back to the non-RA part of the app.

**What happened instead:**
When I navigate from /dashboard to /admin, I get redirected to /admin/user and when I hit back, it goes to /admin and then to /admin/user again. 

If the redirect from /admin to /admin/user is a replace operation in the browser history, I should be able to go back to the dashboard. 

For now, I work around this by navigating directly to /admin/user from /dashboard.

**Comment by aqeebpathan** [comment]
I'm unable to find the part of the code responsible for the redirect from /admin to /admin/user. Could you please point me to where this should be fixed?

**Comment by slax57** [comment]
@aqeebpathan 
On `master` it's here:
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRoutes.tsx#L121-L127

But on `next` this part of the code was refactored due to the upcoming 'canAccess' feature, so if you PR against `next` you'll need to update the code located here instead:
https://github.com/marmelab/react-admin/blob/next/packages/ra-core/src/core/NavigateToFirstResource.tsx#L23-L28

Thanks!

**Comment by fzaninotto** [comment]
Fixed by #10267
