### ISSUE TITLE
Save button (and other inputs) not accessible by their aria roles

### ISSUE THREAD

**Issue by justin-hackin** [marmelab/react-admin#10306]
**What you were expecting:**
To be able to target the UI elements by their aria roles in Playwright.

**What happened instead:**
I can only target them by label.

**Steps to reproduce:**
You can use [Playwright CRX](https://chromewebstore.google.com/detail/playwright-crx/jambeljnbnfbkcpnoiaedcabbgmnnlcd) to observe this behaviour. Screenshots:

## Material UI site
 ![Image](https://github.com/user-attachments/assets/8e4c7397-a060-4077-bb07-4dc3327835c2)

## React-admin site
![Image](https://github.com/user-attachments/assets/ae2bfb41-b036-4acf-abf7-341d476792e4)

* React-admin version:5.3.1

I also noticed a similar problem with `<TextInput>` even when you specify a `label` property.

**Comment by fzaninotto** [comment]
Thanks for your report. 

Semantically, react-admin's `<CreateButton>` component and other navigation buttons are links, as they change the current resource. 

As such, the CreateButton should have [the `link` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role) instead of [the `button` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role). IMO, there is no bug here. 

So I'm closing the report, but feel free to comment with further details if you disagree.

**Comment by justin-hackin** [comment]
Indeed, you are correct, I didn't think of that 😖 I have successfully targeted the create button with the link role 🎉 I guess the tool I used to pick the selector isn't smart enough to pick this up 🤷🏻‍♂️
