### ISSUE TITLE
ReferenceArrayInput, AutocompleteArrayInput and optionValue

### ISSUE THREAD

**Issue by jeromediaz** [marmelab/react-admin#10327]
Version: 5.3.2

**What you were expecting:**
I was expecting a full support to using a field other than id when using ReferenceArrayInput with AutocompleteArrayInput

**What happened instead:**
While the field display the correct values and can edit them, there is a server side error that is displayed bellow it due to a failed query to list currently selected objects.

**Steps to reproduce:**

In my project I need to reference groups not using an ID but using a principal ID (which is the representation of the group as a path)

```
<ReferenceArrayInput source="groups" reference="user_group">
    <AutocompleteArrayInput optionValue="principal" />
</ReferenceArrayInput>
```

While the field display the correct list of groups and their principal, there is also an INTERNAL SERVER ERROR error due to a request to 
user_group?filter=%7B%22id%22%3A%5B%22%2Fgroup%2Froot%22,%22%2Fgroup%2Fadmin%22%5D%7D HTTP/1.1
({"id":["/group/root","/group/admin"]} )

Which is normal as the values "/group/root", "/group/admin" are not from the id field but inside the groups field

**Related code:**

```
<ReferenceArrayInput source="groups" reference="user_group">
    <AutocompleteArrayInput optionValue="principal" />
</ReferenceArrayInput>
```

**Other information:**

What I am expecting is a support inside ReferenceArrayInput (and it's equivalent ReferenceArrayField) to support overriding the field used to fetch the currently selected values: to perform the getMany on a field other than id

**Comment by fzaninotto** [comment]
Thanks for your report. 

`ReferenceArrayInput` fetches its current value using `getMany`. This is not customizable, and it won't be. React-admin uses strong assumptions about foreign keys to offer easy-to-use Reference components. If your model doesn't follow these conventions, you have two options:

1. in your `dataProvider`, convert the `getMany` for this resource to a query that suits you. You can use the `meta` param to identify the queries from `AutocompleteArrayInput`
2. Write your own `ReferenceArrayInput` and use it instead of react-admin's

So what you describe is not a bug but a limitation by design. We won't change react-admin to accommodate this use case.
