### ISSUE TITLE
Form should not re-render after typing first symbol in input

### ISSUE THREAD

**Issue by olesmarola** [marmelab/react-admin#10338]
**What you were expecting:**
The form should not re-render after typing the first symbol for each input.

**What happened instead:**
The whole form re-renders after typing the first symbol for each input.

**Steps to reproduce:**
Create a tabbed form and add some inputs to it.

**Other information:**
Video with reproducing: https://share.cleanshot.com/9wvr1XTs

**Environment**

* React-admin version: 5.3.2
* React version: 18
* Browser: any

**Comment by slax57** [comment]
I believe this is because of the implementation of the [useFormGroup](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/useFormGroup.ts) hook.

In this implementation we need to listen to all changes in the form state (i.e. dirty fields, touched fields, etc.) to be able to update the `TabbedForm.Tab` state accordingly.
This is what causes the multiple rerenders when you touch and dirty an input for the first time.

To my knowledge, react-hook-form does not expose a way to selectively listen to the form state, so AFAICT there is no way to avoid these rerenders.

Hence I'll close this issue as there is no way for us to fix it.
If you think you found a solution to this issue, or if you have come across a use-case where these rerenders cause problems, feel free to reopen.

**Comment by olesmarola** [comment]
@slax57 @fzaninotto we have some issues with these re-renders (significant delay) because we have 200+ input fields in one tabbed form.

**Comment by fzaninotto** [comment]
Putting apart the fact that a 200+ input form might not be user-friendly, this is clearly a limit of TabbedForm. In your case, you should implement your own version of the tabbed form.
