### ISSUE TITLE
Dynamic tabs in DatagridConfigurable break field synchronization with SelectColumnsButton

### ISSUE THREAD

**Issue by nepster-web** [marmelab/react-admin#10397]
The main issue is that when we use dynamic fields in DatagridConfigurable together with SelectColumnsButton, the result works very strangely.

I will try to demonstrate the situation visually and also prepare a sandbox environment for reproduction.

Let’s imagine that we have a complex Datagrid with tabs. For example, we’ll have two tabs: one for sms data and another for email data.

![Image](https://github.com/user-attachments/assets/bfe71f94-da0d-47aa-8e5d-7d3792738c92)

Each entity (SMS and Email) can have its own fields, for example:
sms: date, full price, total, cost
email: date, total, size

When we switch between the tabs, there are no issues.

![Image](https://github.com/user-attachments/assets/11b8534e-2e51-42ff-a963-c5a3f7f89c84)
![Image](https://github.com/user-attachments/assets/89bce018-6f26-49bb-b0bc-6c7d12647809)

Now, let’s focus on the SelectColumnsButton. The dropdown list of fields in the SelectColumnsButton does not respond to tab switching, even though the fields in the Datagrid change.

![Image](https://github.com/user-attachments/assets/ca5b0acf-e969-4f46-96da-12e3966099c9)

The SelectColumnsButton simply uses the fields from the default tab, ignoring any tab switches.

Furthermore, if we try to disable totalPrice (which doesn’t exist for Email), the total field disappears from the Datagrid. This is likely due to index misalignment—SelectColumnsButton seems to rely on the sequence of fields and disables the first one in the list.

![Image](https://github.com/user-attachments/assets/4d17ca0a-eaa7-4406-b91f-a0e83b8d1577)

I also tried performing a refresh, but that doesn’t work either.

**What you were expecting:**

I think the fields in the SelectColumnsButton should update together with the DatagridConfigurable. Additionally, it’s probably better to use source instead of relying on the index.

https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridConfigurable.tsx#L64

**Steps to reproduce:**

You can use the sandbox from the Related code section, go to the tests section (the last icon), ensure the SMS tab is open, and check the fields in COLUMNS. Then switch to the Email tab to confirm that the table changes, but COLUMNS remains the same.

**Related code:**

I was able to reproduce this behavior in the last test tab:

https://bolt.new/~/github-apt5o9-wbtm9a

**Other information:**

Currently, I managed to work around the issue by creating custom components, CustomSelectColumnsButton and CustomDatagridConfigurable, and overriding the preferenceKey:

`preferences.${finalPreferenceKey}.availableColumns`

to

`preferences.${finalPreferenceKey}.availableColumns_${mode}`

while adding the corresponding logic.

I don’t think this is an ideal solution, but I couldn’t find a better way.

**Environment**

* React-admin version: 5.3.3
* Last version that did not exhibit the issue (if applicable): ---
* React version: 18.3.1
* Browser: doesn't matter
* Stack trace (in case of a JS error): doesn't matter

**Comment by slax57** [comment]
Thank you for your report.

First of all, we have an ongoing PR aiming at improving datagrid configurable columns management with dynamic columns: https://github.com/marmelab/react-admin/pull/10339.
However this feature turns out to be more complex than anticipated, so we can provide no ETA for now.

That being said, the issue you are facing is the result of using your own tabs system with Datagrid. This is not a use-case we support out of the box. Hence, this issue can't be considered a bug.
So I'm closing this issue, and inviting you to follow, or even contribute, to PR #10339 to see if it can help solve your issue.

Lastly, I'd like to mention the ability to pass a `preferenceKey` prop to `<DatagridConfigurable>`, which allows 2 Datagrids to have 2 separate configurable states. This could maybe help if you make your tabs actually render 2 different Datagrids, each with its own `preferenceKey`.
You can see an example in our [Storybook](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-list-datagridconfigurable--preference-key).
Hope this helps!
