### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by MarcDeletang** [marmelab/react-admin#1773]
**What you were expecting:**
I was following the "Include in another app" from the documentation.
We already had our 'admin-on-rest' app that was working, however when we updated to 'react-admin' few things broke.
The following modules were exported before:
- adminReducer
- localeReducer
- crudSaga
- fetchUtils
- declareResources
- jsonServerRestClient

**What happened instead:**

- adminReducer => OK
- localeReducer => undefined
- crudSaga => undefined
- fetchUtils => OK
- declareResources => undefined
- jsonServerRestClient => undefined

**Steps to reproduce:**

Follow the custom-app guide: https://marmelab.com/react-admin/CustomApp.html

**Environment**

* React-admin version:  react-admin: 2.0.0-RC1
* Last version that did not exhibit the issue (if applicable): admin-on-rest: 1.4
* React version: 16.0
* Browser: chrome 65

NB: I saw that you were using directly the 'ra-data-simple-rest' [in this page](https://marmelab.com/react-admin/DataProviders.html)
Is this the new way of import things ? (because i'd rather not have 4-5 dependencies just for AOR)

Tell me if you need more informations :)

**Comment by fzaninotto** [comment]
As you see in #1775, some of the problems you reported are due to an outdated documentation, and for the rest, you should read the Upgrade guide.

* `localeReducer` was renamed to `i18nReducer`
* `crudSaga` was renamed to `adminSaga`
* `declareResources` is no longer necessary
* `jsonServerRestClient` must be imported from another package

Could you test #1775 and report if you manage to migrate your custom app?

**Comment by MarcDeletang** [comment]
Hello, sorry i didn't found the Upgrade guide, maybe you should add an entry in the documentation ?
Everything seems good now, I suggest also that you explain the new registerRessource action also in the setup guide.
Thanks for your time.
