### ISSUE TITLE
authProvider does not automatically introduce Logout button to the sidebar

### ISSUE THREAD

**Issue by CAYdenberg** [marmelab/react-admin#1810]
**What you were expecting:**
According to the documentation: "If you provide an authProvider prop to <Admin>, react-admin displays a logout button in the sidebar." This makes it sound like it should happen automatically?

**What happened instead:**
Even when providing an `authProvider`, no Logout button appears.

**Steps to reproduce:**
Load the sample app (https://github.com/CAYdenberg/react-admin-demo/tree/Logout_bug), checkout the Logout_bug branch and run with `npm start`

**Related code:**

```js
const authProvider = () => Promise.resolve()

const App = () => (
    <Admin dataProvider={dataProvider} authProvider={authProvider}>
        <Resource name="posts" list={PostList} authProvider={authProvider} />
    </Admin>
)
```

**Other information:**

**Environment**

React-admin version: 2.0.0-RC2
Last version that did not exhibit the issue (if applicable):
React version: 16.2.0
Browser: Chrome 66 / OSX
Stack trace (in case of a JS error): see above
Also, node 9.10.1, npm 6.0.0

**Comment by fzaninotto** [comment]
In react-admin 2.0, the logout button has been moved to the top AppBar, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/99944/39782052-52edb4d0-5311-11e8-9cdf-fc5a699e79e7.png)

It still displays as a sidebar menu on Mobile devices:

![image](https://user-images.githubusercontent.com/99944/39782091-771df6b2-5311-11e8-90f8-4cec30078f04.png)

In my tests, the Logout button does appear when the `authProvider` is provided. 

Can you confirm that it appears on the top bar, in which case this issue is a matter of adapting the documentation?

**Comment by fzaninotto** [comment]
Also, in your sample app, you add the `authProvider` to the `<Resource>` component, why you should only add it to the `<Admin>` component.

**Comment by CAYdenberg** [comment]
Oops yes I see that now.

FWIW, the **documentation** is still wrong.

Will you accept documentation PRs without a pre-existing issue report? I'm seeing a number of places that it's lagging, but I'm not sure if I should open issues first.

**Comment by fzaninotto** [comment]
Yes please, feel free to open PRs on the doc, even without an issue. Just make sure that you add an explicit PR description.
