### ISSUE TITLE
How to get SQL database for demo project?

### ISSUE THREAD

**Issue by Aurelyn10** [marmelab/react-admin#1831]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.

In documentation, I found one external Data Provider's sources, Xmysql: soaserele/aor-xmysql.
I  want to run the demo project with this provider.
For that, I need to set up mysql database with same dataset from demo project.
There is any way to get SQL file of react-admin demo project' dataset?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by Aurelyn10** [comment]
By the way, do you have SQL file for the demo project?
Where did you get the demo data?

**Comment by djhi** [comment]
No, its data come from a fake api server which servers data from a fake data generation. https://github.com/marmelab/react-admin/tree/master/examples/data-generator
