### ISSUE TITLE
Display a warning when closing tab while optimistic update is waiting

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#1857]
Optimistic updates aren't sent to the server until the undo delay expires. If, within this delay, the user closes the browser window/tab, the update is lost.

In this case, the admin should display an alert, and allow to cancel the browser close.

**Comment by kctrlv** [comment]
Another scenario is if a user switches tabs or clicks out of their window, the notification never closes. They might leave for the day, assume it completed because the notification said it was updated and won't know that it never went through. Because of this possibility, there is some local caution for enabling optimistic rendering.

**Comment by richardartoul** [comment]
Is there any way to disable the optimistic rendering entirely? I'm considering using react-admin for an open-source database administration U.I, but don't like the idea of database operators not getting immediate feedback

**Comment by fzaninotto** [comment]
@richardartoul No, we haven't built such an option. But it can be overridden by hand.

**Comment by fzaninotto** [comment]
Fixed by #2784
