### ISSUE TITLE
can i use ArrayInput as just array form

### ISSUE THREAD

**Issue by findcoo** [marmelab/react-admin#1874]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.
```jsx
<ArrayInput source="backlinks">
    <SimpleFormIterator>
        <DateInput source="date" />
        <UrlInput source="url" />
    </SimpleFormIterator>
</ArrayInput>

{
  id: 123
  backlinks: [
        {
            date: '2012-08-10T00:00:00.000Z',
            url: 'http://example.com/foo/bar.html',
        },
        {
            date: '2012-08-14T00:00:00.000Z',
            url: 'https://blog.johndoe.com/2012/08/12/foobar.html',
        }
   ]
}
```
the above example is common case of ArrayInput
but i need

```javascript
{
  id: 123,
  backlinks: [ 'http://example.com/foo/bar.html', 'https://blog.johndoe.com/2012/08/12/foobar.html' ]
}
```
is possible?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
