### ISSUE TITLE
submenu component

### ISSUE THREAD

**Issue by data-server** [marmelab/react-admin#1877]
when i upgrade version to 2.0.0 , fund only this component, https://material-ui.com/demos/lists/#nested-list , react admin menuitemlink doesn't have the nestedItem props.

**Comment by djhi** [comment]
Please take the time to fully describe your issue.

**Comment by fzaninotto** [comment]
So I made a submenu component myself, using the nest lists technique from material-ui. There is nothing preventing you from doing something similar in react-admin. But you'll need a custom Menu component.

**Comment by DejanBelic** [comment]
@fzaninotto I apologize for writing on a closed issue (don't want to reopen another one), but I just don't get it lost 2 days... If we use example nested list from material-ui, where we can toggle state for menu items to be open or closed... https://codesandbox.io/s/k3kvr7z7n3

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
