### ISSUE TITLE
Is it possible to have have multiple dataProviders?

### ISSUE THREAD

**Issue by rentallect** [marmelab/react-admin#1882]
If I have multiple distinct REST API back-ends (separate apps doing separate things), and I want a single UI (react-admin-based) app that is capable of doing CRUD to entities managed by these various back-ends, I'm curious if it's possible to wire up react-admin to do that.

I'm Imagining that instead of this (single/global dataProvider):

```javascript
const App = () => (
    <Admin dataProvider={simpleRestProvider('http://path.to.foo.api')}>
        <Resource name="foos" list={FooList} />
    </Admin>
);
```

we could do something like this (resource-specific dataProviders):

```javascript
const App = () => (
    <Admin >
        <Resource name="foos" list={FooList} dataProvider={simpleRestProvider('http://path.to.foo.api')} />
        <Resource name="bars" list={BarList} dataProvider={simpleRestProvider('http://path.to.bar.api')} />
    </Admin>
);

```

At any rate, if you have advice on how I can do REST to multiple back-ends, I'd appreciate it very much.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by RodolfoSilva** [comment]
Thanks @djhi 

https://stackoverflow.com/questions/52889909/how-is-the-correct-way-to-have-multiple-dataproviders-in-react-admin/52893150#52893150

https://stackoverflow.com/search?q=%5Breact-admin%5D+multiple+dataProvider

> No, but you can have a super `dataProvivder` which would select the appropriate one depending on the resource. Something like:

```js
import simpleRestProvider from 'ra-data-simple-rest';

const dataProviders = [
  { dataProvider: simpleRestProvider('http://path.to.foo.api1'), resources: ['users1'] },
  { dataProvider: simpleRestProvider('http://path.to.foo.api2'), resources: ['users2'] },
];

export default function dataProvider(type, resource, params) {
  const dataProviderMapping = dataProviders.find(dp => dp.resources.includes(resource));
  return dataProviderMapping.dataProvider(type, resource, params);
};
```

**Comment by twanabrno** [comment]
> Thanks @djhi
> 
> https://stackoverflow.com/questions/52889909/how-is-the-correct-way-to-have-multiple-dataproviders-in-react-admin/52893150#52893150
> 
> https://stackoverflow.com/search?q=%5Breact-admin%5D+multiple+dataProvider
> 
> > No, but you can have a super `dataProvivder` which would select the appropriate one depending on the resource. Something like:
> 
> ```js
> import simpleRestProvider from 'ra-data-simple-rest';
> 
> const dataProviders = [
>   { dataProvider: simpleRestProvider('http://path.to.foo.api1'), resources: ['users1'] },
>   { dataProvider: simpleRestProvider('http://path.to.foo.api2'), resources: ['users2'] },
> ];
> 
> export default function dataProvider(type, resource, params) {
>   const dataProviderMapping = dataProviders.find(dp => dp.resources.includes(resource));
>   return dataProviderMapping.dataProvider(type, resource, params);
> };
> ```

so how to send it to the admin?
