### ISSUE TITLE
How to use bootstrap instead of Material Design ?

### ISSUE THREAD

**Issue by npotier** [marmelab/react-admin#1896]
Hello, and first of all thank you for your amazing work. 

The README file indicates that it is possible to use Bootstrap instead of Material Design, but I can’t find any documentation of how to implement it.

Does anybody has already done that ? Thank you in advance :)

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by npotier** [comment]
Ok thanks. 

For the record, My question is now here : https://stackoverflow.com/questions/50791830/react-admin-how-to-use-bootstrap-instead-of-material-design
