### ISSUE TITLE
Tutorial for including react-admin on another React app

### ISSUE THREAD

**Issue by ace53thntu** [marmelab/react-admin#1901]
Anyone have a demo for how to including react-admin on another React app?
I have seen this link: [https://marmelab.com/react-admin/CustomApp.html](https://marmelab.com/react-admin/CustomApp.html) but not specific. Please help me!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
