### ISSUE TITLE
Create and Edit one-to-many relations as Item collection

### ISSUE THREAD

**Issue by ashkart** [marmelab/react-admin#1904]
Eg you have employee card. Employe has working experiences in few other organisations. As admin you have to create employee cards or edit those you already have. When there is a lot of employees you definitely dont want to switch between screens of employees and work exp. list (and filter it) to make some CRUD (or even only R). This is much more easy to open the employee, go on work exp tab and view/create/update/delete its related records.

**Comment by fzaninotto** [comment]
We won't add that to the core for now. Feel free to work on a standalone component handling this case, and to contribute it to the core when it's ready!

**Comment by thecassion** [comment]
Great I want to have this component also @ashkart . We can do it like ArrayInput but when we add a new element , we must POST  a request to the api and display it in the list.

**Comment by MROFerreiro** [comment]
I wanted the same and searched if using the `ReferenceFields` would solve it, but had no success. However during my investigation I found a questionable work around that may indicate small alterations to `List` in order to the issue be possible.

My thought was:
1. Use a `ReferenceField` to fetch related data (`ReferenceManyField` or `ReferenceArrayField`)
2. Send data used by `ReferenceField` to `List`
3. Create custom actions component
4. Use custom actions component in `actions` prop of `List`

As far as I know is impossible to send data to `List`, but if you edit `resource` prop supplied to `List` it fetches that data. Meaning you could get **ALL** WorkingExperiences inside a `Tab` of Employee. You could also set the `filter` prop of `List` to restrict the WorkingExperienced related to that Employee. **As said before this is a questionable workaround, in a way it works but doesn't seem to be very good.**

You may think that you only need a `List` inside the `Tab` however I think that `Tab` sends its props to `List` resulting in overwriting the resource prop and in consequence fetching Employees and not WorkingExperiences. So you need to put it inside a `ReferenceField` for it to work. **This makes even more questionable since you fetch data 2 times, one for the `ReferenceField` and another for the `List`.**

In my use case, adapted to your problem, I have something like the following:
``` JSX
const EmployeeShow = (...props) => {
  //Copy and edit the resource of props
  let copyProps = Object.assign({},props)
  copyProps.resource = "WorkExperience"

  return <Show>
    <TabbedShowLayout>
      <Tab label="details">
        <SimpleShowLayout>
          {/* Employee Fields */}
        </SimpleShowLayout>
      </Tab>
      <Tab label="Working Experiences" path="workingexperiences">
        <ReferenceManyField label='' reference='workingexperience' target='idemployee'> 
          <List {...copyProps}>
            <Datagrid>
              {/* Your WorkingExperience Fields */}              
              <EditButton />
            </Datagrid>
          </List>
         </ReferenceManyField>
      </Tab>
    </TabbedShowLayout> 
  </Show>
}
```

**The code above is for demonstration only, it is a workaround that repeats processes. It's here to help owners of projects and contributors in the search of a solution reusing `List` component. Use it at your own risk**

I think if you specify the resource we wanted to fetch in `ListController` would not be such a huge difference in terms of logic. `List` continues to be a component that fetches data, has a set of utility actions for CRUD operations, and can send its fetched data to a `Datagrid` to presentation. The only problem I identify here is the actions that can point to routes that don't exist. Maybe not using a default action component in [ListView](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/List.js#L68) and passing it if coming from `Resource` or similar.

**Comment by esistgut** [comment]
Do you have a proof of concept repository for your proof of concept? I'm in need for something like this to edit a list of related resources within the edit view of the parent resource but I'm not sure on which approach I should follow.

**Comment by djhi** [comment]
You might be interested in reading some of our tutorials:
https://marmelab.com/blog/2018/07/09/react-admin-tutorials-form-for-related-records.html
https://marmelab.com/blog/2018/08/27/react-admin-tutorials-custom-forms-related-records.html
https://marmelab.com/blog/2019/02/07/react-admin-advanced-recipes-creating-and-editing-a-record-from-the-list-page.html

**Comment by esistgut** [comment]
@djhi thank you for your quick response even on an hot sunday. I further explored my use case and found the [SimpleFormIterator](https://marmelab.com/react-admin/Inputs.html#arrayinput) to be a better solution as my nested data doesn't really require to be a stand alone resource too (we are talking of a list of prices with related conditions for a given product).
Thank you.

**Comment by jdemangeon** [comment]
Since the issue seems to be solved for some and given the age of the issue, I closing it.

**Comment by fzaninotto** [comment]
also, if anyone feels like taking a shot at it, a volunteer started #744 but never took the time to finish it. If you need this feature, maybe you can take over?
