### ISSUE TITLE
More feature like [other] admin pannel

### ISSUE THREAD

**Issue by mnlbox** [marmelab/react-admin#1910]
`<-- redacted -->`

[I found another] admin panel [that has] good feature like:
* change logo, color, from admin pannel.
* Media manager support as seprate menu item.
* more relation support (one to one - one to many - many to many - one way - ,,,)
* better uu/ux on bulk action and filter feature
* environment support (development, production, stage)

I think you can add some of this ceature to react-admin.

Thanks for all of you work.

**Comment by fzaninotto** [comment]
React-admin will never implement some of the features you ask, because that's your job as a developer to implement them in your application:

- change logo, color, from admin pannel.
- Media manager support as seprate menu item.
- environment support (development, production, stage)

As for the other requests, these are not specific enough:

- more relation support (one to one - one to many - many to many - one way - ,,,): You can already do most of those, depending on your data provider
- better uu/ux on bulk action and filter feature: what's wrong with the current ui/ux?

Please make one issue per feature request, and be more specific as to what you are trying to achieve and what you would like to get. 

Lastly, please don't use this tracker to advocate the use of your (unrelated) library. I've edited your issue so it doesn't read like spam.

**Comment by djhi** [comment]
> change logo, color, from admin pannel

https://marmelab.com/react-admin/Theming.html#using-a-custom-layout

> Media manager support as seprate menu item

Can you please give more details about this ? 

> more relation support (one to one - one to many - many to many - one way - ,,,)

What weren't you able to do with the existing components ?

> better uu/ux on bulk action and filter feature

I don't know what you mean by **better**. Please be specific.

> environment support (development, production, stage)

What does this mean ?

Please take more time to specify the problems you're facing or the feature you're missing and make one issue for each.
