### ISSUE TITLE
Translate URLs

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#1915]
The URL's look awkward with Dutch names for resources followed by `show` and `create` words. Instead of `/dingen/:id/show`, `/dingen/create`, I'd like to be able to configure Dutch words for show and create.

I've created a [SO question](https://stackoverflow.com/questions/50840155/how-to-translate-words-like-show-and-create-in-record-links-in-react-admin) on this topic because I wasn't sure if this should be a feature requests.

The way this would be implementable is that on the places where `/show`and `/create` are appended to a URL, we append 

```javascript
translate(`resources.${resource}.show`, {
  _: 'show'
})
```

(and ``translate(`resources.${resource}.create`, {_:'create'})``.)

Please close this issue if you feel this is outside the range of considered feature requests.

**Comment by fzaninotto** [comment]
I understand the need, but it's really not easy to implement currently (as the translation service isn't accessible from the sagas and controllers where the routing decisions are made). Besides, I think it's a good practice to name your resources in English, because the rest of the code will look weird, too, if you do it otherwise. Lastly, the customers who care about what the URLs look like are less and less common, so I consider this a corner case.

I'l keep this as an enhancement request, but since this isn't a need my team has, we won't implement it  ourselves in the foreseeable future.

But if someone wants to give it a try, I'd be happy to add this to the core.

**Comment by fzaninotto** [comment]
I'm closing this one as we won't implement it ourselves - we simply don't have the need for it, and it implies a different routing layer than what react-admin uses. I don't think the benefit is worth the added complexity.
