### ISSUE TITLE
react-admin migration - not running

### ISSUE THREAD

**Issue by ROcodebear** [marmelab/react-admin#1969]
Hello!

I was trying to migrate from admin-on-rest to react-admin, I have uninstalled admin-on-rest, installed react-admin, basically I followed the steps to upgrade.
After running npm start and fixing the compiling errors from create-react-app, nothing runs. I have attached a photo with the stacktrace.

Environment:
Windows 10, Chrome.

dependencies:
   "material-ui": "^0.20.1",
    "react": "15.6.1",
    "react-admin": "^2.0.3",
    "react-dom": "15.6.1",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-form": "^7.4.2"

![image](https://user-images.githubusercontent.com/37338825/42021941-a093acc8-7ac4-11e8-995a-985394040a1c.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
