### ISSUE TITLE
Deprecation of react-router-redux

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#1999]
React-router-redux is deprecated as can be seen here:
https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

Any plans on finding an alternative?

**Comment by djhi** [comment]
Not yet but I guess we'll have to use https://github.com/supasate/connected-react-router

**Comment by ignlg** [comment]
I've been using https://github.com/FormidableLabs/redux-little-router with some projects, just to point at another option

**Comment by azjgard** [comment]
@ignlg Thanks a ton for passing that along!

**Comment by fenghuizhang** [comment]
> com
Can we use react-router's {withRouter} replace react-router-redux's {routerReducer} ?

**Comment by fenghuizhang** [comment]
> Not yet but I guess we'll have to use https://github.com/supasate/connected-react-router

Can we use react-router's {withRouter} replace react-router-redux's {routerReducer} ?

**Comment by maicWorkGithub** [comment]
> > Not yet but I guess we'll have to use https://github.com/supasate/connected-react-router
> 
> Can we use react-router's {withRouter} replace react-router-redux's {routerReducer} ?

https://reacttraining.com/react-router/core/guides/redux-integration/deep-integration

They say not suggested use router in redux, I'm a noob, why you choose use router in redux? what's the benefit?

**Comment by edy** [comment]
What about [React Navigation](https://reactnavigation.org)? They support [Web and SSR](https://reactnavigation.org/docs/en/web-support.html) too.

**Comment by fzaninotto** [comment]
After re-reading https://reacttraining.com/react-router/core/guides/redux-integration/deep-integration, the proposed solution (do not integrate react-router with redux) seems cumbersome and a very big BC break, because each action that *may* lead to a redirection must have the `history` object in its payload.

So we'll go with [connected-react-router](https://github.com/supasate/connected-react-router), but they haven't integrated react-redux v7 yet (see https://github.com/supasate/connected-react-router/issues/287).

**Comment by fzaninotto** [comment]
Fixed by #3170
