### ISSUE TITLE
Add pagination to ArrayInput

### ISSUE THREAD

**Issue by ronfogel** [marmelab/react-admin#2010]
**Is your feature request related to a problem? Please describe.**
I use an `ArrayInput` to control a value containing dozens of items. When displaying the form, the browser tries to render hundreds of form inputs, and gets stuck (page loads forever, and after a while the "kill page" prompt appears).

**Describe the solution you'd like**
Add pagination to ArrayInput

**Describe alternatives you've considered**
Create a component that makes the above but not as generic as I would want it to be.

**Additional context**
Created a code sandbox to show my problem
https://2z290jvplr.codesandbox.io/#/posts/1 (if you need to login, user: admin, password: password)
https://imgur.com/a/TQyZAOn (screenshot with the prompt)

**Comment by fzaninotto** [comment]
My browser doesn't get stuck at all when displaying this codesandbox. With how many items in the ArrayInput value does the form stop working?

**Comment by ronfogel** [comment]
Well, in my own system, I have an entity with 5000 iterations which obviously stuck.
I believe that even 100 or maybe more will cause it.
Just a time consuming to add more iterations to that demo

**Comment by ronfogel** [comment]
I updated the demo, added 100 comments and 10 users, it's stuck for a few seconds  and then there's a prompt

**Comment by afilp** [comment]
@fzaninotto Pagination is really needed in cases of thousands of possible suggestions while the end-user is not very sure on what to look for (so `<AutocompleteInput />` may not be that useful).

For this reason I created a similar feature request (for `SelectInput` and `AutocompleteInput`) where I describe the use case and a possible UI implementation there:
https://github.com/marmelab/react-admin/issues/2565

**Comment by fzaninotto** [comment]
@aflip it's already marked as 'enhancement', which means that anybody can open a PR for it. If you really need it, give it a try!

**Comment by vctqs1** [comment]
I encountered a similar case with 100 iterations, can you add pagination in array input or any other solution?
if can, please share your experience @ronfogel ,

**Comment by GrzegorzCzm** [comment]
I have stuck with similar problem. I do not have many records (~70) to show, but each record has referenceField which point to Resource with thousands of records.

```
 <ArrayField source='someSource'>
        <Datagrid>
          <TextField source='name' />
          <ReferenceField source='referenceId' reference='referencedResource'>
            <TextField source='name' />
          </ReferenceField>
        </Datagrid>
 </ArrayField>
```

In referencedResource I have thousands of records. In a result ReferenceField stays empty in most of records and in a console many warnings are written. E.g:
```
Material-UI: You have provided an out-of-range value `226` for the select (name="referenceId") component.
Consider providing a value that matches one of the available options or ''.
The available values are `3058`, `2969`, `2467`, `1993`, `1970`, `1752`, `1742`, `1662`, `1574`, `1353`, `1319`, `1293`, `1204`, `1168`, `1167`, `1166`, `1164`, `1159`, `1156`, `1042`, `949`, `836`, `547`, `483`, `482`.
```

Pagination should also help in this case (at least I hope).

**Comment by liviozanol** [comment]
Does anyone have a workaround for this? I'm facing similar issue with 60+ items on array input, each one with 5 inputs (~ 300 inputs in total).

Its unusable for the user. Typing a single character takes too long. Is this due to global form validation, even if I don't have any validation function applied? If so, can I disable it?

Is it possible to use something like material-table (https://material-ui.com/pt/components/tables/#complementary-projects - first table example) to workaround this? Eg.: Only display fields on initial view, that transforms to input on clicking/editing specific item. How

I know that there is a editable datagrid on the enterprise version, but unfortunately I can't use it.

**Comment by jdemangeon** [comment]
Hello @liviozanol, as @fzaninotto said,  it's already marked as 'enhancement', which means that anybody can open a PR for it. If you really need it, give it a try!

**Comment by liviozanol** [comment]
Hey! Thanks for your reply @jdemangeon.  I was able to add material-table on a tab, and making it functional on my specific case. Doing this I found an interesting thing, and I don't really know what it means, since react is not my expertise, but I'll write here and maybe someone could understand better.

Using the react-scripts to build or run my app like shown at tutorial or the docs made my app slower and eventually freezing upon SetState insite the material-table, until the browser completely stops.

**Using webpack like saw on the sandbox code, made the app really faster and no freeze at all. Maybe its something to try later with the original big arrayinput.**

About the PR, sometime ago there was an issue and a PR with something like editable-grid, but since its a "premium" feature was kind of discontinued. I can't PR my solution because it was specific made for my case with a lot of custom code, unfortunately,

If I could understand react better I world certainly make a better solution and submit a PR. Sorry :/

regards!

**Comment by fzaninotto** [comment]
This issue didn't gather enough attention from the community to be fixed. The core team doesn't currently have the need for a paginated ArrayInput, so we'll close this issue as part of our effort to keep the issues list manageable. 

Feel free to submit a PR to fix it anyway.
