### ISSUE TITLE
How to concat source inside ReferenceField

### ISSUE THREAD

**Issue by Mysh3ll** [marmelab/react-admin#2041]
Hello,

I have a table "fos_user" and "version", I would like to display "9.0.1.A" instead of "/ version / 1".

**=>fos_user**
[https://i.imgur.com/C8f0qor.png](https://i.imgur.com/C8f0qor.png)

**=>version**
[https://i.imgur.com/HFSKIdz.png](https://i.imgur.com/HFSKIdz.png)

Is it possible to concatenate the fields of the "version" table to display it in the source, like this?
[https://i.imgur.com/rxJBmtp.png](https://i.imgur.com/rxJBmtp.png)

Because it will prevent me from creating a new field in the "version" table.

Best regards,

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
