### ISSUE TITLE
permissions not available within a CardAction

### ISSUE THREAD

**Issue by ricktbaker** [marmelab/react-admin#2048]
**What you were expecting:**
Wanting to show a custom button at the top of the page only if the user is an admin.   This works for showing/hiding certain fields on the same page.

**What happened instead:**
It does not work on a CardAction component, so the button never shows. Even when it is working on other components such as a datagrid on the same page.   

**Related code:**

```
const UserListActions = ({ permissions, ...props }) => (  
  <CardActions> . 
      <RefreshButton />  
      {permissions === 'admin' &&   
        <Button color="primary"> . 
          <SyncIcon /> Sync Users . 
        </Button> . 
      } . 
  </CardActions> . 
);

export const UserList = ({ permissions, ...props }) => (
  <List actions={<UserListActions />} title="All users" {...props} bulkActions={false}>
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
