### ISSUE TITLE
[RFC] Remove the List button

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2069]
Sometimes making a UI better means removing things. I feel that the ActionBar is usually too cluttered, and I'm thinking about how to make it smaller, or even how to remove it completely. 

My first suspect is the List button. 

![2018-07-24_1406](https://user-images.githubusercontent.com/99944/43137668-b128ea5c-8f4c-11e8-841c-6951b84b8caf.png)

Whenever a user is in a Show, Edit, or Create view, the List button gives a way to go back to the list. But there are already two other such ways:

- clicking on the back button (if coming from the list)
- clicking on the resource name in the menu (unless it's a resource without menu entry)

So I think this List button is useless 90% of the time. 

I suggest we remove it from the default `ShowActions`, `EditActions`, and `CreateActions`. React-admin can still export the `ListButton` component for people who actually need it for a good purpose. 

Thoughts?

**Comment by christiaanwesterbeek** [comment]
> So I think this List button is useless 90% of the time.

I think so too. I've been removing it in every instance. The percentage may even go up for default `EditActions`, and `CreateActions`.

As a side note, while in the Edit view I also don't find myself clicking the Show button intuitively.

**Comment by christiaanwesterbeek** [comment]
I also doubt Refresh is clicked very often. Maybe just the Delete button is one that is to be expected in the Edit view.

**Comment by ashim-k-saha** [comment]
My use case is a little different than @christiaanwesterbeek. Most of the time I did not use `delete` button in my `edit` or `show` pages. Actually, most of the resource is not deletable once they created. Due to this kind of use case, I relax default `bulkAction` in the `list` page using `bulkAction={null}`.

In my opinion, it will be better to configure the default actions for `show` & `edit` pages. Also, it will be nice to configure default bulk actions for list view.

Maybe `Admin` is the appropriate component to configure the default action button.

**Comment by fzaninotto** [comment]
Thanks for your comments, we'll remove the List Button. See #2115 for details.
