### ISSUE TITLE
TabbedForm overflows viewport when there are a lot of FormTabs

### ISSUE THREAD

**Issue by AndresVelandia** [marmelab/react-admin#2094]
**What you were expecting:**
When you add a lot of FormTabs in a TabbedForm inside a Edit, I expect a behavior like this: [Material UI Scrollable Tabs](https://material-ui.com/demos/tabs/#scrollable-tabs) 

**What happened instead:**

It overflows the viewport in an annoying way

**Steps to reproduce:**
I reproduced it in CodeSandbox, I recommend to **open in a new window**

**Related code:**
CodeSandbox (https://codesandbox.io/s/0p6v43wnl)

* React-admin version: 2.1.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
We won't include the `scrollable` behavior of material-ui for `Tabs` and fix the center section width because it has unwanted effects of on the List pages too. We decided to fallback to standard window scrolling for all pages.

If you really want this, you'll have to make your own layout which will disable overflow on the content section and your own `TabbedForm` or `TabbedShowLayout` to set the `scrollable` prop.
