### ISSUE TITLE
ra-realtime example saga not working

### ISSUE THREAD

**Issue by adriankirchner** [marmelab/react-admin#2154]
**What you were expecting:**
I was using the example saga for ra-realtime from the [readme](https://github.com/marmelab/react-admin/blob/master/packages/ra-realtime/README.md) (`createRealtimeSaga.js`).
I was expecting the saga to subscribe to any request the `dataProvider` was handling and to refresh this request after 5 seconds.

**What happened instead:**
Nothing happened - it seems like the saga does not get executed

**Steps to reproduce:**
- install ra-realtime
- create createRealtimeSaga.js
- remove `if (resource !== 'posts') return;`
- import createRealtimeSaga.js in app.js and register via `customSagas={[ realtimeSaga ]}`
see https://codesandbox.io/s/2wvj91z62n

**Related code:**
https://codesandbox.io/s/2wvj91z62n

**Environment**

* React-admin version: 2.2.0 
* React version: 16.4.2
* Browser: Chrome 68.0.3440.106 @ macOS 10.13.6 (17G65)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
