### ISSUE TITLE
Would be great to add a feature of adding items to a create/edit order

### ISSUE THREAD

**Issue by anoop2811** [marmelab/react-admin#2157]
Hi, 
  Would be great if you could show in the example demo orders page an option to create an order an order adding product items to that order as both an example of one to many relationship which may start without an order id as well as for completeness if you agree so.

Thanks,
Anoop

**Comment by fzaninotto** [comment]
Hi Anoop. This greatly depends on your backend. Since there is a one to many relationship between the order and the items, the creation of two related resources at once isn't standard. 

We won't add it to the demo, but you're welcome to ask the question on StackOverflow to see how people would do it.
