### ISSUE TITLE
Client side resource list page

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [marmelab/react-admin#2180]
I checked StackOverflow - I didn't find answer to my question.

Is there a simple way to create a resource which reads all records from server on first page load.
And then the sort, filter, paging is done client side.
Also to have option to disable paging.

I tried to make a copy of ListController.js from ra-core and List.js from ra-ui-materialui and customize it, but error and I could go forward. I am new to react and making PoC.

**Comment by ivan-meridianbanc-com** [comment]
This is the changed ListController.js file:

[ListController.txt](https://github.com/marmelab/react-admin/files/2300661/ListController.txt)

Here is the error:

TypeError: Cannot read property 'apply' of undefined
(anonymous function)
node_modules/recompose/compose.js:22
  19 | 
  20 |   return funcs.reduce(function (a, b) {
  21 |     return function () {
> 22 |       return a(b.apply(undefined, arguments));
  23 |     };
  24 |   });
  25 | }
View compiled
./src/ListController.js
src/ListController.js:431
  428 | export default compose(
  429 |     connect(
  430 |         mapStateToProps,
> 431 |         {
  432 |             crudGetList: crudGetListAction,
  433 |             changeListParams: changeListParamsAction,
  434 |             setSelectedIds: setListSelectedIdsAction,
View compiled

I have changed the imports from relative paths to import 'react-admin';
Any suggestions how to fix the error ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
