### ISSUE TITLE
Edit fields are not filled when GET_LIST and GET_ONE doesn't return same fields

### ISSUE THREAD

**Issue by davidclochard** [marmelab/react-admin#2197]
**What you were expecting:**
I'm on my Edit Form, all my fields are filled

**What happened instead:**
I'm on my Edit Form, only 2 fields are filled

**Steps to reproduce:**

1. Declare a resource (with this example fields: id, nom, titre, description, parent_id)
2. GET_LIST (returns id, nom, parent_id) and GET_ONE (returns id, nom, titre, description, parent_id)
3. Create an Edit page with these inputs : 
   - nom : TextInput
   - titre : TextInput
   - description : TextInput
   - parent_id : Reference + SelectInput

**Environment**

* React-admin version: 2.1.5
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: All

**Comment by djhi** [comment]
Adding some info: this was made obvious for a recursive resource.

Example:

Category has a `parent_id` referencing its parent category.
The List page shows them all.
The Edit page loads the edited category and has a `ReferenceInput` targetting the categories.
When the `ReferenceInput` loads them, the results override all categories in the redux state, including the one being edited. 

This is problematic when the `GET_LIST` does not return the same fields as the `GET_ONE`. 

I think we should merge data instead of overriding them. On the top of my head, it should at least impact the data reducer [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/reducer/admin/resource/data.js#L43)

**Comment by djhi** [comment]
Discussed with @fzaninotto. We can't merge data from a `GET_LIST`with one from a `GET_ONE` as this could have weird side effects too. For instance, you may return properties from the `GET_LIST` which are not used in the Edit form. However, as the record is used to initialize the redux-form, those properties will be sent in the CRUD_UPDATE call.

You might be able to workaround this by specifying a filter on your `ReferenceInput` which references the resource, explicitly excluding the one being edited.
