### ISSUE TITLE
Any help to implement react-admin over a prisma API ?

### ISSUE THREAD

**Issue by maximejen** [marmelab/react-admin#2205]
Hello, I just wanted to install react-admin and connect it to my Prisma GraphQL API To directly admin my DB through this API. The only problem is that react-admin seems impossible to connect to my Prisma API ... I wanted to develop my own DataProvider using the "ra-data-graphql" one, but impossible and any time I wanted to read and understand the code of the "ra-data-graphql" or "ra-data-graphcool" datProvider was a complete failure, since they use some code of the huge "react-admin" package...

Is there any "Getting Started with dataProviders" ? or any documentation that could help developping this ? Or any recent plan on handle prisma (since Graphcool is recomending Prisma by it's own ... (look at GraphCool Website)).

Thank you for your time. 

Bye.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
