### ISSUE TITLE
How to support view other resources data on a resource view

### ISSUE THREAD

**Issue by LMApro** [marmelab/react-admin#2214]
For examples, I have 3 resources that lied on 3 different API endpoints. 
- `<FooResource />` ~ my.api/foo
- `<BarResource />` ~ my.api/bar
- `<BuzResource />`~ my.api/buz

The `<FooResource />` has the correspond Show layout called `<FooResourceShow />`
The `<BarResource />` has the correspond List layout called `<BarResourceList />`
The `<BuzResource />` has the correspond List layout called `<BuzResourceList />`

How can I display `<BarResourceList />` and `<BuzResourceList />` in `<FooResourceShow />`, or in other words, display others resources data in a resource view ?

I tried to import the BarResourceList and BuzResourceList components into the FooResourceShow component, but it doesn't work, because it doesn't know the data to be displayed from BarResourceList and BuzResourceList

I'm using *react-admin 2.2.0*
Any solutions on this case ? 
Thanks

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
