### ISSUE TITLE
SelectArrayInput without choices

### ISSUE THREAD

**Issue by codingmaster** [marmelab/react-admin#2261]
We need an **input** field to enter **multiple values**. In our case tags. The user should be able to enter **new** tags which are not in choices property.

In _admin-on-rest_ you had very nice `<SelectArrayInput source="tags"/>`. It was exactly what we needed.

![image](https://user-images.githubusercontent.com/2438864/44931278-5d16ac00-ad61-11e8-9d98-a515dcd43e27.png)
 Unfortunately in _react-admin_ I wasn't able to find such feature and it is essential for us to move from admin-on-rest to react-admin.
`SelectArrayInput`, which is available works only with predefined choices.
Please help me to solve this problem or to find an alternative solution.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
