### ISSUE TITLE
I have an error with graphcool example

### ISSUE THREAD

**Issue by nmeesang** [marmelab/react-admin#2264]
![40642809_2174512716157073_1572948759032102912_o](https://user-images.githubusercontent.com/13285031/44946745-4ee19200-ae2c-11e8-8f45-30e758d06842.jpg)

I'm sorry for a dumb question i'm new here and new programming
I clone your example project and run it. Why i got an error? how  can i solve it?
thank you  and sorry for my english

**Environment**

* React-admin version: 2.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
