### ISSUE TITLE
How debug with VSCode + Chrome Debug + Docker

### ISSUE THREAD

**Issue by nietzscheson** [marmelab/react-admin#2276]
Hey, hello everyone ...

I would like to know how I can debug this package with vscode and chrome debug on Docker. Outside there is a lot of documentation, I know... maybe you can help me... very grateful...

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
