### ISSUE TITLE
Simple example use the wrong .babelrc

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#2280]
**What you were expecting:**
When starting the simple example (with `make run` or `cd examples/simple && yarn start`), I assumed that the Babel config was in `examples/simple/.babelrc`

**What happened instead:**
Instead, the babel config used is `.babelrc`, at the root folder.

**Steps to reproduce:**
Just try to do anything with `examples/simple/.babelrc`, it will have no effect on the simple example.

**Other information:**
I had hard time trying to make the simple example's webpack config use the right `.babelrc`, perhaps it will work only with Babel 7.
Perhaps, the solution is just to delete `examples/simple/.babelrc`.

**Environment**

* React-admin version: 2.2.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
I think that's a side effect of @material-ui/core requiring babel 7. Looking at the `yarn.lock`, I see both babel 6 and 7 being loaded. That would explain the behavior you're describing, which is [specific to babel 7](https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading). Maybe in the presence of babel 7, the webpack config of the example somehow uses babel7 instead of babel6.

**Comment by fzaninotto** [comment]
We've updated to babel 6 since then, it should be fixed by now.
