### ISSUE TITLE
Delete Bulk button does not use custom dataProvider

### ISSUE THREAD

**Issue by plugow** [marmelab/react-admin#2323]
**What you were expecting:**
Sorry for my English. Delete bulk action or crudDeleteMany should get custom dataProvider and send request.

**What happened instead:**
Delete bulk button does not use custom dataProvider, so does not create header with Authorization

**Steps to reproduce:**
built-in bulk delete button with custom provider or custom button for many records

**Related code:**
custom delete bulk button for example:
`import React, { Fragment, Component } from 'react';
import { connect } from 'react-redux';
import { Button, Confirm, crudDelete, startUndoable, crudDeleteMany } from 'react-admin';

class DeleteBulkButton extends Component {
    state = {
        isOpen: false,
    };

    handleClick = () => {
        const {  basePath, resource, selectedIds, startUndoable } = this.props;
        startUndoable(
            crudDeleteMany(resource, selectedIds, { views: 0 }, basePath)
        );
    };
    
    

    render() {
        return (
            <Button label="Delete" onClick={this.handleClick} />
        );
    }
}

export default connect(undefined, { startUndoable })(DeleteBulkButton);`

**Other information:**
Is it bug or Im doing something wrong? 

**Environment**

* React-admin version:2.3.1
* React version:16.4.1
* Browser: chrome

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
