### ISSUE TITLE
Warning: Missing translation for key: "Illegal invocation"

### ISSUE THREAD

**Issue by ak-il** [marmelab/react-admin#2387]
I'm using `react-admin` with `ra-data-graphql` as my data provider but with a custom buildQuery to match my `postgraphile` server's graphql flavor.  
After invoking GET_LIST for one of my resources I get the following error:
```
Warning: Missing translation for key: "Illegal invocation"
```
I tried to log the actions using a custom reducer. I can see that a failure action is being dispacthed but I can't see where and why...
How can I debug the application to better understand it?
Sadly I can't share the code right now, many thanks!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
