### ISSUE TITLE
InputField doesn't work with ReferenceField in Filters

### ISSUE THREAD

**Issue by evygovskaya** [marmelab/react-admin#2416]
**What you were expecting:**
When I use filters and don't want to use AutocompleteInput, but want to use a TextInput and search by name
```
<Filter {...props}>
	<ReferenceInput source="useId" reference="User" perPage={5}>
		<TextInput source="name" />
	</ReferenceInput>
</Filter>
```
The same as this
```
<Filter {...props}>
	<ReferenceInput source="useId" reference="User" perPage={5}>
		<AutocompleteInput optionText="name" source="useId" />
	</ReferenceInput>
</Filter>
```

**What happened instead:**
When I'm trying to find a user by name, I got an error:
GraphQL error: nora is an invalid Id

Is there a way of using TextInput without changing filters on backend as this works in List with Grid?

**Environment**
The last version of react-admin.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
