### ISSUE TITLE
[Documentation] README.md suggests "npm install --save-dev react-admin" instead of "npm install react-admin"

### ISSUE THREAD

**Issue by ajhool** [marmelab/react-admin#2420]
This is a minor documentation issue so I am ignoring the standard bug report for brevity's sake. Happy to edit to the full format if need be!

The README.md installation section:

> Installation
> React-admin is available from npm. You can install it (and its required dependencies) using:
> 
> npm install --save-dev react-admin

react-admin is a runtime package, so why is --save-dev suggested?

Suggested update: change README.md to use `npm install react-admin` or `yarn add react-admin` instead of `npm install --save-dev react-admin`

**Comment by phacks** [comment]
I was asking myself the exact same question. Did a little bit of digging and it looks like the `--save-dev` dates back to the early days of `admin-on-rest`, 2+ years ago.

Maybe @fzaninotto knows the reason?

**Comment by fzaninotto** [comment]
It dates from my confusion about how React apps are built: since we use webpack at build time, and webpack creates a bundle with all the required dependencies, I thought there were no need for react or react-admin to actually *run* the app. But `dependencies` for SPAs aren't about *running* the app, but about *building* the app. 

So yes, you're right, we can remove `--save-dev`. Would you like to open a PR?

**Comment by phacks** [comment]
@fzaninotto thanks for the explanation! I wouldn’t mind opening a PR, but maybe @ajhool might want to give it a go since they spotted this in the first place. What do you think @ajhool?

**Comment by ajhool** [comment]
Thanks for reminder, see below :)
https://github.com/marmelab/react-admin/pull/2574

**Comment by fzaninotto** [comment]
fixed by #2574
