### ISSUE TITLE
Lost Id of complex record on save action in request of TabbedForm.

### ISSUE THREAD

**Issue by RNagaev** [marmelab/react-admin#2424]
Hello! I have a strange behavior of saving action on Edit form which contains TabbedForm. My data has complex structure: { "id": value, "operators_description": { "id": value } }. So i use a path with dot separators as the source attribute. Everything is ok when I reseived data with GET request from server and responce has existing ID of internal objest. But when I send PUT sequest for save data instead of sending existting ID of internal objest it send ID = 0. 
Here is an example of Edit form:
`<Edit {...props}>
        <TabbedForm>
            <FormTab label="Main">
                <TextField label="Id" source="operators_description.id" />
            </FormTab>
 </Edit >`

Can you help me with this?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
