### ISSUE TITLE
strange behaviour of with 

### ISSUE THREAD

**Issue by vedmalex** [marmelab/react-admin#2432]
Hi!
In advanced tutorials "Custom Forms and UI for related records" we have cool sample of using react-admin for preview record for selected reference.

I have issue with extending it.

if i add reference to preview form don't work at all: it shows and then hides very fast.
to reproduce i've  modified the sample:

https://codesandbox.io/s/mm28kpvx1p

open comment to edit and click preview button next to the post reference control.
![bug](https://i.imgur.com/kmrfrOn.gif)

**Comment by vedmalex** [comment]
if I not use component state, but redux-store it behave like that:
![another-strange](https://i.imgur.com/nBaHDLk.gif)

repository: https://codesandbox.io/s/n03k162q1j

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by vedmalex** [comment]
thank you! i've just update the dependencies and bug disappeared, so thank you
