### ISSUE TITLE
Render crash

### ISSUE THREAD

**Issue by arkkanoid** [marmelab/react-admin#2471]
Hi, 
I'm using React Admin to create my backoffice. 
In my dev environment (with Docker) it's working fine.
But when I deploy to prod I see the backoffice like the following images.
How can I solve it?

I'm using :
node 9.4.0
 react-admin 2.3.4
react 16.5.2
materialui/core 3.1.2

![captura de pantalla 2018-10-25 a las 15 43 58](https://user-images.githubusercontent.com/3811604/47506644-cbaf4c00-d870-11e8-9bb4-9550a3488011.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
