### ISSUE TITLE
error " Cannot read property 'split' of null "

### ISSUE THREAD

**Issue by M-Gouss** [marmelab/react-admin#2482]
I get this error in => Etap Connecting To A Real API
" Cannot read property 'split' of null " 
Please How fixed this error

<img width="1280" alt="screen shot 2018-10-29 at 9 15 34 am" src="https://user-images.githubusercontent.com/7656403/47640531-b3cf1500-db5b-11e8-8bfe-619aaabfe36c.png">

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
