### ISSUE TITLE
Export button should not show up on empty List page

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#2483]
When new users discover a react-admin app, and they have no data yet, the list screen is intimidating.  It shows a "no results found" and an export button...

![image](https://user-images.githubusercontent.com/99944/47641685-019d4a80-db67-11e8-8b40-4834881c6522.png)

- If there is no result, the export button should not appear - or should appear greyed out

**Comment by afilp** [comment]
@fzaninotto Regarding the default "EXPORT" functionality, in most cases we do not need this, as it would require us to do major work on custom "exporter" functions.

Instead of us having to create our own `actions` component, could we just use `exporter = {false}` in order to disable the "EXPORT" functionality? (not show it at all).

The above proposal is exactly similar to what we do with `bulkActions={false}`.

**Comment by afilp** [comment]
Concerning my latest comment above, I have created a PR for your evaluation.

I already use this option in my projects (i.e. hiding the export button inn some Lists) and I have the feeling that others may need it too. It is up to you to decide. Thanks!
