### ISSUE TITLE
how to export all fields data with exporter ?

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2490]
Hello,
I created my react-admin exporter to export my data. But the problem is that I only get the fields I display in my list when I want to export all the fields (even those visible in edit or display). Even with fetchRelatedRecords I don't recover all the data. How to export all existing fields ?

Link: https://stackoverflow.com/questions/53081021/how-to-export-all-fields-with-exporter-react-admin

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by nacimgoura** [comment]
Yes, I know the contributing guide. I first asked my question about stackoverflow but no answer.
Link : https://stackoverflow.com/questions/53081021/how-to-export-all-fields-with-exporter-react-admin
