### ISSUE TITLE
data empty using ReportUserAction component

### ISSUE THREAD

**Issue by arkkanoid** [marmelab/react-admin#2501]
I'm using the following code to create an action on a Edit View:

    const PostEditActions = ({ basePath, data, resource }) => (
    <CardActions>
    <ReportUserAction record={data} />
    </CardActions>
    );

    export const UserEdit = (props) => (
    <Edit title="Modify user parameters" actions={<PostEditActions />} {...props}>
    ....
In ReportUserAction component I receive data = undefined, but I don't know why. The edit view has data:

    {"data":{"locale":"en","status":"enabled","facebookId":"XXXXX","createdAt":"2016-06-    15T20:21:47.000Z",...
And I can access to other variables such as basePath and Resource. I think that maybe it can be a bug, can you check it?

Thanks

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

If you think this really is a bug, please provide a CodeSandbox reproducing the issue. But I suspect there is no bug in this case - the Edit component starts rendering *even before the data is loaded*, so it will render your `PostEditActions` once with no data, then render it again once the data arrives.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
