### ISSUE TITLE
Customization for Menu background and Button Icons

### ISSUE THREAD

**Issue by selenyillar** [marmelab/react-admin#2507]
I'd like to know if we can change the background color of the left Menu and can add custom icons to `EditButton`, `ShowButton` and `DeleteButton`.

It would be great if they have icon and some design related props.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by selenyillar** [comment]
@djhi Actually, I was requesting for new features. On stackoverflow I already asked question for how to change the background.

**Comment by djhi** [comment]
This is already possible as explained in the [documentation](https://marmelab.com/react-admin/Theming.html#using-a-custom-menu).

Besides, please don't cross post from StackOverflow here.
