### ISSUE TITLE
FunctionField render component inside

### ISSUE THREAD

**Issue by darkiron** [marmelab/react-admin#2520]
Hi, 
It seem's it possible to render a component inside a FunctionField
like this [https://api-platform.com/docs/admin/getting-started#managing-files-and-images](https://api-platform.com/docs/admin/getting-started#managing-files-and-images)

This doesn't work, document need some improvements

**Comment by fzaninotto** [comment]
We don't maintain the API platform documentation, please open an issue on their GitHub issues instead.

**Comment by darkiron** [comment]
I speak about your because I little bite more simpler than your components.  React-admin is not maintained by other team than you, you have made this component you know How is work... 


Wait 5 days to found bad answers ...

You  answer me you don't know how work your's components ?

**Comment by djhi** [comment]
The URL you posted is from the api-platform project which uses react-admin but is not react-admin. We don't maintain api-platform

**Comment by fzaninotto** [comment]
If you met a bug with react-admin, please describe it here, instead of linking to a large chunk of code located in a site we don't maintain, without explaining what it outputs and what you expected instead. 

We wrote an issue template to help you describe your issue in a way we can understand. Please follow it.
