### ISSUE TITLE
props become undefined after calling another UR

### ISSUE THREAD

**Issue by modiodio** [marmelab/react-admin#2545]
Hi there ,
I have a weird bug with react admin, the bug occurs in the "show" screen. The code is below
```
<Show {...props}>
    <SimpleShowLayout>
            <TextField source="givenName"/>
            <TextField source="familyName"/>
            <DateField source="email"/>
            <ReferenceManyField label="" reference="user-projects" target="user" >
            	<Datagrid {...props}>
	                <ReferenceField label="Invitation receiver" source="user" reference="users" allowEmpty sortBy="user.givenName">
	                    <TextField source="givenName" />
	                </ReferenceField>
	                <TextField source="status"/>
	            </Datagrid>
            </ReferenceManyField>
    </SimpleShowLayout>
</Show>
```

CALL 1 : The "show" action automatically fetch the user details below :
```
GET /api/users/1
{
	@context: "/api/contexts/User"
	@id: "/api/users/1"
	@type: "http://schema.org/Person"
	email: "test1@test.com"
	givenName: "Martin"
	familyName: "Lelong"
}
```

CALL 2 : The call attached to the "ReferenceManyField" get the JSON below :
```
[
	{
		@id: "/api/user-projects/1"
		@type: "UserProject"
		id: "1"
		isAdmin: true
		isMember: true
		status: "ACCEPTED"
		user: {
			@id: "/api/users/1"
			@type: "http://schema.org/Person"
			givenName: "Martin"
			familyName: "Lelong"
		}
        }
]
```

I do not understand why the result of the "call 2" replace the result of the "call 1".
I think there is a mechanism that detect the URL of the resource (@id: "/api/users/1") and replace it with the most recent result.
The consequence of this is the "email" wich present in the "call 1" becomes undefined after the execution of the "call 2".
Any idea ?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
