### ISSUE TITLE
Empty choice added to SelectInput in Filter

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#2546]
You have to set **allowEmpty={false}** explicitly to avoid empty choice.

```
const ManagerFilter = (props) => (
    <Filter {...props}>
        <TextInput label="app.search" source="q" alwaysOn resettable clearAlwaysVisible />
	<SelectInput label="app.is_active" source="is_active" 
		choices={[
			{ id: 'active', name: 'app.yes' },
			{ id: 'inactive', name: 'app.no' },
		]}
	/>
    </Filter>
);
```

**Environment**

* React-admin version: 2.4.2

**Comment by fzaninotto** [comment]
Hi, and thanks for opening the Issue. 

What you describe is a feature of react-admin - we designed filters like that on purpose. If we didn't do that, there would be no 'empty' state for a filter with several choices.

I'm closing this issue because we won't change that behavior, but I'm still curious to understand why that `allowEmpty` bothers you.

**Comment by esoulution** [comment]
Why did I submit this issue? In a form you add `allowEmpty` to have empty choice, for example
```
<ReferenceInput label="app.priority" source="campaign_priority_id" reference="campaign-priorities" allowEmpty {...props}>
    <SelectInput />
</ReferenceInput>
```
In a filter form, empty choice added by default, so that is some inconsistency IMHO, but I'm OK with different approach for the filters.
