### ISSUE TITLE
Map ReferenceInput to a different source

### ISSUE THREAD

**Issue by trsteel88** [marmelab/react-admin#2570]
I am having an issue mapping a SelectInput to the correct source.

I have the following dataset:

```json
{
@id: "/template-shots/1"
@type: "TemplateShot"
id: 1
name: "Name 1"
shotType: "/shot-types/1"
}
```

Since the shopType comes back as an IRI, it doesn't map to the SelectInput correctly. It only works if shotType is "1".

My form is as follows:

```
<ReferenceInput source="shotType" reference="shot-types">
    <SelectInput source="@id" optionText="name" />
</ReferenceInput>
```

Should the above tell SelectInput to use @id as the map?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
