### ISSUE TITLE
dataProvider field selection

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [marmelab/react-admin#2599]
**Is your feature request related to a problem? Please describe.**
Oftentimes only a subset of REST resource fields are needed, especially in the `List` case. We already have needed fields described in `<DataGrid>`,`<SimpleShowLayout>`, etc. Why don't we use this to add another query parameter for `GET`, `GET_MANY`, containing a list of field names needed.

**Describe the solution you'd like**
Getting a list of defined field names from  `<DataGrid>`,`<SimpleShowLayout>`, etc., and provide those to `dataProvider` in `params.fields`. This will be backward compatible with all existing data providers, since they will not know about this `params.fields` and will fetch the complete REST document.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

We choose not to parse the children of the `List` or `Edit` views to grab the list of fields before querying the dataProvider because they can be at any depth, and of any type (field, input, etc). We did the opposite in the precusrsor of react-admin, ng-admin, and it caused many issues.

You can tweak your `dataProvider` to retrieve just a subset of fields depending on the verb (`GET_LIST`, `GET_ONE`). You'll have to maintain a list of fields in two files, that's all.
