### ISSUE TITLE
Is there a way to remove anchor tag from url?

### ISSUE THREAD

**Issue by kumarpatel** [marmelab/react-admin#2642]
Already checked stackoverflow for answer. No luck.

Default url for home page `http://localhost/#/`
Default url when navigating from side menu to a resource is `http://localhost/#/<resource>`

How do I remove this anchor tag from all my routes? (or even some)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by kumarpatel** [comment]
https://stackoverflow.com/questions/53709040/is-there-a-way-to-remove-anchor-tag-from-url
