### ISSUE TITLE
default routes modification

### ISSUE THREAD

**Issue by MohammedFaragallah** [marmelab/react-admin#2647]
I'm using react-admin to manage my app's front-end (website/management dashboard) and strapi for the back-end its really great together but i have some problems and I'm not very sure what to do without Including React-Admin In Another Redux Application this is exactly how I'm trying to do. 
- '/' route will serve a custom no layout component.
- couple other predefined routes like '/contacts'  '/about'
- '/dashboard' will serve react-admin <Admin> component dashboard instead of '/'
- resources as default '/resource name'
  I would prefer to prefix everything that belongs to react-admin because it meant to be reached by admins only.
- for not found also a custom (404) nolayout component.

I would love to help but I'm very new to development so I'll need some guidance.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by MohammedFaragallah** [comment]
@djhi Thank you for your response but I don't think it a how-to as much as a feature request because after some investigation I don't think its possible out of the box because its hard coded in the CoreAdminRouter

**Comment by MohammedFaragallah** [comment]
here is the answer to what i was really asking
i'm putting it here because it's a really common scenario and it took me a lot of time searching for this really simple solution

https://stackoverflow.com/questions/50402692/mount-react-admin-under-admin
