### ISSUE TITLE
ra-data-graphql-simple: No query or mutation matching aor fetch type DELETE could be found for resource

### ISSUE THREAD

**Issue by kfern** [marmelab/react-admin#2663]
Hello.

I have a basic graphql poc using json-graphql-server. I followed steps from https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/README.md and https://github.com/marmelab/json-graphql-server

List, Create, Show and Edit works fine. Delete fail with "No query or mutation matching aor fetch type DELETE could be found for resource". 

removePost mutation works fine in json-graphql-server/graphiql

Any idea?

I can't find any online demo to reproduce it. Are there any?

Thanks in advance

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
