### ISSUE TITLE
nolayout routes customisation

### ISSUE THREAD

**Issue by MohammedFaragallah** [marmelab/react-admin#2680]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to use react-admin as a part of my react app but it already has everything I need (routing, redux store, sagas, etc) and by following the documentation on [CustomApp](https://marmelab.com/react-admin/CustomApp.html) it didn't get me anywhere.
So if I'm able to use a custom no layout 404 pages there will be no need for CustomApp.

Current behavior 
- custom routes will be tested first (nolayout available).
- '/' will be tested to render react-admin app if not customized 
  (I suggest to make it customisable as a prefix to the admin panel i.e "/management/{resource name}").

- Forced react-admin layout routes
1. resources routes.
2. catchall
3. dashboard

**Describe alternatives you've considered**

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
