### ISSUE TITLE
DateTimeInput not working in Firefox and Safari

### ISSUE THREAD

**Issue by tomtom16** [marmelab/react-admin#2685]
**What you were expecting:**

Expected Behaviour is only in Chrome --> Datepicker opens, Time can also be set
<img width="300" alt="screenshot_chrome" src="https://user-images.githubusercontent.com/23172948/50304119-656d3100-048f-11e9-9cec-4509e70487c4.png">

**What happened instead:**

String value is shown, but is not editable.
<img width="315" alt="screenshot_firefox" src="https://user-images.githubusercontent.com/23172948/50304078-4e2e4380-048f-11e9-8b94-7753e2582d8a.png">

**Steps to reproduce:**

Add DateTimeInput to your Edit Configuration and open in the different browsers

**Related code:**

```
<DateTimeInput source={property.name} />
```

**Other information:**

**Environment**

* React-admin version: ^2.4.4
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.5.2
* Browser: Firefox and Safari not working; Chrome working

* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
hi, and thanks for your bug report.

What you describe is the documented behavior (see https://marmelab.com/react-admin/Inputs.html#datetimeinput), and it's due to variable browser support of the `datetime-local` input type (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local). There is nothing more we can do.

As explained in the docs, if you need a cross-browser, material-ui styled DateTime input, check out https://github.com/vascofg/react-admin-date-inputs.

**Comment by martdavidson** [comment]
The confusion is that the docs only mention Safari - not Firefox. I was bit by the same.
