### ISSUE TITLE
Page rendering fails if List view is passed bulkActions={true}

### ISSUE THREAD

**Issue by kodepareek** [marmelab/react-admin#2687]
**What you were expecting:**
I am reusing a certain List component on multiple locations. I would like to have the bulkActions enabled based on the basePath.

`const displayBulkActions = basePath && basePath.substring(1) === newOrders ? true : false
`

**What happened instead:**
However if displayBulkActions == true then the component does not render with invariant violations.

**Steps to reproduce:**
As above

**Important Note**
Everything renders fine if bulkActions={null}

**Environment**
* React-admin version: 2.3.4
* Browser: firefox
* Stack trace (in case of a JS error):

**Comment by kodepareek** [comment]
**Stack Trace**: 
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback.

- `bulkActions` is deprecated since 2.3.0. You should use `bulkActionButton` instead.
- `bulkActions` expects an element of `false`. Passing `true` isn't supported (I don't even know what you would expect by that).

For your need, you'll have to wrap the default ListActions inside another component.
