### ISSUE TITLE
Build simplification

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#2701]
react-admin build contains some drawbacks, can be optimized and simplified.

Examples:

- lot of modules generate target files for both es2015 and esm modules. This is time consuming and uneccessary
- debugging is done with transpiled es5 js files and not with original js/ts source files
- Some modules or examples projects contains babel/webpack build. Its unneccessary because react-script 2.1.x can build now js/ts files. 
- Simple project build could be simplified, to be like others examples project. 

I'm building a react-admin fork with theses enhancements described. 

I'll make a pull request tonight or tomorow  with these modifications.

**Comment by fzaninotto** [comment]
We deliberately have examples using Create-React-App and examples not using it. In particular, not using CRA in the simple example allows us to use module aliases in webpack, which speeds up the development a great deal (we don't need to rebuild after a change in react-admin to see the result in the simple example) and wouldn't be possible in a CRA app (unless ejecting CRA, which defeats the purpose of using it).

Feel free to open a PR that brings actual benefits. This issue is too broad.
