### ISSUE TITLE
CloneButton should sanitize its rest props

### ISSUE THREAD

**Issue by djhi** [marmelab/react-admin#2781]
**What you were expecting:**
Using a `<CloneButton />` inside an `<Toolbar />` from an `Edit` view should not trigger any React warnings

**What happened instead:**
Lots of warnings about unkown props passed by the `<Toolbar />`

**Steps to reproduce:**
Using a `<CloneButton />` inside an `<Toolbar />` from an `Edit` view .

**Related code:**
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/CloneButton.js#L25

**Environment**

* React-admin version: 2.6.1
* Last version that did not exhibit the issue (if applicable):

**Comment by fzaninotto** [comment]
I'm not sure we should address this case.

`<CloneButton>` is designed to be used in an edit view *Actions* component, not inside a *Toolbar*. The Toolbar is basically for submitting the form, not for going to another resource. If we support the usage of any button inside `Toolbar`, then we can't pass specific props that are useful to `SaveButton` only. Or we need to specifically sanitize the props injected by Toolbar, which seems like encouraging a bad pattern.

But since we don't explicit the purpose of `Toolbar`, let's address it.

**Comment by mnlbox** [comment]
@fzaninotto Please add this as a note to docs. I lost 3 hour until find this issue and fix my problem :disappointed: 
> `<CloneButton>` is designed to be used in an edit view _Actions_ component, not inside a _Toolbar_. The Toolbar is basically for submitting the form, not for going to another resource.

**Comment by djhi** [comment]
@mnlbox Waiting for your PR :wink:

**Comment by mnlbox** [comment]
I'm a little new in react-admin and I think it's a little soon for me but thanks for your suggestion. :thinking:

**Comment by djhi** [comment]
This is a documentation pull request. The documentation is located [here](https://github.com/marmelab/react-admin/tree/master/docs) and it seems you already have the text to put in it :)

**Comment by mnlbox** [comment]
@djhi I done it man: #2904 :wink:
