### ISSUE TITLE
Text not displaying correctly

### ISSUE THREAD

**Issue by hamzayoussef** [marmelab/react-admin#2809]
**What happened instead:**
![image](https://user-images.githubusercontent.com/22435038/51706829-e59f2d00-201f-11e9-9c0d-05b21805788a.png)

**Repository**
https://github.com/hamzayoussef/store-client

**Environment**

"@material-ui/core": "~1.4.0",
"@material-ui/icons": "~1.1.0",
"react": "~16.3.1",
"react-admin": "^2.0.0",
"react-app-polyfill": "^0.1.3",
"react-dom": "~16.3.1",
"react-redux": "~5.0.7",
"react-router-dom": "~4.2.2",
"react-scripts": "^2.0.5",
"recompose": "~0.26.0",
"redux-form": "~7.4.0",
"redux-saga": "~0.16.0",
"prop-types": "^15.6.2",
"query-string": "6.1.0",
"ra-data-json-server": "^2.4.2",
"ra-input-rich-text": "^2.4.2",
"ra-language-english": "latest",
"ra-language-french": "^2.3.1",
"react-dropzone": "latest"

**Comment by fzaninotto** [comment]
Sorry, what's not displaying correctly? What did you expect?

**Comment by hamzayoussef** [comment]
Instead of "ra.action.create", it should be normally "Create", that's what I'm expecting ...
It's look like a resource file has a relationship with i18n is broken ...
![image](https://user-images.githubusercontent.com/22435038/51837625-3a82c200-2304-11e9-89ae-a05cbebf3f79.png)

**Comment by fzaninotto** [comment]
I suspect it's a bug in your code with the way you handle i18n. If you think the opposite, and you can replicate the bug outside of your project, please for the standard CodeSandbox to show the issue in the simple example. The link for your code forces us to understand your domain before trying to figure out if the bug is on your side or on react-admin-s side, so it's too much work.
