### ISSUE TITLE
customReducers

### ISSUE THREAD

**Issue by rankaifeng** [marmelab/react-admin#2827]
By the way, if I register a global state in redux, how can I get this state in another js

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
