### ISSUE TITLE
set aMonthAgo correctly

### ISSUE THREAD

**Issue by hanhgia** [marmelab/react-admin#2837]
**What you were expecting:**

**What happened instead:**

**Steps to reproduce:**

**Related code:**

```
var aMonthAgo = new Date();
// Set it to one month ago
aMonthAgo.setMonth(aMonthAgo.getMonth() - 1);
// Zero the hours
aMonthAgo.setHours(0, 0, 0);
// Zero the milliseconds
aMonthAgo.setMilliseconds(0);
```

**Other information:**

https://github.com/marmelab/react-admin/blob/a466471fa089d83b261d617d8badd0be84240f0d/examples/demo/src/dashboard/Dashboard.js#L25

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Well, the "monthly revenue" displayed the dashboard could be the revenue over the last 30 days, revenue from the beginning of the month, or revenue from the same date the previous month. These are different definitions, none of them are wrong. The right one is the one that makes sense to the customer. 

And, since this is a demo, I'm fine with the 30 days definition.
