### ISSUE TITLE
Wanted: DataProvider that doesn’t require changes on the backend

### ISSUE THREAD

**Issue by tomsoderlund** [marmelab/react-admin#2853]
I’m trying to get a simple admin system running but the DataProviders won't work with my JSON backend.

- `ra-data-simple-rest` needs header `Content-Range`
- `ra-data-json-server` needs header `X-Total-Count`

Side-note: why different header names on these two DataProviders?

Can I somehow get it to work without these headers?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
