### ISSUE TITLE
Elegant way add full page like login?

### ISSUE THREAD

**Issue by maicss** [marmelab/react-admin#2862]
Add some full page route like login, eg: register?

For now I am thinking of write a full width and full height page, with rise `z-index` value to cover menubar and drawer, then add route to `Admin -> customRoutes`, to looks like a isolate page

Is there a elegant way to do this?

thanks

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by maicss** [comment]
ok...

https://github.com/marmelab/react-admin/blame/master/docs/CustomApp.md#L238

```
+export default withContext(
+   {
+       authProvider: PropTypes.func,
+   },
+   () => ({ authProvider })
```

looks like write propType into `mapStateToProps`
@fzaninotto

**Comment by maicss** [comment]
code in [this page](https://marmelab.com/react-admin/CustomApp.html) cannot run, so many errors...

would you improve this page? Thanks a lot
