### ISSUE TITLE
Getting "Unknown resource", but resource defined in the back

### ISSUE THREAD

**Issue by aleguern** [marmelab/react-admin#2865]
Hello, this is my first time opening an issue !

I've got a strange issue with naming variables in my server.

Example : 

When I write my graphql query using a simple like the word "Dog" it works, but when I change it to "Salesperson" it doesn't work anymore ...

Resolver : 
```
Dog(parent, args, context, info) {
      return dogs[0];
    },
    allDogs() {
      return dogs;
    },
    _allDogsMeta() {
      return 2;
    },

    Salesperson(parent, args, context, info) {
      return Salespersons[0];
    },
    allSalespersons() {
      return Salespersons;
    },
    _allSalespersonsMeta() {
      return 2;
    }
```
Graphql definition : 

```
type Query {
    Dog(id: ID!): Dog
    allDogs: [Dog]
    _allDogsMeta(
      page: Int
      perPage: Int
      sortField: String
      sortOrder: String
      filter: ClientFilter
    ): ListMetadata

    Salesperson(id: ID!): Salesperson
    allSalespersons: [Salesperson]
    _allSalespersonsMeta(
      page: Int
      perPage: Int
      sortField: String
      sortOrder: String
      filter: ClientFilter
    ): ListMetadata
}

  type Dog {
    id: ID!
    name: String!
  }
  type Salesperson {
    id: ID!
    firstName: String!
    lastName: String!
    email: String!
  }
```

What could be the problem ? Thanks.

**Comment by aleguern** [comment]
After multiple tests the problem seems to be the numbers of character in the query.

when the word is lower or equal than 8 it is working but when it's greater it's not ...

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
