### ISSUE TITLE
Title is overriden by react-admin components title in custom page

### ISSUE THREAD

**Issue by EricTousignant** [marmelab/react-admin#2869]
**What you were expecting:**
I was expecting to see the title I defined in my custom page with <Title> to be displayed.
Any title for the AppBar defined in a <Title> should take precedence over any other title input.

**What happened instead:**
Because my custom page is using a show and edit form for the user, the title from the form is overriding the page title that I defined. And if I were to show two forms, I see a double title.

**Steps to reproduce:**
Create a custom page
Add a custom <Title>
Add two show/edit/create/list components in the page
See the result in the AppBar (double title from the components, title from <Title> is not there)

![screenshot](https://user-images.githubusercontent.com/2239084/52598527-fcb58b80-2e23-11e9-894e-f1594606bb9b.png)

**Related code:**
```
<Title>My Profile</Title>
<Show title="Show Profile" resource={Resources.User} > [...] </Show>
<Edit title="Edit Profile" resource={Resources.User} > [...] </Edit>
```

**Other information:**
I tried not setting the title attribute on the forms, as well as setting it empty or null and then the title was the default form title, still overriding the <Title>.

**Environment**

* React-admin version: 2.7.0
* React version: 16.8.1
* Browser: Chrome

Thanks

**Comment by fzaninotto** [comment]
Hi Eric, and thanks for this report.

As explained in [this tutorial](https://marmelab.com/blog/2019/02/07/react-admin-advanced-recipes-creating-and-editing-a-record-from-the-list-page.html), this is the desired behavior and the fix is easy (just set the title of one of the two components as a single space).

I don't see how react-admin can do otherwise: if two components set the title, how can react-admin decide which ones takes precedence on the title ? And it can't be based on the order in which they appear in your code, as the render order can vary significantly (think rerenders and pure component optimizations).

So we won't fix this.

**Comment by EricTousignant** [comment]
Thank you for the explanation as to why it was decided the way it was.

I was also seeing an issue because I was not using the <Title> tag properly.

Sorry and thank you :)
