### ISSUE TITLE
Store Row Expansion state

### ISSUE THREAD

**Issue by kdabir** [marmelab/react-admin#2884]
**Problem:**
When using Row Expansion feature, if I traverse from expanded row to another url, there is no way for me to come back to the expanded row. I have to find out and expand the row again.

**Proposed Solution:**
React-Admin should store the expansion state of the row (in URL hisotry) so that browser back and redirects (from form submits) can take back to the original expanded row.

**Demo:**
The following gif demonstrates the problem in the React-Admin demo site
![expansion](https://user-images.githubusercontent.com/735240/52763823-534ce080-3043-11e9-8bc9-deffa2580ddb.gif)

If I traverse from a given invoice to its details page and then I go back, I see the unexpanded row which makes it hard for me to figure out which row was expanded in the first place.

**Comment by fzaninotto** [comment]
Hi @kdabir, and thanks for your suggestion. I modified the issue name to express that we prefer storing that kind of UI state in the redux store rather than in the URL. 

I'm marking this as an enhancement.

But since we don't need it ourselves, we won't work on implementing it. Any PR on the subject is welcome. If the community doesn't provide an implementation, we'll eventually close this issue as keeping all possible feature requests adds a lot of noise.

**Comment by fzaninotto** [comment]
Fixed by #4624
