### ISSUE TITLE
Integrate with react-jsonschema-form for more complex form handling

### ISSUE THREAD

**Issue by mnlbox** [marmelab/react-admin#2896]
**Is your feature request related to a problem? Please describe.**
Integrate with [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) for form generation then we can implement complex form more easier.

**Describe the solution you'd like**
Have a form component that integrate with react-admin for CRUD operation.

**Describe alternatives you've considered**
Do all thing manually.

Let's talking about this here.

**Comment by djhi** [comment]
Hi and thanks for your suggestion. This is not something we need nor want to maintain and nothing prevents you to do it in userland. I suggest you implement this as an addon package and we'll include it in the [ecosystem](https://marmelab.com/react-admin/Ecosystem.html) documentation.

**Comment by fzaninotto** [comment]
Also, "implement complex form more easily" is a bit too broad for us to understand your need. what exactly are you trying to achieve that the current stack doesn't allow you to do?

**Comment by UltimateForm** [comment]
@fzaninotto  hi, and sorry for resurrecting a dead issue, but I might be able to clarify what he wanted because it is something I want too and I have implemented it on my side. It's essentially about drastically reducing the complexity in writing and maintaining forms for very complex objects -and you can stop reading there if you're not interested, or skip to end

On a project I am working on I have very complex objects that work with modular data, as in, imagine the resource is "person" and depending on the environment I might want or not want to input data for "clothing" and/or "body", each of these can  grow quite big in terms of fields

it'd be very inefficient to write and **maintain** forms for each module in this "person" resource so an automatic measure would be great improvement here, here's a quick example:
![image](https://user-images.githubusercontent.com/24314735/76004715-dcaaab80-5f01-11ea-9971-807f54ff8fbe.png)


these are buttons inside SimpleForm that go to a new form generated by the package above mentioned, the best thing about this is that the management of this form is centralized at the server through its JsonSchema generation (have in mind that a lot of APIs these days already use this through [swagger](https://swagger.io/tools/swagger-codegen/), which also helps fixing compatibility issues, i.e.: if the server no longer requires a field or a field changed datatype i don't need to worry about updating input fields on the react-admin front end

[react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) is a great tool that does a quite good job in generating forms from json-schemas, I've been using it alongside react-admin to tackle the problem above mentioned but there are some itchy aspects in the mix, many arising from the different UI systems, react-jsonschema-form allows you to customize the UI but it's still a limited system and right now it's hard to make it dance well with react-admin - which is why i have placed the generated forms inside dialogs that are called by the buttons in the image - (there's also the bootstrap bias on the package), another itchy aspect is that react-jsonschema-form is based on redux-forms which you guys probably want to distance yourself from at this point

**What can you do about this?** In my opinion integrating with react-jsonschema-form would not be the best approach. However I think it'd be of great value to have that level of automation on react-admin. I can do it myself, like most of things, but it will never be as robust. And I do believe this will be a recurring request as react-admin grows

**Comment by mjattiot** [comment]
We, indeed, have the exact same issue.
Having a "model-based" generated UI is very important to be very efficient. Like stated by @UltimateForm it's very common to have dynamic objects that have a structure that changes based on business rules. Such objects need to be visualized and edited (forms). We are working for major banks and I can tell you that such GUI is deeply required.
We are in the process of choosing new technologies for our frontend team and we would love having react-jsonschema-form implemented (in some way) into react-admin enterprise edition.

**Comment by gustavorps** [comment]
+1

**Comment by qianxuanyon** [comment]
Have the same needs

**Comment by fzaninotto** [comment]
Good news: The Enterprise Edition now contains a `<JsonSchemaForm>` component that does the integration of react-admin and react-jsonschema-form. It even includes a `<ReferenceInput>`!

https://marmelab.com/ra-enterprise/modules/ra-form-layout#jsonschemaform

**Comment by UltimateForm** [comment]
@fzaninotto it's a joy to finally have this included :) good work
