### ISSUE TITLE
[Bug] resourcesRoutes list is sensitive to ordering

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#2910]
We have the following `resourcesRoutes`:

```jsx
    <Resource
      name="project-management/projects"
      list={ProjectList}
      edit={ProjectEdit}
      create={ProjectCreate}
      show={ProjectShow}
    />,
    <Resource
      name="project-management/projects/services"
      list={ProjectServiceList}
      edit={ProjectServiceEdit}
      create={ProjectServiceCreate}
      show={ProjectServiceShow}
    />,
```

This fail to generate a working `<Route />`, because `project-management/projects/services` will catch before `project-management/projects`.

Instead we must order it DESC :  

```jsx
    <Resource
      name="project-management/projects/services"
      list={ProjectServiceList}
      edit={ProjectServiceEdit}
      create={ProjectServiceCreate}
      show={ProjectServiceShow}
    />,
    <Resource
      name="project-management/projects"
      list={ProjectList}
      edit={ProjectEdit}
      create={ProjectCreate}
      show={ProjectShow}
    />,
```

This will make a valid `<Route />`.

It can also be solved using `exact` props, and `customRoutes`, but this is too sensitive for being an expected behaviour, and it is not specified anywhere in the documentation.

If you agree, this ticket consists of taking all the user props from `<Resource />` and pass them to the `<Route />` component.

https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/Resource.tsx#L80

**Comment by fzaninotto** [comment]
> This fail to generate a working `<Route />`, because `project-management/projects/services` will catch before `project-management/projects/visibilities`.

I don't see how that can be possible. On which URL? 

> Taking all the user props from `<Resource />` and pass them to the `<Route />` component.

Which props are you thinking about? Also, one `Resource` creates up to 4 routes, I'm not sure that additional props make sense for all 4 routes.

I suspect you have a very custom use case, in which case I advise implementing your own `<Resource>` component.

**Comment by kopax** [comment]
> I don't see how that can be possible. On which URL?

The router tries to match your routes in the order they are defined, this is how react-router work.

https://github.com/ReactTraining/react-router/issues/1677#issuecomment-129484241

> Which props are you thinking about?

- `exact`
 - https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#exact-bool
 - https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path

If we allow `exact`, why not allowing `strict` too ? https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#strict-bool

**Comment by fzaninotto** [comment]
> The router tries to match your routes in the order they are defined, this is how react-router work.

I don't understand how an URL like `project-management/projects/visibilities` can be caught by a route like `project-management/projects/services`. The two don't match.

**Comment by kopax** [comment]
You are right, I was pasting the wrong example.

**Comment by fzaninotto** [comment]
I'm wondering why we don't use `exact` in the first place. It should not break BC on existing apps, am I right @djhi?

**Comment by fzaninotto** [comment]
@kopax thanks for the detailed description. There is indeed a bug.

**Comment by kopax** [comment]
Thanks do you want me to fix this? What action do you prefer?

**Comment by fzaninotto** [comment]
Let's wait for @djhi's feedback before deciding on a fix.

**Comment by kopax** [comment]
@djhi any though about this one?

**Comment by djhi** [comment]
Sorry, missed this one. I'm ok for using `exact` ou our routes.

**Comment by kopax** [comment]
I was hitting this more and more while adding resources. Can we add this to next release? Thanks.

**Comment by kopax** [comment]
@fzaninotto @djhi, I have found that `MuiTab` does not work well with `exact`, because the `<Switch />` in charge of rendering them will not trigger the rendering when `exact` is set.

I purpose the following fix:

1. We allow `<Resource exact={false} />` and set `exact: true` by default.
2. User who wants `MuiTab` must set `exact` to their resource route (`BREAKING CHANGE` if (1) is true)
3. We allow `<Resource list={(props) => <List {...props} exact />} />`, and during `<Route />` creation, we omit `props.exact` on the `<List />` and use it on `<Resource />`

Regarding (3), because they are all tight coupled to the URL, it is not dirty to apply a route props on them. This would only work on `<Resource />` and we could keep using `<List />` on `customRoutes` as usual.

To remove the breaking change, we could just keep `exact: false` by default.

This will have benefits:

- User decide route logic 100%
- Tabs can work, and there is not side effect except for tabs children route that are not existing:

Example:

- `/:id/show/2` => correspond to `tab 2`
- `/:id/show/2/something/awesome` => If a link exist to this route, and the page is `404`, instead of showing 404 it will display `/:id/show/2`.


If you agree with or without (1), I can do it.

**Comment by santaclauze** [comment]
Hey, I have a similar issue.

I have a custom route `/:resource/:id/authorities/show` where :resource = users that is linked via a resource route `/users`.

I have been unable to reach my custom route and was redirected towards my resource route. After investigation, the easiest way to fix this was to change my custom route as following:

My resource route:
```jsx
    <Resource
      name={"user-management/users"}
      list={UserList}
      edit={UserEdit}
      create={UserCreate}
      show={UserShow}
    />
```

My custom route:
```jsx
    <Route path={"/:resource/:id/authorities"} component={AuthoritiesEdit} />
```

The route couldn't render. We use the `sort` fix, but because the sort happen **on two separate** list, it is still not sufficient to do it userland.

The quickest fix i found was the following: 
```jsx
-  <Route path={"/:resource/:id/authorities"} component={AuthoritiesEdit} />

+  <Route path={"/authorities/:resource/:id"} component={AuthoritiesEdit} />

```
Could we please support `exact` on resource instead of forbidding path?

**Comment by kopax** [comment]
We need to give back the control to the end user, could we please have an update on this issue?  I'll gladly help to implement the next specification to see it release soon.  

As a reminder, tabs needs `exact: false` while we generally want to have `exact: true` for our route, but that's not always true if we encapsulate `<Switch />` within each over.

**Comment by fzaninotto** [comment]
I'm not fond of any of the solutions you've suggested:

- Making TabbedForm fail by default is a no-go. It is used more often than resources with overlapping names 
- The alternative, defaulting to `exact=false`, which is what we do, means that people will get the bug you described. Whatever the solution is, they'll have to search in the documentation first. 
- It's not possible to have `exact=true` on CRUD routes AND TabbedForm, and that's a serious limitation. 

Also, using resource names that are actually paths is mixing responsibilities between the frontend and the backend. In react-admin's design, it's the data provider's responsibility to translate a resource name into an API URL. This makes me think that the problem you're having in the first place it due to a wrong usage of react-admin.

So I maintain my initial reaction: your use case isn't supported by react-admin, and you should write your own `Resource` component. 

I'll close this issue and the related PR. Thank you anyway for helping us understand the problem.

**Comment by kopax** [comment]
That could definitely be done in the `dataProvider`. But what if we want to have similar links between the two, 99% of the code can do it, the current implementation doesn't give us the grain to configure the router properly. 

I offer an alternative that is quite good, using sorting (by PATH desc) won't have any effect on the current strategy for all use cases. I recommend to use that one.
