### ISSUE TITLE
React Router 404 not found 

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#2911]
I have written the login Page router below.  I have to integrage with okta
When the okta returns back to /implicit/callback i get 404 not found nginx.This works fine in my local.but when i move to dev env i get this error

<Route path='/implicit/callback' component={ImplicitCallback}/>

<Router>
        <Security issuer={config.issuer}
                  client_id={config.client_id}
                  redirect_uri={config.redirect_uri}
        >
        <Switch>
          <Route path='/' exact={true} component={Home}/>
          <Route path='/implicit/callback' component={ImplicitCallback}/>
          </Switch>
        </Security>
      </Router>

**Comment by anuraram12345** [comment]
<Route path='/implicit/callback' component={ImplicitCallback}/>

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
