### ISSUE TITLE
TypeError: buildQueryFactory is not a function

### ISSUE THREAD

**Issue by nunovieira** [marmelab/react-admin#2934]
**What you were expecting:**

Initialize dataProvider with ra-data-graphql.

**What happened instead:**

Error in browser console:

> Unhandled Promise Rejection: TypeError: buildQueryFactory is not a function. (In 'buildQueryFactory(introspectionResults, otherOptions)', 'buildQueryFactory' is undefined)

**Steps to reproduce:**

[Sample application](https://github.com/nunovieira/react-admin-tutorial)

**Related code:**

ra-data-graphql uses this `buildQueryFactory` that's not defined anywhere.

https://github.com/marmelab/react-admin/blob/648289aaf83511f66391dd05efd3b3e8ce50bdb6/packages/ra-data-graphql/src/index.js#L78

**Other information:**

Is `buildQueryFactory` supposed to be the same as in [ra-data-graphql-simple](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildQuery.js)?

**Comment by Kmaschta** [comment]
This variable is defined when destructuring the provider options: 

https://github.com/marmelab/react-admin/blob/648289aaf83511f66391dd05efd3b3e8ce50bdb6/packages/ra-data-graphql/src/index.js#L56

But this parameter `buildQuery` isn't provided by default and the documentation is lacking details about this variable (at least at the start).

I tag this one as a bug since either the documentation should be improved or a condition might be wrote.

Thanks for reporting!

**Comment by nagad814** [comment]
how will this work when directly passing an Apollo Client?

**Comment by dougwithseismic** [comment]
I feel documentation hasn't been updated to explain this well enough. Also have same query as @nagad814

**Comment by fzaninotto** [comment]
@dougwithseismic your PR with a better explanation is welcome. Also, I don't understand the Apollo 1 comment, please be more specific.

**Comment by dougwithseismic** [comment]
Sure thing - If can manage to get a working example going then I'll submit.
Re Apollo Client, the readme includes functions found in Apollo Client 1.x,
not 2.x
 - again, I'll cover that in an example.
