### ISSUE TITLE
[RFC] Message priority for notification side effect on failure

### ISSUE THREAD

**Issue by sorjef** [marmelab/react-admin#2949]
**Steps to reproduce:**
Custom action example:
```js
{
    type: CUSTOM_TYPE,
    payload: { 123 },
    meta: {
      resource: 'kits',
      fetch: GET_ONE,
      onFailure: {
        notification: {
          body: 'MESSAGE FROM REACT ADMIN',
          level: 'warning',
        },
      },
    },
}
```

Backend response example:
``` json
{"statusCode":404,"error":"ERROR FROM BACK END","message":"ERROR FROM BACK END"}
```

**What you were expecting:**
Notification with a message `MESSAGE FROM REACT ADMIN`

**What happened instead:**
Notification with a message `ERROR FROM BACK END`

**Related code:**
The bug occurs specifically because of this line, where backend error message is prioritized over message body:

https://github.com/marmelab/react-admin/blob/29fc75e19b917bb37952dcbeb881b840f2a07b38/packages/ra-core/src/sideEffect/notification.ts#L34

**Environment**

* React-admin version: 2.7.2
* React version: 16.8.3
* Browser: Chrome Version 72.0.3626.119

**Comment by Kmaschta** [comment]
You're right, the [documentation says](https://marmelab.com/react-admin/Actions.html#success-and-failure-side-effects) that we should be able to customize these error messages.

Thanks for reporting!

**Comment by fzaninotto** [comment]
I'm not sure it's a bug. We decided to prioritize server messages from app messages when the server message is provided. In general, it seems a good choice, because the user may need to know why the action failed, and the server message is more informative. 

For instance, all the failure messages for react-admin crud actions are "http error". If the dataProvider answers to a `DELETE` verb with an error carrying a message "Item does not exist", should the user see "http error" or "Item does not exist"? To my mind, the latter.

There may be cases when it's not the desired outcome. We have 3 solutions to deal with those cases:

- do nothing and let the users handle the error notification by hand using custom sagas
- add another parameter to the notification side effect to let it decide if, in case of error, it should default to the server error or the body
- concatenate the 2 messages (body and server error) 

We could do even further and let developers pass a *function* body instead of a *string*, letting them decide what to do with the error message. But I'm not fond of having non-serializable data in actions.

So anyway I'm removing the bug tag, and turning this into a Request For comments.

**Comment by SorJEF** [comment]
@fzaninotto I still think this is a bug. This creates a dependency on the implementation of the backend. As react-admin is backend agnostic such a dependency breaks its principles and ultimately impacts other features. For instance, everybody who has localization implemented on the UI will need to implement custom sagas for notifications and such a declarative feature becomes useless. Furthermore, this is quite confusing and counterintuitive as one would never expect the message in the `body` to be simply ignored.

I would suggest additional solutions:
1. Have a simple format tag like `%message%`, which can be used in a string in the `body` parameter. This way there is no need in a non-serializable function.
2. Use backend's message only if the `body` parameter is empty.

**Comment by fzaninotto** [comment]
I like your first solution, because it could handle all cases:

1. if `body='Server error'`, ignore the backend error message
2. if `body='Server error: %error%'`, display both the standard and the server error message
3. if `body='%error%'`, display only the server error message. We'd just need to add a test, in the third case, to see if the server error message is empty, and in this case, display the standard error message.

However, this creates translation problems, as the errors from the server wouldn't get translated anymore in case 2. That's a breaking change.

I though about your second solution, too, but in general it leads to empty errors. Because we'd need to remove the `body` of error notifications, and in case of server error, if the message is empty, the notification would be empty, too.

**Comment by Kmaschta** [comment]
IMO error messages coming from server aren't translated most of the time (and it shows warning often). In my case, I never translates them.

I'm also in favor of a higher priority of client-side error messages, and notification body templating seems a fair tradeoff :+1:

**Comment by fzaninotto** [comment]
This enhancement request hasn't gained enough interest to get a PR from the community. As we canot keep all feature requests open, I'm closing it. 

If you feel like working on this feature, we'd love a PR!
