### ISSUE TITLE
Custom controller for ReferenceManyField

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#2962]
Hi guys

I'm trying to implement my own controller logic using ReferenceManyField. I think ReferenceManyField would be more flexible if controller could be passed to ReferenceManyField, and if not, use current ReferenceManyFieldController as default.

What do you think?

**Comment by djhi** [comment]
It was designed so that you can use the logic from the controller with another view, not the other way around.

Besides, the `ReferenceManyField` doesn't do [much](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/field/ReferenceManyField.js). If you implemented custom `ReferenceManyFieldController`, you might as well implement a custom `ReferenceManyField`.

**Comment by developerium** [comment]
Yes I had to copy and change them both, OK thanks
