### ISSUE TITLE
while using open crud adapter with a secret secured prisma  react-admin doesn't ask for authentication and crashes with invalid token

### ISSUE THREAD

**Issue by dpereira411** [marmelab/react-admin#3008]
**What you were expecting:**
Setup react-admin auth provider to fetch a JWT token that would be then used by the data provider to connect to Prisma

**What happened instead:**
React admin crashed with wrong Prisma token (during GraphQL introspection)

**Steps to reproduce:**
Setup Prisma with secret token and setup react admin with openCRUD adapter

**Other information:**
Maybe I'm missing something, or is there a way to wait for auth provider before data provider initialization? I couldn't find it

**Comment by Kmaschta** [comment]
Sorry but, if you have issues with `ra-data-opencrud`, you'd better to open an issue on this repository: https://github.com/Weakky/ra-data-opencrud

This is a third-party library supported by the community, and not by the core react-admin team.

If you take a look in the issues, you'll find some similar issues:
- Authentication in react-admin https://github.com/Weakky/ra-data-opencrud/issues/24
- [Question] Use prisma-client https://github.com/Weakky/ra-data-opencrud/issues/16

Moreover, as explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the is a better place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.
