### ISSUE TITLE
Export only selected item

### ISSUE THREAD

**Issue by Denys8** [marmelab/react-admin#3009]
![Annotation 2019-03-15 183257](https://user-images.githubusercontent.com/43750159/54447022-00a13a00-4751-11e9-99ab-89986b37fd4b.png)
How I can export only selected item?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by Kmaschta** [comment]
As explained on the [documentation](https://marmelab.com/react-admin/List.html#exporter), the export button create a CSV file with the whole list (with the current filter and sort).

![image](https://user-images.githubusercontent.com/1819833/54447655-3d1d6780-474a-11e9-8837-e53cc27ea69d.png)

If you want to implement your own ExportButton with a different behavior, I advise you to look at Stack Overflow.
That said, there already is a question about that: https://stackoverflow.com/questions/53081021/how-to-export-all-fields-with-exporter-react-admin

@djhi IMO the UI is pretty misleading about this feature

**Comment by fzaninotto** [comment]
The ui isn’t misleading: by default, the export button doesn’t appear among the bulk actions. I believe @Denys8 added it to the bulkActionButtons and expected that it would work.

**Comment by Denys8** [comment]
@fzaninotto yes, you are right. Can you tell me. Is it possible to export selected items?

**Comment by fzaninotto** [comment]
it's possible, but not with the Export component that ships with react-admin. You'll have toi write your own Export component for that.

**Comment by Denys8** [comment]
@fzaninotto okay. Thank for answer!

**Comment by Denys8** [comment]
@fzaninotto Can i ask you a couple more questions???

**Comment by fzaninotto** [comment]
No, please use StackOverflow for support.

**Comment by christiaanwesterbeek** [comment]
@Denys8 I've created a SO question and answer with a custom BulkExportButton component that allows you to export only the selected items.

https://stackoverflow.com/questions/58665276/how-can-i-export-only-the-selected-items-in-a-list-in-react-admin

**Comment by fzaninotto** [comment]
See #4109 for an implementation of the `<BulkExportButton>`

**Comment by Odonno** [comment]
@fzaninotto Thank you very much for this feature. It is working great.

On the other hand, I don't see anything on the documentation about that. I mean, when searching on the documentation website. It could be good to at it to the documentation. But that's not a big deal for me, I found the way to use it pretty quickly.

Thank you again.
