### ISSUE TITLE
How to add global CSS?

### ISSUE THREAD

**Issue by daviddelusenet** [marmelab/react-admin#3016]
If I would like to add something like [reset-css](https://www.npmjs.com/package/reset-css) then how would I do it? 

Also, if I would want to style the `body` element for example, where would I do this?

So basically, how can I add global CSS?

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by daviddelusenet** [comment]
For other people who might come here in the feature: I opened an [issue](https://stackoverflow.com/questions/55218652/how-to-add-global-css-to-react-admin) on Stackoverflow.
