### ISSUE TITLE
Disable Pagination

### ISSUE THREAD

**Issue by annyip** [marmelab/react-admin#3052]
Is there a way to disable pagination as a whole? I want all my records to show up in one long list and not broken up into pages.

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by raman1212** [comment]
can't you tell details here. I mean what is the problem.

**Comment by faizan-tariq** [comment]
I couldn't find any thing related to this on stackoverflow
@raman1212 did you find any way to disable pagination?

**Comment by faizan-tariq** [comment]
@Kmaschta https://stackoverflow.com/questions/62494361/react-admin-disable-pagination

**Comment by raman1212** [comment]
Answered on StackOverFlow. @Kmaschta
