### ISSUE TITLE
ra-data-graphcool : How to implement n

### ISSUE THREAD

**Issue by mtheolog** [marmelab/react-admin#3077]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(http://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.

**Comment by fzaninotto** [comment]
I don't understand this issue. This is already part of the issue template.

**Comment by mtheolog** [comment]
Suppose i have the following schema:
type User
{id: ID! @unique
age: Int
email: String! @unique
name: String!
posts: [Post!]!
}

type Post 
{id: ID! @unique
title: String!
published: Boolean!
author: User!
}
How can I implemented a nested mutation like:
mutation {
createPost
(data: 
{title: "This is a draft"
published: false
author: 
{create: 
{email: "athina@example.com"
name:"athina"}}}) 
{id
title
published
author {
name
email}}}
--

**Comment by djhi** [comment]
As specified in the issue template you included in your initial comment and in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
