### ISSUE TITLE
Warning: Missing translation for key: "Cannot read property 'hasOwnProperty' of undefined"

### ISSUE THREAD

**Issue by marvincolgin** [marmelab/react-admin#3097]
I'm having an issue, as I run through the tutorial with regards to the<Edit />. 

It appears that anytime I use the <Edit /> with a <SimpleForm /> or <FormGuesser /> (or anything), the "PostEdit" is rendered from the "PostList" and it looks great.. but the browser, displays the following error message and then flips back to the "PostList" after approx 1 second. 

ERROR:
"Warning: Missing translation for key: "Cannot read property 'hasOwnProperty' of undefined"" 

react-admin: 2.8.4

**Comment by djhi** [comment]
Can you please correct your message ? It's very difficult to understand it.

You can see the tutorial code on this codesandbox: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/tutorial

It might help you understand what you did wrong.

Finally, as explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
