### ISSUE TITLE
location.search takes precedence over defaultValue (breaking comment example)

### ISSUE THREAD

**Issue by SevereOverfl0w** [marmelab/react-admin#3111]
**What you were expecting:**

When linking to a url with some parameters supplied in the search, the defaultValue in the component would take precedence over the value in search.

**What happened instead:**

The value in search is given preference over the parsed defaultValue. This is problematic, as I need to convert a string to an integer in order to submit to the API.

**Steps to reproduce:**

https://marmelab.com/blog/2018/07/09/react-admin-tutorials-form-for-related-records.html

1. Update the example sandbox dependency to the latest react-admin
2. Try and create a comment from a post
3. See blank in dropdown

**Related code:**

* CodeSandbox (https://codesandbox.io/s/2393m2k5rj)

**Environment**

* React-admin version: 2.8.3
* Last version that did not exhibit the issue (if applicable): 2.1.0
* React version: 16.8.5

**Comment by SevereOverfl0w** [comment]
Looks like an outdated article issue :). I fixed this by not using location.search, and finding the `state` and `record` options in "Prefilling a <Create> Record"

**Comment by djhi** [comment]
Indeed, this article was written just before we added this feature. Actually it was the reason we added the feature almost immediately.

**Comment by SevereOverfl0w** [comment]
Despite how I stumbled into this, it might still be preferable to allow users to override what comes in via location.search. But I don't personally have an immediate need for that.

**Comment by djhi** [comment]
It's actually the other way around on purpose. You might have defaults for your Create form but what comes from the location will override it. If you don't want this behavior, you can create your own [`CreateController`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/CreateController.tsx) and [`Create`](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/Create.js) components

**Comment by christiaanwesterbeek** [comment]
For a different reason, I have some URL parameter (x) in there while I submit a SimpleForm. I was surprised to see that that parameter became part of the record that was posted, resulting in my API saying: > "column "x" of relation "posts" does not exist".

I noticed it's intentional and built-in here: https://github.com/marmelab/react-admin/blob/c44c6953cc313fd167dc57b5525db58dd9ba2038/packages/ra-core/src/controller/CreateController.tsx#L104-L105 in this commit: https://github.com/marmelab/react-admin/commit/7845ebec7a8aead597e25ec9738f2cc19c845081#diff-2ade63f0bf44e74c12b44e9e88ff5a21

Can I convince you guys to introduce a prop for Create that makes that behavior optional? I'm thinking:

```jsx
<Create 
    includeSearchValues={false}
    ...
/>
```

It would be an optional prop that's true by default.

If not, I'll probably copy and alter CreateController for this. Of course, I could intervene in just the `save` function and remove the key-value pairs from `data` that are exactly like that in the URL, but you can't be sure that that key-value wasn't actually also there as a field value in the form, so I suppose I need to copy and alter CreateController otherwise.

**Comment by Kmaschta** [comment]
@christiaanwesterbeek Can you open a new issue with that proposal please?
That way, it would be tracked on its own.
