### ISSUE TITLE
Menu Label is not showing Up

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3121]
**What you were expecting:**

![image](https://user-images.githubusercontent.com/45010414/55988507-09166300-5c72-11e9-8005-f1c5f05a2d4e.png)

**What happened instead:**

![image](https://user-images.githubusercontent.com/45010414/55988512-0d428080-5c72-11e9-8137-7c1481912c44.png)

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by anuraram12345** [comment]
I am not able to see the Label in menu items.Please help?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by kiad** [comment]
@anuraram12345 I had the same issue upgrading from 3.12 to 3.15; I downgraded to 3.14.5 to see if it came from the last version, and it worked. I updated back to 3.15 to check again, and it worked 🤔  I don't understand exactly why, but it looks like it is a package version issue, not a but from react-admin; maybe you should clean everything :)
