### ISSUE TITLE
Seems like ra-realtime doesn't work correctly after redirecting

### ISSUE THREAD

**Issue by AntonZapara** [marmelab/react-admin#3124]
Hi, we use ra-realtime in 'list' component as described in documentation and it's work correctly when user browsing between Resources into the app by own.

We have 'create' component, which has redirection 
` <SimpleForm redirect="list" submitOnEnter={true}>`
 to the 'list' component. So, after creating element and auto-redirection to the 'list', realtimeSaga doesn't receive event (doesn't called) and list doesn't updating automatically. If user moves to another Resource and returns to this 'list' - realtimeSaga works correctly.

I checked, dataProvider received event in this case and it works correctly, so seems like problem into ra-realtime.

Thx for answer, and thank you for this great project.

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by Titannet** [comment]
Thx for answer.

Hm, it works on sandbox: https://codesandbox.io/embed/zx8z0y8773

But still has a warning message: `[...effects] has been deprecated in favor of all([...effects]), please update your code` - it is possible to fix it?

The differences between sandbox and our application - we are using ra-loopback as a dataProvider, and after redirecting I haven't seen message 'realtimeSaga called!'. 

So, I will try find issues in ra-loopback.

**Comment by Titannet** [comment]
I reproduced this issue into sandbox: https://codesandbox.io/embed/zx8z0y8773

Steps: Click "Add" into post list, after fill title and teaser and press "Save and Edit". After redirection - list doesn't updating automatically.

But, if you trying to edit post and click save - after redirection list updated correctly. Magic...

**Comment by Titannet** [comment]
Hi guys, just wondering if you had a chance to look at issue described.
Thanks and any feedback would be highly appreciated.

**Comment by djhi** [comment]
Hi @Titannet, no sorry, I haven't got any time to investigate yet.

**Comment by Titannet** [comment]
Hi, just found another steps to reproduce this bug. I think it can help to fix this.

Steps:
1. Open sandbox in full screen mode, url: https://zx8z0y8773.codesandbox.io/#/posts - Auto-updating works fine 
2. Click on “Posts” tab in left up corner - we can see “Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack” in console and auto-updating doesn’t work after this.

I think when we get redirecting to the list after creating new post - tab doesn’t changed and we get the same story as I described above.

I hope this will help to solve this problem, because we really need it.

Thx.

**Comment by Titannet** [comment]
Hi @djhi, @fzaninotto,

I understand it takes time to look thru but could you please at least guide me when you will be able to have a look?

We have a product based on this technology and this bug is very critical for the overall product. If we are not able to fix this at all then we need to consider to switch to another technology.

Thanks.

**Comment by zenflow** [comment]
@djhi I guess this can be closed since ra-realtime has been removed from the repo and is no longer supported (reference: https://github.com/marmelab/react-admin/pull/3908)

**Comment by fzaninotto** [comment]
right, thanks.
