### ISSUE TITLE
Transition between posts

### ISSUE THREAD

**Issue by Denys8** [marmelab/react-admin#3130]
Hi, i use React-admin. And I should add on the page "Edit", for example, products, two buttons.
That on clicking the corresponding button it was possible to pass to the next or previous products not refund to the list of all products. Is it possible in react-admin?
![Screenshot_1](https://user-images.githubusercontent.com/43750159/56213531-de0e8380-6064-11e9-8e94-8f0a8a9269ec.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
