### ISSUE TITLE
NumberInput doesn't support steps on IE

### ISSUE THREAD

**Issue by guoyibj** [marmelab/react-admin#3173]
**What you were expecting:**

NumberInput support steps on all famous browers.

**What happened instead:**

There is no step controller on IE.

**Steps to reproduce:**

<img width="609" alt="Screen Shot 2019-04-29 at 11 02 46 AM" src="https://user-images.githubusercontent.com/35130561/56874737-87467800-6a6e-11e9-8bc6-bbb3de50021a.png">

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, I believe this is either an IE (which version?) problem, or a material-ui issue. React-admin outputs an input type="number". If it's not rendered correctly, it's probably caused by an underlying tech.
I advise you to do a simple test with material-ui using CodeSandbox, and open an issue in their repository if you can reproduce the issue.
