### ISSUE TITLE
Link entities between them when use an ORM backend

### ISSUE THREAD

**Issue by keulu-ing** [marmelab/react-admin#3196]
**Is your feature request related to a problem? Please describe.**
It's not a really big problem, it's just a big missing.

**Describe the solution you'd like**
Provide a way to send a containable entities. For example, CakePHP, symfony, slim and other framework with ORM, can join entities between them really easily.

**Describe alternatives you've considered**
provide a "with" parameter available on all controllers. (Edit, show, list, delete etc...)

**Additional context**
For my case, i use cakePHP3.7, and cake don't join entities between them automatically... i have to specify every contains. so i use a devious way with the filter query parameter. For example, for a customer, i send a filter like that on a listing : `{"with_Account":"id,account_name", "with_Addresses":"*", "with_CustomerType":"*"}`

but that doesn't work with a GET_ONE query (Edit & Show).

SO link for discuss : https://stackoverflow.com/questions/55970158/possible-use-of-filter-in-edit-show-controller

Maybe for the V3 ?

**Comment by fzaninotto** [comment]
This is something we've excluded by design. It allows us to implement optimistic rendering because resources are shared across all pages, and it simplifies the development of the frontend interface without harming performance (because react-admin knows how to aggregate and deduplicate requests for related resources). We discourage using embedded resources.
