### ISSUE TITLE
Unable to use strapi.io as my GraphQL Server

### ISSUE THREAD

**Issue by essamsalah** [marmelab/react-admin#3255]
Hi,

I followed the example in the [ra-data-graphcool provider](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphcool) but my server is not GraphCool, it is actually Strapi.io and I created the Post type.

The application is not able to fetch the data saying "Unknown resource Posts" , I tried to use the resource name in all options like Post/Posts/post/posts and it seem nothing is making a difference here.

Any advice how to investigate the issue specially that the error is not thrown in the JS Console or Command line 

![image](https://user-images.githubusercontent.com/3326831/58060327-3b6c8780-7b71-11e9-945a-f47df826aa31.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
