### ISSUE TITLE
Resource that have list, but did not displayed in side menu

### ISSUE THREAD

**Issue by deksden** [marmelab/react-admin#3272]
there is no simple way to define resource that can have list, but will not be displayed in side menu. For example, this can be details for orders.

My proposed solution is to add one more option (maybe "hideFromSideMenu") in options property.

**Comment by deksden** [comment]
As for now - the only criteria to make resource appear in menu is having list prop. 

    Menu.js:51: .filter(r => r.hasList)

Maybe this can be transformed like (haveList and did not have option to hide it from list:

    .filter(r => r.hasList && (!r.options || !r.options.hideFromList))

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

The limited ability of the react-admin Menu component is a design choice. We know that designing a Menu component that works in more situations would bring significant complexity. Since building your custom menu is straightforward, we've chosen to address the simplest case, and let developers implement more complex cases in userland.

So we won't implement what you're suggesting in core, but feel free to write your own Menu component to address that need and publish it as a standalone package. We'll link to it from the Ecosystem documentation.
