### ISSUE TITLE
Each child in a list should have a unique "key" prop. Check the render method of `DatagridBody`. I know that similar query has been posted before, I followed them but it is still not working

### ISSUE THREAD

**Issue by dmajumder4292** [marmelab/react-admin#3298]
When I try to update an item in a list, the operation works and the item gets updated in the DB, in the UI as well the update works, although it takes a while and shows an additional row temporarily for a brief moment. However I get a warning in the console and the message says, "Each child in a list should have a unique "key" prop. Check the render method of `DatagridBody`". I saw that this link [https://github.com/marmelab/react-admin/blob/master/docs/FAQ.md#can-i-have-custom-identifiersprimary-keys-for-my-resources](https://github.com/marmelab/react-admin/blob/master/docs/FAQ.md#can-i-have-custom-identifiersprimary-keys-for-my-resources) was said to be the resolution for the above warning, however I already have an attribute id in the json response, see the code below:

```
const convertHTTPResponseToDataProvider = (response, type, resource, params) => {
    const { headers, json } = response;
    
    switch (type) {
    case GET_LIST:
        return {
            data: json.map(x => x),
            total: parseInt(headers.get('content-range'), 10),
            //total: parseInt(headers.get('content-range').split('/').pop(), 10),
        };
    case CREATE:
        return { data: { ...params.data, id: json.id } };
    case UPDATE:
        return { data: { ...params.data, id: json.id } };
    default:
        return { data: json };
    }
};
```
Please help me figure how to resolve this warning.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by dmajumder4292** [comment]
I'm sorry about that, but currently I am not able to ask question on stackoverflow, because I asked few question which were considered not very helpful for the community. If possible, can you guide me here in this channel. It would be a huge help!
