### ISSUE TITLE
Where is CreateButton example docs?

### ISSUE THREAD

**Issue by HyunSangWon** [marmelab/react-admin#3318]
i'm looking for documentation related <CreateButton> tag .. I do not know where.
I looked up this site 
https://react-admin.com/docs
https://marmelab.com/react-admin

May you tell me where the CreateButton document is? ..

**Comment by fzaninotto** [comment]
Hi, and thanks for your report.

The domain react-admin.com does not belong to us. Someone copied an outdated version of the doc there, so you should not use it (and you can flag it to Google so that they remove it from their index). 

As for the doc of the CreateButton, the [Reference page](https://marmelab.com/react-admin/Reference.html) shows that it's not written yet. 

Until it is written, do as in every other open-source project, [read the source, Luke!](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/CreateButton.js)
