### ISSUE TITLE
Custom (redux-form's Field) input doesn't bind prop to record.

### ISSUE THREAD

**Issue by Bohmaster** [marmelab/react-admin#3330]
**What you were expecting:**

Custom input prop "name" (via redux-form Field) to be added to the record on save or edit.

```
<Field name="age" value={10}/>
```
I expect on POST/PUT the record to have "age": 10.

**What happened instead:**

Custom input doesn't add input value to record

```
// tariff.js

import TextField from '@material-ui/core/TextField';
import { Field } from 'redux-form';

const renderTextField = ({ input, label, meta: { touched, error }, ...custom }) => {
    const { defvalue } = custom;
    
    return (
        <TextField
            label={label}
            error={!!(touched && error)}
            helperText={touched && error}
            {...input}
            {...custom}
            value={defvalue}
        />
    )
};

class Tariff extends React.Component {
    state = {
        tariffs: [],
        selectedTariff: {}
    }
    
    // other methods...
    
    render() {
        const { tariffs, selectedTariff } = this.state;

        return (
            <React.Fragment>
                <Autocomplete suggestions={tariffs}
                    label={'Elija una tarifa'}
                    onChange={this.onTariffSelected}
                    defaultValue={''} />
                <Field name="tariff" component={renderTextField} label="Tarifa" defvalue={selectedTariff.amount || 0} />
            </React.Fragment>
        )
    }
}

// 
```

**Other information:**

**Environment**

* React-admin version: 2.7.2
* React version: 16.8.3
* Browser: Chrome/Firefox

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by jturge0n** [comment]
Yeah but no one answers the questions there...

**Comment by dominathan** [comment]
Quick and dirty version us <Link>

```js
import React from 'react'
import { List, Datagrid, TextField } from 'react-admin'
import { Link } from 'react-router-dom'

export const PatientList = props => (
  <List {...props} title="Patients" perPage={25} bulkActionButtons={false}>
    <Datagrid>
      <TextField source="id" label="ID" />
      <TextField source="patient_source_id" label="Patient Source ID" />
      <TextField source="patient_source" label="Patient Source" />
      <PatientIdWithLinkToGene />
    </Datagrid>
  </List>
)

const PatientIdWithLinkToGene = ({ record = {} }) => {
  const to = `/gene-results?filter=%7B"patient_source_id"%3A"${record.patient_source_id}"%7D&order=ASC&page=1&perPage=25&sort=id`
  return <Link to={to}>Show Gene Results</Link>
}
```
