### ISSUE TITLE
AutocompleteArrayInput displays blank entries

### ISSUE THREAD

**Issue by wesk** [marmelab/react-admin#3331]
I have an array in my db which I would like to CRUD using react-admin. The `AutocompleteArrayInput` component meets my needs in every way but one. The problem I am experiencing is that `AutocompleteArrayInput` only displays entries which are from the finite list of options provided to the component. If an entry is not present in the list of options, react-admin does not display the custom text which was inserted and instead shows no text instead.

**What happened instead:**

Instead of displaying the inserted text, I see empty entries as follows: 

<img width="350" alt="Screen Shot 2019-06-11 at 12 13 16" src="https://user-images.githubusercontent.com/1182047/59397231-d49a5280-8d59-11e9-982b-7f9123a45ae1.png">

Is there a configuration setting which will allow me to view the text? Or must I instead ensure that every possible input is included in the `choices` array.

**Sample code:**
```

const my_choices = [
  {id:'red', name:'red'},
  {id:'green', name:'green'},
  {id:'blue', name:'blue'}
];

export const ResourceEdit = (props) => (
  <Edit {...props} redirect="list">
      <SimpleForm>
          <AutocompleteArrayInput source="Colors" choices = {my_choices} allowEmpty />
      </SimpleForm>
 </Edit>
);
```

For the above example, I would like autocomplete for `red`, `green`, and `blue`, but if another color is present in the array, I want to be able to see it in the admin interface, too, and not just have it show up as blank.

Am I missing a configuration setting? I want to avoid providing an exhaustive list of options to the component, if possible.

**Environment**

* React-admin version: 2.9.2
* Last version that did not exhibit the issue (if applicable): Unknown
* React version: 16.8.6
* Browser: Tested on Chrome and Firefox

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by wesk** [comment]
Hi djhi, thanks for your response! I [posted this question on stackoverflow](https://stackoverflow.com/questions/56554337/autocompletearrayinput-displays-blank-entries) a few days ago -- hopefully the question gets an answer there.

**Comment by wesk** [comment]
@djhi no answers on stackoverflow yet -- any idea for how I can solve this problem? (Happy to x-post the answer back to S.O. so that it becomes searchable.) The `react-admin` is still a bit of a niche tag, which is why I originally opened this as an issue here in this repo. Thanks for your time!

**Comment by sebashwa** [comment]
Hey @wesk, I've got the same issue here.
Did you somehow solve / work around this already?
Would be happy for some advice

**Comment by nickgrealy** [comment]
@sebashwa -> https://stackoverflow.com/a/64961397/782034

**Comment by neerajmind1** [comment]
Just add **allowEmpty={false}** attribute to <AutocompleteArrayInput> tag, and it will work.
