### ISSUE TITLE
Popup List

### ISSUE THREAD

**Issue by romadinov** [marmelab/react-admin#3378]
Hi,

I'm trying to embed List with a Filter in a popup. The use case is the following:
1. I need to register customer's visit into my gym
2. For this one, I need to locate the customer
3. The ideal scenario is to use Filter + List to locate the customer. I.e. I'm starting to time the customer's name, the list is filtered, I'm selecting the record(s) that match

The issue is that I would like to have this Add Visit functionality in a popup that is accessible from all of the screens of my gym housekeeping app. I've managed to embed the List with a Filter into a popup. However, when I implemented server-side, I noticed that Filter always change the current #/ via routing and hence routes away from the popup. 

Is there any way to prevent List from pushing new routes ?

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
