### ISSUE TITLE
Cache react-admin

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3380]
**Is your feature request related to a problem? Please describe.**
I have the AutoComplete Box Which has the space names like dlab,qlab etc
I want to store these names in MongoDB

**Describe the solution you'd like**
I want to show these space names in UI, Which needs to show the values from the cache.
From the db, the cache must be updated.Is there any cache option in react-admin.so that when ever i go to the page,i dont have to hit the DB

**Describe alternatives you've considered**
I have considered the alternative the store the values in localStorage.but in react-admin,i am not able fetch the value from DB and directly add it to localStore.Please give me other options

**Additional context**
Is there this feature of caching in react-admin?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
