### ISSUE TITLE
access to Datagrid table head

### ISSUE THREAD

**Issue by mrlaseptima** [marmelab/react-admin#3382]
can i access to Datagrid table head for chang some stuff like remove that select all checkbox ?
anyone can help me ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by djhi** [comment]
You can disable bulk actions altogether as stated in the documentation:
> You can also disable bulk actions altogether by passing false to the bulkActionButtons prop. When using a Datagrid inside a List with disabled bulk actions, the checkboxes column won’t be added.

However, if you want to keep the bulk actions but remove the select all checkbox, you'll have to implement your own datagrid, using the existing one as a starting point
