### ISSUE TITLE
Make nested API call to fetch all list

### ISSUE THREAD

**Issue by bhumidevninja** [marmelab/react-admin#3424]
Hey,

I've got a scenario in which I'm stuck.

In my scenario, I've got an API call to hit and on the response of the API, I've to call the final API to get records of list.

From the first API, I'll get a flag on which I've to make the conditional API call to get the records.

The problem is, `GET_LIST` gets called by react-admin and in that, I cannot handle two asynchronous API call. 

Can you share an example in which this type of calls is made?

Any type of help will be appreciated.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by bhumidevninja** [comment]
here is the link for the stackoverflow. Please help me out in this issue.
https://stackoverflow.com/questions/57107799/make-nested-api-call-to-fetch-all-list
