### ISSUE TITLE
How to combine create and edit page

### ISSUE THREAD

**Issue by jiafei1986** [marmelab/react-admin#3430]
Hi
   thank you for the amazing framework,  i am new for react and react-admin, but I am now using it in our project, everything is good, but there is one thing i don't know how to make it.   in our application. the create and edit page almost same, the only difference is some fields are disabled in edit view,  so i want to combine  create and edit,  is there any document about it.  I searched it but it seems not an easy way to do it,  it's appreciated if can get some sample code.  thank you !!!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by jiafei1986** [comment]
@djhi  Thank you, I will post it on the StackOverflow.
