### ISSUE TITLE
Remove delete many

### ISSUE THREAD

**Issue by Wellers0n** [marmelab/react-admin#3447]
remove delete many 

![WhatsApp Image 2019-07-23 at 10 57 15 AM](https://user-images.githubusercontent.com/39449389/61718141-bcdec280-ad38-11e9-96e4-de529d06f327.jpeg)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
