### ISSUE TITLE
SimpleForm does not reset after successful submit

### ISSUE THREAD

**Issue by iskrenantonov** [marmelab/react-admin#3454]
**What you were expecting:**
After creating new record in dialog simple form next opening the form should be empty.

**What happened instead:**
The next opening the form is populated with the previous record

**Steps to reproduce:**
Go to new comment, click on create post button, fill the form and submit it. click again - the form in the dialog is still populated.

**Related code:**
[![Edit React Admin Advanced Recipes - Quick Create/Preview](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-admin-advanced-recipes-quick-createpreview-lg49w?fontsize=14)

**Other information:**

**Environment**

* React-admin version: 2.9.5
* Last version that did not exhibit the issue (if applicable): 2.1.0
* React version: 16.3.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment]
I confirm I can reproduce.

1. Go to comments
2. Add a comment
3. Click on the "+" to add a post, and create it
4. Re-click on the "+"

That being said, this is not a bug from React Admin since it is custom code that runs on that CodeSandbox.

You can easily change the behavior of that form by editing `PostQuickCreateButton.js`.
