### ISSUE TITLE
Query Response not showing up

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3462]
I am trying to Execute the Query

```jsx
const UserProfile = ({ record }) => (
          <Query type="GET_LIST" resource="artifacts" >
              {({ data, loading, error }) => 
                   <div>{data}</div>
              }
          </Query>
```

**What you were expecting:**
I expect the data to be below JSON 

```json
[{"artifactId":"deliveryMethod","artifactValues":[{"id":"AAL","name":"Activity Log"},{"id":"Alert","name":"Alert"},{"id":"Email","name":"Email"},{"id":"SMS","name":"SMS"},{"id":"ExternalSMS","name":"External SMS"},{"id":"InternalEmail","name":"Internal Email"},{"id":"Push Notification","name":"Push Notification"}]}] 
```

**What happened instead:**
I get this response 
```js
function UserProfile(_ref4) {
        var record = _ref4.record;
        return __WEBPACK_IMPORTED_MODULE_1_react___default.a.createElement(
          __WEBPACK_IMPORTED_MODULE_3_react_admin__["L" /* Query */],
          { type: 'GET_LIST', resource: 'artifacts', __source: {
              fileName: _jsxFileName,
              lineNumber: 110
            },
            __self: _this2
          },
          function (_ref5) {
            var data = _ref5.data,
                loading = _ref5.loading,
                error = _ref5.error;
            return __WEBPACK_IMPORTED_MODULE_1_react___default.a.createElement(
              'div',
              {
                __source: {
                  fileName: _jsxFileName,
                  lineNumber: 112
                },
                __self: _this2
              },
              data
            );
          }
        );
      }
```

**Related code:**

```
  const UserProfile = ({ record }) => (
          <Query type="GET_LIST" resource="artifacts" >
              {({ data, loading, error }) => 
                   <div>{data}</div>
              }
          </Query>
        );
```

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
