### ISSUE TITLE
pass props from Resource to dataProvide

### ISSUE THREAD

**Issue by Wellers0n** [marmelab/react-admin#3464]
pass props from Resource to dataProvide, it is possible ?
![Screenshot from 2019-07-26 13-57-47](https://user-images.githubusercontent.com/39449389/61968536-ad68af00-afae-11e9-9538-b79e6ab277ca.png)

**Comment by Wellers0n** [comment]
![Screenshot from 2019-07-26 14-11-08](https://user-images.githubusercontent.com/39449389/61968793-44ce0200-afaf-11e9-9082-5d2b4b9b8928.png)

**Comment by Wellers0n** [comment]
DataProvider Receives Properties
![Screenshot from 2019-07-26 14-02-46](https://user-images.githubusercontent.com/39449389/61968815-56afa500-afaf-11e9-8274-8e7aaaa749fe.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by Wellers0n** [comment]
forbidden to open issue?

**Comment by djhi** [comment]
If this is an issue, please follow the issue template
