### ISSUE TITLE
Apply Custom Filter when source is not given to the field

### ISSUE THREAD

**Issue by bhumidevninja** [marmelab/react-admin#3474]
**What you were expecting:**
The filter should work when we select the value from the dropdown.

**What happened instead:**
The filter is not working. When selecting the value, nothing happens.

**Steps to reproduce:**
When displaying all the data in the list, have `FunctionField` when displaying the value. Also, do not have the `source` field. Instead, use `render` props.

**Related code:**

I want to use Filters in the table. Currently, I'm not using source to display the name because I'm getting id from the API.So, I'm

```jsx
renderRealtorName = (data) => {
    const { agents = [] } = this.props
    const agent = agents.find(agent => agent.id === data.truRealtor)
    if (agent) return agent.doc.displayName
    return <span style={style}>Not Assigned</span>
  }

<FunctionField label="Lead Owner" render={this.renderRealtorName} />
```

Now, when doing the filtration, I'm using SelectInput.

```jsx
<SelectInput
        optionText="name"
        optionValue="id"
        choices={leadOwnerArr}
      />
```

**Environment**

* React-admin version: 2.9.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.0
* Browser: Google Chrome
* Stack trace (in case of a JS error):

**Comment by bhumidevninja** [comment]
I want to use Filters in the table. Currently, I'm not using source to display the name because I'm getting `id` from the API.So, I'm
```
renderRealtorName = (data) => {
    const { agents = [] } = this.props
    const agent = agents.find(agent => agent.id === data.truRealtor)
    if (agent) return agent.doc.displayName
    return <span style={style}>Not Assigned</span>
  }

<FunctionField label="Lead Owner" render={this.renderRealtorName} />
```

Now, when doing the filteration, I'm using `SelectInput`.
```
<SelectInput
        optionText="name"
        optionValue="id"
        choices={leadOwnerArr}
      />
```

I can't see a solution to give the reference and also cannot find any custom way of doing it in the documentaion.

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by bhumidevninja** [comment]
I've done some changes, it is giving me an error. It is not allowing me to add `Views` in the filter.
I've done the code. I think you will get an idea of the scenario.

https://codesandbox.io/s/simple-tcf8f

Have a look to it. I'm getting the `id` from the backend. And on the basis of the `id`, I'm displaying the `name`.

**Comment by bhumidevninja** [comment]
Did you get anything? I'm stuck in this issue and want to complete it as soon as possible.
It will be great if you guys can help me out in this.

**Comment by Kmaschta** [comment]
This is not really a problem with React Admin components themselves, but with your usage of the library.

We do not provide support on GitHub issues. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
