### ISSUE TITLE
Mapping a mongodb comparison (e.g. $ne) inside a <Filter /> input

### ISSUE THREAD

**Issue by DanStorm** [marmelab/react-admin#3484]
Posted a question about this [here](https://stackoverflow.com/questions/57152972/how-to-map-a-mongodb-comparison-e-g-ne-inside-a-filter-input), but haven't gotten any attention there, so I am wondering if it is a bug or even a feature request.

We are using some softDelete functionality for some of our mongodb collections (e.g. Users). The `deletedAT` prop of these collections is either null or a date. I need to use a filter input to show active (`deletedAt = null`) or inactive (e.g., `deletedAt = ISODate("2019-07-18T20:45:45.340Z"`)) collection items. 

This works for a `<List /> filter` prop

```
<List title="User List" {...props} filter={{ deletedAt: null }} >
OR
<List title="User List" {...props} filter={{ deletedAt: { $ne: null } }} >
```

It actually also works for the `filterDefaultValues` prop

```
<List title="User List" {...props} filterDefaultValues={{ deletedAt: null }} >
OR
<List title="User List" {...props} filterDefaultValues={{ deletedAt: { $ne: null } }} >
```

However, I cannot make this work inside a `<Filter />` input e.g., 

```
export const UserFilter = (props) => (
  <Filter {...props}>
    <RadioButtonGroupInput source="deletedAt" choices={[
      { id: null, name: 'No' },
      { id: '$ne: null', name: 'Yes' },
    ]} alwaysOn />
  </Filter>

)
```

I get errors like this `Cast to date failed for value "$ne: null" at path "deletedAt" for model "User"` I've tried a number of different syntaxes, including trying to pass as objects, strings, etc with no luck. I suspect there is a difference in the request between a filter input and the `filter/filterDefaultValues` props of `<List />`.

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, since you already have a question open on SO.

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
