### ISSUE TITLE
Changed resource when url is not changed, will result in request old resource data

### ISSUE THREAD

**Issue by developerium** [marmelab/react-admin#3486]
Hi guys, hope you doing well

I've noticed a bug in **ListController**, and the bug maybe because of how I'm using this component, but never the less I though I'd share it and get your feedback on it.

I've defined a custom List, because I needed multiple grids from different resources and I use **ListController** to represent resource.

Resource name of the second grid is dynamic (url will not change since main list not changed), and when it is changed, it request the old resources data from api.

I think it's because , [this.updateData](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.tsx#L220) is called from within **componentWillRecieveProps** and then [this.props.resource](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.tsx#L315) will be referring to old props.

To address this issue, I think **updateData** should also accept props like:

`updateData(query, props = this.props) { ...`

let me know what you guys think.
Thanks

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by fzaninotto** [comment]
No news for some time, closing.
