### ISSUE TITLE
[RFC] Remove Implicit Translation (labels, notifications, errors, etc)

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/react-admin#3490]
As explained [in the documentation](https://marmelab.com/react-admin/Translation.html#translating-your-own-components), field and input labels are implicitly translations.

 ```jsx
<TextField source="first_name" label="myroot.first_name" />
```

This is a common practice in React Admin, but it does cause more harm than good, in my opinion.

My proposal is to take advantage of the next major release to remove as many as implicit translations as possible.

### Field and Input Labels

If an input or a field do not have a label, we can keep the current default translations. But if a label is specified, we have to use the `useTranslate` hook.

```jsx
// Translation available at `resources.customers.fields.first_name`
<TextField source="first_name" />

// No longer translated
<TextField source="first_name" label="myroot.first_name" />

// Translated
const translate = useTranslate();
<TextField source="first_name" label={translate('myroot.first_name')} />
```

### Side Effect Notifications

Currently, side effects notifications are implicitly translated. With this proposal, this will be no longer the case.

```diff
+const translate = useTranslate();
+
dataProvider(UPDATE, 'comments', { id: record.id, data: updatedRecord }, {
    onSuccess: {
        notification: {
-            body: 'comments.update.success',
+            body: translate('comments.update.success'),
            level: 'info'
        },
    },
    onError: {
        notification: {
-            body: 'comments.update.failed',
+            body: translate('comments.update.failed'),
            level: 'warning'
        }
    }
})
```

### Data Provider Errors

Data provider errors are translated somehow. This is a twofold issue:
- The real error and its stack trace are hidden by the translation (see #3428)
- Your everyday REST API doesn't return translated error messages

My proposal is to translate default error messages that React Admin is aware of (dataProvider error), or let the dataProvider translate error messages by itself.

> To be completed with examples

### Field Validation

Currently, if a field validator returns a string, it is implicitely translated.
Better use the `useTranslate` hook too.

```diff
+const translate = useTranslate();
+
const validate = (value) => {
    if (isInvalid(value)) {
-        return 'validation.invalid';
+        return translate('validation.invalid');
    }
};

return <BooleanField validate={[validate]} />;
```

### Unified Way To Handle Translation, Reduce API and Documentation

After this change, there will be ONE way to do translation: use the `useTranslate` hook.
This will make the documentation more clear and lower the barrier for newcomers.

[Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/), this change will definitely make the translations easier to understand.

### Less Data Conversion and Easier Data Flow

Data provider errors are a great example of how we can lose data with the current implementation: stack trace is lost while translated.

By forcing users to use translate their strings, React Admin has less magic to do.

### Less Dynamic Translation Keys

If users define their own keys, React Admin does not have to define keys based on resources, at least there will be less of these keys.

### Improve Dynamic Code Analyser Integration

Tools like [i18n-extract](https://www.npmjs.com/package/i18n-extract) are almost required on large projects when you have to check that all translations are correctly filled with all the locales.

But they are confused when a library uses dynamic translation as React Admin does.

### Non-Translated App

Not all React Admin applications need to be translated. Whenever a small app uses non translated labels, they have warnings in development mode.

### Breaking change

This will be a major breaking change, and users will have to handle their translations the new method. It can impact third-party libraries too.

That being said, all `ra-language-*` will not have to be changed.

### A bit more work for maintainers

Code owners will have more efforts to use translations every time they need to and will need to call the `useTranslation` hook too.
This is an overhead we have to take into account.

Feel free to share your opinion about this proposal! This RFC is mainly open to get the userland feedback about this feature. I'll update the original post whenever needed.

**Comment by Kmaschta** [comment]
Added form validation paragraph.

**Comment by fzaninotto** [comment]
I'm -1 on that change. Let me explain why.

I agree that the fact that translation is sometimes implicit, sometimes explicit is confusing. However, we could solve that by improving the documentation (https://marmelab.com/react-admin/Translation.html#translating-your-own-components is the only place where it's mentioned).

I think that the fact that we sometimes log warnings for untranslated messages or swallow the stack trace may be a bug, and we should solve it. Changing the translation strategy seems to be the wrong solution to that problem.

I think that detecting untranslated messages in components that use implicit translation (i.e. that don't use `translate`) could be done at runtime, by disabling the default translation fallback on the entire i18n provider. That way, a developer using the app would see warnings for all untranslated messages, including field and input names. This is not a breaking change and it could be added anytime.

But mostly, I believe that requiring the explicit use of `translate` everywhere will actually make i18n harder. The reason is that most developers start by implementing apps in one language, without necessarily adding translation, then add i18n in a second time. In such cases, running a static analyzer looking for the `translate` function wouldn't return anything, and the developer would have to go through all their components to look for missing `translate` calls. Whereas today, i18n is basically free for core components - the developer just needs to add a dictionary. 

Last but not least, that's a huge breaking change that will require a lot of work to developers migrating from v2. 

Overall, I think there are alternative, less cumbersome solutions to the problems you mentioned.
