### ISSUE TITLE
default http headers

### ISSUE THREAD

**Issue by Ralireza** [marmelab/react-admin#3491]
in my data-provider, I used simple Rest that you mentioned in the document.
when i add sth in option of convertDataRequestToHTTP() and suddenly content-type in request header transform to text/plain from JSON.  now I have to change header by hand. that is annoying.

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by Ralireza** [comment]
Hi
Thanks for your advice. But i think its a bug not "how to" question . Ok
i'll ask in stackoverflew

**Comment by Kmaschta** [comment]
If it's a bug, please open a new issue and follow the bug issue template, ideally with a CodeSandbox fork reproducing the issue (links are in the template).
