### ISSUE TITLE
Persist/save filter selection to localstorage

### ISSUE THREAD

**Issue by ricardovf** [marmelab/react-admin#3521]
**Is your feature request related to a problem? Please describe.**
I would like to be able to save the filter selection to localstorage and auto-retrieve it if not present in the URL already.

**Comment by djhi** [comment]
Hi and thank you for your suggestion. As we store the filters in the redux store too, this is achievable in userland with a [custom saga](https://marmelab.com/react-admin/Admin.html#customsagas) which would react to the `CRUD_CHANGE_LIST_PARAMS` and `LOCATION_CHANGE` (from `react-router-redux`) actions. Note that this action is called for pagination, sort and filter updates on the list.

If you need help to create this saga, please open a question on StackOverflow and I'll try to answer asap.

PS: This will be even easier with the hook API in V3

**Comment by ricardovf** [comment]
Thanks for the quick reply and directions!

**Comment by ricardovf** [comment]
@djhi do you have an example/docs using V3?

**Comment by christiaanwesterbeek** [comment]
I have a requirement for kind of the same thing, though I don't need localStorage to persist the filter. I just don't want the url to change, because another list (different resource) on the same page is noticing the url parameter changes and starts filtering on a search term that is unrelated.

https://stackoverflow.com/questions/59883643/how-to-not-change-the-url-on-list-filtering-with-react-admin
