### ISSUE TITLE
why actions render the filters

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3529]
```
const LeadTimeFilter = ({ ...props }) => (
  <div>
    <Filter {...props}>
      <SearchInput source="itemSearchKey" label="item" alwaysOn />
      <SearchInput source="locationSearchKey" label="location" alwaysOn />
    </Filter>
    <Button variant="contained"></Button>
  </div>
);
const LeadTimesList = props => (
  <List
    {...props}
    filters={<LeadTimeFilter />}
    bulkActions={false}
    // actions={null}
  >
```
[
![1565786877066](https://user-images.githubusercontent.com/19420622/63022250-128c3200-bed5-11e9-9d00-3f773ffccae2.jpg)
](url)
**question:**
the filter tooltar and the actions will all render the button,this is why
`  {filters &&
            cloneElement(filters, {
                resource,
                showFilter,
                displayedFilters,
                filterValues,
                context: 'button',
            })}` in the '../ListAction'  

**Environment**

* React-admin version: 2.8.5

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
