### ISSUE TITLE
Problems with data in forms using Grids,divs or element box.

### ISSUE THREAD

**Issue by jereef** [marmelab/react-admin#3531]
**What you were expecting:**
I need put components inside div, Grid or any box element on a CRUD Page.

**What happened instead:**
I got an error: "Cannot read property '...' of undefined".

If I insert the component **outside** of the divs, the component **works**.

**Related code:**
```javascript
export const PersonasEditComponent = props => (
    <Edit title="Editar Persona" actions={<PersonasEditActions />} {...props}>
        <div>
            <AsistenciasCreateButton />
        </div>
    </Edit>
);
```

and my Component code:

```javascript
import React from 'react';
import { Link } from 'react-router-dom';
import ChatBubbleIcon from '@material-ui/icons/ChatBubble';
import { withStyles } from '@material-ui/core/styles';
import { Button } from 'react-admin';
import { LibraryAdd } from '@material-ui/icons';

const styles = {
  button: {
    marginTop: '1em'
  }
};

const AsistenciasCreateButton = ({ classes, record }) => (
  
  <Button
    className={classes.button}
    variant="raised"
    component={Link}
    to={`/asistencias/create?persona_id=${record.id}`}
    label="Agregar asistencia"
    title="Agregar asistencia"
  >
     <LibraryAdd />
  </Button>
 
);

export default withStyles(styles)(AsistenciasCreateButton);
```

**Environment**

* React-admin version:2.9.5
* React version: 16.5
* Browser: Chrome

**Comment by Kmaschta** [comment]
This is not really a bug, but a misconception about how React Admin works.

Your button have to receive a prop `record` from the Edit component.
By using a `<div>` between the Edit and the button, your are blocking this prop cascade.

That's why Create and Edit views are completed with a `<SimpleForm>` or a `<TabbedForm>`.
These components clone their children by passing them all the required props.

You'll can find all these informations on the related documentation:
https://marmelab.com/react-admin/CreateEdit.html

Also, feel free to ask this kind of questions on  [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin) with the tag `react-admin`.

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by jereef** [comment]
Kmaschta thanks for answering!. I used these components in the code, however the error still appears. I wish I could better understand how to make the cascade of props using Grids in a form.

I have this:
```javascript

  <Create title="Crear nueva Personas" {...props}>
            <TabbedForm
              className="test-tab"
              toolbar={<PersonasCreateToolbar />}
              variant="scrollable"
            >
              <FormTab
                className="tab-title"
                icon={
                  <Tooltip title="Datos Personales">
                    <AccountCircle />
                  </Tooltip>
                }
              >
                <div>
                  <AsistenciasCreateButton />
                </div>
              </FormTab>
            </TabbedForm>
          </Create>

```

Thanks you!

**Comment by Kmaschta** [comment]
Try to remove the `div` around `AsistenciasCreateButton`.
Again, please use Stack Overflow for a community support.
