### ISSUE TITLE
Custom Toolbar for TabbedForm don't work

### ISSUE THREAD

**Issue by rethink-vinicius** [marmelab/react-admin#3532]
**What you were expecting:**
TabbedForm to work when adding a custom toolbar. The intent is to have the toolbar without the delete button.

**What happened instead:**
When clicked, the save button of a custom toolbar didn't worked when added to a TabbedForm.
However, the component works as expected when using the default toolbar.

**Related code:**
```javascript
const VisitorEditToolbar = props => (
    <Toolbar {...props}>
        <SaveButton />
    </Toolbar>
);

export const VisitorEdit = withStyles(editStyles)(({ classes, ...props }) => (
    <Edit {...props}>
        <TabbedForm redirect={false} submitOnEnter={false} toolbar={<VisitorEditToolbar />}>
            <FormTab >
              ...
```

**Environment**

* React-admin version: 2.4.0
* React version: 16.8.6
* Browser: Chrome

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by rethink-vinicius** [comment]
We have solved that issue. Thanks for the support.

**Comment by Kmaschta** [comment]
Glad to hear that! Any insight for a later reader of the community?
