### ISSUE TITLE
Issue with loading the values from localStorage into 

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3535]
componentDidUpdate() {
    this.checkAuthentication();
    restDataProvider('GET_MANY', 'artifacts', { })
    .then(({ data }) => {
             data.forEach(dnduiartifacts => {
             localStorage.setItem("dnd-ui-artifacts-"+dnduiartifacts.artifactId,JSON.stringify(dnduiartifacts.artifactValues));
        });  
       })
    .catch(error => console.log("Error is fectching artifacts"))
     }

const templateMode = JSON.parse(localStorage.getItem("dnd-ui-artifacts-templateMode"));

<SelectInput
          source="mode"
          label="Mode"
          choices={templateMode}
        />

**What you were expecting:**
I was expecting the values to get refreshed when the user clicks on the refresh button in the browser

**What happened instead:**
The New Values from the localStorage were not loaded in the UI when the user refreshes the browser

The values were loaded in the localStorage.But the Select multiple-choice did not have the new values

**Steps to reproduce:**
Please set some values in localStorage and load the values in multiple-choice

**Related code:**
I have added the code above in top of this Issue

```
insert short code snippets here
```
 componentDidUpdate() {
    this.checkAuthentication();
    restDataProvider('GET_MANY', 'artifacts', { })
    .then(({ data }) => {
             data.forEach(dnduiartifacts => {
             localStorage.setItem("dnd-ui-artifacts-"+dnduiartifacts.artifactId,JSON.stringify(dnduiartifacts.artifactValues));
        });  
       })
    .catch(error => console.log("Error is fectching artifacts"))
     }

const templateMode = JSON.parse(localStorage.getItem("dnd-ui-artifacts-templateMode"));

<SelectInput
          source="mode"
          label="Mode"
          choices={templateMode}
        />
**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:Chrome
* Stack trace (in case of a JS error):

**Comment by stephen-trippett** [comment]
You're setting the localStorage to a string constant. Try making it a function so it's recalculated every time the variable is referenced.

Like this:

```
const templateMode = () => {
  return JSON.parse(localStorage.getItem("dnd-ui-artifacts-templateMode"));
};
```

**Comment by Kmaschta** [comment]
Yeah, this is not really related to React Admin, but with your custom implementation.
Please, feel free to ask your question on [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin) with the tag `react-admin`.

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
