### ISSUE TITLE
Passing FilterList in ReferenceMany view

### ISSUE THREAD

**Issue by jordanvector** [marmelab/react-admin#3646]
The filterlist feature for the list component is great.  Is there anyway to pass that down to a referenceMany view in a show method?

For example we have a couple 100 to a couple 1000 records per reference many view and would be great to filter those lists.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

We made the choice to omit the filter for a ReferenceManyField component, because it's a complex feature both in terms of code and UX, and because there is a better alternative from a UX standpoint: linking to a filtered list. 

That being said, if you want interactive filters in a ReferenceManyField, you can implement your own version of the component reusing the same logic. Note that it's much easier in v3 with hooks.

So I'll close this issue as we won't implement it in the near future. But if you have a working demo, I'll be curious to see how you tackled the UX challenges.
