### ISSUE TITLE
if i hava some different api , how can I do ?

### ISSUE THREAD

**Issue by 97thjingba** [marmelab/react-admin#3715]
I hava some questions just like 
https://api.ww/admin/avatar
https://api.ww/admin/profile/id

the Home page 
<TextField source="avatar"/>
if i want to use http://api.ww/admin/profile/id 
how can i do ?

other question 

<FormTab label="user_id">
                <TextField source="id"/>
                <TextField source="nickname"/>
                <ImageField source="url"/>
 </FormTab>
 <FormTab label="dd">
            <TextInput source="nickname"/>
  </FormTab>

every formtab page when i click save just like all formtab update ?

**Comment by djhi** [comment]
Please follow the issue template

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
