### ISSUE TITLE
Material-ui card displays improperly within TabbedShowLayout

### ISSUE THREAD

**Issue by instantlinux** [marmelab/react-admin#3719]
**What you were expecting:**

When I design a customized screen that contains some @material-ui/core Card elements (displayed above the content generated by react-admin), the react-admin FormTab elements should display full width of the TabbedShowLayout screen element.

**What happened instead:**

FormTabs are given only about one-fourth of the TabbedShowLayout width, with white-space to the right.

**Steps to reproduce:**

This happens only after running an optimized _react-scripts build_. I'm not sure but I think this is related to the outdated version-pinning that react-admin has for @material-ui/core (^1.4.0 which brings in 1.5.1; current version is 4.4.2). I'll attach my package.json here; the symptom appears whether I omit the two @material-ui lines or leave them in.

**Related code:**
I haven't published my app source but it's available online at www.conclave.events (haven't yet added the account-create workflow so contact me to add one).

The screenshots I'm attaching come from this fairly-generic piece of code to display expandable comments:
```
        <FormTab label='discussion'>
          <ReferenceManyField reference='message' target='event_id'
                    addLabel={false} perPage={250} >
                <Datagrid rowClick='show' expand={<MessageDisplay />} >
                    <ReferenceField source='sender_id' reference='person'
                            linkType='show' >
                        <TextField source='name' />
                    </ReferenceField>
                    <TextField source='subject' />
                    <DateField source='created' showTime />
                </Datagrid>
            </ReferenceManyField>
            {permissions && permissions.match(/event/)
	        && permissions.includes(props.id)
                && <CreateMessageButton />}
        </FormTab>
```

**Other information:**
My failing view file imports four core components: Button, Card, CardHeader and Grid thus:

```
import Button from '@material-ui/core/Button';
import Card from '@material-ui/core/Card';
import CardHeader from '@material-ui/core/CardHeader';
import Grid from '@material-ui/core/Grid';
```
Developer Tools reports the js class for my TabbedShowLayout as "MuiPaper-root-38 MuiPaper-elevation1-41 MuiPaper-rounded-39 MuiCard-root-37 Component-card-36"; the optimized-build process renames that to a generic short name so I can't really troubleshoot it. I'm hoping that this problem would go away if react-admin's dependency on material-ui were brought up to current 4.x version; as a newbie with JavaScript it's hard for me to figure out a workaround.

**Environment**

* React-admin version: 2.9.6
* Last version that did not exhibit the issue (if applicable):
* React version: 16.9.0
* Browser: mobile, Mac Safari, Google Chrome (all the same)
* Stack trace (in case of a JS error): N/A

**Comment by instantlinux** [comment]
Here's my package.json:
[package.json.txt](https://github.com/marmelab/react-admin/files/3634251/package.json.txt)

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by fzaninotto** [comment]
Then it's a bug, sorry for misjudging the report.
