### ISSUE TITLE
Caching "bug" when fetching data

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#3727]
Just noticed a weird "bug" in ra-core/src/reducer/admin/resource/data.ts

When fetching data they get cached, but when one (or more) of the items is deleted on the backend, the RA cache fails to remove it from existing items.

ie. lets have data:
 [{id: 1, name: "one"}, {id:2,name:"two"}]

it gets fetched by GET_LIST and cached
then the data on api is changed, ie. by another app (mobile,db,...)

when you press refresh in RA you get new data without the deleted item
 [{id:2,name:"two"}]

but the addRecord method looks on the incoming data and says "look item one is not here, lets just return the old one" and so you have stale data

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

Moreover, in general, please follow the template for bug report (which version of react admin are you refering to? etc)

**Comment by natrim** [comment]
well you cannot reproduce it by using the codesandbox because changing the fake backend data causes whole app to reload and thus negating the RA caching

noticed it on v3 but the v2 uses same code

**Comment by fzaninotto** [comment]
Confirmed, the bug exists in the `ids.ts` reducer rather than the `data.ts` reducer.

**Comment by sebitoelcheater** [comment]
any news respecting this issue?

**Comment by fzaninotto** [comment]
Fixed by #4261
