### ISSUE TITLE
Parenthesis wraping the id of a record breaks show and edit page

### ISSUE THREAD

**Issue by gregbelyea71** [marmelab/react-admin#3729]
**What you were expecting:**
same functionality as when brackets are not present

**What happened instead:**
brackets lead to no data displaying in show or edit mode but no error being thrown

This works fine for all numbered id field or string fields that don't contain brackets, but my case involves the tag name being the id field in this case... Some tag names have and abbreviation in brackets at the end of them.  These and only these records will not display, if i remove the brackets it works fine but that is not really a desirable option... any ideas? The data comes back to the UI from the graphql server no problem at all, it just will not render

react-admin version is 2.7.1, chrome is the browser but same behavior in explorer...

**Comment by Kmaschta** [comment]
I cannot reproduce the issue with React Admin v2.9.6.

Take the following CodeSandbox: https://codesandbox.io/s/simple-b3r87
- Search for the post named `Accusantium qui nihil voluptatum quia voluptas maxime ab similique`
- I changed its id for `{[abctest]}`

For me, the edit view and show view of this post works fine, I can even create a comment linked to that post.

In order to confirm the bug, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by gregbelyea71** [comment]
I have verified that [***] will indeed work, but maybe i mispoke in my post... i should have said parenthesis. This is an example that will work with square brackets but not parenthesis..

id: Energy Star Central Air Conditioning (CAC)

**Comment by Kmaschta** [comment]
Ow. This is an issue, you're right!

Way to reproduce:
1. Go to https://codesandbox.io/s/simple-xvm8w
2. Search for the post named `Accusantium qui nihil voluptatum quia voluptas maxime ab similique`
3. The edit and the show view doesn't display the correct infos for that post

Thanks for reporting it!

**Comment by bicstone** [comment]
The Parentheses mean special characters.
Parentheses need to add an escape character `\` .
see [React Router API docs](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteMatching.md#path-syntax).

https://github.com/marmelab/react-admin/blob/83f2b4e98f7d4fda945a56a76d8cc0d295163e67/packages/ra-ui-materialui/src/detail/TabbedShowLayoutTabs.js#L6-L9
