### ISSUE TITLE
Load nested resource properties values in edit inputs

### ISSUE THREAD

**Issue by Dogson** [marmelab/react-admin#3762]
In my API, I have an resource Person which contains a nested resource Profile on a one-to-one relation.
When creating and editing a person, my API allows to directly send the properties of the profile, and create or edit the nested Profile resource.

This is what I receive when I do a `GET` on a person, and it's also what I can send to my API when I do a `PUT` or `POST`
```
person: {
    profile: {
        firstName,
        lastName
   },
   ...otherPersonProperties
}
```

On the Edit page of the resource Person, I display the input fields relative to the profile nested resource :

```
<Edit {...props}>
    <SimpleForm>
        <div className={classes.cardContent}>
            <TextInput source="profile.firstName"/>
            <TextInput source="profile.lastName"/>
        </div>
    </SimpleForm>
</Edit>
```

**What you were expecting:**

The text inputs relative to the nested resource Profile should be pre-filled with fetched values.

**What happened instead:**
The inputs are empty.

Is it not possible to load values of a nested resource properties into a TextInput ?

**Comment by Kmaschta** [comment]
SimpleForm close its children and inject its props to its children.
If you are inserting a component between the form and its children, be sure to propagate the props.

Moreover, as explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
