### ISSUE TITLE
when i refresh the page the appbar overlaps the whole page

### ISSUE THREAD

**Issue by angelonino02** [marmelab/react-admin#3779]
**What you were expecting:**
I expect the dashboard is the same 

**What happened instead:**
from **dashboard**..
when i refresh the page the **APPBAR** overlaps the whole page
you need to **relogout** and **relogin** to view the normal state.

**Environment**

* React-admin version: react-admin": "^2.9.7
* Last version that did not exhibit the issue (if applicable):
* React version: 16.10.2
* Browser: brave, chrome
* Stack trace (in case of a JS error):
![image](https://user-images.githubusercontent.com/17834016/66256687-0af55500-e7c3-11e9-9581-1a7b83463f25.png)

**Comment by Kmaschta** [comment]
Weird.. Does it happen only in production? In that case, it might be related to #1782

In other cases, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by angelonino02** [comment]
Hi.. I think theres a conflict in material ui version.
can i install updated material ui? and material-table along with react-admin?

**Comment by angelonino02** [comment]
Yes in production

**Comment by Kmaschta** [comment]
Yep, definitely related to #1782 so I close this one as duplicated.

@angelonino02 to answer you, React Admin v2 only support Material UI 1.x versions, and React Admin v3 will support Material UI v4.
Besides, be sure to have exactly the same version of Material UI as the React Admin one.

For all your others questions, please ask them on [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin) with the tag `react-admin`.

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

**Comment by angelonino02** [comment]
I see how can I use the 3.0.0.0 beta.0? thanks :)
