### ISSUE TITLE
How to link two DateField ? Or get the value of a FormDataConsumer

### ISSUE THREAD

**Issue by quentincapra** [marmelab/react-admin#3790]
I'm working on a React project with React admin and I have a problem about linking two fields.

I know how to link two Inputs (with FormDataConsumer) but I don't know how to link two fields (which correspond to the inputs) or get the value of the FormDataConsumer to display it in a Field.

Here is my code :

```
class CreateClient extends React.Component {
  state = {
    installationDate: new Date()
  };

  render() {
    const { classes, translate, ...props } = this.props;
    return (
      <Create {...props} title={<ClientCreateTitle />}>
        <TabbedForm>
          <FormTab label="resources.client.tabs.identity">
            <TextInput autoFocus source="name" required />
            <TextInput
              type="email"
              source="email"
              validation={{ email: true }}
              formClassName={classes.email}
              validate={[required(), email()]}
            />
            <TextInput
              type="phone"
              source="phone"
              validation={{ phone: true }}
              formClassName={classes.phone}
            />
          </FormTab>
          <FormTab label="resources.client.tabs.address" path="address">
            <LongTextInput
              source="address"
              formClassName={classes.address}
              label="resources.client.localisation.address"
              required
            />
            <TextInput
              source="zipcode"
              formClassName={classes.zipcode}
              label="resources.client.localisation.zipcode"
              required
            />
            <TextInput
              source="city"
              formClassName={classes.city}
              label="resources.client.localisation.city"
              required
            />
            <TextInput
              source="country"
              formClassName={classes.country}
              label="resources.client.localisation.country"
              required
            />
          </FormTab>
          <FormTab label="resources.client.tabs.equipment" path="equipment">
            <DateInput
              source="installDate"
              label="resources.client.info.installationDate"
              defaultValue={this.state.installationDate}
            />
            <FormDataConsumer>
              {({ formData, ...rest }) => (
                <DisabledInput
                  source="installDate"
                  label="Date de garantie (Automatique)"
                  format={value =>
                    new Date(
                      new Date(value).getTime() + 86400000 * 365
                    ).toLocaleDateString()
                  }
                  {...rest}
                />
              )}
            </FormDataConsumer>
          </FormTab>
        </TabbedForm>
      </Create>
    );
  }
}

export default withStyles(styles)(CreateClient);
```
I have the installationDate which is a DateInput and the warrantyDate (the DisabledInput) which is the installationDate + 1 year.

As you can see, my DisabledInput has the same source as the DateInput, these two inputs work fine but when I want to display them in a Show view I can't display the value of the DisabledInput because it hasn't its proper source.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
