### ISSUE TITLE
When I repeatedly refresh the page during the data request, it will cause the login to pop up.

### ISSUE THREAD

**Issue by 97thjingba** [marmelab/react-admin#3793]
**What you were expecting:**
I think I won't log out when I repeat the refresh.

**What happened instead:**
When I repeatedly refresh the page during the data request, it will cause the login to pop up.

**Steps to reproduce:**
When I repeatedly refresh the page during the data request, it will cause the login to pop up.

**Environment**
```
    "react": "16.10.2",
    "react-admin": "3.0.0-beta.0",
    "react-dom": "^16.4.1",
    "react-scripts": "1.1.4",
    "reactbulma": "3.0.4",
    "whatwg-fetch": "^3.0.0"
```

And will tell me when I am popped up.

![WeChatd58beb9cd680170afc24e7a78cf90b12](https://user-images.githubusercontent.com/39749571/66472367-a9cdca00-eabf-11e9-93d5-1b9f9258d18e.png)

**Comment by Kmaschta** [comment]
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by 97thjingba** [comment]
I have solved this problem ..thankes

**Comment by jmccabe-harmelin** [comment]
@97thjingba how did you end up solving this? Thanks.

**Comment by 97thjingba** [comment]
@jmccabe-harmelin  This is a problem with my own login token. Do you have a similar problem?
