### ISSUE TITLE
"Invalid Token Specified" issues

### ISSUE THREAD

**Issue by thtan89** [marmelab/react-admin#3814]
https://marmelab.com/react-admin/Authorization.html

Hi, I was follow this AUTH_GET_PERMISSIONS to do the permissions but it come out this error when I want to login:

![Screen Shot 2019-10-14 at 11 54 18 AM](https://user-images.githubusercontent.com/51570658/66731906-4f03ec00-ee8c-11e9-9a30-3860e879b5c8.png)

Is it related with the token defined here?

![Screen Shot 2019-10-14 at 12 03 33 PM](https://user-images.githubusercontent.com/51570658/66731924-60e58f00-ee8c-11e9-919f-678628cff2f9.png)

Or need to pass the permissions parameter to here:

const httpClient = (url, options = {}) => {
    if (!options.headers) {
        options.headers = new Headers({ Accept: 'application/json' });
    }
    const token = localStorage.getItem('token');
    options.headers.set('Authorization', `Bearer ${token}`);
    return fetchUtils.fetchJson(url, options);
}

If it is how to pass the parameter? Thank you.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
