### ISSUE TITLE
Remove ra-tree from v3

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#3827]
The ra-tree modules will be overhauled in v2 (#3771). We won't have time to port these changes to v3, or it would delay v3 too much. As a consequence, we must remove ra-tree from version 3. We'll add it back later, but that leaves us more freedom in the release schedule.

**Comment by kopax** [comment]
Hi and thanks for accelerating the v3 official release, I can't wait to try it out.

Curiosity but could you already tell if the API in v2 and v3 will be the same?

> We'll add it back later

By later do you mean v3.1 or possibly further?

**Comment by djhi** [comment]
We're not sure yet. It currently forces you to implement your tree using a parent/child relationship or to make a translation layer if you implemented yours using linked list. We'd like to find a better solution. The new ra-tree for v2 is an improvement though and good enough for our usage.

**Comment by kopax** [comment]
Hi and thanks for the big rush for v3, it looks very promising, we will upgrade our codebase soon, what's how do you welcome react-simple-form compare to redux-form?

Following v3 (don't forget to rest a bit in between) and this [comment](https://github.com/marmelab/react-admin/issues/3902#issuecomment-547834745), now that the release is on, is there any plan to reintegrate ra-tree-materialui in v3.1.0? Since I don't see it in the [milestone](https://github.com/marmelab/react-admin/milestone/71).

Thanks in advance,

**Comment by fzaninotto** [comment]
We don't have any demand from our customers yet, so i'ts not a priority. Feel free to work on an implementation on your side.

**Comment by justin2taylor** [comment]
Checking in to confirm that `ra-tree` / `ra-tree-ui-materialui `still isn't compatible with react-admin 3 correct?

**Comment by fzaninotto** [comment]
Correct
