### ISSUE TITLE
"Works with Django"

### ISSUE THREAD

**Issue by oi-eddyoj** [marmelab/react-admin#3841]
**What you were expecting:**
Has anyone actually tried this? I expected this to work out the box with Django Rest Framework but it doesn't. It has been a time consuming task trying to set custom headers to fit react-admins requirement for X-Total-Count header. Django Rest Framework prefers to put in to the json response. 

Can't react-admin read from the json instead? It seems like an option should be set instead of reinventing with Django or other rest frameworks.

**Comment by oi-eddyoj** [comment]
I don't think I'm the only one:

https://stackoverflow.com/questions/57376651/adding-x-total-count-with-django-corsheaders

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by oi-eddyoj** [comment]
I did. I have this working exclusive of paginated results by adding my own custom header through a custom class based view in Django. When I add their pagination code, I lose the header. I really think the feature to use 'z-total-count' should be default but changeable. This has taken me 2 evenings to try and resolve something that should be fairly simple.

**Comment by Kmaschta** [comment]
You're right, the Simple REST data provider do not suites the huge diversity of API standards out there.

That said, React Admin is designed with heavy customization in mind: you are not forced to change every aspect of your API to consume it with React Admin.

The community wrote a lot of [data providers](https://marmelab.com/react-admin/DataProviders.html#available-providers) for many APIs, in fact there is a data provider dedicated to Django REST Framework:
https://github.com/synaptic-cl/ra-data-drf

Feel free to try it and report any issues to the author of that library.
Issues on this repo are only related to the React Admin own design & code.

**Comment by oi-eddyoj** [comment]
Thanks @Kmaschta , I'll check it out.
