### ISSUE TITLE
 I want to know if there is any way for my picture to display an alternative picture in the case of 404? Use ImageField

### ISSUE THREAD

**Issue by 97thjingba** [marmelab/react-admin#3846]
**English is not my native language; please excuse typing errors.**
**What you were expecting:**
I want to be able to display a default image when my image is 404.

**What happened instead:**
When I request a 404 image, the console will report a 404 error, I don't want to do this.

![image](https://user-images.githubusercontent.com/39749571/67155586-d8ac3180-f344-11e9-9c26-7d039b412b89.png)

**Environment**

- ra-data-json-server: 2.9.6,
- react: 16.10.2,
- react-admin: 2.9.7,
- react-dom: 16.10.2,
- react-scripts: 1.1.4,
- reactbulma: 3.0.4,
- whatwg-fetch: 3.0.0

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
