### ISSUE TITLE
save confirm undoable question

### ISSUE THREAD

**Issue by pjw9195** [marmelab/react-admin#3854]
i see activate (delete undoable ) -> dialog confirm
but (save undoable) dont activate 
i dont see dialog confirm
why not?

React admin dont support save undoable ??  

please answer i m  crying..

**Comment by fzaninotto** [comment]
"confirm" and "undoable" mean the opposite in react-admin. "undoable" means no confirm dialog, but the ability to undo the action in the notification. In that sense, the Edit view does support undoable. Now, if you want the Save button of the Edit form to show a confirm dialog instead of dispatching an undoable action, you can do it by replacing the react-admin SaveButton by your own. 

As to how to do it, please go to StackOverflow - this issue tracker isn't for HowTo questions. Also, in the future, please follow the issue template.
