### ISSUE TITLE
No data shown in DataGrid in ReferenceManyField 

### ISSUE THREAD

**Issue by zhouhao27** [marmelab/react-admin#3916]
**What you were expecting:**

My `article` has multiple `comments` which identified by `article_id`. 

**article**
<img width="874" alt="Screenshot 2019-11-01 at 3 36 30 PM" src="https://user-images.githubusercontent.com/8099731/68009645-7ac10780-fcbd-11e9-998c-2f987acfd278.png">

**Comments**
<img width="929" alt="Screenshot 2019-11-01 at 3 36 19 PM" src="https://user-images.githubusercontent.com/8099731/68009658-81e81580-fcbd-11e9-889b-e88a5b6f3ded.png">

**What happened instead:**

No records shown for comments.

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

Code in my PhotoEdit:

```
         <ReferenceManyField
        reference="comments"
        label="Comments"
        target="article_id"
        fullWidth
      >
        <Datagrid>
          <TextField source="body" />
        </Datagrid>
      </ReferenceManyField>
```

My [CodeSandbox link](https://codesandbox.io/s/immutable-cherry-6mtp2).

**Other information:**

User name: demo@mail.com
Password: password

**Environment**

* React-admin version: 3.0.0-beta.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.10
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by zhouhao27** [comment]
Sorry. But I thought this is  a bug. No data shown in DataGrid.

**Comment by djhi** [comment]
It's not. This is a feature used in all our examples, which work, so there is something wrong with your code and StackOverflow is where you should ask for help.

**Comment by gabrielperales** [comment]
@zhouhao27 Did you manage to make it work? I'm having the same problem but I don't know if it's my fault or if it is a bug

**Comment by gabrielperales** [comment]
Ok, It was my fault. The problem was that there was not a resource in the `Admin` component for the resource we are making reference in `ReferenceManyField`. Read more https://github.com/marmelab/react-admin/issues/1903#issuecomment-396900348

**Comment by Cornul11** [comment]
@zhouhao27, probably not actual anymore, but for those finding this in the future, usually this problem occurs when you didn't define a proper resource in the `<Admin>` component. So, in order to fix your problem @zhouhao27, you'd have to have something along these lines:
```
<Admin ...>
    <Resource ...> // other resources
    <Resource name="comments">
</Admin>
```

**Comment by ayushsingh2204** [comment]
for active filters in simple grid , a default message come "No results found" when list returns empty . 
Its not reading empty prop ?
