### ISSUE TITLE
Multiple create (and update) forms to a resource

### ISSUE THREAD

**Issue by kornelc** [marmelab/react-admin#3962]
Dear Dev Team, thanks for this great tool! 

I'm looking to add multiple posts forms to a user signup API, but react-admin only supports one per resource. 

I have a REST API which receives POSTs from multiple sources. E.g. a User resource is created by a signup POST, and then gets posts from Stripe afterwards, to post credit card purchases to a user account. I would like to have a "Send Test Stripe Post" button, or other similar test buttons for a particular resource to simulate posts that I expect in production. This would be very useful when testing if things work in production.

Allowing to specify multiple POST forms for a particular resource would make all these use cases possible. We could just have an array of edit and update forms, triggered from different buttons each, instead of a single create/edit property on Resource.

**Comment by Kmaschta** [comment]
Hi, and thanks for your question.
The core team won't implement such a specific need in React Admin, but it's customizable enough to let you do something on your own.
Feel free to read [advanced tutorials](https://marmelab.com/react-admin/AdvancedTutorials.html) to become familiar with RA customization!

As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!
