### ISSUE TITLE
how to reset SimpleForm values after submit in v3

### ISSUE THREAD

**Issue by XHMM** [marmelab/react-admin#4005]
**Is your feature request related to a problem? Please describe.**
I'am using `v3` version, when I use `SimpleForm`  to implement a custom form component, I didn't find a way to reset/clear form values after submit

```jsx
import React, {useState } from 'react';
import { FileInput, Toolbar, SimpleForm, FileField,useDataProvider,useNotify } from "react-admin";

const UserActions = (props) => {
  const dataProvide = useDataProvider();
  const notify = useNotify();
  const [loading, setLoading] = useState(false);
  
  return(
    <SimpleForm  save={(p) => {
      if (p.files) {  
        setLoading(true)
        dataProvide.create('file', {
          data: p.files.rawFile
        }).then((data) => {
          notify('succeed');
          setLoading(false);
          // how to clear files preview here?
        }).catch(err => {
          notify(`fail`);
          setLoading(false);
        });
      }
    }} saving={loading}>
      <FileInput source="files" value={file}>
        <FileField source="src" title="title" />
      </FileInput>
    </SimpleForm>)
};

export default UserActions;
```

**Describe the solution you'd like**
As code above, I want to clear files preview after request succeed, but there is no way to do it, `react-admin` seems not expose `reset` function from `react-final-form` .

**Describe alternatives you've considered**
I have no idea how to solve this, unless implement a form from scrath, if so I will not benefit from `SimpleForm` builtin features.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
