### ISSUE TITLE
optimistic rendering causing unexpected checkAuth redirect behaviour in v3.0

### ISSUE THREAD

**Issue by girishla** [marmelab/react-admin#4006]
First of all, let me thank the core team for all your efforts. BIG kudos and version 3.0 looks fantastic. Here's something I perceive as an issue:

### ISSUE DETAILS:

**What you were expecting:**
When an authProvider is supplied, Resources should be rendered only after the checkAuth function resolves. 

**What happened instead:**
Resources are optimistically rendered before checkAuth resolves and then if the promise is rejected, the user is redirected to the login page
This would be a security hole as users get a peek before being kicked out. Agreed, in cases of dataProviders backed by authenticated API's, this would be less of an issue, but it still feels wrong.

**Steps to reproduce:**
see attached gif

**Related code:**
The following `authProvider` demonstrates the behaviour

```javascript
export default {
    login: ({ username }) => {
        localStorage.setItem('username', username);
        // accept all username/password combinations
        return Promise.resolve();
    },
    logout: () => {
        localStorage.removeItem('username');
        return Promise.resolve();
    },
    checkError: () => Promise.resolve(),
    checkAuth: async () => {
        // added fake delay to simulate behaviour clearly
        await new Promise(resolve => setTimeout(resolve, 10000));
        return localStorage.getItem('username')
            ? Promise.resolve()
            : Promise.reject();
    },
    getPermissions: () => Promise.reject('Unknown method'),
};


```

**Other information:**

![RA_Issue1](https://user-images.githubusercontent.com/10451063/69165308-45a01c00-0ae9-11ea-8ec6-8d7898f0435d.gif)

**Environment**

* React-admin version: 3.0.0-beta.6
* Last version that did not exhibit the issue (if applicable):
* React version: 16.9.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
First, thanks for the kudos! We love that you love us and that we make your life better. 

Thanks also for the detailed and very clear issue description. 

I disagree that this is an issue because an application working as you describe would expose a data API without authentication, which is a huge security hole. It would take a hacker half a second to grab all the API data, whether react-admin puts the authProvider as synchronous or not. So I think the case you describe doesn't exist in real life. In my experience, APIs check for auth token and return a 403 if it's not valid, in which case the react-admin user never sees any data. 

And if someone decides to build a web app with such a huge vulnerability, we don't mind that they can't use react-admin. It's probably not a good fit for their project anyway.

**Comment by girishla** [comment]
@fzaninotto Thanks for the detailed response. On second thought, I think I agree, this is a non-issue.

**Comment by pdiniz13** [comment]
@fzaninotto while I agree with this in terms of data security. This is actually causing another problem, this extra requests that are getting fired are actually failing and trying to redirect the user. The extra redirect attempts are actually resetting the value of nextPathname.

**Comment by Rmannn** [comment]
As @fzaninotto said this is causing another problem with extra redirects. Why are those requests fired even when the login action is dispatched ?

**Comment by luanped** [comment]
Sorry for re-opening this, in my case I'm using react-admin with react-admin-firebase, and although no real data is ever displayed before the checkAuth is resolved, we still see a "dashboard flashing issue" (just like in the gif above). So there is no security risk, but just looks weird, was wondering if there is a way to disable the optimistic rendering part for authentication, so that the dashboard isn't momentarily displayed (without information) before checkAuth returns and redirects user to login

**Comment by fzaninotto** [comment]
I'm afraid that's not possible, because we want to prioritize one use case, which is when an already identified user opens a new browser tab on the admin. They should see the content right away.

So we favor speed for returning users over a small flash for users accessing an internal page without valid credentials. That's a trade off, and a design decision, but your remark doesn't make it invalid in my opinion.

**Comment by mondayrris** [comment]
The captioned behaviour is fixed recently by adding `requiredAuth={true}`. See [Admin docs](https://github.com/marmelab/react-admin/blob/master/docs/Admin.md#requireauth)

```
const App = () => (
    <Admin dataProvider={dataProvider} authProvider={authProvider} requireAuth>
        <Resource name="posts" list={PostList} />
    </Admin>
);
```

**Comment by dnk8n** [comment]
I get the same redirect to login page behavior independent of requiredAuth={true} or requiredAuth={false}
