### ISSUE TITLE
2FA Integration

### ISSUE THREAD

**Issue by maxschridde1494** [marmelab/react-admin#4010]
My team has a few projects that are currently using react-admin as our admin dashboard (and loving it). We need to incorporate 2FA in the login flow. I found a single stack overflow post touching on the issue here https://stackoverflow.com/questions/56029279/react-admin-two-factor-authentication-implementation but this has received zero responses so I am creating an issue in hopes of garnering a little support.

Has anyone integrated 2FA with the react-admin login flow? If so, can you please share any best practices and / or sample code? If not, does anyone have any ideas regarding how to integrate 2FA? Specifically, how can you issue 2 requests in the authProvider AUTH_LOGIN (one for username / password authentication, one for 2FA) before issuing the login success redirect?

Any suggestions would be greatly appreciated. Thanks!

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
