### ISSUE TITLE
Nested Queries?

### ISSUE THREAD

**Issue by hassanbazzi** [marmelab/react-admin#4149]
How can we possibly use Nested Queries? It just seems like a big waste when my server fully supports nested queries.

I'm also unable to make a nested input form.

I have a book, that has an author, and the author has a username with a first name and last name.

When creating the book, I want to show a list of Authors, but the `optionText` needs to be the author's user's first and last name.

I've been trying to figure it out but figured I'd post here since I've had no luck.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
