### ISSUE TITLE
Use react-admin inside nextJs

### ISSUE THREAD

**Issue by NykolaySavin** [marmelab/react-admin#4158]
I want to render react-admin application inside nextJs. I solved the problem with "document is not defined" using dynamic import and application is rendered But when I try to move to any page inside application I get error from data provider that headers were not set. My server logs tells that only auth check route is called, but no one get items route were called after it.

**Comment by Kmaschta** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [Stack OverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike GitHub, Stack Overflow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

Once you get a response, please continue to hang out on the react-admin channel in Stack Overflow. That way, you can help newcomers and share your expertise!

**Comment by pacikav** [comment]
Hey Nikolay
Could you please paste example code here how you solved problem 'document is not defined'?

**Comment by austinwalter** [comment]
If anyone else runs into the "document is not defined" issue, as the original poster said you can get around it by using dynamic import, with server-side rendering disabled.

`const PageNoSSR = dynamic(() => import('../views/page'), { ssr: false });`

https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by sidonaldson** [comment]
Linking back to a SO post for reference https://stackoverflow.com/questions/65629726/react-admin-with-next-js
