### ISSUE TITLE
Injecting List, Show, Edit, Create in any places

### ISSUE THREAD

**Issue by jedrzejowski** [marmelab/react-admin#4194]
I would like create a file browser with `<List />` component in `<Show />` component.

Let's say we have a user with home directory and we want to create a file browser to this directory with ability to remove files. The idea of files doesn't match the idea of simple tables, which rows can be edited.

So I have created my own component with username and directory as states, `useDataprovider()` as hook, and `<Table/>` from MUI, altered data provider a bit. And it works quite nice.

The problem comes when there are many position in list, like 50+. A pagination would be nice. So I tried to _fake_ props of `<List />` and later `<ListView />` to replace `<Table />` but I failed.

After short code review, it looks like implementing `<List />` as is, is not possible, because many hooks and other things it uses. In general nesting one into another of any type would be a mess in come.

My idea of this would look like this:
```jsx
function HomedirBrowser({username}) {

    const [usrPath, setUsrPath] = React.useState("/");

    return (<List
        resource={`/users/${username}/dir/${usrPath}`}
    >
        <Datagrid>
            <TextField source="type"/>
            <TextField source="name"/>
            <TextField source="last_edit"/>
            <TextField source="size"/>
            <Button onClick={({record}) => setUsrPath(usrPath + "/" + record.name)}>Enter</Button>
        </Datagrid>
    </List>)
}
```
The custom `resource` which would depend on a state and the button could alter the state.

Is this possible to do? Or there is any other way to achieve nesting one element into another.

Edit:
Of course, I don't want to save state to browsing in url of anywhere at all.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
