### ISSUE TITLE
How to use another format for links with ReferenceField

### ISSUE THREAD

**Issue by radostnomne** [marmelab/react-admin#4272]
Hi! I have a link on backend with format: `/users/:id`. But **RefernceField** sends request to `/users?id=123456`. How to adopt **ReferenceField** for my format?

I tried this variant:
```js
<ReferenceField
    source="userId"
    reference="users"
    link={(record, reference) => \`localhost:1234/reference/${record.userId}\`}
>
    <TextField source="firstName" />
</ReferenceField>
```

But this variant doesn't work.
What am I doing wrong?

**Comment by Luwangel** [comment]
Hi, and thanks for your question.

As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md#asking-questions), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is the [React Admin Channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

This will make your question easy to find by the core team and the react-admin developers community. Unlike GitHub, StackOverflow has great SEO, gamification, voting and reputation. That's why we chose it and decided to keep GitHub issues only for bugs and feature requests.

So I'll close this issue and invite you to ask your question on the [React Admin Channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

Once you get a response, please continue to hang out on the React Admin Channel. That way, you can help newcomers and share your expertise!

PS: you should look at the documentation about custom data providers
https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider
