### ISSUE TITLE
How to pass enctype to simpleform ?

### ISSUE THREAD

**Issue by thatshailesh** [marmelab/react-admin#4284]
I want to build file upload functionality using `simpleform` component.

For this, I want to pass enctype="multipart/form-data" to form.

I am not able find any documentation or forums to understand, how can I pass this, if inside any props, or some other way.

Please help with this.

```
<Create {...props}>
    <SimpleForm enctype="multipart/form-data">
        <FileInput source="files" label="Related files" multiple accept="text/*,image/*">
            <FileField source="src" title="title" />
        </FileInput>
    </SimpleForm>
</Create>
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by thatshailesh** [comment]
@djhi This question have been asked on stackoverflow and no answer received since 2 years
https://stackoverflow.com/questions/48096825/how-to-pass-enctype-to-simpleform-in-admin-on-rest
Hence submitting here
