### ISSUE TITLE
List views occasionally show out-of-sync filtered results

### ISSUE THREAD

**Issue by garethsb-sony** [marmelab/react-admin#4287]
**What you were expecting:**

When typing fairly quickly in a filter box, the list should be refreshed live. After stopping typing, the filtered list contents should be consistent with the contents of the filter box.

**What happened instead:**

Using a REST API that takes a variable length of time to respond to filtered queries, it is possible to end up with inconsistent filter box contents and listed items.

**Steps to reproduce:**

Typing even fairly quickly in a filter box results in multiple requests being sent by react-admin via the data provider. Just occasionally, esp. when going from empty filter box to one char or one to two chars, the response to the earlier request arrives afterwards, and this results in the list showing results which do not correspond to the filter.

Is react-admin intended to potentially have multiple data provider requests in-flight?
Should react-admin handle making sure the response displayed is based on the most recent request?

**Related topic:**

When a filtered query takes some time to respond, it would be nice to be able to 'debounce' the live filtering, i.e. don't issue the data provider request until a short interval (e.g. 0.5s) after the last typed character.

**Comment by fzaninotto** [comment]
hi, and thanks for your report. 

React-admin debounces the filter requests, but it may happen that the results arrive in a different order than the requests. That's a know limitation. 

We used to have a request cancel system within react-admin in the past (using redux-saga's `takeLatest`), and we had to remove it due to side effects. 

So the current situation is a compromise: it fails in situations like yours, but works in most situations. 

If you use an HTTP client like axios, you can still cancel some requests at the dataProvider level. Also, you can also implement a Filter component that filters on submit instead of on change, which will remove the problem. 

So I'll close this issue: unless we do a major paradigm shift, and decide to use reactive programming, this won't be fixed.

**Comment by garethsb-sony** [comment]
Many thanks @fzaninotto, we have now added `lodash.debounce` to our custom views, so hopefully that will nicely work around the issue.
