### ISSUE TITLE
React-admin is using values from getList when running update

### ISSUE THREAD

**Issue by dryhten** [marmelab/react-admin#4297]
Hey guys! Not entirely sure this is an issue, I understand that react-admin is written to be primarily used with a REST server in the back (in which case it's not an issue), but for some custom GraphQL data providers in some edge scenarios, it can be.

The problem is this: if your data provider returns different fields in `getList` and `getOne`, then the extra fields you specify in `getOne` will be replaced by null if you don't use an input component where the field is the source. This only happens if `getList` is run before `getOne`, otherwise everything is fine.

Again, really edge case, I'll leave this one up to you if you consider it a problem or not. Here is an example where it can happen: assume you have a database with the following users collection https://my-json-server.typicode.com/dryhten/typicode-fake-db/users

So basically each user has a username, email and active field. Let's say you write a custom graphql data provider and in `getList` you only want username and email. Then in `getOne` you also want `active`, but only to display it in a custom way. When you run the update, the active field will be replaced by null which is not what you'd want. To overcome this you'd either have to query for it in `getList` or add it as source to some input component.

Here is an example of what I just said: https://codesandbox.io/s/crazy-jennings-t1b7k

If you open the console, it prints messages as it goes along: first the data you get in `getList`, then the data in `getOne` and finally in `update`. You can see that the `active` field is null.

My guess is that react-admin is using an object to store data for each resource key, it first populates this with what it gets from `getList` and it doesn't update it with values from `getOne`. It only updates with whatever the Edit view/form returns. I will not further investigate this.

I guess more than finding it as an issue I just find it confusing that react-admin uses data from getList to update, rather than getOne.

**Comment by fzaninotto** [comment]
Hi, and thanks for your comment. 

This has already been required multiple times (e.g. #3767), and we have always said that the react-admin data model requires entire resources, and shares them between views **by design**. This strong design decision allows optimistic rendering and improved performance in most cases.  

I realize this may mean we're under-using the potential of GraphQL, but I also realize that GraphQL makes less and less sense now that we have http/2. 

So this isn't considered as a bug, and you have to return the same shape for a given resource from all methods in your dataProvider - the REST way, even if it's a GraphQL server.
