### ISSUE TITLE
Better element selection for browser testing

### ISSUE THREAD

**Issue by archfz** [marmelab/react-admin#4316]
**Is your feature request related to a problem? Please describe.**
It is very hard to write proper browser tests for react admin based applications since most of the elements have no proper selectors.

**Describe the solution you'd like**
A solution would be to have some attribute like data-js or data-test on the elements that atleast give some context. For example the resource menu items could have ``data-js=resource_menu_item:{resource_id}`` and buttons like the save form button to have `data-js=resource_submit_button:{resource_id}`.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

It is possible to write e2e tests for react-admin apps - we do it all the time. This very repository has [numerous examples](https://github.com/marmelab/react-admin/tree/master/cypress/integration). 

Form fields and datagrid rows already have distinctive ids. For menu items and buttons, I suggest you use the displayed text as selector, following the guiding principles of react-testing-library underlined [in this article](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change).

If you absolutely cannot write a test because of a particular missing id or class, please open a new issue with a specific case.

**Comment by archfz** [comment]
@fzaninotto Best practices dictate that one should not base their tests on text in elements. Currently this is what we need to do yes but its not ideal. Any changes to these translations would require changes to tests as well.

**Comment by fzaninotto** [comment]
It seems that we chose different sets of best practices - which means that neither are really "best" practices. So I'll rephrase my answer: not including classes in every element is a design choice.

**Comment by archfz** [comment]
@fzaninotto  Using classes for selection in JS or tests is again a bad practice. You want to separate the concerns and properly signify the scope of these: classes should be used only for styling, which means you need different means of selection path for tests. 

I actually saw that there are cypress test for react admin. Cypress also states that data-cy attribute would be the best practice. Anyways this should be a nice to have feature request that actually has benefits. So can we maybe leave it open for a while and see if other community members would like it?
