### ISSUE TITLE
X-Total-Count Problem

### ISSUE THREAD

**Issue by onlineverh** [marmelab/react-admin#4320]
My Backend is with Sails.js ,
I install React-admin and this Package ra-data-json-sails
this is my Code
![photo_2020-01-19_20-48-47](https://user-images.githubusercontent.com/55762364/72686136-7826bf00-3b02-11ea-90f5-0fd065085b74.jpg)
and i showing this error.
![photo_2020-01-19_20-48-48](https://user-images.githubusercontent.com/55762364/72686145-85dc4480-3b02-11ea-9cb4-65159f6c6e0c.jpg)
Plz help me

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
