### ISSUE TITLE
Edit or Create layout improvement for Input component's styles

### ISSUE THREAD

**Issue by deksden** [marmelab/react-admin#4321]
Currently we have 2 options for default layout of edit/create input components: 251px wide control or 100% wide control. I see some limitations for wide-screen displays for 251px wide-controls - they appears subjectively short.

Maybe slightly more better layout can be 25% (or 33% ?) wide controls (not less than 251px) and 100% wide controls.

**Comment by fzaninotto** [comment]
Hi, 

And thanks for your suggestion. 

I don't believe that very large inputs are usable - when switching from one line to the other, a user usually has trouble finding the next line when the character size / line length ratio exceeds a certain amount. 

I agree that 250px inputs can appear 'small' in large screens, but making them longer will harm usability. So that boils down to a UI/UX tradeoff.

We won't change default input length on SimpleForm for that reason. But the documentation explains how you can easily [build your custom form layout](https://marmelab.com/react-admin/CreateEdit.html#customizing-the-form-layout) if you think it's a mistake.

**Comment by deksden** [comment]
Just for reference for googlers: customizing input components can be as easy as following code:

form-styles.js:
```
export const FormStyles = {
  wide35: {
    width: '35%',
    minWidth: '251px'
  },
  wide45: {
    width: '45%',
    minWidth: '251px'
  },
  wide50: {
    width: '50%',
    minWidth: '251px'
  },
  wide60: {
    width: '60%',
    minWidth: '251px'
  },
  wide75: {
    width: '75%',
    minWidth: '251px'
  }
}
```

Any component (UserGroupForm in this sample):
```
...

import { makeStyles } from '@material-ui/core/styles'
import { FormStyles } from './form-styles'

const useStyles = makeStyles(FormStyles)

...

const UserGroupForm = (props) => {
  const classes = useStyles()

  return (
    <SimpleForm {... props}>
      <TextInput source='id' label='Id' className={classes.wide35} disabled />
      <TextInput source='name' label='Name' className={classes.wide35} />
      <SelectInput source='systemType' className={classes.wide35} choices={choices} translateChoice={false} />
      <ReferenceArrayInput source='users' label='Users' className={classes.wide50} reference='user'>
        <SelectArrayInput source='name' />
      </ReferenceArrayInput>
    </SimpleForm>
  )
}

export const UserGroupEdit = props => (
  <Edit title={<UserGroupTitle />} {...props}>
    <UserGroupForm />
  </Edit>
)

export const UserGroupCreate = props => (
  <Create {...props}>
    <UserGroupForm />
  </Create>
)

```
