### ISSUE TITLE
Undocumented difference between useQuery and useGetList Hooks

### ISSUE THREAD

**Issue by nik-lampe** [marmelab/react-admin#4325]
Hello,

When retrieving a list of entities with the useQuery hook, the data property of the response is an array of entites. But when using useGetList (or also useGetManyReference) the response has a data property which is an object with id -> entity pairs, and an ids property which includes all the IDs.

```
 const { data } = useQuery({
    type: 'getList',
    resource,
    payload: {pagination, sort, filter}
})
```

=> data is an array of objects.

```
 const { data, ids } = useGetList(
    resource,
    pagination,
    sort,
    filter,
  )
```

=> data is on object like `{ 1: entity, 2: entity, ... }` and ids is an array with IDs like `[1, 2, ...]``

I was wondering, why is it like this?
And maybe it should be documented :) (or maybe it is, but I didn't find it)

**Comment by deksden** [comment]
I m not sure, but useGetList looks like suitable to processing foreign keys in components like ReferenceArrayInput (optimization: one query - multiply components processed)

**Comment by fzaninotto** [comment]
Hi, 

You're right, the documentation doesn't explicit the output of specialized hooks:

![image](https://user-images.githubusercontent.com/99944/72735881-fb94ee80-3b9c-11ea-926a-6f92cfd7add6.png)

I'm marking this as a documentation enhancement. 

And to understand why it's this way, it's because useGetList is used to display Datagrid and SimpleList, which expect a list of ids and a data dictionary.

**Comment by nik-lampe** [comment]
Thanks.

I also noticed that the useDelete hook is not documented right. It takes previousData as third argument, and then the callback options as forth.

Can I help with the documentation? Maybe it's easier when I create PRs with the changes to things I find :)

**Comment by fzaninotto** [comment]
Sure, feel free to open a PR to fix this.
