### ISSUE TITLE
OpenAPI support?

### ISSUE THREAD

**Issue by Niek** [marmelab/react-admin#4328]
Sorry to submit a support question, but I assume more people will encounter this issue - so posting here for visibility.

The [react-admin homepage](https://marmelab.com/react-admin/) prominently shows an OpenAPI (formerly Swagger) logo, but I can't find the relevant Data Provider in [the list](https://marmelab.com/react-admin/DataProviders.html) or on GitHub. Is it best to use ``ra-data-simple-rest`` and extend it, or am I missing something and is there a ready-made adapter that parses an OpenAPI spec file?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by Niek** [comment]
SO thread for reference: https://stackoverflow.com/questions/59837102/openapi-support-in-react-admin

**Comment by olivierdalang** [comment]
Can we transform this in an enhancement request, to include some equivalents of Guesser components, but that would consume the API specification instead of guessing accord to the response ?

Combined with OpenAPI compliant API backends (postgrest ❤️), that would be an absolute blessing.

BTW: StackOverflow is okay for asking/answering questions, but not a good place to discuss (e.g. I wanted to discuss this idea, but it's neither a question, nor an answer, and I need some reputation points to comment... Why not a good old mailing list for react-admin ?)

**Comment by alanpoulain** [comment]
You have more or less something like this with API Platform Admin: https://github.com/api-platform/admin.
It's Hydra by default, but since it's based on https://github.com/api-platform/api-doc-parser, having an OpenAPI support should be doable.

**Comment by fzaninotto** [comment]
@olivierdalang I agree that would be nice, but we can't add all features that would be nice in react-admin because we have limited resources to develop and maintain them. 

So we won't implement that in react-admin core. Feel free to build a package with OpenAPI guessers and open a PR in the documentation to add a link to it! 

About adding a mailing-list, we are already struggling with notifications from GitHub alone, so we won't multiply the entry points. If you want to discuss something, you can open an issue here with the `[RFC]` prefix.

Finally, the best way to get significant contributions from the core team is to relieve us from the work that can be done by someone else (e.g. bug triaging, simple doc and bug fixes, StackOverflow support).
