### ISSUE TITLE
ReferenceInput not updating with custom form layout and crudGetMatching

### ISSUE THREAD

**Issue by guilleironhack** [marmelab/react-admin#4345]
**What you were expecting:**
I have a custom form layout with `FormWithRedirect` as per the documentation example, and I am also using a feature inspired in the post quick create feature of the simple example.

**What happened instead:**
- The `ReferenceInput` choices are not updated

**Steps to reproduce:**
- Create a custom form layout with `FormWithRedirect`
- Use `crudGetMatching` to update the choices of a `ReferenceInput`
- The `ReferenceInput` choices are not updated

**Related code:**
https://codesandbox.io/s/empty-grass-dxl34

Go to the comment create view

**Environment**

* React-admin version: v3.1.2
* React version: v16.12.0
* Browser: Chrome 79.0.3945.117

**Comment by fzaninotto** [comment]
You're not exactly following the documentation, because you're inlining FormWithRedirect directly inside Create. In the react-admin doc, we explain that you must use in intermediary Form component.

I don't think there is a bug in react-admin. 

Feel free to reopen if you can find a bug with the exact same code as in the documentation.

**Comment by guilleironhack** [comment]
You are right, sorry for that.

I extracted the form and used it as per the documentation (if I left something out it's purely accidental) and still see the same behaviour.
