### ISSUE TITLE
Server Side Validation Response

### ISSUE THREAD

**Issue by pashaworks** [marmelab/react-admin#4352]
Hello everybody.
How I can show error response message from my API server react-admin version 3.0 ?
![2020-01-24_14-39](https://user-images.githubusercontent.com/49949779/73066533-4f624900-3eb7-11ea-826a-9acce6b5962c.png)
This variant doesn't work 
https://github.com/marmelab/react-admin/pull/871

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by sebashwa** [comment]
I shared a possible solution to this problem here #871
