### ISSUE TITLE
How to get the onChange() value from React Rrule Generator

### ISSUE THREAD

**Issue by thtan89** [marmelab/react-admin#4387]
Hi Sir, may I know how to get the onChange() value from the React Rrule Generator.
---https://github.com/fafruch/react-rrule-generator

I was able to get the onChange() value but dunno how to pass the value to the TextInput field.

![Screen Shot 2020-02-05 at 4 53 43 PM](https://user-images.githubusercontent.com/51570658/73828704-b16a6900-483c-11ea-979d-8911b2ed3083.png)

![Screen Shot 2020-02-05 at 4 53 49 PM](https://user-images.githubusercontent.com/51570658/73828716-b6c7b380-483c-11ea-9b2e-85e16a3a3f57.png)

![Screen Shot 2020-02-05 at 4 51 53 PM](https://user-images.githubusercontent.com/51570658/73828733-bfb88500-483c-11ea-9ed3-9ff0b3e02a52.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
