### ISSUE TITLE
Globally select variant

### ISSUE THREAD

**Issue by nescim** [marmelab/react-admin#4398]
I expected to find a way to set the default variant for input fields to "outlined" rather than the "filled" one. Apparently there is none, because I saw it hardcoded into each and every input component individually. This issue is a request for such a feature.
I am a bit surprised because which variant to use is a choice that I'd expect to be usually made for the whole application, with maybe an odd exception here and there. From a design perspective is like the choice of a dark or light theme.

I know the variant can be passed to individual fields and but this makes it quite verbose and couples this styling choice to each component. It limits reuse across projects and it would be quite bothersome to change it in the project's lifetime.

**Comment by fzaninotto** [comment]
You can select the variant at the form level (see https://marmelab.com/react-admin/CreateEdit.html#the-simpleform-component), form all the inputs of that form. 

For an app-wide setting, you may have success with material-ui props default in the theme. 

We haven't implemented an app-level setting for that, because we always use the default variant. 🤷‍♂ You're the first to ask otherwise. 

If you build a patch for global input variants, feel free to open a PR!

**Comment by fzaninotto** [comment]
A quick and efficient way to do what you ask is to use your variation of Input components rather than react-admin's one:

```jsx
// in src/myapp/form/TextInput.tsx
import { TextInput } from 'react-admin';

export default props => <TextInput variant="outlined" {...props} />
```

Then in your form:

```diff
-import { TextInput } from 'react-admin';
+import { TextInput } from '../form';

...
```
