### ISSUE TITLE
zebra look: alternating lines in the list (no hover)

### ISSUE THREAD

**Issue by sidescraper** [marmelab/react-admin#4420]
as in the example shown, the rowStyle should be used. the lines from the list should be colored alternately. this also works, but the hover color is no longer shown :-(

```
const postRowStyle = (record, index) => ({
  backgroundColor: index % 2 ? "#cdcdcd" : ""
});
export const PostList = (props) => (
    <List {...props}>
        <Datagrid rowStyle={postRowStyle}>
            ...
        </Datagrid>
    </List>
);
```

what needs to be done so that the hover comes again?
THX

https://codesandbox.io/embed/vigorous-dubinsky-n2sx0?fontsize=14&hidenavigation=1&theme=dark

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
