### ISSUE TITLE
What is best practice on creating new user? 

### ISSUE THREAD

**Issue by williamwxz** [marmelab/react-admin#4440]
**Is your feature request related to a problem? Please describe.**
Looks like the current Login component provided from react-admin, does not support user sign up. I can create my own login in page, however, what is the best practice to do so? 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
