### ISSUE TITLE
Get request does not populate table with simpleRestProvider

### ISSUE THREAD

**Issue by bradmk-1** [marmelab/react-admin#4470]
Hi there

Currently have a basic list that displays data, and a get endpoint with to go with it that returns my data correctly. I can see my 3 records are being returned with the get request, however they arent being mapped and displayed into the table. I currently only have the get endpoint setup.

Any ideas why this is? i am getting no error messages, do you have to place a content-range header for data to be mapped correctly, or is it due to some sort of requirment of all of the CRUD endpoints before data is mapped into the lists?

Thanks for any help.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
