### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by aa947** [marmelab/react-admin#4498]
I am facing strange behavior from node-react app,
this is the normal page ..
![chrome_U4KN8RUqhS](https://user-images.githubusercontent.com/46387030/76246076-f2d3a700-6234-11ea-96bd-eb877a5ad87b.png)

this is what looks like after you hit refresh 
![chrome_qo0IRvikYB](https://user-images.githubusercontent.com/46387030/76246083-f6ffc480-6234-11ea-8f6e-7bde93c5df81.png)

![chrome_wnsSaHURRK](https://user-images.githubusercontent.com/46387030/76246084-f830f180-6234-11ea-8c6d-12f699233f80.png)

I disabled all extensions and still the same problem.

even in the real server here https://www.ahmad-ali.co.uk/api/s/forecast 
just hit refresh  .. and same thing will happen

one Big Notice: now my server uses https representing this bug , 
when it was on http  when you hit refresh the UI will go and you still have only the json data sent by server

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by aa947** [comment]
I solved it, there was no-sniff implemented on the server, 
so I added `%public%` before linking local js and CSS files into `public/index.html`
