### ISSUE TITLE
How to redirect page after finishing create/edit

### ISSUE THREAD

**Issue by vctqs1** [marmelab/react-admin#4510]
Now. when i create/edit. I realized that:
1. It'll redirect to another page and show snackbar with message "Element updated"
2. Hidden snackbar and call API and load "loading icon" in app bar 
3. Call API edit/update and stop loading.

I would like to custom `just redirect after API called`

Please help me for this. I research few days but can't resolve this problem

**Comment by Vadorequest** [comment]
Use the `redirect` option, see https://marmelab.com/react-admin/List.html

```tsx
SimpleForm
        redirect={false} // 'edit', 'show'
      >
        <TextField source="ref" label={'Reference (#)'} />
        <TextInput source="labelEN" label={'Label (EN)'} />
        <TextInput source="labelFR" label={'Label (FR)'} />
        <TextInput source="terms.html" label={'Terms'} />
      </SimpleForm>
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by vctqs1** [comment]
@Vadorequest thanks your question. Props `redirect={false}` will help page don't redirect to another.

But with message on snackbar(show before API called). Sometimes, when API fail. it show another message and that make user confused.

I found a solution is `undoable={false}` to <Edit> or <Create> component.
