### ISSUE TITLE
Add supporting all  properties for tooltip sort in Datagrid, instead only left and right

### ISSUE THREAD

**Issue by Gryshchenko** [marmelab/react-admin#4551]
Hi, I have some problem in my UI with tooltip in Datagrid component, I need align it on bottom or top.
Currently it's support only align by left and right, can we add supporting all properrtys whats support by material ui Tooltip "placement"

Overriding headerCell in Datagrid not fix my problem, because I have some header cell what should be centered and some should not

For it only need, replace the use of the ternary operator with the property itself

Please help me with it) and thanks

![Screenshot_1](https://user-images.githubusercontent.com/24548664/76936289-5d52aa00-68fb-11ea-9654-26912c44812a.png)
![Screenshot_2](https://user-images.githubusercontent.com/24548664/76936946-7740bc80-68fc-11ea-91b1-9c36c261f689.png)

**Comment by Gryshchenko** [comment]
I realized that using a pure property would not help me in my problem, it should be an array of properties, and then select property to use

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
