### ISSUE TITLE
Mongo support

### ISSUE THREAD

**Issue by oklas** [marmelab/react-admin#4567]
Mongo database by default uses primary identifiers named **`_id`**.

I am trying to use with Mongo and still not checked all the use cases yet but already have something to implement. Inference elements form values do not expect **`_id`** field (only **`id`**).

Please take a look at [this](https://github.com/oklas/react-admin/commit/3b160ae4d918d7b6f191f9fbf5823d1cd2cfd28a). Simple test in previous commit.

I will add something else when it will be required in next use case. Give me some feedback.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by oklas** [comment]
I suggest a new feature (not question ask). Currently react-admin do not supports **`_id`** as primary key. I refer a work possible to future pr.

Only repo owners can review and comment to how feature may be implemented and accept pull requests. Stackoverflow community may have opinion but unable to make a decision about contributions. This is only for repo owners not for stackoverflow.

**Comment by fzaninotto** [comment]
React-admin epxects the dataProvider to have an identifier field called `id`. If your backend uses another field name for identifiers, it's your job to do the translation in your dataProvider. 

This has been done numerous times in userland, and there is no need for any change in react-admin to support it.

**Comment by MrWittman612** [comment]
> React-admin epxects the dataProvider to have an identifier field called `id`. If your backend uses another field name for identifiers, it's your job to do the translation in your dataProvider.
> 
> This has been done numerous times in userland, and there is no need for any change in react-admin to support it.

could at least show a snippet of how to do that? not using _id is frustrating, to say the least....

**Comment by fzaninotto** [comment]
That's already documented in the FAQ: https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources

**Comment by dylanh724** [comment]
I'd have to agree, since `mongodb` standard is `_id`. When would anyone actually use `id` instead of `_id` outside a simple json file? Even then, the average person would still use `_id` in almost all cases involving json if you're even considering using a proper db.
