### ISSUE TITLE
No option to unregister hidden field

### ISSUE THREAD

**Issue by Rawphs** [marmelab/react-admin#4580]
Hey! I have a form in which I'd like to unregister a field if the value of a `BooleanInput` is false.

If I submit the form without toggling this `BooleanInput`, everything behaves as expected. But if I set it to `true` then to `false` again and submit the form, the initial value of this field I'd like to remove is sent with the form data.

I'd like to make use of `react-final-form`'s `destroyOnUnregister` and I understand it was requested by #388 and removed by #3884 but along with not allowing for props to be passed down to the `Form` component it just becomes very annoying to have to write custom forms for something that isn't so special.

**Environment**
* React-admin version: ^3.3.1
* React version: ^16.13.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Thanks for the report. 

`destroyOnRegister` isn't documented on react-final-form's [FormProp documentation](https://final-form.org/docs/react-final-form/types/FormProps). That's why we didn't include it in the first place. But I see that it's a mistake in their doc. I'll add support for that prop in react-admin.
