### ISSUE TITLE
Unable to get simpleform data on save button click

### ISSUE THREAD

**Issue by ravi-pandit14** [marmelab/react-admin#4583]
**Description:** I am configured react-admin in my react web app. I want to invite user with email but not getting 'email' and 'role' field in console.

**Issue:** I am unable to get simpleform data on save button click. I have create custom toolbar in simpleform and only get privious data.

**My code**

```
const UserCreate = (props) => (
    <Create title="Invite" {...props} >
        <SimpleForm toolbar={<EditFormToolbar />}>
            <TextInput source="email" />
            <SelectInput source="role" choices={constants.role_choices} optionText="role_name" optionValue="id" />
        </SimpleForm>
    </Create>
);
const inviteUser = (props) => {
    console.log("inviteUser props:", props)
}

const FormToolbar = (props) =>
    (
        <Toolbar {...props} >
            <SaveButton
                label="Invite"
                redirect={false}
                // handleSubmit={handleSubmit}
                // submitOnEnter={true}
                handleSubmitWithRedirect={() => inviteUser(props)}
            />
        </Toolbar>
    );

const EditFormToolbar = compose(
    withFirebase,
)(FormToolbar);
export default withFirebase(UserCreate);
export { EditFormToolbar }
```

> package.json

"react": "^16.13.0",
"react-admin": "^3.3.1",
"react-admin-firebase": "^3.1.4",

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
