### ISSUE TITLE
How can I add translate to <SimpeForm /> validation?

### ISSUE THREAD

**Issue by Joci933** [marmelab/react-admin#4605]
I can't translate the validation message. The validation return only the validated string (example.: app.errors.startIsRequired, not the translated string (example: Start is required).

Example:

Form.js
```
 <SimpleForm
        toolbar={<LoggingChangeToolbar label={submitButtonText} />}
        validate={ValidateLoggingChangeForm}
        className={"logging-form"}
        save={handleSubmit}
        redirect={false}
      >

....

</Simpleform>
```

Validation.js
```
export const ValidateManualLogForm = (values) => {
  const errors = {};
  if (!values.start) {
    errors.start = 'app.errors.startIsRequired';
  }

  if (!values.end) {
    errors.end = 'app.errors.endIsRequired';
  } else if (values.start > values.end) {
    errors.end = 'app.errors.endMustBeGreaterThanStart';
  }

  if (!values.project) {
    errors.project = 'app.errors.projectIsRequired';
  }

  if (!values.task) {
    errors.task = 'app.errors.taskIsRequired';
  }

  if (!values.brId) {
    errors.brId = 'app.errors.brIDIsRequired';
  }

  if (!values.description) {
    errors.description = 'app.errors.descriptionIsRequired';
  }

  return errors;
};
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
