### ISSUE TITLE
Custom mui theme is not overriding properties

### ISSUE THREAD

**Issue by marosmola** [marmelab/react-admin#4617]
**What you were expecting:**

After changing global props in my global theme created by `createMuiTheme` i expect property to be changed on the component.

**What happened instead:**

Property is not overridden.

**Steps to reproduce:**

**Related code:**

Material-ui style sheet name is `MuiTextField`, i even tried `TextField` but still nothing changed
```js
export const globalTheme = createMuiTheme({
  props: {
    MuiTextField: {
      variant: "standard"
    },
    TextField: {
      variant: "standard"
    }
  }
})
```

**Other information:**

Screenshot from dev tools
![image](https://user-images.githubusercontent.com/19537488/78134837-0e3f6580-7421-11ea-8646-7146ba4d099d.png)

**Environment**

* React-admin version: 3.2.3
* React version: 16.9.0
* Browser: Chromium 77.0.3865.120 (Official Build) Arch Linux (64-bit)

**Comment by fzaninotto** [comment]
Material-ui allows to change defaultProps AND styles of their components with the theme, we only allow to change styles of react-admin components. 

The main reason is that, to allow theme override of defaultProps, one has to use `withStyles` instead of `makeStyles`, and we're engaged in a migration to do just the opposite to modernize the codebase and make typing easier.

As a side note, the material-ui docs never explain how this defaultProps override works, and I had to look at their code to understand how it works. 

So this is basically a wontfix.

Note that you can override the variant at the Form level in react-admin.
