### ISSUE TITLE
Views title in layout implementation

### ISSUE THREAD

**Issue by TCM5** [marmelab/react-admin#4622]
Sorry for asking here, but I'm not a stackoverflow user... Just a googleoverflow user!

Anyway, is possible to make each view have the title in the content?
The prop "title" in each view solves the problem, but requires a lot of boilerplate copy paste in each view. I already tried to make this a child of Layout, but overrides the view.

By the way, congratulations to this amazing project. You guys rock!

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by TCM5** [comment]
@fzaninotto thanks for the reply. But i started my statement about not having stackoverflow account. I will create one.... 

Thank you
