### ISSUE TITLE
how to separate form data and file field

### ISSUE THREAD

**Issue by luckdream** [marmelab/react-admin#4623]
I have a product form:
```js
<Create {...this.props}>
    <SimpleForm defaultValue={postDefaultValue}>
        <TextInput source="productName" />
        <ReferenceInput label="Category" source="categoryId" reference="categories">
            <SelectInput optionText="categoryName" />
        </ReferenceInput>
        <TextInput source="price" label="Price"/>
        <ImageInput source="pic" label="Related pictures" accept="image/*">
            <ImageField source="src" title="title" />
        </ImageInput>
    </SimpleForm>
</Create>
``` 
at BE side, I have 2 apis:
one is for saving product info and return generated product id to FE, accept a json body(from the form):
```json
{
  "productName": "test",
  "price": 10.99,
  "categoryId": 1
}
```

one is for saving the image, the product id should be interrelated.

so how can I work like this? what should I do with my dataProvider?

Thank you all.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
