### ISSUE TITLE
altering the form value before submit not working as per documentation

### ISSUE THREAD

**Issue by dhavalk-simform** [marmelab/react-admin#4640]
**What you were expecting:**
When user submit a form want to pass a custom value (altering the form value)

**What happened instead:**
form submit with default value instead of custom value.

**Steps to reproduce:**
following this doc to alter the form value:  [react-admin doc](https://marmelab.com/react-admin/CreateEdit.html#altering-the-form-values-before-submitting)

**Related code:**

* I've asked a question on StackOverflow and you can see my implementation [here](https://stackoverflow.com/questions/60971351/change-altering-the-form-value-before-submit)

**Environment**

* React-admin version: ^3.3.3
* React version: ^16.13.1
* Browser: chrome

**Comment by JulienMattiussi** [comment]
Hello. I've read what you posted on stackoverflow, but I can't see a `form.change` in your example to alter the form value. 

In v3, you can't use a custom function inside `handleSubmit`.
You have to use this syntax as in the ra doc :

```js
const handleClick = () => {
        // change the average_note field value
        form.change('average_note', 10);
​
        handleSubmitWithRedirect('edit');
};
```
Can you try this ?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
