### ISSUE TITLE
React-admin components / hooks throws error in react developer tools

### ISSUE THREAD

**Issue by josephktcheung** [marmelab/react-admin#4697]
**What you were expecting:**

Expect choosing react-admin components / components that use `react-admin`'s data fetching hooks in react developer tool will show component state, hooks, props correctly.

**What happened instead:**

Choosing a react-admin component that use dataloader related hooks e.g. `List` will throw error in console
Custom component that uses `useDataLoader` related hooks  e.g. `useCreate`, `useGetOne`, etc. has same issue.
**Steps to reproduce:**

Prerequisite: Install React Developer Tools extension in chrome https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

1. Run simple demo `make run-simple`
2. Go to `http://localhost:8080/#/posts`
3. Open console -> React Developer Tools, search and choose `List` component
4. Console throws following error
![Screenshot 2020-04-17 at 2 38 29 PM](https://user-images.githubusercontent.com/4270232/79539558-2833a600-80b9-11ea-99a6-2ae1096fdd5f.png)
5. Right panel stucks at `Loading`
![Screenshot 2020-04-17 at 2 40 13 PM](https://user-images.githubusercontent.com/4270232/79539771-8c566a00-80b9-11ea-96e2-9eb7bdd80a31.png)

**Environment**

* React-admin version: master
* Last version that did not exhibit the issue (if applicable):
* React version: react@16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error):
```
Uncaught TypeError: uploadCapableDataProvider[name] is not a function
    at Proxy.<anonymous> (dataProvider.js:22)
    at dataProvider.js:26
```

**Comment by JulienMattiussi** [comment]
I reproduced this issue, thanks for reported it.
It seems that when using React Developper Tools to investigate the List, there is a call with`name='Symbol(Symbol.iterator)'` passed to the dataProvider instead of the known action `name='getList'`

I tried to bypass it, but without success for now.
The `Uncaught TypeError: undefined is not a function` from `react_devtools_backend.js` still remains.

If someone have an idea, feel free to suggest a fix.
