### ISSUE TITLE
Auth provider checkError takes me to localhost:3000/[object%20Object]

### ISSUE THREAD

**Issue by ybrodsky** [marmelab/react-admin#4711]
**What you were expecting:**
I was using version 2.x and everything was fine. Started to upgrade following the upgrade guide. 
Now when I fire up the app, I go to the index and I see the network request returning 401. I see the relevant authProvider function being called and returning Promise.reject(). But then, instead of going to the login I get to `localhost:3000/[object%20Object]`

My auth provider
```
export default {
  login: async (params) => {
    const { username, password } = params;

    const { status, data } = await axios.post('/api/admin/login', {
      username, password,
    }, {
      validateStatus: () => true,
    });

    if (status === 200) {
      localStorage.setItem('user', JSON.stringify(data));

      return Promise.resolve();
    }

    return Promise.reject(data.error || data.message);
  },
  logout: () => {
    localStorage.removeItem('user');

    return axios.get('/api/auth/logout');
  },
  checkAuth: () => {
    return Promise.resolve();
  },
  checkError: (error) => {
    const { status } = error;

    if (status === 401 || status === 403) {
      localStorage.removeItem('user');

      return Promise.reject();
    }

    return Promise.resolve();
  },
  getPermissions: (params) => {
    try {
      const json = JSON.parse(localStorage.getItem('user'));

      return Promise.resolve(json);
    } catch (err) {
      return Promise.reject(err);
    }
  },
};
```

My data provider
```
const convertDataProviderRequestToHTTP = (type, resource, params) => {
  switch (type) {
    case GET_LIST: {
      // etc
    }
   // etc

export default (type, resource, params) => {
  const { fetchJson } = fetchUtils;
  const { url, options } = convertDataProviderRequestToHTTP(type, resource, params);

  return fetchJson(url, options)
    .then(response => convertHTTPResponseToDataProvider(response, type, resource, params));
};
```

The request is made successfuly and if I remove the authProvider from <Admin nothing breaks.

* React-admin version: 3.4.2
* React version: 16.13.1

Any ideas?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
