### ISSUE TITLE
ReferenceArrayInput usage with relationships

### ISSUE THREAD

**Issue by pesseyjulien** [marmelab/react-admin#4740]
Hi,

I have followed the doc for the ReferenceArrayInput (https://marmelab.com/react-admin/Inputs.html#common-input-props) but it does not seem to be working with relationship fields.

For example, I have this many-to-many relation for my Users (serialized version) : 

![Capture d’écran 2020-04-30 à 16 00 30](https://user-images.githubusercontent.com/10850944/80719412-be28f100-8afb-11ea-9061-4862231531c9.jpg)

Coming from (raw response from my API):

![Capture d’écran 2020-04-30 à 16 00 23](https://user-images.githubusercontent.com/10850944/80719465-cda83a00-8afb-11ea-85ad-b93576bdb644.jpg)

I have setup the ReferenceArrayInput as followed : 

```
 <ReferenceArrayInput source="profiles" reference="profiles" >
           <SelectArrayInput optionText="label"  />
</ReferenceArrayInput>
```

I think it's making the appropriate calls : 
![Capture d’écran 2020-04-30 à 15 58 35](https://user-images.githubusercontent.com/10850944/80719282-88840800-8afb-11ea-8655-fe306e072dad.jpg)

But here is my result : 
![Capture d’écran 2020-04-30 à 15 58 22](https://user-images.githubusercontent.com/10850944/80719297-8f127f80-8afb-11ea-8a83-c00a6fcb1919.jpg)

Any idea what I'm doing wrong ?

Thanks in advance for your help !

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by pesseyjulien** [comment]
alright, thanks !
