### ISSUE TITLE
How to bind value of TextInput from changed state

### ISSUE THREAD

**Issue by arrrrny** [marmelab/react-admin#4750]
I have a TextInput <TextInput source="categoryId" />

When I fill categoryId using keyboard, value is sent correctly. I have another set of inputs that goes deep to find category,I want to bind the value of my textinput to the selected value of other input. I tried setting state, no luck. How do I change the value of Reac-admin inputs when state has changed?

Thanks

**Comment by edulecca** [comment]
@arrrrny think that the place where the "How to" question is the Stackoverflow channel
However think you are needing something like these https://marmelab.com/react-admin/Inputs.html#linking-two-inputs

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by ajay-dev-j** [comment]
ANyone, SHare the Stackoverflow link for this, please.

**Comment by Rathavi** [comment]
https://stackoverflow.com/questions/72725105/adjust-a-simple-form-fields-value-with-a-button

Hope this helps
