### ISSUE TITLE
User Saga does not close the sidebar anymore on application start

### ISSUE THREAD

**Issue by Alex1844** [marmelab/react-admin#4777]
I have used the user saga (see the code below) to close the sidebar by default on application start, but now it does not work anymore. I have just upgraded to react-admin 3.5.0 but I am not sure when it stopped working.

```
// closeSidebarSaga.js

import {
  put,
  takeEvery,
} from 'redux-saga/effects'

import {
  SET_SIDEBAR_VISIBILITY,
  setSidebarVisibility,
} from 'react-admin'

function* closeSidebar(action) {
  try {
    if (action.payload) {
      yield put(setSidebarVisibility(false))
    }
  } catch (error) {
    console.log('closeSidebar:', error)
  }
}

function* closeSidebarSaga() {
  yield takeEvery(SET_SIDEBAR_VISIBILITY, closeSidebar) 
}

export default closeSidebarSaga

// App.js:

import closeSidebarSaga from './closeSidebarSaga'

<Admin customSagas={[ closeSidebarSaga ]} ... }>
...
</Admin>
```

**Comment by fzaninotto** [comment]
There was a bug in react-admin < 3.5 that forced using a saga, but it's now fixed. You don't need a custom saga for that anymore. Passing `initialState={{ admin: { ui: { sidebarOpen: false } } }}` to your `<Admin>` should be enough.

**Comment by christiaanwesterbeek** [comment]
@fzaninotto I discovered that if you do this, you also need to add `version: 0` in there. Otherwise at first version is `undefined`, after the first refresh it becomes `NaN` (`undefined + 1`) en then it stays `NaN`. In other words, if you omit `version: 0` in the initialState like that, refresh will work only once! I recommend passing in the following:

`initialState={{ admin: { ui: { sidebarOpen: false, version: 0 } } }}`
