### ISSUE TITLE
Dynamic input depend on others field in Create Form

### ISSUE THREAD

**Issue by mrtk0y** [marmelab/react-admin#4792]
As the title, I want to ask how to autofill the 3rd field depend on 1st, 2nd 
`

NumberInput source="original_price" step={1000000} validate={validateRequired}       
NumberInput source="number" step={1} validate={validateRequired}         
NumberInput  source="share_price" step={100000} validate={validateRequired} 
          `

for example: share_price = original_price/number

is it possible to do dynamically

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by oklas** [comment]
For those who are looking for, check [this](https://stackoverflow.com/questions/59819489) and [this](https://codesandbox.io/s/z2yr616ll).
