### ISSUE TITLE
Add `download` attribute for FileField

### ISSUE THREAD

**Issue by datakurre** [marmelab/react-admin#4795]
**Is your feature request related to a problem? Please describe.**

I cannot set filename with `download` attribute when passing files as data URIs for FileField-components.

I have a backend that returns files as BASE64 encoded strings and they are not downloadable with direct URLs. I can make them downloadable with `FileField`-widget by wrapping the widget and passing the files as data URIs. With `download`-attribute I could also set filename and provide better downloading experience.

**Describe the solution you'd like**

Add `download` attribute support for FileField. Attribute could be optional and empty (not rendered) by default, so adding it should be safe an cause no regression for existing uses.

Thank you for this awesome framework!

**Comment by djhi** [comment]
Thanks for the report. Not sure we will implement this. However, you can create your own `FileField`

**Comment by fzaninotto** [comment]
Fixed by #4798

**Comment by najibullo-kenjaev** [comment]
Hello @datakurre  how did you do it. My Backend returns base 64 file but the FileField does not download!!

**Comment by najibullo-kenjaev** [comment]
@datakurre >>> I can make them downloadable with FileField-widget by wrapping the widget and passing the files as data URIs. With download-attribute I could also set filename and provide better downloading experience.
How did you do this.

**Comment by najibullo-kenjaev** [comment]
Please can you help me
My Bekend Response                                                                                                                                                                           url: "aWQsaXNEZWxldGVkLHJlY29yZERhdGUsbmFtZSxjb3VudHJ5.........."                                                                                                         React admin                                                                                                                                                                                         <FileField  source="url"  title="fileName"  download="cv"	 />

**Comment by slax57** [comment]
@najibullo-kenjaev Please do not post support questions here.

As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question, you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.
