### ISSUE TITLE
Filter List by array property

### ISSUE THREAD

**Issue by sulcad14** [marmelab/react-admin#4803]
I am trying to filter List of 'vid' entity by 'tag' property. I created custom component that I later on import to filters property of List. I transform data of an array accordingly to `<SelectInput />` component with this function:

```
transformToObject = () =>
    {
        if (this.state.tagsList !== null)
        {
            const value = Object.keys(this.state.tagsList).map((index) => {
                return { id: this.state.tagsList[index], name: this.state.tagsList[index] };
            });

            return value;
        }
    }
```
Then I return this as an output of my component:

`<SelectInput source={source} choices={this.transformToObject()} />`

And finally I import it to my model and initialize it:

```
const VideoFilter = (props) => (
    <Filter {...props}>
        <TextInput source="_id" alwaysOn />
        <TextInput source="name" alwaysOn />
        <TagsFilter source="tags" alwaysOn />
    </Filter>
);
```

However, if I select the tag that should filter the List, it return an empty List.

Any ideas what is the problem? Or any suggestions how can I filter List by an array properly?
Thank you in advance.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by sulcad14** [comment]
I posted this question on StackOverflow about a week ago, still without any response. Tried my luck here.
