### ISSUE TITLE
SelectInput does not work when source points to array item's attribute; SyntaxError: Failed to execute 'querySelector' on 'Document': '#title[0].txt-label' is not a valid selector.

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#4816]
**What you were expecting:**
The latest react-admin release (v.3.5.1) broke SelectInput when source points to child attributes of an array. Prior to this update, everything worked fine. 

Note:

- source='title[0].txt' does not work while source='title' does
- I change SelectInput  to TextInput, everything works just fine.

```
export const PostEdit = (props) => (
  <Edit title={<PostTitle />} {...props}>
    <SimpleForm>
      <TextInput disabled source='id' />
      <SelectInput source='title[0].txt' choices={[{ id: '1', name: 'default' }]} />
    </SimpleForm>
  </Edit>
);
);
```

**What happened instead:**

![image](https://user-images.githubusercontent.com/48455289/81981269-aec69f00-95f5-11ea-873e-a62673e245af.png)

**Steps to reproduce:**
Go to posts, and click edit.

**Related code:**
https://github.com/panfiva/sample_error/blob/96f2ce195ad09da8312305a0b325460a191e90d9/src/posts.js#L53

**Other information:**

**Environment**
Chrome 81.0.4044.129

{
  "name": "react-admin-error",
  "version": "0.1.1",
  "dependencies": {
    "@material-ui/core": "^4.9.14",
    "axios": "^0.19.2",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^3.5.1",
    "react": "^16.13.1",
    "react-admin": "^3.5.1",
    "react-dom": "^16.13.1",
    "react-final-form": "^6.4.0",
    "react-scripts": "^3.4.1",
    "typescript": "^3.9.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not ie <= 10",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by gpietro** [comment]
I'm experiencing the same problem.

**Comment by djhi** [comment]
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by gpietro** [comment]
I think the problem come from material-ui v4.19.4.

https://github.com/mui-org/material-ui/blob/v4.9.14/packages/material-ui/src/Select/SelectInput.js#L96

**Comment by panfiva** [comment]
There are some firewall issues, so I cannot connect to codesandbox from work; however I have a gitub repository

https://github.com/panfiva/sample_error

**Comment by gpietro** [comment]
@panfiva I think you could "fix" this by using yarn instead of npm, because a don't see a package-lock in the project so the material-ui installed is the latest version with the bug and until isn't going to be fixed react-admin will broke.

**Comment by panfiva** [comment]
closing the issue since it is not related to react-admin

**Comment by paulito415** [comment]
Thanks so much @panfiva for posting this and sharing potential workarounds. @gpietro I tried using yarn instead of npm and the same problem persisted. 

I experienced this with react-admin 3.5.2. So one thing I tried to do, given that this is an issue that was reported to be from react-admin 3.5.1, was to revert to my previous version 3.3.0. But for some reason no amount of cleaning up package.json and yarn.lock was able to bring me back. This is my package.json
```
{
  "name": "ac.healthbuy.server.admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "prop-types": "^15.7.2",
    "ra-i18n-polyglot": "^3.3.0",
    "ra-language-chinese-traditional": "^1.0.0",
    "react": "^16.13.0",
    "react-admin": "^3.3.0",
    "react-dom": "^16.13.0",
    "react-final-form": "^6.3.5",
    "react-scripts": "^3.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "homepage": "./"
}
```
Is there anywhere in here that still is bringing in react-admin 3.5.2? I see in the `yarn install` call the following:
```
[3/4] Linking dependencies...
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "connected-react-router@^6.5.2".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "final-form@^4.18.5".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "react-redux@^7.1.0".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "react-router@^5.1.0".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "react-router-dom@^5.1.0".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "redux@^3.7.2 || ^4.0.3".
warning "ra-i18n-polyglot > ra-core@3.5.2" has unmet peer dependency "redux-saga@^1.0.0".
```
but that doesn't make any sense because in my package.json it points to ra-i18n-polyglot@3.3.0. Am I missing something else?

Another way I wanted to consider is to roll back material-ui to a previous version. But as I'm not familiar with the way dependencies are managed in npm packages, I'm not even sure how to do that. 

I know the original poster has already closed this but any help on this matter would be greatly appreciated.

**Comment by djhi** [comment]
You are specifying versions using the `^` sign which means "take any version greater or equal to the one specified after the ^". Remove the sign and it should use the exact version specified

**Comment by paulito415** [comment]
Thanks @djhi I actually did try that eventually but still couldn't get it to work. Incidentally I don't think I have the option of downgrading now anymore because I just learned yesterday that [react-admin 3.5.3](https://github.com/marmelab/react-admin/blob/master/CHANGELOG.md) (one version higher than my original one) fixes [a problem](https://github.com/marmelab/react-admin/pull/4819) I needed to have solved. 

For now I just wanted to find out when this specific issue here is slated to be fixed because I have a page that is no longer functioning because of this. I know that it's been labeled to not be in the jurisdiction of react-admin because it's a material-ui [issue](https://github.com/mui-org/material-ui/issues/21045). And in fact, it's mentioned to be fixed in "@material-ui/core": "4.10.0". I'm a bit inexperienced in nodejs dependency management so I'm wondering how I can pull this into my build. Does simple explicit inclusion of that line in my package.json do it?

**Comment by paulito415** [comment]
So after just straight copying that dependency line in `package.json` I was met with the following error:

```
Cannot find module: '@material-ui/icons/ViewHeadline'. Make sure this package is installed.

You can install this package by running: yarn add @material-ui/icons/ViewHeadline.
```

But running that `add` line ended with 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui%2ficons/ViewHeadline: Request \"https://registry.yarnpkg.com/@material-ui%2ficons/ViewHeadline\" returned a 405".
```

So long story short, I figured that maybe I can't use the syntax where it pointed to a specific icon. So I replaced the line with:

```
yarn add @material-ui/icons
```

and the `yarn run build` now works.

But running it (and I verified that I'm using a latest version of material-ui because my UI looks a bit different now, I still get the same problem mentioned here. Could it be that the material-ui issue mentioned is not exact tracking the "same" issue as reported here?

**Comment by paulito415** [comment]
So I did a quick grep under `node_modules` for `querySelector` (and other filters) and found:

```
node_modules/react-admin/node_modules/@material-ui/core/esm/Select/SelectInput.js:112:      var label = ownerDocument(displayNode).querySelector("#".concat(labelId));
node_modules/react-admin/node_modules/@material-ui/core/Select/SelectInput.js:138:      var label = (0, _ownerDocument.default)(displayNode).querySelector("#".concat(labelId));
node_modules/react-admin/node_modules/@material-ui/core/es/Select/SelectInput.js:90:      const label = ownerDocument(displayNode).querySelector(`#${labelId}`);
```

And in all of them the incorrect element lookup using `querySelector` was used. So I chased down the material-ui issue [21045](https://github.com/mui-org/material-ui/issues/21045), and from there found the [pull-request](https://github.com/mui-org/material-ui/pull/21047) that fixed it (on their side) and looked at the [diffs](https://github.com/mui-org/material-ui/compare/bf8f3f7d35114e2df9b9836ae663187c7d65e608...15c686752df28d5adeb79f651ff346058887b8c5), to find that the fix was just to replace the usage of `querySelector` with `getElementById`. 

I wasn't sure which one of the 3 I listed above I should modify but basically I modified all 3 with the fix and lo and behold, my problem was fixed! I guess it may take some time for their changes in material-ui to trickle down to react-admin. In the meantime I have added an extra step in my build to patch these files every time.

**Comment by paulito415** [comment]
Sorry this is totally unrelated and is a long shot. But I posted a [question](https://stackoverflow.com/questions/61884435/react-admin-referenceinput-usage-data-provider-update-function-params-data-has) on SO a week ago and wanted to know the best way to get eyeballs on it from the react-admin team. Is there a place where I can post that link?

**Comment by fzaninotto** [comment]
@paulito415 The react-admin team looks at bugs here, and sometimes helps with troubleshooting on StackOverflow. But the troubleshooting work is mostly delegated to the community. Cross-posting in SO and here will have the inverse effect of what you expect: with double the noise, and a disregard for our issue template, we'll just silence the notifications coming from you.

If you have no reply on SO, be patient. If you're in a hurry, contact Marmelab for Professional Services.

**Comment by paulito415** [comment]
Thanks for the clarifications @fzaninotto! I will refrain from cross posting on SO and here.
