### ISSUE TITLE
ShowGuesser is not working

### ISSUE THREAD

**Issue by cycorld** [marmelab/react-admin#4833]
**What you were expecting:**

I expect to see SHOW page. 

**What happened instead:**

When I click a user in the list of USER, url address is changed to #/users/1. But, it is show the list view only.

**Steps to reproduce:**

**Related code:**

https://codesandbox.io/s/github/tomttoms/test-admin/tree/master

```
    <Resource name="users" list={ListGuesser} show={ShowGuesser} />
```

ShowGuesser is not working.

**Other information:**

**Environment**

* React-admin version: 3.5.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error): None

**Comment by fzaninotto** [comment]
Hi, and thanks for your report. 

When using the ListGuesser, the list renders with a click handler on every line that leads to the *Edit* page. Your resource doesn't have an Edit page, that's why nothing displays when clicking on the list.

The Show guesser does work: just append "show" after a record url and you will see it.

**Comment by cycorld** [comment]
Thanks a lot!!
