### ISSUE TITLE
Associated reference no longer appears to be available.

### ISSUE THREAD

**Issue by shamim2883** [marmelab/react-admin#4839]
**What you were expecting:**
Add ReferenceInput inside SimpleFormIterator inside ArrayInput, I should be able to add as many fields as i like and they keep their selected value.

**What happened instead:**
If i add more than perPage value of ReferenceInput, it shows "Associated reference no longer appears to be available." if i try to add any more field after 10 minutes.

**Steps to reproduce:**
add following code in Create
```
        <ArrayInput source="tags" label="Tags">
          <SimpleFormIterator>
            <ReferenceInput perPage={2} source="id" reference="tags">
              <AutocompleteInput
                optionValue="id"
                optionText={choice =>
                  !!choice ? `${choice.id} (${choice.name})` : ""
                }
              />
            </ReferenceInput>
          </SimpleFormIterator>
        </ArrayInput>
```
Then add more than 2 fields (as i set 2 as perPage value of ReferenceInput) and select their values from search. Try to select other values which does not shows initially in dropdown) Then wait 10 minutes. Then try to add more fields. 

**Related code:**
https://codesandbox.io/s/goofy-wind-ct9v3?file=/src/posts/PostCreate.js

**Comment by djhi** [comment]
Reproduced. Thanks

**Comment by fzaninotto** [comment]
This is a consequence of our cache eviction strategy, which is voluntarily very basic - but doesn't work all the time. This strategy avoids that the query cache grows endlessly over time, which would be a memory leak.

What react-admin does is that whenever the app receives the response for a read query for a resource, it removes the records of this resource received more than 10 minutes before. There is a risk that these records, fetched more than 10 minutes ago, are still in use.

What more sophisticated data fetching libraries do (react-query, apollo-client) is that they trace the components that depend on a query, and mark the cache ready for eviction when the components unmount. But this comes with a lot more complexity, and side effects, too.

So I see 3 ways to fix this bug:

1. We simply increase the retain duration (currently, 10 minutes) to reduce the likeliness that this bug may occur. It won't *fix* the bug completely, but it doesn't add any complexity to the code
2. We dispatch a custom action when main resource pages (Edit, Show, List, etc) unmount, and the data reducer removes stale data only in reaction to that action (instead of when receiving responses from the dataProvider). This will fix the current bug - but may create other bugs, as the cache will probably be cleared more often.
3. We change our cache eviction strategy to use a full blown garbage collector with reference tracing, just like react-query. I must admit that I'd prefer switching to react-query completely than rewriting a large share of their code. 

Feel free to comment if you see another solution.

**Comment by djhi** [comment]
I would definitely recommend switching to react-query.

**Comment by fzaninotto** [comment]
> I would definitely recommend switching to react-query.

That is not an option for a quick fix. Any other idea?

**Comment by fzaninotto** [comment]
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.
