### ISSUE TITLE
How can we display LHC form data in react admin UI without a data provider?

### ISSUE THREAD

**Issue by shanilsasikumar** [marmelab/react-admin#4841]
I have created a react app component in react admin and displayed the LHC form data by using the lforms module [lforms](https://www.npmjs.com/package/lforms)
When I installed this module an error occurred like the following
`'Module not found: Can't resolve 'prop-types'`
I have solved this problem by installing another module called 'prop-types' [prop-types](https://www.npmjs.com/package/prop-types)
Initially, the LHC form is displayed, by going forward an extra # symbol is getting added continuously to the URL and the page is redirected to 4o4.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
