### ISSUE TITLE
I have same return data .but it is show different 

### ISSUE THREAD

**Issue by 97thjingba** [marmelab/react-admin#4883]
**What you were expecting:**

This is my first kind of function processing when returning data
```js
fetchReportList = () => {
        const { page } = this.params.pagination;
        const config = {
            path: `/report/laiwan?&&size=4&&page=${page}`,
            headers: ApiHeaderFactory.headersWithAuthorization(),
        };
        let total;
        return this.fetchJson(config).then((response) => {
            const ar = response.items.map((item) => {
                localStorage.setItem(item.id, item.user_id);
                return {
                    ...item,
                };
            });
            ar.forEach(async (item) => {
                const reportAvatar = await this._fetchAvatar(item.user_id);
                const reportedAvatar = await this._fetchAvatar(item.reported_user_id);
                item.avatar = reportAvatar !== null ? this._buildAvatar(reportAvatar) : null;
                item.reported_avatar = reportedAvatar !== null ? this._buildAvatar(reportedAvatar) : null;
                item.handled_avatar = reportAvatar !== null ? this._buildAvatar(reportAvatar) : null;
            });
            total = response.total;
            const cc = {
                data: ar,
                total,
            };
            console.log(cc);
            return cc;
        });
```

This is my second function processing when returning data
```js
fetchReportList = () => {
        const { page } = this.params.pagination;
        const config = {
            path: `/report/laiwan?&&size=4&&page=${page}`,
            headers: ApiHeaderFactory.headersWithAuthorization(),
        };
        return this.fetchJson(config).then((response) => {
            const cc = {
                data: response.items.map((item) => {
                    localStorage.setItem(item.id, item.user_id);
                    return {
                        ...item,
                        avatar: `${avatarDomain()}/${item.user_id}/${item.user_id}.jpg`,
                        reported_avatar: `${avatarDomain()}/${item.reported_user_id}/${item.reported_user_id}.jpg`,
                        handled_avatar: `${avatarDomain()}/${item.user_id}/${item.user_id}.handled.jpg`,
                    };
                }),
                total: response.total,
            };
            console.log(cc);
            return cc;
        });
    }
```

**What happened instead:**
first way 
![image](https://user-images.githubusercontent.com/39749571/83493655-ac19e400-a4e7-11ea-91b4-af1c4cc6695d.png)

second way 
![image](https://user-images.githubusercontent.com/39749571/83493642-a6bc9980-a4e7-11ea-86f7-39725e940c8c.png)

**Environment**

* React-admin version: 2.9.7
* Last version that did not exhibit the issue (if applicable):
* React version:16.10.2
* Browser: chrome

**Comment by 97thjingba** [comment]
same return data .but the second way do not show avatar

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
