### ISSUE TITLE
Compatibility with Gatsby

### ISSUE THREAD

**Issue by jzohdi** [marmelab/react-admin#4893]
**expecting**
I wanted to include react-admin in a Gatsby project so that I could have a /admin route that will be an interface for the site data.

**What happened instead:**
Using gatbsy new ____, I setup a boilerplate gatsby project. Then installing react-admin and adding a page into the gatsby project, while following [react-admin tutorial](https://marmelab.com/react-admin/Tutorial.html), causes gatsby to fail building. 
> gatsby develop

seems fine and does not crash the app, however

> gatbsy build 

leads to 

>  WebpackError: Invariant failed

**Steps to reproduce:**
gatsby new _____
npm install react-admin
npm install ra-data-simple-rest

- add a minimal admin page to gatsby's pages folder

gatsby develop = OK
gatsby build = Failed

**terminal output**
![Gatsby Build Fail](https://user-images.githubusercontent.com/31998568/83698208-dabeba00-a5ce-11ea-8d07-004f4a01e9d6.PNG)

**Related code:**
Here is a repository that can be cloned to reproduce:
https://github.com/jzohdi/react-admin-gatsby-test

**Environment**
from package.json
    "gatsby": "^2.22.15",
    "gatsby-image": "^2.4.5",
    "gatsby-plugin-manifest": "^2.4.9",
    "gatsby-plugin-offline": "^3.2.7",
    "gatsby-plugin-react-helmet": "^3.3.2",
    "gatsby-plugin-sharp": "^2.6.9",
    "gatsby-source-filesystem": "^2.3.8",
    "gatsby-transformer-sharp": "^2.5.3",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-admin": "^3.5.5",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.0.0"

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
