### ISSUE TITLE
list inside view or edit ,resource Props not reflected

### ISSUE THREAD

**Issue by AymanElarian** [marmelab/react-admin#4910]
**What you were expecting:**

i want to use list from other resource inside edit record  or show record 
i use the following code , 

```
   let fakeProps = {
            basePath: "/" + metaData.reference,
            hasCreate: false,
            hasEdit: false,
            hasList: true,
            hasShow: false,
            history: {},
            location: { pathname:"/"  ,search: "", hash: "", state: undefined },
            match: { path: "/" , url: "/", isExact: true, params: {} },
            options: {},
            permissions: null,
            resource: metaData.reference
        }

   <List {...fakeProps} >
....
            </List>
```
        
for example my current edit record is for artist , i want to include list for his songs as   "metaData.reference" is songs as list inside artist edit view 
 

**What happened instead:**
it keep load from artist using graphQL not songs , i need to use list with its filter not just ReferenceManyField with datagrid 

any advice please ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
