### ISSUE TITLE
Dashboard render without login

### ISSUE THREAD

**Issue by alierenkara** [marmelab/react-admin#4919]
Hello guys, 

I request "/login" page and no problem, loaded login page. But i request "/" first render dashboard after coming login page. Any idea ?

Example, i am going "http://localhost:3001/react-admin-demo#/login" no problem, dont render dashboard. but i am going "http://localhost:3001/react-admin-demo#/" i see "dashboard use effect" log.

<img width="448" alt="Ekran Resmi 2020-06-09 00 47 02" src="https://user-images.githubusercontent.com/25728199/84084096-801cc800-a9eb-11ea-95a4-790126a28df7.png">
<img width="638" alt="Ekran Resmi 2020-06-09 00 48 18" src="https://user-images.githubusercontent.com/25728199/84084104-8317b880-a9eb-11ea-973a-b6dfb30ffc63.png">

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
