### ISSUE TITLE
Get my user's roles with getList or another way

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#4961]
I need to bring the roles of my user, when I edit a user, that way I edit the roles assigned to my user, but my api is different, I need to adapt it and I don't know how to do it.

In my api endpoint http://localhost/api/user/{id}/role, i get user roles of user {id}. I need know how i do for this:

my code is:

```
const App = ( ) => (
    <Admin dashboard={ Dashboard } dataProvider={ dataProvider } authProvider={ authProvider }>
        <Resource name="user" list={ UserList } create={ UserCreate } edit={ UserEdit } icon={ UserIcon }/>
        <Resource name="role" list={ RoleList } create={ RoleCreate } edit={ RoleEdit } icon={ ContactsIcon }/>
    </Admin>
);

```
The following code does not work for what I need

```
export const UserEdit = props => (
    <Edit title={<RoleTitle />} {...props}>
        <SimpleForm validate={validateUserEdition}>
            <TextInput source="name" />
            <TextInput source="email" type="email" />
            <TextInput source="password" type="password" />
            <ReferenceInput label="Role" source="role" reference="role">
                <AutocompleteArrayInput source="id" {...props} />
            </ReferenceInput>
        </SimpleForm>
    </Edit>
);
```

any ideas?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
