### ISSUE TITLE
How to add custom error message notification in login page

### ISSUE THREAD

**Issue by aarukarthiga** [marmelab/react-admin#4972]
I have started integrating the react-admin page, In the login page, I'm trying to manage the error message in the auth provider. I'm not able to get the error message to display in the notification .any one please help.

```
`login: ({ username, password }) => {
        const request = { 'email': username, 'password': password}
        return axios.post(process.env.REACT_APP_URL+`/login`, request).then(response => {
            let result = response.data;
            
            if(result.success){

            } else {
                console.log(response.data);
                throw new HttpError(result.message);

            }
           // localStorage.setItem('username', username);
            return Promise.resolve();
        }).catch(error => {
            return error;
        });`

```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
