### ISSUE TITLE
Show the resource of a relationship - http://localhost/api/user/2/role?...

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#4977]
my code is: 
```
export const UserEdit = props => (
    <Edit title={<RoleTitle />} {...props}>
        <SimpleForm validate={validateUserEdition}>
            <TextInput source="name" />
            <TextInput source="email" type="email" />
            <TextInput source="password" type="password" />
            <ReferenceManyField label="Roles" reference={"user/"+props.id+"/role"}>
                <AutocompleteArrayInput source="role" {...props} />
            </ReferenceManyField>
        </SimpleForm>
    </Edit>
);
```
That reference returns me `[{"id":2,"name":"CARGAR","created_at":"2020-05-08 19:36:46","updated_at":"2020-05-08 19:36:46","pivot":{"user_id":2,"role_id":2,"created_at":"2020-05-08 19:36:47","updated_at":"2020-05-08 19:36:47"}}]`

I want to show that role that returns the endpoint set as AutocompleteArrayInput, but with the option to edit, that is, in the AutocompleteArrayInput options all existing roles should appear.

If you know of another way of bringing the roles of the user / role relationship, I would be very grateful.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
