### ISSUE TITLE
AutocompleteArrayInput "Associated reference no longer appears to be available."

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#4984]
I don't want this message "The associated reference no longer seems to be available". when I add more than one element to AutocompleteArrayInput.

How can I solve it?

My code i

```
export const RoleCreate = props => (
    <Create undoable={false} {...props}>
        <SimpleForm>
            <TextInput source="name" />
            <ReferenceInput label="Permisos" source="permissions_id" reference="permission" {...props}>
                <AutocompleteArrayInput source="name" {...props} />
            </ReferenceInput>
        </SimpleForm>
    </Create>
);
```
Thank

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
