### ISSUE TITLE
ReferenceInput does not pass loading prop to child component

### ISSUE THREAD

**Issue by sebashwa** [marmelab/react-admin#4992]
**What you were expecting:**
According to the [documentation](https://marmelab.com/react-admin/Inputs.html) `ReferenceInput` should pass down a `loading` prop. I'd like to wrap `AutocompleteInput` so it shows a loading indicator whilst loading the references.

**What happened instead:**
I can not find a loading prop passed down to the child component. I think it is extracted from the `ReferenceInput` in order to figure out wether a `<LinearProgress />` or the `<ReferenceInputView />` should be shown at all.

**Steps to reproduce:**
Wrap a component in a `ReferenceInput`

**Related code:**
I created a minimal version to reproduce the behaviour logging the props of the user autocomplete in `PostEdit`:

https://codesandbox.io/s/exciting-wilbur-jkwdo?file=/src/posts/PostEdit.js

**Environment**

* React-admin version: 3.6.2
* React version: ^16.9.0

**Comment by djhi** [comment]
That's because the `<ReferenceInput />` already show a `<LinearProgress />` when loading. In order to customize that, you'll have to write your own `<ReferenceInput />` component using the underlying hook: `useReferenceInputController`

**Comment by sebashwa** [comment]
Thanks for your reply. What I actually want to do is show a spinner in case references are fetched (when someone types something inside the input). I think this should be possible with the (according to the documentation) passed loading prop:

> The child component receives the following props from <ReferenceInput>:
>  loading: whether the request for possible values is loading or not

But this one does not seem to be passed along.

**Comment by djhi** [comment]
Indeed. Thanks for reporting this

**Comment by fzaninotto** [comment]
The `loading` prop computed by `useReferenceInputController` combines the loading state of the matching references and the loading state of the reference record. It's probably not what you want. 

In the short term, the solution to fix this issue is probably to *remove* the mention of the loading prop in the doc. 

In the longer term, we need to have `<ReferenceInput>` implement a `<ListContext.Provider>` - and this will give access to `loading` to its children. 

It's a new feature though, so this will come in a minor branch.
