### ISSUE TITLE
SaveButton label prop does not work

### ISSUE THREAD

**Issue by cgarrotti** [marmelab/react-admin#5010]
**What you were expecting:**

SaveButton label prop to work
**What happened instead:**

SaveButton label prop does not work

**Steps to reproduce:**

Insert a SaveButton on a Form and set label
**Related code:**

Insert a SaveButton on a Form and set label
* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue
Insert a SaveButton on a Form and set label

insert short code snippets here

```jsx
const CustomToolbar = props => (
    <Toolbar {...props} classes={useStyles()}>
        <SaveButton label="SALVAR" />
        <DeleteButton label="Excluír" undoable={false} />
    </Toolbar>
);
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by Luwangel** [comment]
Hi, and thank you for opening this issue :pray:

We need to reproduce the problem you describe in order to fix it quickly.

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by fzaninotto** [comment]
Also, if you want to *translate* the Save button label, you'd better use the translaiton feature of react-admin. 

https://marmelab.com/react-admin/Translation.html

**Comment by cgarrotti** [comment]
Thanks, i has used: https://marmelab.com/react-admin/Translation.html
