### ISSUE TITLE
How i can use the Autocomplete from MaterialUI do Filter a Datagrid ?

### ISSUE THREAD

**Issue by cgarrotti** [marmelab/react-admin#5023]
How i can use the Autocomplete from MaterialUI do Filter a Datagrid ?

I need that when selecting an item in the ComboBox (AutoComplete MaterialUI), the DataGrid is filtered according to the value that is in the combo. I've tried it via filter but I haven't been successful. This is the screen:
![pesquisaAcessos](https://user-images.githubusercontent.com/56283778/86932420-b8f5ad00-c10f-11ea-8b66-a013c7c6eb07.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
