### ISSUE TITLE
custom filter logic

### ISSUE THREAD

**Issue by eliasor96** [marmelab/react-admin#5028]
Hi,

I have a table of users and I wish to filter upon 2 columns of type array.
I use postgres as my db and I have a data provider that forwards request to postgREST.
I wish for these certain 2 columns that the filter will be of multi select input type and so that data provider will issue a query
where it tries to find overlapping items between the filter values and the value in the records.

I can change the data provider so that it will issue a query with the appropriate operators (in case of postgres overlap operator `&&`), when it encounters a filter with value of array, but the problem with this approach that I do not always wish to filter this way and sometimes I just want to use an `in` operator where I just check if the value of a column is in the filter value which is an array. To make this distinction I thought I could use the `params` object sent to the data provider and dispatch action of type `CRUD_CHANGE_LIST_PARAMS` to add a key to the `params` object where I add an operation key with value of type operation such as ``overlap or include to make a distinction between different operations that uses array filter values. The problem is that `params` is of type `ListParams` which is defined as such (we're using React-Admin 2.9.6):

```ts
export interface ListParams {
    sort: string;
    order: string;
    page: number;
    perPage: number;
    filter: any;
    displayedFilters: any;
}
```
so that we can't dispatch such action with adding additional meta data to the `params` object so to use different operators that deals with arrays for different input filters.

What can I do to overcome this issue, any ideas?

Thanks.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
