### ISSUE TITLE
Provide ability to hook in a custom notifications library

### ISSUE THREAD

**Issue by kingsleyh** [marmelab/react-admin#5035]
**Is your feature request related to a problem? Please describe.**
In our application we are using this notification library https://github.com/jossmac/react-toast-notifications
We have added react-admin to our larger application and would like the notifications in react-admin to be consistent with the rest of our application.

**Describe the solution you'd like**
We would like a way to use this react-toast-notifications library in place of the current notifications

**Describe alternatives you've considered**
We have considered the possibility of styling the default react-admin notification to look like the notification from react-toast-notifications but there is a lot of additional functionality like count down animation on the toast version which is not easy to replicate using styling alone

**Additional context**
If there is any workaround or existing way to hook in a custom notification library we did not find it.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by kingsleyh** [comment]
Hi - thanks for your response. This was intended to be a feature request and not a question since we have investigated and see no way to hook in a custom notification library and believe it would require a code change for this to be made possible. But if you think that it is possible already and thus this is just a question of how and does not require a feature request kind of change - then I will raise it on StackOverflow.

**Comment by fzaninotto** [comment]
We won't implement the ability to hook in another notifications library in react-admin. I believe you can replace the `<Notification>` component by your own to do it in user land. As for getting help on how to do it, the right place to ask is, indeed, StackOverflow.
