### ISSUE TITLE
RA 3.6.0 - notifications not showing on screen when REST API returns an error

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#5038]
**What you were expecting:**

When the REST API returns a 500 error, I expect a notification to appear on screen that displays the text of the "message" key of the returned json payload

**What happened instead:**

Nothing happens, I don't see any notification, but in my chrome dev tools network tab I see the 500 error from the API, with a json payload and a "message" key in it

**Steps to reproduce:**

Here is my httpClient:

```
const httpClient = (url, options = {}) => {
    if (!options.headers) {
        options.headers = new Headers({ Accept: 'application/json' });
    }
    const token = localStorage.getItem('token');
    options.headers.set('Authorization', `Bearer ${token}`);
    const email = localStorage.getItem('email');
    options.headers.set('email', `${email}`);
    return fetchUtils.fetchJson(url, options);
}
```

Here is my dataProvider:
```
import simpleRestProvider from 'ra-data-simple-rest';
const dataProvider = simpleRestProvider(window.location.origin + '/api', httpClient);
```

Here is the Create component in question:
```
export const AdminContractCreate = props => (
    <Create {...props}>
        <SimpleForm
        redirect="list"
        variant="outlined"
        >
            <ReferenceInput label="Véhicule" source="vehicule_id" reference="admin_vehicules" validate={[required()]} >
                <SelectInput optionText="immat" />
            </ReferenceInput>
            <ReferenceInput label="Chauffeur" source="driver_id" reference="admin_drivers" validate={[required()]} >
                <SelectInput optionText="societe" />
            </ReferenceInput>
            <DateInput label="Date de livraison" source="date_livraison" validate={[required()]} />
            <SelectInput label="Statut" source="status" choices={[
                { id: 'En attente', name: 'En attente' },
                { id: 'Livré', name: 'Livré' },
            ]} validate={[required()]} />
            <NumberInput label="Km véhicule départ" source="km_vehicule_depart" validate={[required()]} />
            <SelectInput label="Offre location" source="offre_location" choices={[
                { id: 'Offre 1', name: 'Offre 1' },
                { id: 'Offre 2', name: 'Offre 2' },
            ]} validate={[required()]} />
        </SimpleForm>
    </Create>
);
```

**Other information:**

In my browser console I see the rejected promise

**Environment**

* React-admin version: 3.6.0
* Last version that did not exhibit the issue (if applicable): 3.1.3
* React version: 16.13.1
* Browser: chrome
* Stack trace (in case of a JS error): none

**Comment by L-Luciano** [comment]
+1

**Comment by Luwangel** [comment]
Hi and thanks for opening this issue :+1: :

I need to reproduce the problem you describe in order to fix it quickly.

As explained in the bug report template:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by fzaninotto** [comment]
The problem can't be reproduced in the simple example. Go to https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple, edit a post, type "f00bar" in the ttile, and submit the form, you will see an error notification once the optimistic update fails.

that's why we need a complete example reproducing the issue - the code you provided isn't enough. 

Did you, by any chance, use a custom `<Layout>` component, and forgot to include the `<Notification>` component in it?

**Comment by L-Luciano** [comment]
For me, I found my problem. It was an old saga which catch a specific error but the structure of error changed, so the saga had an error.

**Comment by jdemangeon** [comment]
Hello @francoisruty! Can you provide us a working example ?

**Comment by fzaninotto** [comment]
No news for some time, closing
