### ISSUE TITLE
Add a way to disable useGetOne in useEditController

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#5048]
**Is your feature request related to a problem? Please describe.**

Example of us case:

- Form where previous record is better when not shown
  - Password reset form
  - Live forecasting

**Describe the solution you'd like**

Add a `prop.previousRecordingFetch = true` by default.

**Describe alternatives you've considered**

Create my own `useEditController`, copy and paste `useEditController` and remove the `useGetOne` fetching.

**Additional context**

React-admin: 3.7.0

**Comment by Luwangel** [comment]
Hello,

Thanks for submitting an issue.

It's already possible in React-Admin to build custom views. Instead of using the `<Edit>` component, you can use the `<EditView>` component in combination with the [useUpdate hook](https://marmelab.com/react-admin/Actions.html#specialized-hooks).

Don't hesitate to ask questions on the [React Admin Channel on StackOverflow](http://stackoverflow.com/questions/tagged/react-admin). if you have more questions.

Regards,
Adrien
