### ISSUE TITLE
Can an empty TextInput value be sent to the DataProvider as empty string instead of converted to null?

### ISSUE THREAD

**Issue by gavacho** [marmelab/react-admin#5076]
I'm using a `<TextInput>` in a `<SimpleForm>` and when I clear out the value at runtime, react-admin sets the property's value to `null` when it sends the values to the `DataProvider`. I would like to store empty strings instead of null. Is that possible? If so, how?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by gavacho** [comment]
@djhi I understand the desire to direct howto questions to stackoverflow and I posted [this question](https://stackoverflow.com/questions/62853538/can-my-empty-textinput-value-be-sent-to-the-dataprovider-as-empty-string-instead/63060294#63060294) 11 days before creating this github issue.

Will you help me turn this into a feature request or bug report?

If I were 100% sure that react-admin does NOT support sending empty strings instead of NULL when the user has deleted the value from a TextInput, then I would open a feature request.

On the other hand, if this is something that is intended to work (e.g. via the `initialValue` property) then I will open a bug issue.

Which should be opened?
