### ISSUE TITLE
BulkActionButton

### ISSUE THREAD

**Issue by alpern95** [marmelab/react-admin#5118]
Hello,
How can i use the props to change "basepath" in custom Bulk Action Button

I have tree Bull Action Buttons
stop, start, refresh

And i will change api route
to have 
../api/v1/groupes/stop/{id}
../api/v1/groupes/start/{id}
../api/v1/groupes/refresh/{id}

in src/groupes
...
const PostBulkActionButtons = props => (
            <Fragment>
            <StopViewsButton label="Stop Views" {...props} />
            <StartViewsButton label="Start Views" {...props} />
            <RefreshViewsButton label="Refresh Views" {...props} />
            {/* default bulk delete action */}
        </Fragment>
);
...

in doc isee we can use the props bit i dont know hoxw

Bulk action button components receive several props allowing them to perform their job:

resource: the currently displayed resource (eg posts, comments, etc.)
basePath: the current router base path for the resource (eg /posts, /comments, etc.)

![2020-08-05 16_36_38-React App](https://user-images.githubusercontent.com/1835110/89426044-00388300-d73a-11ea-8068-766d7b3e05c6.png)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
