### ISSUE TITLE
If the data object has depth, how can I access it from the filed in the <Datagrid>

### ISSUE THREAD

**Issue by shkyung** [marmelab/react-admin#5141]
Im using   
    "react": "^16.13.1",
    "react-admin": "^3.6.0",

and I used to access data below. It works !
```js
 <Datagrid>
              <TextField source="product.no" label="Product ID" />
              <TextField source="productModelPiName" label="Product Model(PI)" />
              <TextField source="version" label="Product Version" />
              <TextField source="inStock" label="In stock" />
              <TextField source="outOfStock" label="Out of stock" />
              <TextField source="disposal" label="Disposal" />
            </Datagrid>
```

but the server response is changed. 
so I need to access like **source = product.di.productModelPiName** but It doesn't work.
How can I use react-admin for this case???

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by shkyung** [comment]
I posted my question several times on stackoverflow, but I couldn't get the answers that I needed

**Comment by fzaninotto** [comment]
I understand, but we don't provide free support by GitHub anyway. If you really need assistance, consider adding a bounty on StackOverflow, or contact Marmelab for paid support.
