### ISSUE TITLE
Associated reference no longer appears to be available

### ISSUE THREAD

**Issue by Dzhakhar** [marmelab/react-admin#5142]
I have found other issues with the same title here, but there was no answer and no solution provided.

Please explain me, why this sample code is working properly
```
  <ReferenceInput label={"Specification"} perPage={20} source={"specificationName"}
                                    reference={ResourceNames.SPECIFICATIONS}>
                        <SelectInput optionText={"name"}/>
   </ReferenceInput>
```
while this code is showing the "Associated reference no longer appears to be available" error message.

```
  <ReferenceInput label={"Specification"} perPage={20} source={"specificationName"}
                                    reference={ResourceNames.SPECIFICATIONS}>
                        <SelectInput optionText={"name"} optionValue={"name"} />
   </ReferenceInput>
```

The only difference between above given examples - is the `optionValue` property passed to `SelectInput`. What's wrong with it? I don't want my `SelectInput` to use `ID` as a value... How the `optionValue` property is related to the above mentioned error message?

Please help! Thank you in advance

**Comment by Dzhakhar** [comment]
When I pass `id` in the `optionValue` property - error message disappears... I see no logic behind that. But I still need to pass `name` instead of `id`

**Comment by djhi** [comment]
Because React-Admin **requires** the `id` for resources identification.

See https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources

**Comment by Dzhakhar** [comment]
> Because React-Admin **requires** the `id` for resources identification.
> 
> See https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources


But `name` it is suitable for resource identification as well

**Comment by Niraj-Kamdar** [comment]
I have the same issue and setting a custom primary key doesn't seem like the right solution for my use case.
I have a purchase table with (id, customerId) fields. I want to reference customerId into an another table and I want to save customerId, not purchaseId. How can I accomplish it? Because setting OptionValue to "customerId" throws "Associated reference no longer appears to be available." error. 

Here is my code:
```js
<RA.ReferenceInput
    label="Customer ID"
    source="customerId"
    reference="purchases"
    filterToQuery={searchText => ({ purchasesByCustomerId: searchText })}
>
    <RA.AutocompleteInput optionText="customerId" optionValue="customerId" resettable />
</RA.ReferenceInput>
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
