### ISSUE TITLE
💡 Shouldn't define default style for TextInput/ResettableTextField

### ISSUE THREAD

**Issue by tanpld** [marmelab/react-admin#5160]
<img width="374" alt="Screen Shot 2020-08-14 at 5 38 59 PM" src="https://user-images.githubusercontent.com/25787149/90241389-24404680-de55-11ea-95d3-8888b7555cfb.png">
I don't think we should include the default style here.
I can't update style with Theme Provider. It's so redundant to put props whenever I have a TextInput like this

    <TextInput source="username" variant="outlined" margin="normal"/>

I would be great if you guys can update this, thank you so much.

**Comment by fzaninotto** [comment]
I don't see the problem. Just create your own variant of TextInput with these props, and use it instead of react-admin's version.

**Comment by JacobGalati** [comment]
@fzaninotto I would just like to add that I disagree with your assessment. This is exactly what the theme props are for. It would be better to include your default props in the defaultTheme so they can be easily overwritten in one place instead of having to write a custom component for 22 different input component type in react-admin just because we want to change the default style.
