### ISSUE TITLE
Export zip with password

### ISSUE THREAD

**Issue by winilau** [marmelab/react-admin#5162]
**Is your feature request related to a problem? Please describe.**
I am trying to make a custom export action/button that zips the csv string (from the old exporter or just a csv string generated from the List) and provides password protection. It's a bit hard because I am new to JScript and react-admin. 

**Describe the solution you'd like**
Can I make a new export button and inherit the functions of the old exporter button (I want to keep the csv string but I need to route the button to my nodejs function with dataprovider). If not then is there a way to make a new custom action but have the data output like the exporter function, I don't know how I would format/write that. 

**Describe alternatives you've considered**
Or is it possible for you to make a new action for exporting as a zip file with password protection, I figured it would be easy for you guys. And I would appreciate it very much, but if not I totally understand.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
