### ISSUE TITLE
Restrict access to logged in user's data

### ISSUE THREAD

**Issue by seranotannason** [marmelab/react-admin#5163]
To my understanding, the best that react-admin can do in authorization right now is role-based access control. It doesn't allow users to have their own set of data that they have access to. For example, user Alice may have her own posts that only she can access while user Bob, from another organization, has his own set of posts that only he can access. 

I imagine this feature is very complex and requires quite a number of constraints on DataProvider etc., but is potentially a very useful feature. Is this on the roadmap?

**Comment by djhi** [comment]
> To my understanding, the best that react-admin can do in authorization right now is role-based access control.

No, we built authorization so that it allows many patterns including but not limited to role-based access control. For example, see https://github.com/marmelab/ra-auth-acl

> It doesn't allow users to have their own set of data that they have access to.

It is possible to implement this without any change in the core. I suggest you post a question on [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

**Comment by seranotannason** [comment]
Hi @djhi, thanks for the references, though I think those are still unsuitable for multi-tenancy
