### ISSUE TITLE
Not able to update SimpleForm TextInput value 

### ISSUE THREAD

**Issue by rohit-gautamQSS** [marmelab/react-admin#5208]
<SimpleForm
      label="resources.xyz"
      {...props}
    >
      <TextInput
        source="latitude"
        label="resources.latitude"
        defaultValue={
          gpsLocation?.capturedLocation?.latitude || props?.record?.latitude
        }
        value={
          gpsLocation?.capturedLocation?.latitude || props?.record?.latitude
        }
      />

In this the gpsLocation?.capturedLocation?.latitude and longitude is change when we capturing the location by a separate function but the textInput value is not going when we submit the form.

**Comment by djhi** [comment]
Please follow the issue template

**Comment by rohit-gautamQSS** [comment]
Hi Gildas Garcia,

I am using SimpleForm in which there are two lat long and there one button which will capture the location and gives the value gpsLocation?.capturedLocation  = { latitude: 28.4645, latitude: 78.224 } something like this.

But when there is no value is set in TextInput (like in case of create or first time setting value in the textInput) it goes with form with updated value.

But in edit case when we want to update the value (by capture location button **gpsLocation?.capturedLocation?** this props update and shown also on the UI but it does not go with the form when submit again the previous value go always.)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
