### ISSUE TITLE
Can't get data from useEditController

### ISSUE THREAD

**Issue by dangchinh25** [marmelab/react-admin#5215]
I want to create a custom edit page so I use useEditController to get the data from dataProvider.getOne(). But when I want to restructure the data, it can't do so because of undefined. I think this is because useEditController is an async call and we will have to wait for it before destructuring the data.

![image](https://user-images.githubusercontent.com/35798337/91768725-afcf0c80-eba3-11ea-9149-855d0654932c.png)

![image](https://user-images.githubusercontent.com/35798337/91768946-0ccac280-eba4-11ea-859b-779b6355297c.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
