### ISSUE TITLE
useDataProvider vs useGetOne - EDIT component not getting record data

### ISSUE THREAD

**Issue by HamAndRock** [marmelab/react-admin#5217]
Hello, I am having trouble getting data from API to Edit Component. I have custom data provider querying our API but the data from API aren't written to back to the Edit Component.

However when I try to printout the data in data provider they are OK, and I can see them in Networking tab and also in console.log(). But my edit component is blank without any inputs.

![image](https://user-images.githubusercontent.com/24235083/91851884-3e08c880-ec60-11ea-926d-80f2329e611f.png)

If i try to call the dataProvider manually I get 2 different results from it. When I use `useDataProvider()`, then my data is filled, however when I try to use `useGetOne()` the data is undefined, even thought my data provider was called 100%, by looking into Networking tab in Chrome.

![image](https://user-images.githubusercontent.com/24235083/91852008-74dede80-ec60-11ea-86e5-4920e3bfb389.png)

![image](https://user-images.githubusercontent.com/24235083/91851996-6bee0d00-ec60-11ea-8ecc-d71d0734ae87.png)

Code of my data provider. I tried to use async, promises nothings works. Also if I replace the `.filter()` with static object like `{test: 1}`, the same problem occurs. 
![image](https://user-images.githubusercontent.com/24235083/91851611-c9ce2500-ec5f-11ea-8d27-ffcb85a4b001.png)

Thanks for any help, really struggling with this one.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
