### ISSUE TITLE
when updating the TextInput by setstate then the update value is not going in the form on submit

### ISSUE THREAD

**Issue by rohit-gautamQSS** [marmelab/react-admin#5225]
**What you were expecting:**
When we set the value by state and try to update the value while in edit mode by just random value (not key press) on click any button through the function call. Then it the update value is not going with form while submitting

**What happened instead:**
The update value is showing but not going the updated value with form while submitting.

**Steps to reproduce:**
1. Create a form 
2. Add any field and set that value by random number by state by another button which will set the value
3. Then save it and again go to the edit mode 
4. Try to update the value by clicking button which set the random number and save it.

**Related code:**
const UserEdit = props => {
   const [lat, setLat] = useState(props?.record?.latitude);
    return (
    <SimpleForm
      label="test"
      {...props}
    >
      <TextInput
        source="latitude"
        label="latitude"
        value={lat}
      />
      <Button
            variant="contained"
            color="primary"
            size="small"
            onClick={()=>{setLat(Math.random());}}
          >
            update late
          </Button>
        )}
 </SimpleForm>
}

**Environment**

* React-admin version: 3.0.4
* Last version that did not exhibit the issue (if applicable): No
* React version: 16.12.0
* Browser: Version 84.0.4147.89 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
