### ISSUE TITLE
After build "Could not find: "store" in either the context or props of "Connect(Form(Component))"

### ISSUE THREAD

**Issue by vogt31337** [marmelab/react-admin#5226]
**What you were expecting:**

My App does work nicely in my develop environment ("yarn start"), after building ("yarn build") and deploying it it should still work nicely...

**What happened instead:**

Nothing happens, blank screen and the following console output:
```
Invariant Violation: "Could not find "store" in either the context or props of "Connect(Form(Component))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Form(Component))"."
    exports browser.js:38
    i Redux
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    unlisten Router.js:34
    r history.js:155
    notifyListeners history.js:173
    notifyListeners history.js:172
    P history.js:561
    push history.js:664
    confirmTransitionTo history.js:145
    push history.js:648
    c useLogout.js:62
react-dom.production.min.js:209:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    unlisten Router.js:34
    r history.js:155
    notifyListeners history.js:173
    notifyListeners history.js:172
    P history.js:561
    push history.js:664
    confirmTransitionTo history.js:145
    push history.js:648
    c useLogout.js:62
```

**Steps to reproduce:**

Sorry code is not providable... If REALLY needed, I'll try to create an example.

**Related code:**

I think it happens, because I'm bad at javascript and I just upgraded to the newest version of react admin. I think it happens, because I want to access the state, and therefore I'm using:

```
const mapStateToProps = state => ({
    version: state.admin.ui.viewVersion,
});

export default compose(
    connect(mapStateToProps),
    withDataProvider
)(Dashboard);
```

But I really don't know how else I could do this thing.

**Other information:**

Possible solution seems to be doing something like described here: [Accessing react redux store](https://react-redux.js.org/using-react-redux/accessing-store), but I can't use it, because on the hand I haven't understood the concepts until now and on the other hand, there seems to be some mandatory reducer functions, which I don't know what they are supposed to do and how to get "the correcte react-admin ones". Also since react-admin should do this stuff for me [Caching](https://marmelab.com/react-admin/Caching.html#optimistic-rendering)

**Environment**

* React-admin version: 3.8.3
* Last version that did not exhibit the issue (if applicable): 2.9.8
* React version: 16.13.1
* Browser: Firefox 68.12.0
* Stack trace (in case of a JS error): see above.

Sorry I'm lost :(

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
