### ISSUE TITLE
Masking Custom Action Button during loading or for a certain condition

### ISSUE THREAD

**Issue by winilau** [marmelab/react-admin#5241]
I made a custom export button where instead of a csv string the button exports a zip with a csv inside it. I used dataprovider to route it to backend. The button works perfectly now but I noticed that the original export button from react-admin is disabled/grey during loading and when the list is empty. I want to make that possible for my custom export button too but I don't think there is a feature like that.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
