### ISSUE TITLE
How to get ra-data-json-server data provider response body

### ISSUE THREAD

**Issue by AlbertVasilew** [marmelab/react-admin#5308]
Hello everyone,

I am using ra-data-json-server as data provider. I have initialized list and create resources, which works fine. But, in my back-end web api, when creating new record, I am returning message in the response body, if the record already exists.

My question is: **how to read the response body**, so I can show the message in the right component, to the user?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
