### ISSUE TITLE
Custom Saga in not triggering in Jest

### ISSUE THREAD

**Issue by alirni** [marmelab/react-admin#5320]
React-Admin: 3.5.5
React: 16.9.0
Jest-Enzyme: 7.1.2

Hi.
I have a functional component which has a function that dispatches a custom action. I also have a custom saga which is registered to listen to that custom action dispatches. Now, I want to test this component with the help of Jest.
In my test case, when the component has mounted, that function dispatches the custom action and the problem appears: custom saga is not triggering.
Do you have a solution to this problem?

``` javascript
// MyComponent.js
export default myComponent = props => {
  const myFunction = () => {
    // Dispatches Custom Action
    myAction(()=>{
      console.log('foo');
    });
  }

  return (<button data-test="btn" onClick={myFunction}>Click Me</button>)
}

// Action.js
const myAction = (callback) => {
  return {
    type: FIND_ONE,
    callback
  };
}

// customSaga.js
function* mySaga({ callback }) {
  try {
    //...
    callback();
  } catch (error) {
    //...
  }
}

export default function* customSaga() {
  yield takeEvery(FIND_ONE, mySaga);
}

// Component.test.js
describe('`myComponent`', () => {
  const wrapper = mount(
    <TestContext>
      <MyComponent />
    </TestContext>,
  );

  test('Run myFunction', () => {
    const button = wrapper.find(`[data-test="btn"]`);
    button.simulate('click');
  });
});
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
