### ISSUE TITLE
Time-range filter for Datagrid

### ISSUE THREAD

**Issue by StanleyP** [marmelab/react-admin#5325]
I'm using RA + ra-data-postgrest trying to implement log viewer. As the table is VERY long, my goal is to have one input for timestamp and one input for timerange with predefined time intervals (10s,30s,1min...). But the select input is bound to column due to source prop so it gets propagated to call to postgrest and so nothing is returned.

What I would like is to have select input that is not bound to any particular column, but its value (and change of value) is propagated to i.e. some calculated "hidden" input with value of current timestamp + interval and the second boundary.

Is this possible with RA?
Could you please give me some pointers how to do it?

I also created question on SO: https://stackoverflow.com/questions/64124008/react-admin-timerange-filter

Thanks for any help.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
