### ISSUE TITLE
TextInput defaultValue with a function does not work

### ISSUE THREAD

**Issue by edulix** [marmelab/react-admin#5354]
**What you were expecting:**
Setting a `defaultValue={() => uuid()}` to a TextInput should work. I'm creating an UuuidInput field, that should by default provide a new uuid. It works if the `SimpleForm` sets an `initialValues` function, but that's not what I need.

**What happened instead:**
The TextInput appears empty inside the SimpleForm.

**Steps to reproduce:**
Use a SimpleForm with a TextInput

**Related code:**
Take a look at https://codesandbox.io/s/intelligent-bartik-km7ed?file=/src/posts/PostCreate.js

I modified the forked default code sandbox so that he create post form has a `title` `TextInput` field with a string `defaultValue` and `teaser` field has a functional `defaultValue` property. The `title` works, the `teaser` field appears empty:

```
        <TextInput autoFocus source="title" defaultValue="static value" />
        <TextInput
          source="teaser"
          defaultValue={() => "value from a function"}
        />
```

**Environment**

* React-admin version:3.9.0
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.9.0
* Browser: chrome
* Stack trace (in case of a JS error): -

**Comment by fzaninotto** [comment]
Reproduced, thanks. 

Looking at the react-admin code, this regression seems to be caused by the FormWithRedirect refactoring. However, reintroducing this feature (which is documented in  CreateEdit.md#per-input-default-value) isn't trivial, and besides it never really worked: we had to inspect Form children, which was never robust.

I think this should be a react-final-form feature, and making it work outside of that lib is too risky.

So I think what we should do here is fix the documentation to remove the ability to pass a custom function as default value.

In your case, you can use the **form** `initialValues` to set the initial value for one field at the form level.

**Comment by alextaymx** [comment]
How do i fill up the values for the next <SelectArrayInput/> field based on the values obtained from current input field? I couldn't find any way to access the record data / or even modify it beforehand
