### ISSUE TITLE
How to custom value in some tags like '+CREATE', 'EXPORT', 'EDIT', 'DELETE'. 

### ISSUE THREAD

**Issue by tomeczekstecc** [marmelab/react-admin#5365]
How to custom value in some tags like '+CREATE', 'EXPORT', 'EDIT', 'DELETE' (e.g. in Resource component).  Obviously these are english words as values and I'd like to custom then to another valueus -> maybe another language or just another words like 'ADD POST', 'EDIT POST' ... 

Thanks.

 StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`).

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
