### ISSUE TITLE
AutocompleteInput slow with lots of options

### ISSUE THREAD

**Issue by thekevinbrown** [marmelab/react-admin#5367]
**Is your feature request related to a problem? Please describe.**
In my code I currently need to allow users to select a timezone in the Admin UI. So I'm using `AutocompleteInput` with the choices created like this:

```typescript
import countriesAndTimezones from 'countries-and-timezones';

const choices = Object.keys(countriesAndTimezones.getAllTimezones())
	.sort()
	.map(tz => ({ id: tz, name: tz }));
```

This list has 594 items in it. Showing the autocomplete takes about a half a second, and the thing generally feels laggy.

**Describe the solution you'd like**
I'd like `AutocompleteInput` to be performant like in this example: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/other-examples/react-window/index.js&moduleview=1&file=/src/downshift/other-examples/react-window/index.js

I'd expect to use `react-window` to accomplish this.

**Describe alternatives you've considered**
Implement a custom autocomplete for use in my project only, but in general it feels like this is likely to be a pretty common use case for this component, so I think we should try to solve the problem for everyone.

**Additional context**
I'd be happy to have a go at a PR that changes AutocompleteInput to use React Windowed in all scenarios if it'd be a welcome addition to React Admin.

**Comment by fzaninotto** [comment]
Hi @thekevinbrown, and thanks for your suggestion.

The delay here is mostly due to material-ui rendering. 

But I'm not sure using an autocomplete with 500+ choices is such a common case. I'd probably use a server to return only the relevant choices on input, to avoid making the admin bundle too large with useless data. Besides, [react-window weights 865 kB](https://www.npmjs.com/package/react-window), so we won't include it as a dependency unless it's for  good reason.

I encourage you to create a variation of the AutocompleteInput dedicated to large choice lists, and publish it as a standalone package. We'll link to it in the react-admin documentation.
