### ISSUE TITLE
ReferenceInput not working into SimpleForm

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#5437]
Hello, the problem is that I find that within a component created by me, where I do not use Create or Edit, I only use a SimpleForm as I show in the code, the ReferenceInput does not work for me. which queries my API fine, but it doesn't show me the values ​​I get, any help?
```
    return (
        <>
            <Dialog
                fullWidth
                open={props.createEvent}
                onClose={handleCloseClick}
                aria-label="Crear turno"
            >
                <DialogTitle>Indicar el rango de horas disponibles</DialogTitle>
                <DialogContent>
                    <SimpleForm
                        resource="session"
                        save={handleSubmit}
                        validate={validate}
                        toolbar={<ButtonToolbar onCancel={handleCloseClick}/>}
                    >
                        <ReferenceInput
                            source="patientId"
                            reference="patient"                            
                            label="Paciente"                             
                            filterToQuery={searchText => ({ name: searchText })}>
                                  <AutocompleteInput initialValue={ props.initialValue ? props.initialValue : null } optionText="name" />
                        </ReferenceInput>
                    </SimpleForm>
                </DialogContent>
            </Dialog>
        </>
    );

```
Thanks

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
