### ISSUE TITLE
Link Chips of AutocompleteArrayInput

### ISSUE THREAD

**Issue by henrik-d** [marmelab/react-admin#5439]
**Is your feature request related to a problem? Please describe.**
I often use `ReferenceArrayInput` and `AutocompleteArrayInput` to create relations between resources. E.g. I have `Posts` and let the user assign `Tags` to it. If the user wants to see details of a chosen `Tag`, he must change to the `Tag`-Resource and find it there. Would be nice if he could navigate to the selected `Tag` directly.

**Describe the solution you'd like**
Maybe you could detect if `AutocompleteArrayInput` is used with `ReferenceArrayInput`, which would imply that the selected choice is a linkable resource and link it automatically?

**Describe alternatives you've considered**
1. You could allow to render own `Chips` (or any other component) through render-props. This would also allow other customizations.
2. Or you could add a `onClick` callback, so one could trigger the navigation manually.

**Comment by fzaninotto** [comment]
It's hard to offer a selection control which allows both addition, deletion, AND click. Also, for the end user, leaving the form because they clicked on a chip might be confusing. 

So we won't be adding this feature in `AutocompleteArrayInput`, but feel free to use your own component instead. And if you are kind enough to open-source it, please add it to the list of third-party inputs!
