### ISSUE TITLE
useGetMany data into List component

### ISSUE THREAD

**Issue by tannerPriest** [marmelab/react-admin#5451]
We primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`). Thanks! 😁.

https://stackoverflow.com/questions/64363330/dynamically-inject-records-into-list-component

This is my stack overflow question Id like to get answered.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by tannerPriest** [comment]
@djhi I have had that stackoverflow question up for 2 weeks now and havent gotten a response. Am I flagging it correctly? I would like at least a message saying either it cant be done or at least a point in the right direction please. Thank you for responding to this!

**Comment by fzaninotto** [comment]
@tannerPriest The react-admin core team doesn't commit to doing free support on StackOverflow. This is delegated to the community so that we can focus on fixing bugs and improving the library.

If you absolutely need and answer, consider adding a bounty on StackOverflow, or subscribing to the Enterprise Edition for paid support.

**Comment by tannerPriest** [comment]
Thank you for responding! Will look into those options
