### ISSUE TITLE
Should I use ra-tree-materialui or other tree view in react-admin?

### ISSUE THREAD

**Issue by vahidqo** [marmelab/react-admin#5470]
I'm using react-admin to develop a dashboard web app. One of my data list views needs a tree view. I'm trying to use ra-tree-materialui but it doesn't work. Can somebody help me with this and also recommend alternatives besides ra-tree-materialui? Thanks.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. Note that ra-enterprise has a [package](https://marmelab.com/ra-enterprise/modules/ra-tree) for trees.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
