### ISSUE TITLE
TestContext, not using store w/ `useQueryWithStore`

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#5474]
I'm trying to write a simple unit test for a component that uses `useQueryWithStore`. But no matter what I do it fails and just returns `undefined`

**What you were expecting:**
When unit testing a component wrapped in `TestContext` with an initialStore, it should use the data from the store.

I would expect it to return the mock I provided:
1. `{ loading: false, data: { example: true }, error: null }`

**What happened instead:**
`useQueryWithStore` returns 3 times.
1. `{ loading: true, data: undefined, error: null }`
2. `{ loading: true, data: undefined, error: null }`
2. `{ loading: false, data: undefined, error: null }`

**Steps to reproduce:**
I have a component with the following `useQueryWithStore`
```
const { data, loading, error } = useQueryWithStore({
        type: 'getList',
        resource: 'probe',
        payload: {
            filter: { site_id: siteId }
        }
    });
```
And my unit test, is attempting to render this code like so:

```
const state = {
  admin: {
    customQueries: {
      '{"type":"GET_LIST","resource":"probe","payload":{"filter":{"site_id":2743}}}': {
        data: [
          {
            site_id: 2743,
            type: 'probe-ping',
            active: true,
            remote_id: '76.9.60.84',
            config: {
              ip_address: '76.9.60.84',
              device_type: 'primary'
            }
          }
        ],
        total: 1,
        validUntil: '2020-11-02T19:17:17.328Z'
      }
    }
  }
}


describe('react-admin test', () => {
  test('renders Component', () => {

    render(
      <TestContext initialState={state}>
        <Component filter={filterMock} siteId={2743} />
      </TestContext>
    )

    screen.debug()
  });
});

```

**Other information:**
I have also tried a normal `useQuery` and `useGetList` (and adding the correct redux state for those), but both of these ends up in an infinite loop if I attempt it.

There is also an error from react-dom when I run the above test:

```
console.error node_modules/react-dom/cjs/react-dom.development.js:88
    Warning: An update to SiteCharts inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in SiteCharts (at SiteCharts.test.tsx:111)
        in Router (created by TestContext)
        in Provider (created by TestContext)
        in TestContext (at SiteCharts.test.tsx:110)
        in ThemeProvider (at test-utils.tsx:10)
        in Providers
```

How are you supposed to test a Component that does any dataFetching with mocks? 

**Environment**

* React-admin version: 3.9.2
* React version: 16.13.1
* Browser: All

**Comment by djhi** [comment]
Hi, and thanks for your question. Not sure what you expect but the following test displays the correct logs:

```js
it('A test', () => {
    const Component = ({ siteId }) => {
        const { data, loading, error } = useQueryWithStore({
            type: 'getList',
            resource: 'probe',
            payload: {
                filter: { site_id: siteId },
            },
        });

        console.log({ data, loading, error });

        return <div />;
    };

    const state = {
        admin: {
            customQueries: {
                '{"type":"GET_LIST","resource":"probe","payload":{"filter":{"site_id":2743}}}': {
                    data: [
                        {
                            site_id: 2743,
                            type: 'probe-ping',
                            active: true,
                            remote_id: '76.9.60.84',
                            config: {
                                ip_address: '76.9.60.84',
                                device_type: 'primary',
                            },
                        },
                    ],
                    total: 1,
                    validUntil: '2020-11-02T19:17:17.328Z',
                },
            },
        },
    };

    render(
        <TestContext initialState={state}>
            <Component siteId={2743} />
        </TestContext>
    );
});
```

This is the very first log I get:
```sh
{
  data: [
    {
      site_id: 2743,
      type: 'probe-ping',
      active: true,
      remote_id: '76.9.60.84',
      config: [Object]
    }
  ],
  loading: true,
  error: null
}
```

Which means it work as expected and your question is actually a support question ("How To", usage advice, or troubleshooting your own code). So you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
