### ISSUE TITLE
Why is there no createMany method type in useMutation Hook?

### ISSUE THREAD

**Issue by NetMelon** [marmelab/react-admin#5501]
**Is your feature request related to a problem? Please describe.**
I have a use case where I want to upload a file and its contents to the react-admin data provider, but I find it questionable to dispatch individual requests for each record instead of using one request for the create method similar to _updateMany_ .

**Describe the solution you'd like**
Please implement a **createMany method** type in the data provider API.

**Describe alternatives you've considered**
Among the alternatives I can think of are to make a request for each single record and even using _fetch()_ for it.

**Additional context**
I'm talking about the [_useMutation Hook_](https://marmelab.com/react-admin/Actions.html#usemutation-hook) in the documentation.

Btw, I think react-admin is a great piece of code. Ride on my friends!

**Comment by fzaninotto** [comment]
Hi @NetMelon, and thanks for your suggestion.

We could add a new dataProvider method, but that would make things harder for new developers when they build a new admin. One new method to implement, usually with a Promise.all() trick because not many backends support batch insertions. As we won't be using this method in the react-admin code, it doesn't make sense to add more work to developers for no benefit.

Instead, nothing prevents you from creating this createMany method in your own provider, and to call it with useMutation in your own components. In fact, custom dataProvider methods are even encouraged!
