### ISSUE TITLE
Options in dataprovider

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5519]
When we use basic dataprovider from the tutorial, it's fine. The problem starts if we make custom admin UI.  
The dataprovider from the tutorial suddenly starts unusable since react-admin fails at `TypeError: can't convert undefined to object`.  
And it fails in `isDataProviderOptions` function, located in `node_modules/ra-core/esm/dataProvider/getDataProviderCallArguments.js:19`  
It asks for options in dataprovider. Therefore - how this "options" object should look like?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question.

In order to reproduce your problem, we need a sample of the code that triggers your bug. The best way to do that is to provide a link to a CodeSandbox based on the [react-admin simple example](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

Oh, and while we are at it: We wrote an issue template to be sure that we have all the input to solve each issue efficiently. Make sure you use it if you want us to pay attention to your demand ;)

**Comment by Xeizzeth** [comment]
The latest update fixed the issue.
