### ISSUE TITLE
Fields within ListBase take data from parent Edit

### ISSUE THREAD

**Issue by izziaraffaele** [marmelab/react-admin#5533]
**What you were expecting:**

I have a resource with an Edit view. Within its Aside I show a list of another resource using the ListBase component, a Datagrid and some TextFields as usual.

With react-admin@3.9.2 everything works as expected but if I update to the latest release the Datagrid within the ListBase component doesn't show the correct data

**What happened instead:**
It seems that fields inside the Datagrid are taking the record from the main Edit view instead of picking up the values of the parent ListBase component. Also columns label are broken: it doesn't pick up the right translation.

**Other information:**
react-admin@3.9.2 (correct)
![Schermata 2020-11-13 alle 19 59 17](https://user-images.githubusercontent.com/2734825/99110526-d02b3680-25ea-11eb-9b95-f72ac2d45390.png)

react-admin@3.10.1 (wrong)
![Schermata 2020-11-13 alle 19 53 13](https://user-images.githubusercontent.com/2734825/99110218-57c47580-25ea-11eb-8304-caf5f57ea482.png)

**Comment by fzaninotto** [comment]
Yep, that's because the Datagrid is now relying on a context rather than prop injection to get its data and translations. It broke in your case because displaying data about another resource in the aside part was never a supported feature. 

You can, however, make your setup work again. You have to wrap the content of your Aside component inside a `<ResourceContextProvider>` (for translations) and a `<ListContextProvider>` (for data).

**Comment by izziaraffaele** [comment]
@fzaninotto I thought that was the purpose of the `ListBase` component: setting up the context for a list. In fact, the only thing I see in the ListBase component is a ListContextProvider (which apparently is ignored by the child Datagrid). Maybe the ListaBase component is missing a ResourceContextProvider?

**Comment by fzaninotto** [comment]
The resource context is created by the Resource component, so it's based on the url. It's higher in the React tree than the List component. 

The ListBase component calls the useListController hook and passes the data to the ListContext. In your case, you probably don't want to use the useListController as it uses the ressource from the URL to determine what to fetch. 

ListBase should not implement a ResourceContextProvider - it's not its responsibility.

**Comment by izziaraffaele** [comment]
Clear. Thanks for the explanation

**Comment by nik-lampe** [comment]
Interesting.
I stumbled across this too, and it totally confused me until I started looking for it here.

Maybe it needs an explanation in the docs? Especially as the behaviour changed in version 3.10?

I'm not using the `ListBase` component, but the `List`component and was expecting, that this would create it's own context, because I need to pass a resource and a basePath prop anyway.
