### ISSUE TITLE
Edit component does not call update function

### ISSUE THREAD

**Issue by AlbyIanna** [marmelab/react-admin#5534]
**What you were expecting:**
When I click the **Save** button in the Edit view, I'd expect the `update` function in my `dataProvider` to be called.

**What happened instead:**
The update function in my `dataProvider` is not called when the **Save** button is clicked under the edit view.

**Steps to reproduce:**
Look at the code

**Related code:**
my code:
- **index.tsx**
```ts
...
    <Admin dataProvider={dataProvider} layout={AdminLayout}>
      <Resource name={ResourceType.Sessions} list={SessionList} edit={SessionEdit} create={SessionCreate} />
      <Resource name={ResourceType.Clients} list={ClientList} edit={ClientEdit} create={ClientCreate} />
    </Admin>
...
```
- **ClientEdit.tsx**
```ts
import React from 'react';
import {
  DateInput,
  Edit,
  EditProps,
  SimpleForm,
  TextInput,
} from 'react-admin';

export const ClientEdit: React.FC<EditProps> = (props) => {
  console.log(props)
  return (
    <Edit {...props}>
      <SimpleForm>
        <TextInput source="id" />
        <TextInput source="name" />
        <DateInput source="createdAt" disabled />
        <DateInput source="updatedAt" disabled />
      </SimpleForm>
    </Edit>
  );
};
```

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

As explained in [this Stack Overflow question](https://stackoverflow.com/questions/63960736/react-admin-edit-component-does-not-call-update-function)'s answer, I tried to set the `undoable` prop to `false` in the `Edit` component and **it worked**.
```
...
<Edit {...props} undoable={false}>
...
```

**Environment**

* React-admin version: **3.10.1**
* Last version that did not exhibit the issue (if applicable): -
* React version: **16.13.1**
* Browser: **Chrome**
* Stack trace (in case of a JS error): no errors in the console

**Comment by fzaninotto** [comment]
I cannot reproduce the problem [on a CodeSandbox based on the master branch](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple). You probably have a problem somewhere else in your code. I suspect you forgot to include the `<Notification />` component in your custom Layout (if so, re-read the [custom layout documentation](https://marmelab.com/react-admin/Theming.html#layout-from-scratch), especially the final note).

If it's not the case, please join a link to a CodeSandbox reproducing the issue.

**Comment by oklas** [comment]
Thank that this issue already exists.

I have same problem and I have some more info:

The execution sequences goes to line [useDataProvider.ts:232](https://github.com/marmelab/react-admin/blob/v3.10.2/packages/ra-core/src/dataProvider/useDataProvider.ts#L322)

Then seems execution does not continue to the next lines. Possible page reloading or fiber destroying has place.
 
I am trying to figure out problem. Most probably that is due to destroying of components (together with they states and therefore cancel event processing). After calling `onSuccess()` the next execution is appears at breakpoint at line [useDataProvider.ts:140](https://github.com/marmelab/react-admin/blob/v3.10.2/packages/ra-core/src/dataProvider/useDataProvider.ts#L140)
Possible [useEditController.ts:L195](https://github.com/marmelab/react-admin/blob/v3.10.2/packages/ra-core/src/controller/details/useEditController.ts#L195) is the latest line of this process.

It does not depend from custom or not the history: `<Admin dataProvider={provider}>` or `<Admin dataProvider={provider} history={history}>`.

However in first case (without custom router) panel with `undo` button appears (but visible only in debug due to break point) without debug panes is not visible. But in second case (with custom router) no such panel at all even under break. Code behaviour at mentioned points is the same as above described in both case.

Any thoughts?

**Comment by oklas** [comment]
As appears in my case this is a duplicate of #4429.

**Comment by fzaninotto** [comment]
So the answer is the same as in #4429: it's not supported. So I'm going to close this bug.
