### ISSUE TITLE
Path variables in resources used by ReferenceInput

### ISSUE THREAD

**Issue by Gericop** [marmelab/react-admin#5544]
Is it possible to use path variables in `Resource` names or allow any requests with a wildcard? It would have a semantic value as well as a proper REST path form.
For example:
```jsx
<Resource name={"users/:id/something"} />
```
would mean that a specific user's extra data can be retrieved on a page with this:
```jsx
<ReferenceInput reference={`users/${props.record.id}/something`}>...</ReferenceInput>
```
However, this doesn't seem to work as it results in `Error: Cannot fetch a reference to "users/1/something" (unknown resource).`

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
