### ISSUE TITLE
'ra-realtime' was converted to an enterprise module? I thought it wasn't migrated...

### ISSUE THREAD

**Issue by benwinding** [marmelab/react-admin#5547]
Firstly, I love react-admin and appreciate the team who've created and maintained it, I've also contributed 2 popular packages to the ecosystem, so please don't dismiss my concerns too quickly. (_Also let me know if I've misinterpreted anything_).

Last year, this issue #4044 shows why `ra-realtime` wasn't migrated to _react-admin v3_ apparently due to [breaking compatibility with _redux-saga_ and _hooks_ etc](https://github.com/marmelab/react-admin/issues/4044#issuecomment-669003404)... but now it seems it's back, but it's become a [private module](https://marmelab.com/ra-enterprise/modules/ra-realtime) available on your new enterprise plan? As far as I can tell this wasn't publicly stated anywhere, was it?

This worries me, because `ra-realtime` was a simple and highly useful module that many people depend on, now it's essentially been silently converted to a propitiatory feature... This is one of my big fears of the [Open Core](https://en.wikipedia.org/wiki/Open-core_model) business model, as the company has the incentive to charge for features, so features are taken from the open-source community and made a premium features...

Is it possible for the open-source community to develop modules which rival the _react-admin_ enterprise modules? Seems like a conflict of interest for _react-admin_, as people wouldn't pay if all features were freely available from the open-source community. The main reason I contribute to the _react-admin_ ecosystem is to develop open-source features which rival closed source propitiatory systems, so I hope it's possible to develop a community version of `ra-realtime`...

Anyway, I understand it's built by a company which deserve to make money, seems like some great new features. I just hope the open source version will retain it's greatness!

Kind regards,
Ben

**Comment by fzaninotto** [comment]
Hi @benwinding, and thanks for your contributions to the react-admin ecosystem.

We don't have the intention to remove features from the open-source version. On the contrary, you can see that since the release of the Enterprise version, we've continued adding new features to the open-source version:

https://marmelab.com/blog/2020/10/07/react-admin-october-update.html

The case of ra-realtime is special as it required a full rewrite to work with react-admin 3.x. This was done at great cost, and publishing it as a private package was a way for us to make this effort sustainable. The process allowed us to offer many more features (like lock management) and a much better developer experience with this new package, which is entirely different than the realtime module of react-admin version 2.0, 

We've stated it publicly in #5272.

We don't do open-source to reproduce existing commercial systems - that would be a waste of money. We build tools for our own usage, and we open-source them because we use a lot of open-source ourselves. It's a way for us to give back to the community. But once an open-source library becomes popular, its maintenance represents significant costs. So a companion product is absolutely necessary. React-admin is no exception. That's why I don't understand your point about contributing to open-source only to rival proprietary systems. 

We've explained that in greater detail in a blog post: https://marmelab.com/blog/2020/09/02/react-admin-enterprise-edition.html#why-react-admin-needs-an-enterprise-edition

You are free to develop whatever module you want, but we won't include in our Ecosystem doc links to modules rivaling our Enterprise Edition modules. 

We hope you'll continue to contribute to the open-source version of react-admin!

**Comment by benwinding** [comment]
Appreciate the detailed response @fzaninotto,

Yes it's true that reproducing FOSS versions of commercial systems is a waste, but to build around propitiatory systems is also a waste. Building FOSS tools that other people can use/change/own is much better for people who can't afford the expensive tools and is a much better feeling. Also, I think people in Open-Source _should_ aim to rival commercial systems, as there's so many benefits to everyone else in the world _(also pretty sure react-admin is a rival to many commercial admin frameworks out there)_... But I guess I'm using Github, Google, etc.., so maybe not _everything_ needs to be rebuilt in Open-Source.

Anyway, it's been quite inspiring to watch `react-admin` go from 4k to 15k stars in the past 2 years, and I'm happy to see the team finally earn some reward off of the product.

> We hope you'll continue to contribute to the open-source version of react-admin!

I will!

Cheers,
Ben
