### ISSUE TITLE
MenuItemLink route forming

### ISSUE THREAD

**Issue by Xeizzeth** [marmelab/react-admin#5554]
I use custom menu with custom layout.  
And I use routing with the pattern [http://myserver/admin/some_resource/\<id\>](http://myserver/admin/some_resource/1)  
Where id is an int of id of an object in the database.
And I form the MenuItemLink this way:  
```
           <MenuItemLink
                key={`${item.id}`}
                to={`${item.route}`}
                primaryText={item.name}
                leftIcon={<DashboardIcon />}
                onClick={props.onMenuClick}
                sidebarIsOpen={props.open}
                dense={props.dense}
            />
```
"to" is the route that looks like "some_resource/\<id\>" as you can guess.

But if you click on this item, that works with that route, in the menu multiple times, it will start prepending "some_resource" at the route, so it will begin to look something like this: http://localhost:3000/#/some_resource/some_resource/some_resource/some_resource/some_resource/some_resource/1  

How should I work with the routing to avoid this confusion? Or it is a case of a bug?

**Comment by Xeizzeth** [comment]
And btw I use "item route", instead of forming a string that looks something like this: `\`some_resource/{item.id}\`` because it was my attempt to fix the issue.  
Will be happy to get rid of it.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
