### ISSUE TITLE
Can I create two resources using one form?

### ISSUE THREAD

**Issue by ivankirshin** [marmelab/react-admin#5565]
I have two resources: Hardware and Product.
The hardware depends on the Product.
All examples suggest using one create/edit form for one resource. Can I change this behavior?
For better UX, I want to create a product seamlessly.
Users should see just one form with inputs from the two.
Of course, the product must be created before using its identifier as a foreign key.

Do you have similar examples?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
