### ISSUE TITLE
can't access the data on the show page to display them in a pdf 

### ISSUE THREAD

**Issue by Razi321** [marmelab/react-admin#5569]
i tried solutions from stackoverflow , and looked in the documentation but i didn't found an answer ( also i think downloading a pdf is a good features that should be implemented ) 

i create an app based on [react-admin][1] 
 and a fake server using json-server 

my file structure is the following :

    client ( here goes the react app ) 
    node_modules
    db.json
    package-lock.json
    pachake.json
    range.js

then i created products and orders lists and show page :
the link for the show page of an order is ( for example order 3 ) : 
**http://localhost:3000/#/orders/3/show**
and it shows the orders datils 
what i wanna do is to download a pdf file contains this details , i tried the following code as a starting point : 

    import * as React from "react";
    
    import {useQuery,  Show, SimpleShowLayout, TextField } from 'react-admin';
    import { PDFDownloadLink, Document, Page , View , Text } from '@react-pdf/renderer'
     
    const MyDoc = ({}) => {
       
        
    return (
       
        <Document>
          <Page size="A4">
            <View>
               <Text>
             details must go here
               </Text> 
            </View>
          </Page>
        </Document>
       
    
      )};
    
    const OrderShow = (props) => (
        <Show {...props}>
            <SimpleShowLayout>
      
            <TextField source='order_number' />
            <TextField source='reference_number' />
            <TextField source='status' />
            <TextField source='payment' />
            <TextField source='shipment' />
            <TextField  source='created_at' />
              <div>  
            
         
            <PDFDownloadLink document={<MyDoc />  } fileName="somename.pdf">
          {({ loading }) => (loading ? 'Loading document...' : 'Download now!')}
        </PDFDownloadLink>
    
        </div>
            </SimpleShowLayout>
    
        </Show>
    );
    export default OrderShow

with this i got the following output :
[![enter image description here][2]][2]

**when i click on Download now! a pdf with the content ' details must go here ' but instead of that i want the data about the current order** 

  [1]: https://marmelab.com/react-admin/
  [2]: https://i.stack.imgur.com/wjjCL.png

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by Razi321** [comment]
even in stack overflow they did not find an answer !
