### ISSUE TITLE
Simple Codesandbox fails at PostShow

### ISSUE THREAD

**Issue by MicroJackson** [marmelab/react-admin#5574]
**What you were expecting:**
Simple Codesandbox to be working.

**What happened instead:**
Its bugged.

**Steps to reproduce:**
Goto: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
Press Post.
Click one.
Press Show.
![image](https://user-images.githubusercontent.com/39806531/99969898-61dd3580-2d9b-11eb-90aa-c6a92e5a56d6.png)

**Comment by fzaninotto** [comment]
Reproduced, thanks for the report.

**Comment by fzaninotto** [comment]
Well, there is a mystery. I can reproduce the bug on CodeSandbox, but not on master or by downloading the code from CodeSandbox... I guess there is an issue in Codesandbox.

**Comment by fzaninotto** [comment]
![image](https://user-images.githubusercontent.com/99944/99992825-26506480-2db7-11eb-8e0e-69e91d969ffc.png)

**Comment by fzaninotto** [comment]
And if I fork the CodeSandbox, the bug doesn't show up anymore...

**Comment by fzaninotto** [comment]
I'm blocked. This is a CodeSandbox bug. It will likely go away when we deploy a new release (hopefully end of this week).

**Comment by oklas** [comment]
I tried to play with sandbox right now for a 5534 and noticed that it ignores code changes (it does not do rebuild). Code changes applied only after fork sandbox.

But this case there is no `ShowContextProvider` because react-admin v3.0.9 is specified, and it does not appears yet at [v3.0.9:/ra-core/src/controller](https://github.com/marmelab/react-admin/tree/v3.9.0/packages/ra-core/src/controller). And after fork sandbox the package reinstalling take place (there is no yarn or npm lock file and version specified as `ˆ3.0.9`). New packages has a version with `ShowContextProvider`.

**Comment by oklas** [comment]
I tried to play with sandbox right now for a #5534 and noticed that it ignores code changes (it does not do rebuild). Code changes applied only after fork sandbox.

But this case there is no `ShowContextProvider` because react-admin v3.0.9 is specified, and `ShowContextProvider` does not appears yet at [v3.0.9:/ra-core/src/controller](https://github.com/marmelab/react-admin/tree/v3.9.0/packages/ra-core/src/controller). And after fork sandbox the package reinstalling take place (there is no yarn or npm lock file and version specified as `ˆ3.0.9`). New packages has a version with `ShowContextProvider`.

So @MicroJackson check which version you have in `package.json`. Then check lock file. Then check what you have actually installed in `node_modules`. Then check appropriate repositogy slice.

**Comment by fzaninotto** [comment]
Fixed yesterday by the CodeSandbox team, who deleted the persistent volume of our server CodeSandbox.
