### ISSUE TITLE
Use filters to set filter prop

### ISSUE THREAD

**Issue by steventilator** [marmelab/react-admin#5586]
I'm using Firebase as a backend for react-admin. The package I use (react-admin-firebase) is implemented in a way that all entries of a resource are fetched from the database when mounting the app. This leads to a high read count.

I would like to use the filters I define in the `filters` prop of a `List` to set the `filter` prop. In that way, I can more clearly define which data to fetch and thus reduce database usage.

Would it be possible to do this? And – if yes – how would I go about implementing it?

Here's a short example:

If I have the filter component like this:

```
const SessionFilter = props => {
  return (
    <Filter {...props}>
      <NullableBooleanInput
        source="isReviewed"
        alwaysOn
      />
      <ReferenceInput
        source="employee"
        reference="employees"
        alwaysOn
      >
        <AutocompleteInput optionText="fullName" />
      </ReferenceInput>
    </Filter>
  );
};
```

...and pass it to a List like this:

```
<List
  {...props}
  filters={<SessionFilter />}
>
    {content}
</List>
```

...it would automatically set the filter of the List:

```
  <List
      {...props}
      filters={<SessionFilter />}
      filter={{ field: filter }} // This would be dynamically created based on the SessionFilter component.
    >
    {content}
</List>
```

The alternative is to simply write custom filter inputs that run outside of react-admin and use them to set the `filter` prop. Integrating it with the `filters` component would be neat, though.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
