### ISSUE TITLE
Dynamically change breakpoints properties

### ISSUE THREAD

**Issue by dalisalvador** [marmelab/react-admin#5588]
Hello,

I'm trying to accomplish the following:
In Layout.tsx, while creating styles
```
     {
         ...
        appFrame: ({isLargeHeader, isXLargeHeader}) => ({
          display: 'flex',
          flexDirection: 'column',
          flexGrow: 1,
          [theme.breakpoints.up('xs')]: {
             marginTop: isLargeHeader ? '268px' : isXLargeHeader ? '510px' : '130px'
          }
      })
     }
```
But media queries dont change on props update. Is that approach correct?

A workaround I'm currently using is  **useMediaQuery** hooks and pass the props to modify (in this case) the **marginTop**
But the breakpoints approach its cleaner imo

Thanks!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
