### ISSUE TITLE
error message in https://admin.something.co/#/something.stock/create 

### ISSUE THREAD

**Issue by HOCKNAS** [marmelab/react-admin#5592]
Hi team,

I have a issue when i try click on create button, I seen : 
![image](https://user-images.githubusercontent.com/40615475/100326587-23f93080-2f98-11eb-9fc7-33f92d48522e.png)

I don't understand nothing. Please, help!

I was making ```yarn build``` and i when upload this to my s3 bucket that error appear. In my development enviroment all is ok, but after ```yarn build``` or ```npm run build``` and upload to s3 all become crazy.

I think that this issue could be to dependencies, but I don't know how to solve.

Thanks in advance,

Santiago

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
