### ISSUE TITLE
Decouple Redux and make state managemente a provider on its own

### ISSUE THREAD

**Issue by altenorjr** [marmelab/react-admin#5601]
Hi Guys, first and foremost, I'd like to pay my respects to this amazing project. I've been using it for production management panels and the experience has been a bliss. A concise, opinionated set of patterns that we end up using even in other contexts and solutions.

**Is your feature request related to a problem? Please describe.**
The problem has been selling React-Admin for enterprises. Redux is an awesome library, but it comes with overheads that companies quickly grew tired of. So even though the solution is awesome, many enterprises won't adopt it because their stack has abandoned Redux altogether. And even though I've written now a couple apps without ever needing to even think about Redux, enterprises are rightly scared of the edge cases that will force them to keep Redux specialists in house, even though it won't be found anywhere else. (Me personaly, I don't really mind. But selling it as an enterprise solution has been a tough cookie.

**Describe the solution you'd like**
The thing with React-Admin that nearly brings tears to my eyes is that *everything* in it can be simply swapped out through an standardized and clear API. I think this concept should be extended to cover state managemente. We could define a State Managemente Provider that would take care of handling all necessary steps to update the app state. Redux would become a provider, just like we have defaults for everything else. So I the enterprise uses MobX, RxJS, Zustand or any other kind of solution, they could just use/write the correct provider and React-Admin would still be a feasible solution, even for all of the Redux haters out there.

**Describe alternatives you've considered**
One could think of a solution where React-Admin creates a custom API that allows to integrate with the underlying Redux Store without having to know anything about Redux. The problem with this solution is that it would end up closely resembling the proposed State Managemente Provider API and Redux would still be a core dependency, defeating the whole purpose of deferring the state management for a third party and making Redux an option dependency.

**Additional context**
I think I could possibly help trying to figure out the necessary API. I used to be more comfortable with Redux, but It's been a long time since I left it behind. I could try to inspect the code and get what I need from there, but if any in-depth documentation of the internal Redux state tree and it's actions would be available, that would help me a lot.

I've been "leeching" the open source community for way too long, with only a few rare contributions. I think this would be a great way to start paying back all the love I've got from you guys, to a project that has made a better dev and in which I truly believe.

**Comment by fzaninotto** [comment]
Hi Altenor,

And thanks a lot for your kind words. It's always heartwarming to read that our work is appreciated.

I understand your point about Redux. But we don't want to decouple react-admin from Redux, for various reasons:

- This would make the code more complex. I believe it is already complex enough, even for code developers.
- This would create another layer in the code, with abstracted interfaces to communicate with the rest of the code, causing in the passage a whole new class of bugs and performance problems
- The Redux logic is already pretty well hidden under the react-admin hooks. As you said, you almost never need to add a custom reducer or mess with the react-admin actions
- Nonetheless, react-admin does need Redux because React doesn't offer a way to connect to parts of a context.
- If people don't want to use react-admin because they don't want to use Redux, they can always use another library. We don't want react-admin to be to solution for all problems. 
- we don't want to maintain an abstraction layer inside react-admin. We have limited time, and we know that we can only keep react-admin in good shape by keeping it lean. 

Now, react-admin is open-source, so if you desperately need a RxJS- based react-admin, you can always fork react-admin and change the state management library. I would be curious to see how it turns out!

Just be warned that it will probably cost 4 to 6 months.man of development. Is it really worth the effort?

That being said, if you feel like getting invested in react-admin, there are tons of enhancements proposed by the community that just need a helping hand like yours to be added to the core. Just check this list of issues:

https://github.com/marmelab/react-admin/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement
