### ISSUE TITLE
use own input component doesn't work

### ISSUE THREAD

**Issue by TalOrlan** [marmelab/react-admin#5602]
I try your example of try to write your own input component and it's not work

**Comment by fzaninotto** [comment]
Hi,

We write tons of custom input components, and they do work. Maybe you discovered that in some cases they don't, but by reading your issue, we can't tell.

When you opened the issue, you probably saw a template, asking you for many details. Without these details, we can't even qualify your issue. 

So we can only assume that the problem is on your side.

**Comment by TalOrlan** [comment]
```
const LatLongInput = () => (
    <span>
        <Field name="position.lat" component="input" type="number" placeholder="latitude" />
        &nbsp;
        <Field name="position.lng" component="input" type="number" placeholder="longitude" />
    </span>
);
```
I run this code from you web and it's failed I would love some info how to configure this redux-form
