### ISSUE TITLE
ArrayInput : support disabled prop

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#5617]
**What you were expecting:**

`<ArrayInput>` should support the `disabled` prop

**What happened instead:**

It does not. I can disable child inputs though:

![image](https://user-images.githubusercontent.com/99944/100903111-cef07980-34c5-11eb-90a9-85f9d1cd2a33.png)

But there is a problem: the add and remove buttons are not disabled, and still allow to add or remove items.

![image](https://user-images.githubusercontent.com/99944/100903053-c13af400-34c5-11eb-9483-4c35d1128894.png)

So the `<ArrayInput>` should support the `disabled` prop:

```jsx
                <ArrayInput source="backlinks" disabled>
                    <SimpleFormIterator>
                        <DateInput source="date" />
                        <TextInput source="url" />
                    </SimpleFormIterator>
                </ArrayInput>

```

**Comment by josepedrocorreia** [comment]
Hi there,

I have two remarks about this issue:
1. In the [release list](https://github.com/marmelab/react-admin/releases), this is marked as part of release `3.11.0`, but I am using `3.10.4` and I can use `disabled` with `ArrayInput`, so I think it was already included in that release;
2. It seems to me that this change introduced a bug, since I can no longer successfully disable child inputs. I'm calling this a bug because I don't think it was in the scope of this change to do that, and because one might not want to disable the whole `ArrayInput` but still disable individual child inputs.

Cheers

**Comment by djhi** [comment]
Hi @josepedrocorreia, thanks for reporting this. Do you mind opening another issue for the new bug by following the issue template? A codesandbox would help. Thanks!
