### ISSUE TITLE
Why `ra-data-graphql` doesn't work with hooks

### ISSUE THREAD

**Issue by selfrefactor** [marmelab/react-admin#5626]
**What you were expecting:**

It should work with hooks, but it doesn't for some reason.
I created example repo to better show what I mean. The file of interest is https://github.com/selfrefactor/react-admin-issue/blob/master/src/App.js

If I use `AppWithHooks` this is my log:

```
Object { introspectionResults: {…}, other: {} }
Object { x: raDataProvider(aorFetchType, resource, params)
, a: "function" }
Object { raFetchType: null, resourceName: undefined, params: undefined }
Object { raFetchType: null, resourceName: undefined, params: undefined }
Object { raFetchType: null, resourceName: undefined, params: undefined }
Error: Unable to determine the query operation
```

while the log with `App` is very different:

```
Object { introspectionResults: {…}, other: {} }
Object { raFetchType: "GET_LIST", resourceName: "videos", params: {…} }
Error: Unable to determine the query operation
```

**What happened instead:**

I don't have that big of a problem, but at least I want to know the reason for this.

**Steps to reproduce:**

Clone https://github.com/selfrefactor/react-admin-issue and after install, run with `yarn start`. Then switch in `src/index.js` between `App` and `AppWithHooks` as component to render.

**Related code:**

https://github.com/selfrefactor/react-admin-issue

**Other information:**

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: latest of CRA
* Browser: Firefox
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Tip**: The hook version of `setState`, when passed a function, believes it's a state changing function and not a value.
