### ISSUE TITLE
Unhandled Rejection (TypeError): client.query is not a function

### ISSUE THREAD

**Issue by Razi321** [marmelab/react-admin#5706]
i'm tring to get the data frim graphql api that have an authorization token so i tried passing the token with the uri but i got the following error : 
**Unhandled Rejection (TypeError): client.query is not a function**

this is **App.js**
```
import * as React from 'react';
import { Provider } from 'react-redux';

// material
import PostIcon from '@material-ui/icons/Book';
import UserIcon from '@material-ui/icons/Group';

// react admin
import {Admin, Resource, ListGuesser} from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

// pages
import {OrderList, OrderEdit, OrderShow} from './pages/orders';

import {PostList, PostEdit, PostCreate, PostShow} from './pages/posts';
import {UserList} from './pages/users';
import loginPage from "./pages/login";

// components
import Dashboard from './components/Dashboard';
import authProvider from './utils/authProvider';

import { Component } from 'react';
import buildGraphQLProvider from 'ra-data-graphql-simple';

import { ApolloClient, InMemoryCache } from '@apollo/client';
import { createNetworkInterface } from 'react-apollo';
import { HttpLink } from 'apollo-link-http';
// browser history
import { createBrowserHistory as createHistory } from 'history';
const history = createHistory();


class App extends Component {
    constructor() {
        super();
        this.state = { dataProvider: null };
    }
    componentDidMount() {
        buildGraphQLProvider({
            client: {
                link: new HttpLink({
                    uri: 'https://domain/graphql',
                    headers: {
                        authorization: 'Bearer token_

here',
                      
                      }
                }),
            },
        })
            .then(dataProvider => this.setState({ dataProvider }));
    }
 
    render() {
        const { dataProvider } = this.state;
 
        if (!dataProvider) {
            return <div>Loading</div>;
        }
 
        return (
    <Admin
        authProvider={authProvider}
        dataProvider={dataProvider}
        history={history}
        dashboard={Dashboard}
        loginPage={loginPage}
    >
        <Resource
            name="orders"
            icon={PostIcon}
            list={OrderList}
            edit={OrderEdit}
            show={OrderShow}
        />
       
    </Admin>
  );
}
}

export default App;
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
