### ISSUE TITLE
is there a way to got the selected object not just the id

### ISSUE THREAD

**Issue by peacetrue** [marmelab/react-admin#5721]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/38878763/103078959-ec6cbb00-460d-11eb-9bfe-eccf9f56dd98.png)

i want to do something according to the view count of the Post
but i just got the id
can provide the whole object and then i can get the Post.viewCount

**Describe the solution you'd like**

**Describe alternatives you've considered**

1. do not use `ReferenceInput`
2. get the list data by myself and stored as `posts`, then passed to `SelectInput.choices`
3. when i got the id in onChange event,  i got post by `posts[id]`

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
