### ISSUE TITLE
react-admin demo test

### ISSUE THREAD

**Issue by vanderleisp** [marmelab/react-admin#5732]
trying to start with the react-admin demo, but even following all instructions on how to take out the reCaptcha it shows there, and as seems it gets wrong data then can't move forward to see, if at least the demo works here.

Changed the app.js as requested, as to remove the custom login page, and nothing happened, and then also did the auth update (maybe did some wrong answers but seems this doesn't influence on the login page.

I'm a newbie so still learning, and maybe did something wrong.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
