### ISSUE TITLE
Warning An update  inside a test was not wrapped in act(...)

### ISSUE THREAD

**Issue by hieusmiths** [marmelab/react-admin#5750]
For this problem I met it when writing unit test and see bellow warning:

```
Warning: An update to TextInput inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in TextInput (at TextInput.tsx:8)
        in TextInput (at TextInput.test.tsx:21)
        in ReactFinalForm (at TextInput.test.tsx:18)

```

This problem will happen when you pass validate={require()] into any component.

You can try by your TextInput.spec.ts then add  validate={[required()]} to see full error.

Please help me thanks, team.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
