### ISSUE TITLE
Translation not working with app.js

### ISSUE THREAD

**Issue by NuniTelo** [marmelab/react-admin#5836]
Hi everyone. So I have app.js and after providing:

const messages = {
  'it': italianMessages,
  'en': englishMessages
};
 const i18nProvider = polyglotI18nProvider(locale => messages[locale]);
 
 when I try to translate Resouce for example: 
 <Resource
          name="test"
          list={testList}
          show={testShow}
          options={{ label: 'menu.test_field_label'}}
        />

It only displays the "menu.test_field_label" not the actual translation value.
Any help please?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
