### ISSUE TITLE
the css class drawerPaper not work - MySidebar

### ISSUE THREAD

**Issue by DanielSanchez94** [marmelab/react-admin#5838]
Hello, I am sure that someone can help me, and I understand that it is not the right place to ask how to do it. But maybe it's a bug: it turns out that I'm trying to put a green border to the sidebar, in the way I indicate in the photo. but I can't find the way, I can't find the css class that I need to edit to achieve it. any help please?

![Ejemplo](https://user-images.githubusercontent.com/18008219/106335139-f87e1500-626a-11eb-9513-0d6b2c6b78c2.jpg)
 

I want to add the green border as indicated in the image. I have tried as the documentation says, but it does not work:

`import { Sidebar, Layout } from 'react-admin';
import { makeStyles } from '@material-ui/core/styles';

const useSidebarStyles = makeStyles({
    drawerPaper: {
        borderBootom: "15px solid #006a3c",
    },
});

const MySidebar = props => {
    const classes = useSidebarStyles();
    return (
        <Sidebar classes={classes} {...props} />
    );
};

const MyLayout = props => <Layout {...props} sidebar={MySidebar} />
export default MySidebar;
`
Thanks

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
