### ISSUE TITLE
Force logout upon login

### ISSUE THREAD

**Issue by kptdaaron** [marmelab/react-admin#5873]
Hi @marmelab! Thank you for this great framework! I'm fairly new to programming so please bear with me. 

I tried following the docs (3.12.1) in Auth Provider and was able to authenticate user from my backend. 

However, this code 
```
logout: () => {
     localStorage.removeItem("auth");
     return Promise.resolve();
  },
  ```
keeps on logging me out, prompting me to _Please login to continue_ 

 Here is my code...
  
authProvider.js
```
const authProvider = {
  logout: () => {
     localStorage.removeItem("auth");
     return Promise.resolve();
  },
  login: ({ username, password }) => {
    const request = new Request("http://localhost:3000/api/auth", {
      method: "POST",
      body: JSON.stringify({ username, password }),
      headers: new Headers({ "Content-Type": "application/json" }),
    });
    return fetch(request)
      .then((response) => {
        if (response.status < 200 || response.status >= 300) {
          throw new Error(response.statusText);
        }
        return Promise.resolve();
      })
      .then((auth) => {
        localStorage.setItem("auth", JSON.stringify(auth));
      })
      .catch(() => {
        throw new Error("Network error");
      });
  },
  checkError: ({ status }) => {
    if (status === 401 || status === 403) {
      localStorage.removeItem("username");
      return Promise.reject();
    }
    return Promise.resolve();
  },
  checkAuth: () => {
    localStorage.removeItem("username");
    return localStorage.getItem("username")
      ? Promise.resolve()
      : Promise.reject();
  },
  getPermissions: () => Promise.resolve(),

};

export default authProvider;
```

Response I get from the server 
```
{
  "success": true,
  "message": "Successfully Logged In!",
  "userData": {
    "user_id": "601d25ca48305c2ef1e6a42c",
    "firstName": "test",
    "lastName": "test",
    "username": "test@mail.com",
    "token": "eyJhbGciOiJIUzI1NiJ9.NjAxZDI1Y2E0ODMwNWMyZWYxZTZhNDJj.WvYB9-H2kVTtCvRB4YumJe17EIIb0Kiz2t8h1g-IcwY"
  }
}
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
