### ISSUE TITLE
Support payload for Delete mutations

### ISSUE THREAD

**Issue by ValentinH** [marmelab/react-admin#5959]
**Is your feature request related to a problem? Please describe.**
On some of our screens, an admin must fill a comment to explain why a record is deleted. To do this, we would like to use the `body` of the DELETE request but this is not possible currently:
![image](https://user-images.githubusercontent.com/2678610/109286694-e15b2480-7822-11eb-9710-920319eca790.png)
 

**Describe the solution you'd like**
Allow passing a `data` in the `delete`/`deleteMany` payload like it's possible for `update/updateMany`.

**Describe alternatives you've considered**
For now, we are doing a dirty workaround by passing a query string to `payload.id`. For example:

```ts
mutate({
        type: 'delete',
        resource: 'comments',
        payload: {
            id: `${id}?adminComment=xyz`,
        },
    })
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

I assume that you store the deletion reason, and also maybe the deleted record, in another table. In that case, you don't actually  `delete` a record, but rather `archive` it. I suggest you add that custom method to your `dataProvider` and call it instead of `delete()`.

That's the reason why we won't change the signature of the `delete` operation.

**Comment by ValentinH** [comment]
We don't archive but actually delete the record. The admin comment is used as a log to know what happened and the main resource.

As HTTP is allowing using the body for GET (even if it's not standard), I believe it would make sense to support it in the mutations.

The reason we use the delete operation is also to benefit from the automatic deletion of a row when doing an optimistic/undoable mutation. How would this work with a custom archive operation?

For more context, we don't have any custom data providers, we only rely on the `ra-data-json-server`.

**Comment by andrico1234** [comment]
Can you not just do the following?

```
const [deleteUser] = useMutation();

  const submit = (data: FormData) => {
    deleteUser(
      {
        type: "delete",
        resource: "users",
        payload: {
          data,
        },
      },
    );
  };

onSubmit(formData);
```

It passes through the `data` object through to the dataProvider's `delete` method. At least this is what happens on my end. This doesn't seem like a hack, as it's pretty much the documented way of using `useMutation`. It wouldn't be too hard to wrap it in a more specialised hook, should you use this pattern regularly.

**Comment by ValentinH** [comment]
This is exactly what I want to do (unless I'm using 'deleteMany') but this is not supported as the data object is not passed as the request body.

**Comment by andrico1234** [comment]
> For more context, we don't have any custom data providers, we only rely on the `ra-data-json-server`.

My bad, I glossed over the part where you mention you're using `ra-data-json-server`. I've never used it, but I've seen in the RA examples that they occasionally proxy their network requests before it hits ra-djs. Are you able to do the same? For instance, it looks like it they intercept the `update` function in [this file](https://github.com/marmelab/react-admin/blob/master/examples/simple/src/addUploadFeature.tsx) and customise it's behaviour. Otherwise the rest of the dataProvider is exactly the same.

**Comment by ValentinH** [comment]
I'm facing this limitation again and I'm wondering if the last comments here could change your decision of closing this issue @fzaninotto . Especially [this one](https://github.com/marmelab/react-admin/issues/5959#issuecomment-786853158).

**Comment by ValentinH** [comment]
For now, I basically patched the `delete` and `deleteMany` providers methods like this:
![image](https://user-images.githubusercontent.com/2678610/110351904-95378d80-8035-11eb-8114-2bf74139a952.png)


This is only working because the TS definition of the `useMutation's mutate()` payload is loose (`object`).

If this would be accepted, I'm ready to do the PR on `ra-data-json-server` and on the `DeleteParams/DeleteManyParams` to support this.
