### ISSUE TITLE
How to use custom storybook components? 

### ISSUE THREAD

**Issue by irborrero** [marmelab/react-admin#5970]
I'm a newbie to react admin and storybook.

I am writing a react admin application.

Apart from react admin components, I would like to re-use some custom components I have already developed in storybook.

The problem is that these custom components use special theming that messes up with react admin theming. They have their own colors, shapes, logos, etc. In fact, when I want to use them I have to import them from '@mylibrary/ui' .

So when I try to use them I get errors like:

>Uncaught TypeError: Cannot read property 'white' of undefined
    at push.../../../libs/ui/src/lib/input/Checkbox.tsx.styled_components__WEBPACK_IMPORTED_MODULE_1__.default.label.withConfig.theme.theme

Is there a way to use this custom components in react admin?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
