### ISSUE TITLE
Querying relay connections based GraphQL api with ra-data-graphql

### ISSUE THREAD

**Issue by dMaisnam** [marmelab/react-admin#5971]
I have an API that follows the `Relay's connections` relationship model of GraphQL. My query looks something like this:
```
query {
    users {
      edges {
        node {
          id
          username
          email
        }
      }
    }
  }
```
I have tried writing the `dataProvider` as something like the following:
```
// in src/App.js
import { useState, useEffect } from 'react';
import { Admin, Resource, Loading, Error, List, Datagrid, TextField, EmailField } from 'react-admin';
import buildGraphQLProvider from "./dataProvider";
import { useQuery, gql } from "@apollo/client";

const USER_LIST = gql`
  query users {
    users {
      edges {
        node {
          id
          username
          email
        }
      }
    }
  }
`;

const UserList = (props) => {
  const { data, loading, error } = useQuery(USER_LIST);
  if (loading) return <Loading />
  if (error) return <Error />

  return (
    <List {...props}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="username" />
        <EmailField source="email" />
      </Datagrid>
    </List>
  )
}
    
function App() {
  const [dataProvider, setDataProvider] = useState(null);

  useEffect(() => {
    const data = buildGraphQLProvider;
    setDataProvider(() => data);
    }
  }, []);
    
  if (!dataProvider) {
    return <Loading />
  }
    
  return (
    <div>
      <Admin dataProvider={dataProvider}>
        <Resource name="users" list={UserList} />
      </Admin>
    </div>
  )
}
    
export default App;
```
I also wrote a custom `dataProvider` as:
```
// in src/dataProvider.js
import buildGraphQLProvider from 'ra-data-graphql';
import { ApolloClient, inMemoryCache } from "@apollo/client";
import buildFieldList from "./buildFieldList";

const apiUrl = "http://localhost:8000/graphql";
const client = new ApolloClient({
    uri: apiUrl,
    cache: new inMemoryCache()
})
const buildQuery = introspectionResults => (raFetchType, resourceName, params) => {
  const resource = introspectionResults.resources.find(r => r.type.name === resourceName);

  switch (raFetchType) {
    case 'GET_LIST':
      return {
        query: gql`query ${resource[raFetchType].name} {
          data: ${resource[raFetchType].name} {
              ${buildFieldList(introspectionResults, resource, raFetchType)}
          }
        }`,
        variables: params,
        parseResponse: response => response.data,
      }
    break;
  }
};

export default buildGraphQLProvider({ buildQuery: buildQuery, client: client})
```
Sorry if I may sound trivial. I know my approach is not correct but how do I consume APIs following this grammar with `ra-data-grapql`? How do I write the custom `buildFieldList` & connect the dots? I have not found a resource where  APIs following this `connections`-based API structure is consumed. I have also asked for help on Stackoverflow but with no luck getting a solution. Any tip or guidance would be much appreciated.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
