### ISSUE TITLE
Version upgrade problems

### ISSUE THREAD

**Issue by NuniTelo** [marmelab/react-admin#6007]
Hi! 
We were using react admin on a pretty big project and decided to upgrade the version from 2.3 to 3.11. Fixed all the bugs and updated all the related libraries. Project is compiled without problems and runs very good. 
Lists are okay, show is okay. The problem starts with create and Edit. They start to act really strange. 

**What you were expecting:**
To work as before. 

**What happened instead:**
Disabled buttons became active and also can take a status disabled:true when typing on choosing data from drop downs. 

Formdata object inside the FormDataConsumer losses all the data inside. 

Date forms looks really outdated. 

**Steps to reproduce:**
Update versiom from 2.3 to 3.11

**Environment**

* React-admin version: 3.11
* Last version that did not exhibit the issue (if applicable):2.3
* React version:latest
* Browser: chrome
* Stack trace (in case of a JS error): FormData is deprecsted useInput is thrown on the console (not as error) 

Help please.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/). It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
