### ISSUE TITLE
Failed to load config "react-app" to extend from. Referenced from: <path>\react-admin\.eslintrc

### ISSUE THREAD

**Issue by tobbtechnologies** [marmelab/react-admin#6100]
Failed to load config "react-app" to extend from.
Referenced from: <path>\react-admin\.eslintrc

I am not getting help with this problem anywhere

**Comment by tobbtechnologies** [comment]
The react version is 17.0.2

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by tobbtechnologies** [comment]
Thank fzaninotto for your reply. The react-admin  boiler plate is very good from my side. Thank you for creating such a nice thing. I got a similar answer when I wrote to marmelab. I posted on react-admin stackoverflow. No reply and there are 99% questions asked there  react-admin and no reply. This is an indicator that there is no skilled community on react-admin. Its blind people trying to lead blind people. Views are there, showing people are going there but no comments, not even suggestions. It's a mute community.

I will encourage people to take the paid one but for us the paid one is very expensive R2519 per month, billed annually meaning we need to pay R30228. For now we will try the community one and if successful we will come for the enterprise one and also donate to charity as requested.

Once more thank you for you good and impressive product. Keep it up.

**Comment by fzaninotto** [comment]
> It's blind people trying to lead blind people. Views are there, showing people are going there but no comments, suggestions, nor replies. It's a mute react-admin community.

@tobbtechnologies I don't do open-source to receive criticism from people who want more, for free, and never contribute. I don't want that anonymous trolls like you ruin my day. I invite you to use another library, react-admin is not good enough for you.

**Comment by fzaninotto** [comment]
@djhi pointed me this conversation and told me I misunderstood your comment. He's right: I thought you we criticizing our work, while you were just complaining about the community, which is not nice but doesn't deserve the above reaction. Apologies - I should have read your comment three times before replying.

**Comment by alafitamx** [comment]
Check if you have typescript installed 
#npm ls typescript
if not
install with this command
#npm i typescript -d 
Works for me.
