### ISSUE TITLE
Enable grpc-web integration (through read delegation)

### ISSUE THREAD

**Issue by zecke** [marmelab/react-admin#6149]
**Is your feature request related to a problem? Please describe.**

I am using Google's protobuf to describe my "domain" objects and want this to somehow integrate with react-admin. The quirk is that the generated JavaScript is not exposing JavaScript objects with properties but getters and setters. AFAICT there is no way that the "source" property is able to call a function today. I briefly looked at "render" but that doesn't seem feasible either.

**Describe the solution you'd like**

I would like to be able to delegate reading and writing a property to a function. Either by being able to directly specify a function as "source" or by the introduction of read/write delegates (or "accessors").

**Describe alternatives you've considered**

The alternative is to either teach the domain objects to use get/set property or to lower the code to just use the JS Object.

**Additional context**

**Comment by fzaninotto** [comment]
This is not a use case we want to address in react-admin, because it'd add a lot of complexity and corner cases (e.g. field source is used as column header in Datagrid).

It's your responsibility to build plain old JavaScript objects based on what grpc returns in your dataProvider. As each object has an explicit schema, this should be feasible.
