### ISSUE TITLE
Translating/customizing react-admin network error notifications

### ISSUE THREAD

**Issue by edreyyo** [marmelab/react-admin#6172]
Hi

[I posted this question on Stack Overflow](https://stackoverflow.com/questions/66797459/translating-react-admin-network-error-notifications) three weeks ago but haven't had any responses, hence why I'm posting here.

When my API throws a `409 Conflict`, `react-admin` shows a red notification with the text "Conflict" (see attached screenshot).

How can I customize this text?

<img width="482" alt="conflict" src="https://user-images.githubusercontent.com/6125211/114879476-85178880-9e01-11eb-9d6c-fc3e93ea62b0.png">

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc).
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
