### ISSUE TITLE
Export button in panel does not export all data fields from API

### ISSUE THREAD

**Issue by socialvalue** [marmelab/react-admin#6207]
Description
When using a NoSQL database to provide documents(entries) through an API response in react-admin, if the first document in a list does not contain a specific field, then that field will not be exported for any of the following documents and will remain missing in the exported data even though it shows as a blank in the admin panel. 

It appears that react-admin assumes the API response based on the first item, hence, when a field is not included for the first entry, it is also excluded for all following entries and the field is ignored when exporting the data but not when viewing the results in the panel. 

What you were expecting:
The export of the entire data with inclusion of all fields from the API. 

What happened instead:
The exported user data does not include fields if the first occurrence of the entry is empty for that specific field. 

Steps to reproduce:
1 - provide a heterogeneous document structure, where the first entry in the list is missing a certain key value pair.
2- use the dataprovider for provision of the desired fields in react admin panel.
2 - click the exporter button in the panel to retrieve the entire data. 
3 - fields remain missing if the first occurrence of the data is missing the key value pair.

```

**Environment**

* React-admin version: 2.8.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.4
* Browser: Chrome/Firefox
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Thanks for your report. 

This is caused by the library we use to convert JSON to CSV, [jsonexport](https://github.com/kaue/jsonexport). For such cases, jsonexport allows to specify the headers using an option, but we haven't added support for such options in the default exporter. 

However, we won't add support for that option, as it's super straightforward to [replace the default exporter by one with the options you want](https://marmelab.com/react-admin/List.html#exporter). 

For reference, here is the default exporter code:

```tsx
import jsonExport from 'jsonexport/dist';

import downloadCSV from './downloadCSV';
import { Exporter } from '../types';

const defaultExporter: Exporter = (data, _, __, resource) =>
    jsonExport(data, (err, csv) => downloadCSV(csv, resource));

export default defaultExporter;
```

**Comment by tauqeer-trailfive** [comment]
Is anyone here how do guys solve this problem?
