### ISSUE TITLE
hide empty checkboxes, make them appear on-hover

### ISSUE THREAD

**Issue by certuna** [marmelab/react-admin#6224]
**Description**

In [Navidrome](https://demo.navidrome.org), which is based on react-admin, we are looking into ways to _hide unticked checkboxes_ in front of the list items unless the user hovers over them, for a cleaner UI look. Most of the time, users are not looking to multi-select items from this list, so showing a column of empty squares all the time feels redundant.

**Solution**

- See the demo site: https://marmelab.com/react-admin-demo/#/commands

![Screen Shot 2021-04-29 at 16 45 04](https://user-images.githubusercontent.com/62144283/116570117-49ed7d00-a90a-11eb-8c9f-530aabd97db3.png)

- Unchecked boxes would not be visible
- Similar to how the row now changes colour (white to light grey) on-hover, it would show the empty checkbox
- Checked boxes always show

If other RA users would like this feature as well, it make sense to contribute this to `Datagrid` in react-admin.

**Alternatives**

If this can't be a react-admin feature, we can add this as a customization in our own repo, which will deviate our codebase further from standard react-admin.

**Additional context**

Here's an example how this feature looks in another web UI with a list view, [Plex](https://plex.tv):

![Screen Shot 2021-04-28 at 10 10 23](https://user-images.githubusercontent.com/62144283/116567282-c468cd80-a907-11eb-8cbf-3179e5476814.png)

**Comment by fzaninotto** [comment]
Hi, great idea!

I think this can be already achieved in user land in three ways:

- by setting `rowClick="toggleSelection"` and using a custom field that shows a tick depending on the selected status
- by overriding the `checkbox` class to display it only on hover
- by passing a custom `row` element to a custom `body` element to the `datagrid`

However, none of these solutions are particularly straightforward, so I'd be interested in something easier. What API would you propose?

That being said, I'm afraid that

**Comment by Balaguru4580** [comment]
@fzaninotto The datagrid in react-admin right now seems to not offer a way to customise the default checkboxes column. 

It can be hidden using the `isRowSelectable` prop right now, but I don't see any further customization options besides that.

Since it is a default column, maybe there's a way to append a CSS class to it, akin to something like the Classname prop, but specifically for default columns like checkbox?  That would allow for a hover solution to be implemented easily.

>     * by overriding the `checkbox` class to display it only on hover

Unfortunately, I'm not sure I understand this. Did you mean the MUI checkbox class?  Looking through the documentation, I wasn't able to find anything about the `checkbox` class.

**Comment by fzaninotto** [comment]
So why don't you use the `isRowSelectable` prop to hide the default checkbox, and use a custom field as first child of Datagrid to handle your own selection UI?

**Comment by fzaninotto** [comment]
No news for some time, closing.
