### ISSUE TITLE
Nested Datagird

### ISSUE THREAD

**Issue by hani-ghazi-77** [marmelab/react-admin#6265]
I have a set of categories. Categories have type and child/parent relationships between them.

I'm trying to show a nested `expand` datagrid. 

please be mindful that the child/parent relationship is multi-levels (recursion is a must here) 

resource component
```javascript
<List
      exporter={false}
      bulkActionButtons={false}
      {...props}
    >
      <Datagrid
        optimized={true}
        rowClick="expand"
        expand={<SubCategory />}
        isRowExpandable={(row) => !!row.children.length}
      >
        <TextField source="name" />
        <DeleteWithConfirmButton />
      </Datagrid>
    </List>
```

SubCategory component 
```javascript
const SubCategory = ({ id, record, resource, ...rest }) => {
  const { data, loading, error, total } = useQuery({
    type: "getList",
    resource: resource,
    payload: { filter: { query: { parent: record.id } } },
  });

  if (loading) return <Loading />;
  if (error) return <Error />;
  if (!data || !record.id) return null;

  const temp = {};
  data.map((x) => {
    temp[x.id] = x;
  });
  const ids = Object.keys(temp);
  return (
    <Datagrid
      optimized={true}
      data={temp}
      resource={resource}
      ids={ids}
      total={total}
      isRowExpandable={(row) => !!row?.children?.length}
      expand={<SubCategory />}
    >
      <TextField source="name" />
    </Datagrid>
  );
};
```

is somehow working but net perfectly, since the `List` inject the data into the datagrid so if the `nested` datagrid has fewer records than its parent (even I'm passing the `data` and `ids`) it fills the difference in data size from the parent values.

any idea how to make the datagrid ignore its parent?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
