### ISSUE TITLE
pass a callback function to react-admin resource

### ISSUE THREAD

**Issue by maifeeulasad** [marmelab/react-admin#6304]
```

class Home extends React.Component{

    constructor(props) {
        super(props);
        this.state = {
            showModal : false
        }
    }
    ...

    render() {
        return(
            <div>
            ...

                <Admin theme={myTheme} dataProvider={myDataProvider} layout={MyLayout}>
                    <Resource title="Users" name="users" list={UserList}/>
                </Admin>
            ...
```
I want to pass a callback function with UserList, cause UserList has a button, when I'll press that, I want to show some modal.

In my UserList : 
```
export const UserList = (props) => (
    <List {...props}
          pagination={<PostPagination/>}
          actions={<NoneActions/>}
    >
```

**How can I pass a function to Resource-Component?** *I want to receive a callback function inside the props of UserList.*

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
