### ISSUE TITLE
Filter on nested object

### ISSUE THREAD

**Issue by swanyptx** [marmelab/react-admin#6332]
Hello !

I would like to filter with the "status".
This is what my member JSON looks like.
![image](https://user-images.githubusercontent.com/75628820/120798781-c68d0000-c535-11eb-98f2-6a68668e3d42.png)

I manage to access the id (7 in the example) and the filter work good when id == 7
![image](https://user-images.githubusercontent.com/75628820/120798914-f3411780-c535-11eb-9741-7877a8cb9c2e.png)

But, when I try to retrieve the "statut" of the member, it does not work.
![image](https://user-images.githubusercontent.com/75628820/120799345-85492000-c536-11eb-8621-c86305a60525.png)

You have an idea ?

Sorry for my english. ^^

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
