### ISSUE TITLE
Storing the ReferenceField value

### ISSUE THREAD

**Issue by yuvapoojary** [marmelab/react-admin#6369]
**Is your feature request related to a problem? Please describe.**
Suppose if I used `ReferenceField` in the datagrid, it usually fetches `name` or something and renders it, suppose if we want to render the same `name` in another place (in same page) rendered by the ReferenceField we have to make a another request to get the `name` .

**Describe the solution you'd like**
If react-admin able to put the ReferenceField's value in the redux state or somewhere, we can easily reuse the value instead of making another request.

**Describe alternatives you've considered**
Currently I have to make another request to get the name .

**Additional context**
Ex:
```
const PostList = (props) => (
  <List {...props}>
    <Datagrid>
      <ReferenceField source="user" reference="users">
        <TextField source="name" />
      </ReferenceField>
      <DeleteButton undoable={false} confirmTitle="Delete post made by the user {name}" /> // We have to make another request to get the name of the user even if we already fetched it
    </Datagrid>
  </List>
);
```

**Comment by oklas** [comment]
Take a look at `useRecordContext` [here](https://marmelab.com/react-admin/Fields.html)

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
