### ISSUE TITLE
Translate documentation into other languages

### ISSUE THREAD

**Issue by mxmvshnvsk** [marmelab/react-admin#6417]
Hello! It would be great to have translations of the documentation into other languages, in particular, several of my colleagues have raised a similar issue. If it really would be convenient, then was it possible to make this implementation?

**Comment by fzaninotto** [comment]
Hi,

Great idea!

However, having been confronted to this issue in the past (I'm a former Symfony contributor), I know that this requires two key assets for each language:

1. A native speaker of that language
2. With enough availability and dedication to translate 10 pages of doc updates every month

These assets are impossible to find. Even the Symfony project discontinued publishing translations in their website (cf https://symfony.com/blog/discontinuing-the-symfony-community-translations), and they're probably one of the biggest community of contributors. 

So our position about doc translations is:

1. You're free to publish a translation of the documentation anywhere you like. We don't want to be involved because we're not competent to review translations. Don't forget to show prominently the version of the doc you've translated, that it might not be the latest version available, and link to the original documentation
2. Just like with dataProviders, we'll link to third-party documentation sites in the documentation, but in the "Ecosystem" chapter (not via a language selector in the documentation)
3. If we discover that a third-party translation is lagging, we'll remove the link to it. 

My personal opinion is that if you want to contribute content in your language, you'll probably be more useful by publishing text or video tutorials.
