### ISSUE TITLE
Create stuck in endless loading

### ISSUE THREAD

**Issue by qeenking** [marmelab/react-admin#6476]
**What you were expecting:**
 submission should be success, and redirect to show

**What happened instead:**
 I'm stuck in endless loading when Create some post "contents" with REST API

there is no error, 200 ok response, and success to POST
but still in loading status, after receive 200 ok
so,there is no error massage just loading...
when I go to list manually, there is created new post every thing working in backend, but loading is not stop..
I try to use onSuccess, but onSuccess does not start
I guess submission is not end..

**Steps to reproduce:**

insert my dataprovider, extanding dataprovider ( I'm not sure which one is problem)
**Related code:**
 i have code [here](https://github.com/qeenking/admin-web)

**Environment**

* React-admin version:3.16.4
* Last version that did not exhibit the issue (if applicable):
* React version:17.0.2
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
