### ISSUE TITLE
The Content-Range header is missing in the HTTP Response. The simple REST data provider expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you ?

### ISSUE THREAD

**Issue by makozi** [marmelab/react-admin#6526]
I have an error when using react-admin. Please how do I resolve this issue?

**Comment by makozi** [comment]
`import React from 'react'
import { Admin, Resource, ListGuesser, fetchUtils} from 'react-admin'
import simpleRestProvider from 'ra-data-simple-rest'';
import UserIcon from '@material-ui/icons/Group';
import Dashboard from './components/Dashboard';


const httpClient = (url, options = {}) => {
  if (!options.headers) {
    options.headers = new Headers({ Accept: 'application/json' });
  }
  // add your own headers here
  options.headers.set('Access-Control-Expose-Headers', 'Content-Range');
  options.headers.set('Content-Range', 'posts 0-24/319');
  
     
  return fetchUtils.fetchJson(url, options);
}


const dataProvider= simpleRestProvider('http://api.com);

const App= () => (
  <Admin  dashboard={Dashboard} dataProvider={dataProvider}>
    <Resource name="alluser" list={ListGuesser}  icon={UserIcon}/>
    
    
  </Admin>
);
export default App;`

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
