### ISSUE TITLE
graphql connectOrCreate feature request

### ISSUE THREAD

**Issue by winner106** [marmelab/react-admin#6528]
## what I expected
I have a one to many model(eg: customers - orders), when I want to create a record in the ` orders table` , the logic is : " if  the customerId is exists, then  connect , else  create "

## I tried this , but failed

 ```js
const OrderCreate = (props) => (
  <Create {...props}>
    <SimpleForm>
      <ReferenceInput label="Product Name" source="product" reference="Product">
        <SelectInput optionText="name" />
      </ReferenceInput>
      <ReferenceInput source="customer.connectOrCreate" reference="Customer" label="Email" filterToQuery={(searchText) => ({ email: searchText })}>
        <AutocompleteInput optionText="email" />
      </ReferenceInput>
      <NumberInput source="permitUsers" label="permitUsers" initialValue={3} />
      <DateInput source="orderDate" label="orderDate" initialValue={new Date()} />
    </SimpleForm>
  </Create>
);
```
the browser request `payload`:

![image-20210820202851233](https://i.loli.net/2021/08/20/u68Ah3wrObvlPFR.png)

## my backend api service `connectOrCreate ` can work

![image-20210820201745011](https://i.loli.net/2021/08/20/QK7YJNFUXB2wrld.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by winner106** [comment]
`cool`
