### ISSUE TITLE
When clicking on list item url is updated but show view does not appear

### ISSUE THREAD

**Issue by ryanmstokes** [marmelab/react-admin#6559]
I have set up RA with graphql data provider and have set up the getOne data provider and its template, but when i click on an item in the list, the URL updates to for example 'projects/b723f868-801e-4b5e-9280-e4fd9fc771cf' , but nothing happens (e.g. the show view does not appear). When I add /show to the end of the URL I can see the show view for 2 seconds before RA redirects me back to the list view.

I saw this issue which seems to be very similar to mine, so I added an edit template to the <Admin> but I still have the same error.

I saw https://github.com/marmelab/react-admin/issues/4833

I have not set up the update dataProvider yet(which is associated to the edit view/template), is this necessary for show to work correctly?

Could you give me some insight to what may be causing this?

Thanks in advance!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by ryanmstokes** [comment]
Hi thank you, we fixed the the issue. Apologies for posting here!
