### ISSUE TITLE
GetMany/GetManyReference url length overload

### ISSUE THREAD

**Issue by luiscerqueira** [marmelab/react-admin#6725]
I'm having a problem with a use case using `ReferenceManyField`, `ReferenceArrayField` or `ReferenceArrayInput`.
Let's imagine the following data structure:`

```js
{
    id: '4ed7e23fce59270011c26ba7',
    user: 'Lorem Ipsum',
    posts: ['4ed7e23fce59270011c26ba7', '4ed7e23fce59270011c26ba7', ....]
}
```

Using `ReferenceArrayField` I am able to fetch and list all posts related to users, and use it in list, show and edit views.

Now, let's imagine that I have an array of posts that exceed 170 items. With my current dataprovider implementation (which is based on [this one](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-simple-rest/src/index.ts#L88)), the GET_MANY or GET_MANY_REFERENCE (called by the components specified above) methods will receive a huge list of ids, which will be injected into the url as query parameter.
Since each of these ids is 24 characters long, if we multiply it by 170, we will get a long URL of at least 4080 characters. This may exceed the http protocol limit for url length.

I tried using ReferenceManyField, which supports pagination. The results are actually paginated, but the query string has the same length, which makes sense as the list of ids is passed to the backend to be used to filter the data as a "where id in ()".

So my question is:
Is it possible to scale with this approache? Is there any other solution on how should we handle GET_MANY* for this type of use case?

**Comment by yelworc** [comment]
Stumbled upon this problem from a slightly different perspective: My API restricts the number of IDs that can be retrieved in one request (partly to avoid running into more obscure issues with URL length, but also just for performance reasons). So if there happen to be more distinct occurrences of some resource in a list view than that limit, the API request will fail and the user suddenly sees red exclamation marks instead of the expected data.

I can probably work around this in my data provider and split the query into multiple requests, but it feels like this should happen in RA core? `useGetMany` already accumulates and deduplicates IDs, and triggers multiple requests if the debounce time is exceeded…

**Comment by fzaninotto** [comment]
Thanks for resurrecting an old question that we forgot to address. 

React-admin doesn't make any assumption about how your server handles CRUD queries. It's the data provider's responsibility. If ra-data-simplerest doesn't fit your requirements, you can just fork it to change the way getMany requests are handled (e.g. by switching to POST instead of GET, or by splitting the query into several HTTP requests). 

In my opinion, there is no issue in the react-admin code - just some additional work that you have to do on your side.

**Comment by yelworc** [comment]
Thanks for the quick clarification, Francois :) 

After giving it some more thought, I agree with your assessment – the data provider translates RA's abstract CRUD queries into concrete HTTP requests, so that's the right place for this kind of logic. I just tried this in our (already heavily customized) REST provider, and it seems to be working fine.
