### ISSUE TITLE
dataProvider type extends

### ISSUE THREAD

**Issue by MartinJLee** [marmelab/react-admin#6739]
I am implementing custom dataProvider for react-admin. Because we have a number of data types, I thought of having separate resource providers to different files.

Please see the following link for the detail.

https://stackoverflow.com/questions/69718239/react-admin-dataprovider-type-extends

This could be generic typescript question.

It seems the issue is that the interface of `DataProvider` expecting to get `RecordType` which is extended from `Record`.

My data type `Transaction` is also extends from `Record`.

Although `RecordType` and `Transaction` are both extended from `Record`, `Transaction` cannot be assigned as `RecordType` because These are siblings not parent and child.

**Comment by panfiva** [comment]
That's typescript by design - it complains that it is expecting a return of a specific data types, but you might be returning another data type.

If you do not really care about type checking of returned data, you can just cast return data as `any` or use ts-ignore.

An alternative is to make your ResourceProvider implementation generic, and never use the generic part when calling functions from this data provider. I wish typescript had a mechanism to easily dealing with this issue; however that's the best i was able to find.


```ts

// your code
getList: async (params: GetListParams) => {...}

// suggested change; notice that we set R = Transaction by default, so that when you use data provider function, it knows that it returned Transaction
getList: async <R extends RaRecord= Transaction> (params: GetListParams):Promise<GetOneResult<R>>  => {...}

```

**Comment by MartinJLee** [comment]
@panfiva Thank you for the answer, I tried your suggested change. I'm not sure what i did wrong. It still throw similar error message. So I have updated to `ResourceProvider` interface as following
``` typescript
export type ResouceProvider = {
  getList: (params: GetListParams) => Promise<GetListResult<any>>;
```
