### ISSUE TITLE
[Question] Best way to refresh tokens in authProvider?

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6855]
I have spent days on this trying to figure out the best way to refresh tokens in the auth provider. I can't seem to figure out whether you should implement in checkError or checkAuth. I have tried setting it in checkError, but the checkAuth somehow runs during the checkError and I'm just getting so frustrated with it. Does anyone have a working authProvider example for a normal refresh token flow?

I have 3 localStorage items: `access_token`, `refresh_token`, `permissions` that get set on login.

Here is where I'm at now without the refreshing (I removed it all because it was getting confusing)

```js
checkError: (error: any) => {
    console.log("[AuthProvider] CHECK_ERROR");
    const status = error?.status;
    if (status === 401 || status === 403) {
      // If user is not authenticated check for refresh token
      if (status === 401) {
        if (error?.body?.title === 'Token expired') {
          // Refresh here //
        } else {
          localStorage.clear();
          return Promise.reject();
        }
      }

      // If user is not authorized for current route redirect to home
      return Promise.reject({redirectTo: '/', logoutUser: false});
    }

    return Promise.resolve();
  },
  // Called any time the user navigates to list, edit, create, or show
  checkAuth: () => {
    console.log("[AuthProvider] CHECK_AUTH");
    // Check if no previous authentication token
    const auth = localStorage.getItem('access_token');
    if (!auth) {
      return Promise.reject();
    }

    return Promise.resolve();
  },
```

Here is my server JWT if anyone happens to know .NET

```cs
options.Events = new JwtBearerEvents
{
    OnChallenge = async context =>
    {
        context.HandleResponse();

        if (context.AuthenticateFailure is SecurityTokenExpiredException ex)
        {
            var problemDetails = new ProblemDetails
            {
                Title = "Token expired",
                Detail = $"The token expired at '{ex.Expires.ToString(CultureInfo.InvariantCulture)}'",
                Status = StatusCodes.Status401Unauthorized,
                Type = nameof(SecurityTokenExpiredException)
            };
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
            await context.HttpContext.Response.WriteAsJsonAsync(problemDetails);
        }
    }
};
```

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by fzaninotto** [comment]
This is already scheduled for the next minor version, see https://github.com/marmelab/react-admin/pull/8574

**Comment by davidhenley** [comment]
Nice! Thanks @fzaninotto
