### ISSUE TITLE
SelectArrayInput optionText had been record if empty

### ISSUE THREAD

**Issue by ahmettetik** [marmelab/react-admin#6894]
Hello ,
Referance input have been use  in the SelectArrayInput. then SelectArrayInput had been record, if optiontext empty.

Help me?
                <ReferenceArrayInput
                      label="Key Item"
                      reference="keyitems"
                      source="keyItemIds"
                      filter={{ keyId__eq: formData.keyId }}
                      validate={[required()]}
                      className={classes.selectInput}
                      perPage={1000}
                      allowEmpty
                    >
   <SelectArrayInput optionText="keyData" optionValue="id" {...rest} options={{ onBlur: () => {} }}  />
                      
                    </ReferenceArrayInput>
![image](https://user-images.githubusercontent.com/12066748/142871723-e56eab1c-3ae5-4920-9a74-5b618fc2a3ba.png)

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
