### ISSUE TITLE
Table filters remove existing URL parameters

### ISSUE THREAD

**Issue by maxcorbeau** [marmelab/react-admin#6923]
**What you were expecting:**
When using table filters (https://marmelab.com/react-admin/List.html#filters-filter-inputs), table filters should be added to the URL without removing existing parameters (if any).

**What happened instead:**
Existing URL parameters are completely overwritten by the sole **displayedFilters** URL parameter

**Steps to reproduce:**
 - Create a resource with a table filter
 - Access its URL
 - Add some URL parameters
 - Use the table filter
 - Your URL parameters are gone

Before filtering, the URL already contains some params (foo=bar):
<img src="https://i.ibb.co/930s3ny/before.png"/>

After filtering, they are gone:
<img src="https://i.ibb.co/zbvSbdR/after.png"/>

**Why is this bad?**
Because effectively table filters prevent URL parameters from being used to customize app behaviour.

**Comment by djhi** [comment]
Thanks for reporting this!

**Comment by fzaninotto** [comment]
Using custom query params isn't a feature officially supported by react-admin, so I'm removing the bug tag for now. 

What do you use query parameters for in the list view?

**Comment by maxcorbeau** [comment]
Hi Francois,

Not only in list view, but I make use of URL query params everywhere for 2
reasons:

   - **customize UX, save users lots of time with URL replay**: at any point
   admin users can bookmark a URL, and when they replay it they get exactly
   the same dashboard as they left it. For instance in the list view, for the
   same resource, users can select different grids (they all use the
   same underlying resources, but they display different columns and have
   different actions), and all the grid settings are stored as URL
   query params.
   - **save development time by making react-admin more dynamic**: being able
   to customize admin without writing more code logic. Eg I can have
   10 resources, and each 5 grids to view/act on that data differently. All
   those grids are generated using a generic List Renderer I created, so all I
   need to do is define the resources once, then all the grids are handled
   with JSON definitions (what columns to show, actions to take etc...). If
   users want 3 more ways to look at/interact with certain resources, I just
   extend my JSON and I'm done. I don't have to go through defining new
   resources, new menu items, new lists etc... It's all dynamic.

So in general if you guys could preserve existing URL query params instead
of overwriting everything it would make react-admin even more customizable
and powerful.

Many thanks,
Max

**Comment by fzaninotto** [comment]
thanks for your feedback. 

This is not something we'll implement in react-admin in the near future, as it would add a lot of complexity and serve only in a small number of cases. 

I advise you to use Custom pages to handle these query parameters as path parameters.

**Comment by mikhail-fedosenko** [comment]
Supporting this feature request.
I personally don't understand why instead of ovewriting the `search` param in react-router when changing filters you cannot keep current `search` value _and_ just ovewrite List-specific things (like pagination, filters, sortings).

Here:
`useListParams.ts`

```ts
navigate(
    {
        search: `?${stringify({
            ...tempParams.current,
            filter: JSON.stringify(
                tempParams.current.filter
            ),
            displayedFilters: JSON.stringify(
                tempParams.current.displayedFilters
            ),
        })}`,
    },
    {
        state: {
            _scrollToTop: action.type === SET_PAGE,
        },
    }
);
```

I couldn't find react-router "proper" way of getting current query param value (you could use the value from `useLocation` hook but it will trigger the deps in useCallback), so, probably, just reading `window.location`, parsing it into `URLSearchParams` and then merging with updated values (`filter`, `displayedFilters` and whatever is kept in `tempParams.current`).

**Comment by slax57** [comment]
@mikhail-fedosenko Can you tell us more about what use-case you have that would require passing extra parameters in the URL?
As you figured out yourself, adding this feature would bring some complexity, so we need to make sure the problems it solves are common enough to justify the added cost.

**Comment by mikhail-fedosenko** [comment]
@slax57 , well, don't have such example at hand.. But I remember once I noticed that List would overwrite my query param...
Now I'm trying to recall... most likely it was "return URL" parameter - in our Admin Appp we sometimes pass "return URL" to the next view, so it can render "Back" button. Back button will navigate the user to the original view.
Yes, if the target view is only accessible from a specific screen, we could "hardcode" navigation to that screen in Back button...
But sometimes the view can be accessed from different screens, so we need to pass smth that will let the target page know where the user came from...
I can also think of deep-linking approach, where you pass return URL as a query param.
In general, I just used `disableSyncWithLocation` in such places.
Also, if you want to pass some information to the target view via query param... (instead of navigation state that is kept only in memory) you won't be able to preserve it when using the List.

I should also note that I often use <List> component not as a standalone page, but often - nested in Tabs, e.g. Show view with tabs, some of them have Lists (I pass `disableSyncWithLocation`, `title={" "}` so that Title is not overwritten <=== hack :), wrap <List> with `<RecordContextProvider value={undefined}>` so the List doesn't take default values for filters from the record... one more hack :) ).
Why List here? Usually, it should be ReferenceManyField... but I need filters, quick search, etc and ReferenceManyField doesn't have this out-of-the box.

**Comment by fzaninotto** [comment]
Thanks for your feedback. 

For the use cases you describe (back button, return URL), you can achieve the same by wrapping your app in a Context provider filled with the original query parameter, or in session storage, and your buttons will use that context or storage instead of the URL, just like most e-commerce sites do. So, there is an escape hatch. 

As for using List in a Show view, that's indeed a hack - this component was specifically designed to be a page component. Please note that ReferenceManyField creates a ListContext, so you can use `FilterForm` and `FilterButton` in it (see e.g. [this story](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-fields-referencemanyfield--with-filter)).

So although I agree that preserving URL query parameters would be a nice to have, I don't see a compelling enough use case to justify the added complexity...

That being said, you can try and implement the feature in a branch. If the diff is small enough and there is no sign of side effect, we'll consider it.
