### ISSUE TITLE
Ability to override Resource's base path

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#6972]
**Is your feature request related to a problem? Please describe.**
I am trying to build a webpage that includes different tabs, and each tab has resource embedded (includes List, Show, Create and Edit features). I also want to make sure that URL for each tab aligns with page navigation structure to make it easier to users to understand and work with URL links. For example, I am building a search page that has 2 tabs:

- /search/retail_products
- /search/services

To be able to do this easily, I would like to be able to override basePath when registering a resource (currently it uses resource name as base path)

Example
```js
<Admin {...props} >
  <Resource name='products' basePath='/search/retail_products' show={Show} list={List} />
  <Resource name='services' basePath='/search/services' show={Show} list={List} />
</Admin>
```

**Describe the solution you'd like**
Provide ability to override basePath in `Resource` component

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by fzaninotto** [comment]
Hi, and thanks for your request. I'm challenging your need:

> I also want to make sure that URL for each tab aligns with page navigation structure to make it easier to users to understand and work with URL links.

URLs are less and less part of the visible interface in modern browsers, so we don't focus on allowing developers to customize them. 

React-admin makes all resources a root url by design, and this choice simplifies redirections, routing, etc. Changing this would open many more problems. 

So I'm -1 with this one. 

I advise you to use another separator in your resource names:

* `/search/retail_products` -> /`search_retail_products`
