### ISSUE TITLE
[Feature Request] I want to enable to get form or Field scheme in buildQuery for GraphQL Response

### ISSUE THREAD

**Issue by tkow** [marmelab/react-admin#6992]
I have been making buildQuery for ra-data-graphql as referring to ra-data-graphql-simple.
We want to create record with associated models at once request with same form and make it work as our resolver accept associated model parameter.

For example,

```tsx
<SimpleForm>
   //   ...modelA formInput
  <FormDataConsumer>
    {({
            formData, // The whole form data
            scopedFormData, // The data for this item of the ArrayInput
            getSource, // A function to get the valid source inside an ArrayInput
            ...rest
    }) => {
      return (
        <TextInput
          resource={'B'}
          defaultValue={formData.id}
          source={'b.a_id'}
          disabled
       />
    );
  }}
  </FormDataConsumer>
  <SelectInput
    source={'b.availability'}
    choices={selectBoxOptions(Availability)}
  />
  <SelectInput
     source={'b.status'}
     choices={selectBoxOptions(CheckStatus)}
   />
</SimpleForm>
``` 

But,  I notice that [ra-data-graphql-simple](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildGqlQuery.ts#L124-L135) don't have ability to  fetch related model field by GET_ONE method  as the link code says that it gets only id field. So, we can't fetch current value of associated model like b.availability, b.status of above example.

So I make original buildQuery function with slightly ra-data-graphql-simple modification and wanted field can be added to it 
except for Object Type field because it can be infinite repeated reference without knowing form structure. It is enough simple usage, but if we can get field structure or form structure  as arguments of GET_ONE method, we can automatically and correctly determine required field for frontend without infinite recursive parse because form structure definite depth. 

Unfortunately, as long as I know, react-admin don't provide form or field schema in buildQuery function though it's acquired via update or create params (It's not enough to fetch current form  values because GET_ONE or GET_MANY methods can't be passed params to specify schema).  So we want the way to access form or field structure from buildQuery function of dataProvider.

Is there way to achieve?
As I thought it, it may be good that [dataProvider function third arguments](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql/src/index.ts#L156) if possible.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by tkow** [comment]
@fzaninotto 

Sorry misunderstanding.
We do not need supports for this.We already realized the way our projects resolve this situation though it may not be so wise because now official library's dataProvider don't  have receiving form structure.
Mainly purpose is feature request of getting form or field structure from dataProvider if do so, graphQL data provider have  deterministic solution for generating client and have portability with less code.

But, it's okey, this features is not important for your users.

**Comment by fzaninotto** [comment]
What you ask is currently not possible in react-admin because the form renders *after* the dataProvider call is made. We would need to inspect the children of the Form to build a data stucture, then pass it to the dataProvider. [We've done that in the past](https://github.com/marmelab/ng-admin), and it lead us to a pitfall of complexity. 

Our current approach is a tradeoff, that works in most cases (and all of ours!), but I understand it doesn't work in your case. Sorry!

Your best bet would be to declare a second resource name, something like "augmented_user", and build the GraphQL query for that resource manually in the dataProvider.
