### ISSUE TITLE
Ability to set default options on resources, or the whole Admin, e.g. MutationMode

### ISSUE THREAD

**Issue by WilliamABradley** [marmelab/react-admin#7212]
**Is your feature request related to a problem? Please describe.**

It would be awesome to be able to set some defaults without having to create and passthrough replacement toolbars, e.g. if I want all resources to delete and update with the "pessimistic" mutationMode.

It would also be nice to be able to disable deletion for an individual Resource.

**Describe the solution you'd like**

```tsx
<Admin
        theme={Theme}
        history={history}
        options={{ defaultMutationMode: 'pessimistic' }}
        ...
```

```tsx
<Resource
    icon={MyIcon}
    name="My Resource"
    options={{ canDelete: false, mutationMode: 'pessimistic' }}
    list={ResourceList}
    show={ResourceShow}
    create={ResourceCreate}
    edit={ResourceEdit}
  />
```

**Describe alternatives you've considered**

Creating custom toolbars to remove buttons, or customise the behaviour the buttons, feels like work that could be avoided.

**Additional context**

**Comment by fzaninotto** [comment]
Hi, and thanks for your proposal.

this is somethiong we've already considered in the past, and decided not to implement. 

If you want a "variant" of the react-admin views, they are one click away:

```jsx
const PessimisticEdit = (props) => <Adit mutaionMode="pessimistic" {...props} />;
```

Then you can use these variants in your code instead of the react-admin ones. 

We don't want to add more complexity to the react-admin core to save 1 line of code. Besides, this would make learning react-admin more complex, while currently It's just React™.
