### ISSUE TITLE
How can I pass a ReferenceInput id in another ReferenceInput's filter?

### ISSUE THREAD

**Issue by ValchanOficial** [marmelab/react-admin#7236]
Hello, I'm trying to pass **exampleId** from Example as a filter to ExampleTwo, how can I do this?

        <ArrayInput source="list">
          <SimpleFormIterator>

            <ReferenceInput source="exampleId" reference="Example">
                <SelectInput optionText="name" />
            </ReferenceInput>

            <ReferenceInput source="exampleIdTwo" reference="ExampleTwo" filter={{ id: exampleId }}>
                <SelectInput optionText="name" />
            </ReferenceInput>

          </SimpleFormIterator>
        </ArrayInput>

I'm trying to wrap in a Component using useState to get id onChange, but when I do it, this happen: **resources.undefined.fields.exampleId**

```
const MyComponent  = () => {
  const [exampleId, setExampleId] = useState(null);

  const handleOnChange = (e) => setExampleId(e.target.value);

  return (
          <SimpleFormIterator>

            <ReferenceInput source="exampleId" reference="Example" onChange={handleOnChange}>
                <SelectInput optionText="name" />
            </ReferenceInput>

            <ReferenceInput source="exampleIdTwo" reference="ExampleTwo" filter={{ id: exampleId }}>
                <SelectInput optionText="name" />
            </ReferenceInput>

          </SimpleFormIterator>
  )
} 
```

        <ArrayInput source="list">
          <MyComponent />
        </ArrayInput>

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
