### ISSUE TITLE
Authenticated resources show before Login page

### ISSUE THREAD

**Issue by cuong-nguyen** [marmelab/react-admin#7389]
**What you were expecting:**

Authenticated resources should not appear if user is not authenticated

**What happened instead:**

Authenticated resources are showed before Login page
Due to authentication flow we're using in our app, we need to make `logout` async function, then `await` for some async operations. This leads to this bug (maybe)

**Steps to reproduce:**

https://codesandbox.io/s/cool-sound-w7xq3i?file=/src/App.js
1/ Change url path to `/users` then press Enter
2/ Users list page shows up for a second there then page is redirected to /login

**Environment**

* React-admin version: **4.0.0-beta.2**
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by cuong-nguyen** [comment]
Workaround I have for our app right now is move the `async` op out of `logout` method
```
const logout = useLogout();
//...
const handleLogout = async () => {
  await ...
  logout();
}
```

Then there's nothing left for `logout` to handle so it becomes
```
logout: () => Promise.resolve()
```
Which looks a bit weird!

**Comment by CampingPanda** [comment]
The fact that your back end API responds with the resources without valid authentication is an issue, this should never happen.
https://marmelab.com/react-admin/Authentication.html#sending-credentials-to-the-api
Send your credentials with the request, and check if the requester is allowed for the resource that it is requested.
Otherwise decline the request, and React Admin should invalidate the authentication token depending on your AuthenticationProvider class. Never send data that the requester is not allowed to see.

I can probably just send requests to your back end API at the moment and still get the resources entirely ignoring your React Admin application.

**Comment by fzaninotto** [comment]
As explained by @CampingPanda, the problem lies in your API: it doesn't require authentication. That means that even if the react-admin app properly checks the credentiels client-side, any attacker can read the data by calling yiour API directly. This is not an authentication scheme supported by react-admin, and we strongly suggest that you secure your API server-side.

**Comment by cuong-nguyen** [comment]
Hmm. This has nothing to do with API not being protected on server. I am talking about for some reason, make `logout` async function and **await** for some operation to finish before logging out, e.g. call API endpoint to revoke access token. This makes the authenticated page show up for a second or two then Login page shows up. You can follow Step to reproduce to see what I am referring to.

Seems like people run into same thing https://stackoverflow.com/questions/62383779/how-to-prevent-flash-of-dashboard-content-while-unauthenticated-in-react-admin
