### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'breakpoints')

### ISSUE THREAD

**Issue by Santhosh00009** [marmelab/react-admin#7497]
**What you were expecting:**

It must render the List component and i need to get the test status as passed so that I could write the test scenarios for the complete React-admin project but for the below syntax its getting failed in the steps to reproduce section.
For the above mentioned syntax i'm trying to write test cases for my project by using react testing library and jest but every time i'm trying the way to write the test cases for List,create,edit and all the react-admin project dependencies i'm getting the error as below 

```
console.error
    Material-UI: The `query` argument provided is invalid.
    You are providing a function without a theme in the context.
    One of the parent elements needs to use a ThemeProvider.
 at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

**Steps to reproduce:**

```
     describe("List", () => {
          it(" ", () => {
              render(
                  <Admin dataProvider={dataProvider}>
                        <List />
                  </Admin>
      );
  });
 });
    <Admin dashboard={Dashboard} dataProvider={dataProvider} history={history}>
        <App/>
    </Admin>
```

This is how the Admin is beings configured and i have replicated all the steps that are mentioned in the react admin tutorial and created the project.
I need to now how to fix the error that i mentioned and what are the basic requirements for the ThemeProvider for the react admin projects 
If possible kindly share if you they are any other source for testing the react-admin based projects or any sample projects which has test cases

**Environment**

* React-admin version:3.19.5
* mui/material version: 5.3.0
* Last version that did not exhibit the issue (if applicable):
* React version:17.x
* Browser:chrome
* Language: Typescript
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi there!

I'm not sure I understood your issue correctly, because the layout is a bit messed out and the code provided seems a bit incomplete.

Anyhow, I believe your issue is about how you can test your Admin component.
To achieve this you can use the `<AdminContext>` component, as documented here: https://marmelab.com/react-admin/doc/4.0/Upgrade.html#tests
This should solve your ThemeProvider error.

Also, please note that the GitHub issues are for bugs and feature requests only (see [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md)).
If you need further support for writing your tests, you can either ask your question on [StackOverFlow - react-admin](https://stackoverflow.com/questions/tagged/react-admin), or subscribe to the Professional support (see [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support)) to get access to the Professional Support service.

**Comment by fzaninotto** [comment]
Hi, 

The error message is explicit: you must wrap your code with a MUI ThemeContext. React-admin includes one by default, you must add one manually in your tests.

See e.g. https://github.com/marmelab/react-admin/blob/c001779ea47a1d8d5cf1f5da07dfd6e17708b9b8/packages/ra-ui-materialui/src/button/CloneButton.spec.tsx#L34
