### ISSUE TITLE
What is your tracking for (react-admin-telemetry)?

### ISSUE THREAD

**Issue by joaobispo2077** [marmelab/react-admin#7511]
I started using your solution in a project and I noticed that there is a request for https://react-admin-telemetry.marmelab.com/react-admin-telemetry?domain=MY_DOMAIN. 

I have some compliance issues...

So, I was curious what this is for built into the react-admin 3.19.10 public package. I didn't find anything in the docs about this. Is there any way to remove this tracking?

**Comment by WiXSL** [comment]
Yes, you can prevent that call.
https://marmelab.com/react-admin/Admin.html#disabletelemetry

**Comment by flaviut** [comment]
I hope you'll consider a difference stance here. Telemetry in an open-source library without explicit consent is simply not something that is done.

Seeing a surprise HTTP request to your servers just makes me wonder about what else you may decide to send to your servers in the future. The fact that you're only doing this in production and the flag is buried in the documentation is worse, since it looks like you're actively trying to avoid it being discovered.

If you insist on keeping this, it ought to be a required "telemetry={true|false}" so the developer can make an informed decision.

> The only data sent to the telemetry server is the admin domain (e.g. “example.com”) - no personal data is ever sent, and no cookie is included in the response. The react-admin team uses these domains to track the usage of the framework.

this omits that this information can be used to obtain a rough user count, as well as the geographic location of those users. it's obvious to me, but other folks might not realize this to make an informed decision.

**Comment by fzaninotto** [comment]
Our telemetry cannot be used to get the geographic location of users. Again, we don't collect IP addresses, just the requested domain. 

I understand you concerns. But we need the telemetry to make react-admin sustainable. Besides, we document the way to disable it both in the docs and in the response of the telemetry request. So we won't take it away.

If you think this is not acceptable, I'm sorry to disappoint you, but you're free to use another library.

**Comment by hubciorz** [comment]
@fzaninotto 

The current telemetry implementation raises significant GDPR compliance concerns. While only domain names are reportedly collected, there's no transparent documentation about data processing, retention, or geographical tracking potential. The default opt-out mechanism buried in documentation contradicts privacy best practices. Explicit, informed consent should be required, with clear communication about what data is collected and why.

**Comment by fzaninotto** [comment]
Again, no personal data is collected. GDPR is about personal data, so is not relevant here. You mention "best practices", but this is only your point of view, and it's not binding anyone in any way. We don't think our telemetry is abusive as it's documented and can be disabled in one click. Even the HTTP response of the telemetry server is explicit about that.

I'm locking this issue because I don't want to repeat the same things over and over again.
