### ISSUE TITLE
ReferenceInput with AutocompleteArrayInput drops entries, flickers and doesn't seem to work

### ISSUE THREAD

**Issue by vespasianvs** [marmelab/react-admin#7529]
**What you were expecting:**
I have a ReferenceInput which gets user details from the server with an AutocompleteArrayInput inside it using email as the option text. Adding the first two users works fine, calls go to the server as I type to search for the necessary data and the autocomplete box works fine and shows me entries. Adding two users works fine, but it's when I try to add a third user it goes wrong...

**What happened instead:**
As soon as I start trying to add a third user it starts to go wrong. Firstly, entries already added start flickering and disappearing and I get a Warning in the dev console:

```
MUI: The value provided to Autocomplete is invalid. None of the options match with <the user object already added>
```

The autocomplete also fails and just shows all of the entries that it already has as the characters that I typed seem to have been removed.

**Steps to reproduce:**
Using the code sandbox below, go to Create Post in the UI and try to add more than two users to the user array input.

**Related code:**
https://codesandbox.io/s/intelligent-galois-jp555s?file=/src/posts/PostCreate.tsx

```
<ReferenceInput source="users" reference="users">
  <AutocompleteArrayInput optionText="email" />
</ReferenceInput>
```

**Other information:**
Not sure how to go about fixing this...but let me know if there is anything I can do. I am able to help out here, but I can't figure this one out on my own at the moment otherwise I'd have done a PR for you already :)

**Environment**

* React-admin version: v4.0.0-rc.1
* React version: 17.0.2
* Browser: Edge

**Comment by vespasianvs** [comment]
I've realised that I can switch things around and use ReferenceArrayInput -> AutocompleteInput.

However, the docs suggest that what I have done above should work: "even with the component of your choice, provided they detect a ChoicesContext is available and get their choices from it." - AutocompleteArrayInput takes ChoicesContext

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.

Actually, I believe the correct way to do it would be ReferenceArrayInput -> Autocomplete*Array*Input rather than ReferenceArrayInput -> AutocompleteInput. It is also what is suggested in the docs here: https://marmelab.com/react-admin/doc/4.0/ReferenceArrayInput.html#usage
ReferenceInput is for selecting a single reference as input, while ReferenceArrayInput is for selecting an array of references as input (which is what you are doing in your example).
Both need to expose a choice context to child elements to work, but the difference is in how many references you want to select: one or many.
So using ReferenceInput is not meant to work as you expected. It only works with inputs selecting a single value.

Maybe we could try to detect this programmatically and raise a warning, but that would be an enhancement.
Closing for now, unless someone think this should really be done (I'm still open to discussion on this matter 🙂 )

**Comment by slax57** [comment]
I am not sure I understand correctly what is troubling you. Are you suggesting the docs should mention not to use AutocompleteInput in addition to recommend using AutocompleteArrayInput?
Could you provide a PR with the change you suggest? That would allow me to see clearly what you have in mind.
(If you are willing to provide a PR I'll reopen this issue of course)
