### ISSUE TITLE
DateTimeInputs not working correctly as Filters

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7540]
**What you were expecting:**
DateTimeInput components to work correctly as list filter components

**What happened instead:**
Month and date/time values do not register properly when values change, and often reset entirely while picker is active.

**Steps to reproduce:**
Add a DateTimeInput as a Filter component, then try to use the date picker to select a value.

**Related code:**
https://codesandbox.io/s/cool-sound-pdlsh4 Check the published_at filter on the Posts list view.

**Environment**

* React-admin version: 4.0.0.
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment]
Reproduced. Thanks for the report!

**Comment by WiXSL** [comment]
I don't think this is a bug.
The problem is that you are trying to filter a date value with a datetime filter

**Comment by WiXSL** [comment]
The problem is in the `getFilterFormValues` return value, if a field is a Date, and has a `parse` function that returns a date (this is why it happens by default in DateTimeInputs and not in DateInputs), its value gets treated like a regular object, and ends up returning an empty object for that field, instead of the string representation of the date
