### ISSUE TITLE
"Using React-Admin In A Sub Path" does not work

### ISSUE THREAD

**Issue by hjr3** [marmelab/react-admin#7564]
**What you were expecting:**

Following the instructions for [Using React-Admin In A Sub Path](https://marmelab.com/react-admin/Routing.html#using-react-admin-in-a-sub-path), I expected my react-admin application to be served under the http://localhost:3000/admin. I also expected the links in menu to include "/admin" as a prefix.

**What happened instead:**

My react-admin application shows the Not Found page when browsing to http://localhost:3000/admin. The links in the menu do not include the "/admin" prefix.

**Steps to reproduce:**

Start from my modified demo app that includes BrowserRouter and basename: https://github.com/marmelab/react-admin/compare/master...hjr3:basename-broken

```bash
$ cd /path/to/your/react-admin/examples/demo
$ npm run start
```

Go to http://localhost:3000/admin and you will see the Not Found page instead of the dashboard UI.

**Other information:**

I also tried using the deprecated [history](https://marmelab.com/react-admin/Admin.html#history) approach and that did not work either.

**Environment**

* React-admin version: v4
* Last version that did not exhibit the issue (if applicable): v3
* React version: ^17.0.0
* Browser: Chrome (latest)

**Comment by slax57** [comment]
Hi!
Thank you for submitting this.
Actually, setting the `basename` in your `<Admin>` component only helps to get the links right (when you click on items from the menu for example). You still need to tell your external Router that your admin app is inside the `/admin` path.
Here is a codesandbox with a working example (note I have replace `BrowserRouter` with `HashRouter` because it's not compatible with codesandbox): https://codesandbox.io/s/objective-pine-1r59vq?file=/src/index.tsx:244-254
You need to navigate to https://1r59vq.sse.codesandbox.io/#/admintest/posts

Still, I agree the doc needs to be improved to make this clear.
I'll tag this as a doc improvement issue.

**Comment by Ali00Naghiloo** [comment]
> Hi! Thank you for submitting this. Actually, setting the `basename` in your `<Admin>` component only helps to get the links right (when you click on items from the menu for example). You still need to tell your external Router that your admin app is inside the `/admin` path. Here is a codesandbox with a working example (note I have replace `BrowserRouter` with `HashRouter` because it's not compatible with codesandbox): https://codesandbox.io/s/objective-pine-1r59vq?file=/src/index.tsx:244-254 You need to navigate to https://1r59vq.sse.codesandbox.io/#/admintest/posts
> 
> Still, I agree the doc needs to be improved to make this clear. I'll tag this as a doc improvement issue.

the links are out dead, can you give me some fresh examples?

**Comment by fzaninotto** [comment]
https://marmelab.com/react-admin/Routing.html#using-react-admin-in-a-sub-path
