### ISSUE TITLE
204 HTTP Status is handled as an error

### ISSUE THREAD

**Issue by JasonStrazisar** [marmelab/react-admin#7569]
**What you were expecting:**
Have the dataProvider working with 204 http status on delete.

**What happened instead:**
When using the useDelete hook, the api return a 204 No Content status (using api-platform).
But the React-Admin dataProvider handle this as an error and throw a httpError : 

<img width="1082" alt="Capture d’écran 2022-04-20 à 07 54 18" src="https://user-images.githubusercontent.com/59898438/164235635-0321030a-e6b7-4bc2-b2f5-df64b86cb8ca.png">

**Related code:**
This is a sample of the code that use the useDelete hook from React-Admin.

```
  const deleteNode = useCallback(() => {
    deleteOne(activeRecordType, activeRecord.id, activeRecord, {
      onSuccess: () =>
        handleSuccess("ra.notification.deleted", activeRecordType),
      onFailure: (error) => handleError(error),
    });
  });
```

**Other information:**

**Environment**

* React-admin version: **3.19.10**
* React version: **17.0.2**
* Browser: **Chrome / Firefox**

**Comment by slax57** [comment]
Hi!
React Admin actually makes no assumptions regarding the HTTP status codes, this is the responsibility of the `dataProvider`. Same thing goes when you use the `useDelete` hook, it delegates the error detection to the `dataProvider`.
Since you are using api-platform, you are probably using their dataProvider and as such, you will have to open your issue there.
