### ISSUE TITLE
Format of source returned from `getSource` has changed

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7573]
In previous versions of React Admin, when evaluating code like the following:

```
<ArrayInput source="authors">
  <SimpleFormIterator>
    <FormDataConsumer>
      {({ formData, scopedFormData, getSource, ...rest }) => {
        return scopedFormData && scopedFormData.user_id ? (
          <SelectInput
            source={getSource("role")}
            choices={[
              {
                id: "headwriter",
                name: "Head Writer",
              },
            ]}
            {...rest}
            label="Role"
          />
        ) : null;
      }}
    </FormDataConsumer>
  </SimpleFormIterator>
</ArrayInput>;
```

I would expect `getSource("role")` to return the following: `authors[0].role`, as this was the value that `getSource` would have returned in v3. Instead we get `authors.0.role`. 

You can replicate this by inspecting the console logs in the following [CodeSandbox](https://codesandbox.io/s/divine-cookies-f0e60p?file=/src/posts/PostCreate.tsx).

If this is intentional, due to the change of the underlying form library, then it should be acknowledged in the upgrade notes. Otherwise it seems like a bug.

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi!
Thanks for submitting this.
I believe it's intentional, since it's the naming convention expected by [react-hook-form](https://react-hook-form.com/api/usefieldarray).
I'm not really sure this needs to be emphasized this much in the migration guide, since we only say that `getSource` is "a function which will translate the source into a valid one for the ArrayInput", and this remains true.
[This line](https://github.com/marmelab/react-admin/blob/master/docs/Inputs.md?plain=1#L234) however is wrong and needs to be updated.
But maybe I'm missing the point, could you explain to me why this is a big deal to you?

**Comment by andrico1234** [comment]
Thanks for the quick response! It's not too problematic on our end, we just noticed that some tests started failing because of the format changing. I wanted to flag incase this was a bug. Happy to close this 😄
