### ISSUE TITLE
Article with pictures in one field <RichTextInput>

### ISSUE THREAD

**Issue by maymurov** [marmelab/react-admin#7590]
I'm making a knowledge base in React Admin. I ran into a problem, please help.
Creating an article means editing the text (HTML) in one field and uploading pictures to the text itself. But in <RichTextInput> it is not possible to insert pictures.
Logically:
- we have to load a picture into the field with drag and drop.
- it should be uploaded to our server
- a link to this image is automatically recorded in the CMS and on the knowledge base site
Is it possible to do this with standard React Admin tools and how? And if not, what is the best way to implement the knowledge base for react admin?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
