### ISSUE TITLE
Documentation has v4 hardcoded

### ISSUE THREAD

**Issue by ybrodsky** [marmelab/react-admin#7663]
**What you were expecting:**
1. That if I select the version 3.x it's remembered the next time I go into the docs
2. That if I select the version 3.x and I use the search box the results don't redirect me to the version 4 docs

**What happened instead:**
1. Every time you access the docs the default v4 docs is loaded, even if you previously selected something else
2. You are in the 3.x docs, you search something and you are taken to the v4 results

**Steps to reproduce:**
1. Change the version, refresh the page
2. Change the version, search something and click a result

**Environment**
irrelevant

Since updating to the v4 is not a walk in the park, this might be something worth fixing. Thank you.

**Comment by slax57** [comment]
Hi!

Unfortunately, there is not much we can do about both these issues 🙁.
1. Regarding the first one, I recommend adding a v3 documentation page as a browser's favorite, so that you can access v3 directly
2. Regarding the second issue, this is a limitation of the search engine we are using (Algolia). You can work around this by using your browser to search through the [Reference page](https://marmelab.com/react-admin/doc/3.19/Reference.html) to access the doc of the component yielded by Algolia. You can also checkout the v3.x branch of the react-admin repository (which contains all the docs in md files), and search in the doc folder using the git grep command. 

Hope this helps a bit
