### ISSUE TITLE
`sort` props doesn't sort in `<ReferenceArrayInput>`

### ISSUE THREAD

**Issue by DjebbZ** [marmelab/react-admin#7668]
**What you were expecting:**
Using the `sort` props of `<ReferenceArrayInput>` works as expected, referenced data is sorted once fetched.

**What happened instead:**
Whatever I put in the `sort` props of the `<ReferenceArrayInput>` component is not taken into account, and it still filters the content by id.

The only difference I noticed is that by default, it sorts the referenced content by `id` DESC, and when I use the sort option it sorts by `id` ASC.

**Steps to reproduce:**
Use the `sort` props of the `ReferenceArrayInput`

**Related code:**
View the code of the reproduction repository forked from the `simple` example in this PR (in order to have a simple and nice diff) https://github.com/marmelab/react-admin/pull/7666/files

**Environment**

* React-admin version: latest 3.x & 4.x

**Comment by DjebbZ** [comment]
(Mentionning a team-mate so that he can follow the issue @zaruus)

**Comment by slax57** [comment]
Hi!
I believe the problem actually comes from the dataProvider rather than from the ReferenceArrayInput component.
Indeed, when you look at the console, you can see that the sort options are properly passed down to the dataProvider:
```
getList tags {"pagination":{"page":1,"perPage":25},"sort":{"field":"name.en","order":"ASC"},"filter":{}}
```
The tags are not sorted correctly probably because the fake rest provider we use in this demo does not support sorting on this field.
This is something we can confirm by changing the List of the "tags" resource to ListGuesser, and trying to sort on the "Name.en" column: https://codesandbox.io/s/blissful-rgb-8kz7sl?file=/src/tags/index.tsx

By the way, sharing the code reproducing the issue is a good practice (and we thank you for it), but it's better for us if you use a codesandbox for that purpose rather than open a PR, since it's not an actual fix.
Cheers.
