### ISSUE TITLE
The validate errors message are not display when passed as translatable object

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#7690]
**What you were expecting:**

With a the following simple `validate` function:

```typescript
validate={() => ({
    body: {
        message: 'ra.validation.minValue',
        args: { min: 42 },
    },
})}
```

I should have the translation of the `ra.validation.minValue` key with the `min` argument correctly placed.

Related doc: https://marmelab.com/react-admin/Form.html#validate

**What happened instead:**

The error is not displayed on the input help section.

Note: works with string only error keys.

**Steps to reproduce:**

1. `make install run-simple`
2. Go to http://localhost:8080/#/comments/create
3. Submit the form regardless the data you put on it
4. Submit

https://github.com/pocivaneuh/react-admin/pull/1

**Other information:**

**Environment**

* React-admin version: 4.0.3
* React version: 18

**Comment by slax57** [comment]
Reproduced, thanks!

Looks like there is something wrong with the [getSimpleValidationResolver](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/getSimpleValidationResolver.ts)

Possible workarounds in the meantime:
- use this validation method at the field level rather than at the form level
- do the translation manually using useTranslate and use this as string only error key
