### ISSUE TITLE
Validation of TextInput and NumberInput not working the same way

### ISSUE THREAD

**Issue by jmConan** [marmelab/react-admin#7729]
**What you were expecting:**
I expect validation to work on all input the same way. 

**What happened instead:**
`NumberInput` does not react to validation the same way as the other Inputs do. 
Error Messages are not set on them, infact the validation function itself given to the `Form` via `validate={validateUpdateServerSide}` is not run on them if you manipulate the `NumberInput`. 
**No Event Listener is run or propagated to react-hook-form handlers.** 
(Tested for onChange, onBlur)

Global Validation in an onSubmit() is validated in all inputs.

**Environment**
* React-admin version: 4.1.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.x.x
* Browser: Chrome v101
* Stack trace (in case of a JS error):

**Comment by megantaylor** [comment]
there **is** something weird about number input validation. i'm having some trouble reproducing it in the CodeSandbox for v4 though, because it seems like `mode="onBlur` on SimpleForm isnt working there either.

https://codesandbox.io/s/pensive-resonance-16nco7?file=/src/posts/PostCreate.tsx

however, in my app, the onBlur mode works, and if i use a TextInput with `validate={required('Required field')}`, it gets validated on blur and i see the error message and error styling on the input. if i use a NumberInput with `validate={required('Required field')}`, it doesnt get the error message or styling.

a workaround is to use a TextInput as a number input, as described here: https://marmelab.com/react-admin/NumberInput.html#usage-in-filter-form

**Comment by fzaninotto** [comment]
@davidhenley can you please provide a link to a repro?

**Comment by jmConan** [comment]
fixed by #7992

**Comment by davidhenley** [comment]
Wow, that was easy. Good eye! Thanks guys
