### ISSUE TITLE
SelectArrayInput inside ReferenceArrayInput styling is incorrect [4.1.0]

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#7748]
![Screen Shot 2022-05-23 at 3 36 56 PM](https://user-images.githubusercontent.com/15056748/169901888-188bcd33-f6c6-4dbb-9d0c-2aeb71dd7be9.png)

Happens in Create and Edit. Width is wrong and label is cut off.

```html
<TextInput source="email"/>
<TextInput source="rosaKey"/>
<ReferenceArrayInput reference="roles" source="roles">
  <SelectArrayInput optionText="id"/>
</ReferenceArrayInput>
```

**Comment by davidhenley** [comment]
AutocompleteInput styling is the same way.

**Comment by slax57** [comment]
Hi!
I can't reproduce your issue on the simple example, even by adding `variant="outlined"` to the components.
Can you please provide a codesandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple reproducing the issue?

**Comment by slax57** [comment]
Hi, and thank you for the reproduction case.
This happens because your custom theme completely overrides the theme defined by react-admin for its components.
With v4, you need to extend the default theme rather than override it, [as stated in this section of the migration guide](https://marmelab.com/react-admin/Upgrade.html#custom-themes-must-extend-defaulttheme).
That should fix your problem 🙂

**Comment by davidhenley** [comment]
@slax57 that wasn't my problem though. The problem is the widths and paddings are different even without the theme. It's reproduced in that link I sent. Just remove the theme and they are still messed up.
