### ISSUE TITLE
AutocompleteInput does not respect createLabel prop

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#7822]
The createLabel text and selection is missing in version 4.1.3. It is showing correctly on SelectInput but not AutocompleteInput even though it is documented on the AutocompleteInput docs.

https://marmelab.com/react-admin/AutocompleteInput.html

```
The label for the menu item allowing users to create a new choice. Used when the filter is empty
```

**The end of this list should show "Create New Type" when no input is put in**

![Screen Shot 2022-06-13 at 2 27 31 PM](https://user-images.githubusercontent.com/15056748/173429726-2d88fd5a-c9c5-4a49-a486-5a0d6da9222b.png)

```html
    <ReferenceInput source="typeId" reference="customer-types">
      <AutocompleteInput
        source="name"
        createLabel="Create New Type"
        createItemLabel="Create %{item}"
        create={<SimpleCreate resource="customer-types"/>}/>
    </ReferenceInput>
 ```

**Comment by slax57** [comment]
Hi,
Thanks for reporting this!
I reproduced, however, I'm unsure how to qualify this.
Currently the `AutocompleteInput` component only adds the Create option after you enter a filter query, and if the filter does not match exactly with one of the options. I guess the philosophy is different from a `SelectInput`. With an `AutocompleteInput`, you expect the user to search for the pre-existence of the item before allowing the creation of a new one.
But I guess this could be debated.

- If it is confirmed this is the expected behaviour, we'll need to update the docs
- If this behaviour is not desired (and we wish to be able to add items at all times) then this is an enhancement we'll need to implement

I'll request the team's pov.

**Comment by slax57** [comment]
Related code: https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L387

**Comment by davidhenley** [comment]
I would debate at least for our purposes that AutocompleteInput should have createLabel, because sometimes we know that we need to add one on the fly before even searching.

**Comment by davidhenley** [comment]
Nevermind on the create prop. I fixed the documentation. It was incorrect.

https://github.com/marmelab/react-admin/pull/7833

**Comment by davidhenley** [comment]
@slax57 Could I ask why this is so much harder to implement than the SelectInput? What are the pain points? I'm trying to look at both to get a better feel for the CreateSuggestionContext.

**Comment by slax57** [comment]
@davidhenley It's no really that it would be hard to implement, but rather that this component already handles many props for many cases, and we fear that adding one more would make it too confusing.

Actually we thought of adding a prop like `shouldAllowCreate` or something in this taste to handle this, but we gave it up for the reason I mentioned.

Still, if you disagree with us, please let us know here, we might change our minds about this :sweat_smile:

**Comment by davidhenley** [comment]
So my 2 cents is create/createLabel is much more important to have on AutocompleteInput than SelectInput.

If you are using SelectInput to create new items often enough to have an on-the-fly create prop, that list will definitely grow too large for the SelectInput and you need to eventually change it out to an AutocompleteInput.

**Comment by slax57** [comment]
> So my 2 cents is create/createLabel is much more important to have on AutocompleteInput than SelectInput.
> 
> If you are using SelectInput to create new items often enough to have an on-the-fly create prop, that list will definitely grow too large for the SelectInput and you need to eventually change it out to an AutocompleteInput.

Closing this after merging #7844 was intended, since, after internal discussion with the team, we agreed that it would be best not to add complexity to the component, and only improve the docs for this use case.

However, I agree that you make a good point here.

Best I can do is request the opinion of @fzaninotto and @djhi , which are more experience than me with RA, and hence I consider to have a more valuable opinion than mine :grin: 

If you wish, you may also work on a PR to add this, which may convince us that the complexity is manageable, but I can't promise we will accept it :sweat_smile:

**Comment by davidhenley** [comment]
@slax57 we still really need this functionality. I just don't understand why it used to work, but then was taken away. This is such a trivial feature that made it very clear that you can create new items.
