### ISSUE TITLE
How to use react-hook-form and default TextInput of react-admin?

### ISSUE THREAD

**Issue by idehweb** [marmelab/react-admin#7824]
Hello, I made a single page for edit and creating configuration of my app. I can not use useForm or register to handle default TextInput of react-admin, if I use '<input>' I can, but default TextInput is not managing. I am using last version of everything. react-admin, react-hook-form, react and nodejs are last version by this time.
I used many variation type of code, nothign is working with default TextInput of react-admin 
`
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Form,TextInput} from "react-admin";
const Configuration = (props) => {
  const { register, handleSubmit,formState: { errors } } = useForm({
    defaultValues: { title: "x", email: "", password: "" }
  });
 return (
 <TextInput
                autoFocus
                fullWidth
                label={translate("resources.settings.title")}
                source="title"
                disabled={loading}
                defaultValue={title}
                {...register("title")}
                onChange={(event) => {
                  handleChange(event);
                }}
              />
 )
`

when I use useWatch imported from react-hook-form, then I get error: Cannot read properties of null (reading 'control')

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
