### ISSUE TITLE
Add Join query string parametrs to Resource

### ISSUE THREAD

**Issue by chattago2002** [marmelab/react-admin#7897]
Hi everyone.

I'm using React-Admin with "ra-data-treeql" (I'm using "[php-crud-api](https://github.com/mevdschee/php-crud-api)").

I set
`const dataProvider = treeqlProvider('https://www.apiurl.xyz/');`
and then
`const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="sellers"list={sellerList} />
</Admin>`

With a "simple" resource from API all works fine but I need to **join** different tables (for example the partial URL in postman is sellers?join=brands&join=products).
How can I add the join parameters in Resource name? If I use
`<Resource name="sellers?join=brands&join=products"list={sellerList} />`
I receive an error.

Thanks everybody

**Comment by septentrion-730n** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
