### ISSUE TITLE
Nested form receives data from parent form

### ISSUE THREAD

**Issue by hffmnn** [marmelab/react-admin#7934]
**What you were expecting:**
A nested form should only receive its data, not the data of the parent form.

**What happened instead:**

* When pressing save I get an error message: `An item with the identifier 1 already exists` => This is because the `create` used the underlying `id` when submitting the form.
* In the console the following object is logged:

```
{
  id: 1
  author: Object
  post_id: 6
  body: "Queen, tossing her head through the wood. 'If it had lost something; and she felt sure it."
  created_at: Thu Aug 02 2012 02:00:00 GMT+0200 (Central European Summer Time)
  title: "some title"
  teaser: "some teaser"
}
```

**Steps to reproduce:**

* Navigate to a Comment
* The QuickCreate dialog opens
* Type something in
* press save

**Related code:**
I added a codesandbox here: https://codesandbox.io/s/compassionate-tree-0riqvw 

The only thing I changed was adding the `PostQuickCreate` (where I had to remove `` because it couldn't be resolved?) to the `CommentEdit`.

**Environment**

* React-admin version: `^4.2.1`
* React version: `^17.0.0`
* Browser: Firefox

**Comment by djhi** [comment]
Reproduced. Thanks

**Comment by fzaninotto** [comment]
I've simplified the repro in https://codesandbox.io/s/trusting-field-k6et3v?file=/src/comments/CommentEdit.tsx

1. Edit a comment
2. Click on the Post dropdown, and choose the last option "create"
3. Fill in the creation form and submit
4. Console error

To me, this a user land problem, not a react-admin bug. 

The creation form renders in a dialog, but from React's point of view, it's a descendent of the Edit form. And the Edit form creates a Form context. As react-hook-form doesn't support nested forms, the `<Form>` declared by PostQuickCreate reuses the context from the `<Form>` created by the Edit form. 

We don't have the problem in the simple example because we don't use the PostQuickCreate in the edition view. But if we did, we'd have to use `<form>` instead of `<Form>` and pass the controller manually to all inputs. We don't document the quick create with a `<Form>` tag. 

So I think it's a react-hook-form usage problem, and there is nothing to fix..
