### ISSUE TITLE
Force getOne query on Edit after going from a List

### ISSUE THREAD

**Issue by martin-fv** [marmelab/react-admin#8094]
We're using a our custom dataprovider for prisma. https://github.com/codeledge/ra-data-simple-prisma/tree/main/packages/ra-data-simple-prisma
In one custom resources fetches additional data in the getList method. (adds an object layer on within a record)
When coming from a list and updating an item, we can an error since in the data we have a nested foreign object. However if we reload the page it will fetch getOne with only the correct data and there is no error on the update.
Is there a way to force fetching getOne after coming from a list.

**Comment by arimet** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by martin-fv** [comment]
Well for us technically it's a bug. I was asking the question in a sense that it might not be a bug and might be a design choice to save queries.
125€ is a bit steep. But we're happy to donate a smaller amount if there was a sponsor button on your repository.
