### ISSUE TITLE
Move Example to another git repository

### ISSUE THREAD

**Issue by haison8x** [marmelab/react-admin#8151]
Many opensource owners split the main source code and the demo source code to two git repository. Hence, the demo/examples are independent from the main source code, make it easy to learn.

Could you please move examples folder to another git repository?

**Comment by fzaninotto** [comment]
No, because the demos and examples help us test the features during development, and validate some of the features via e2e tests. If we split the repos, we'd have to synchronize PRs between the core and demo repositories. We don't need that extra work.

Also, if you need to run one example in isolation, try a tool like codesandbox:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
