### ISSUE TITLE
Performance issues on forms with large number of inputs when editing

### ISSUE THREAD

**Issue by carl0s-sa** [marmelab/react-admin#8166]
**What you were expecting:**
Writing in inputs isn't laggy

**What happened instead:**
Writing in inputs is laggy when the value changes between the initial one and a different one

**Steps to reproduce:**
- Have a `TabbedForm` with around 600 Inputs split over 16 tabs (around 30 inputs per page)
- Enter in Edit mode with some data in the fields
- Typing in any input reproduces the issue, everytime the input values changes from or to the initial value it lags the page.

**Related code:**
There's nothing too specific on the code, just a bunch of `TextInputs`/`SelectInputs`/`ReferenceInput`/`ImageInput` under `FormTab`

**Other information:**
I turned on react's "highlight when updated" feature and when issue happens its re-rendering the whole page with all the inputs.

**Environment**

* React-admin version: 3.19.7
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by fzaninotto** [comment]
Hi, and thanks for your feedback.

You're hitting the limits of React+MUI+react-hook-form. We've chosen to use controlled input components for various reasons, but this approach doesn't scale to the number of inputs you're evoking. 

In my opinion, a form with 600 inputs is a usability hell, so we won't change the architecture of the react-admin core to support it. 

That being said, react-admin lets you swap its components with your own, so you can write your own `<TabbedForm>`  using either react-hook-form (which allows uncontrolled components) or the approach of your choice.

**Comment by carl0s-sa** [comment]
I see thanks.
I also agree that 600 inputs in a single form is hell, how could I split that? I only get one Edit View for that resource, is there a way to define multiple edit forms for a single resource?
My initial guess was writting a tab form that doesn't render the tabs that aren't showing (actually not rendering them not `display: none`) would help but I'm afraid it might have hidden (no pun intended) repercussions.

**Comment by fzaninotto** [comment]
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.
