### ISSUE TITLE
RowClickFunction could have other returns besides string

### ISSUE THREAD

**Issue by oguhpereira** [marmelab/react-admin#8232]
I would like to raise a dissussion about the data-grid prop

`rowClick?: string | RowClickFunction;`

My question is on top of RowClickFunction, why does it always expect a string? I say for the case when the row is not valid when redirecting I could return a void, undefined or false, what do you think?

Why would RowClickFunction always need to return string and for me to keep it on the page I have to add a `return ''`

**Comment by WiXSL** [comment]
Thanks for your feedback.
Your suggestion seems reasonable.
Let me discuss it with the react-admin team, and I'll get back to you

**Comment by fzaninotto** [comment]
As I understand, in your case, a click on a datagrid row may or may not have an action. If this is the case, this should be handled * before* the `rowClick` function is called, because the pointer shows that a row is clickable. It would be misleading for end users to indicate with the mouse pointer that a row is clickable, then do nothing on click. 

So I suggest adding something like [the current `isRowSelectable` prop](https://marmelab.com/react-admin/Datagrid.html#isrowselectable) to the Datagrid - why not `isClickable`? 

But I don't think we should accept a false or null response to `rowClick`.

**Comment by oguhpereira** [comment]
Suppose you want to do an action from the rowclick that is not necessarily a redirect. Sometimes a copy of data or some other action.

In this case, the redirect is not necessary.

Today I believe that we don't have a callback for rowclick

**Comment by oguhpereira** [comment]
what do you think about these points @fzaninotto @WiXSL ?

**Comment by fzaninotto** [comment]
This is not a use case we want to support out of the box. If you need that UX, you'll have to [pass your own DatagridRow](https://marmelab.com/react-admin/Datagrid.html#body), or a build a custom Datagrid altogether.
