### ISSUE TITLE
How to unit test my CreateField component?

### ISSUE THREAD

**Issue by ayushdevelop** [marmelab/react-admin#8246]
I am trying to test my `CreateField` component as I am fetching the data from an api to show in `<SelectInput>`?

What steps should I follow to test for ensuring if the data populates as options of `SelectInput` ? 

This is my code 

```javascript

const StandupCreate = () => {
  const [channelList, setChannelList] = useState([]);

  useEffect(() => {
    const fetchChannelList = async () => {
      try {
        const data = await fetchChannels();

        const channels = await data.data.data;

        setChannelList(channels);
      } catch (error) {
        throw error;
      }
    };

    fetchChannelList();
  }, []);

  return (
    <Create>
      <SimpleForm>
        <TextInput source="title" />
        <TextInput source="question 1" fullWidth />
        <TextInput source="question 2" fullWidth />
        <TextInput source="question 3" fullWidth />
        <TextInput source="question 4" fullWidth />
        <SelectInput
          source="channel"
          choices={channelList}
        />
        <CheckboxGroupInput source="members" choices={channelMembers} />
        <TimeInput source="time" />
      </SimpleForm>
    </Create>
  );
};
```

**Comment by slax57** [comment]
Hi, and thanks for your question.
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by ayushdevelop** [comment]
hey @slax57 thank you for the response but it seems like the discord invite link has expired, can you please share with me a new invitation link?

**Comment by ayushdevelop** [comment]
Thankyou @slax57 for the quick response.
