### ISSUE TITLE
global configuration be allowed to disable button breakpoint logic

### ISSUE THREAD

**Issue by yanbo8991** [marmelab/react-admin#8281]
i want to Allow button to be displayed on mobile terminal
![image](https://user-images.githubusercontent.com/116255737/196879781-d6d1398e-ca7f-45db-9531-75ee34708f45.png)

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

You can already create your own buttons and replace react-admin ones with your own. We don't want to add more code in the core to support the scenario you're describing, because we don't consider it very usual.

So I'll close this feature request. If you happen to implement this, I suggest you make it an open-source package to let others benefit from your work!

**Comment by fzaninotto** [comment]
Because this allows users to have more content and less chrome on small screens.
