### ISSUE TITLE
Populate form data from 1 resource then update data to another resource when edit

### ISSUE THREAD

**Issue by ductm3112** [marmelab/react-admin#8295]
Hi, how can i populate form data from 1 resource then update data to another source use `Edit ` component

I want to update to `description ` in resource name `source_1` rather than `source_2`, which i currently used for populated description old value

**Related code:**
```
export const SourceMeasurementProtocolUpdateDescription = () => (
  <Edit resource="source_2">
    <SimpleForm>
      <TextInput source="description" multiline />
    </SimpleForm>
  </Edit>
);
```

**Environment**
React-admin version: 4.1.0
React version: 18.0.0

**Comment by slax57** [comment]
Hi, and thanks for your question.
As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
