### ISSUE TITLE
FilterList doesn't pass props like onChange or onSelectionChanged down to List

### ISSUE THREAD

**Issue by cydergoth** [marmelab/react-admin#8446]
In many cases, the set of options in a FilterList will depend on the selection of another filter list, e.g. if I have several `projects` and in each `project` I have a set of `environments`, I should like to show only the relevant set of `environments` if the list is filtered by `project`

This would be achievable if we could listen on the FilterList for changes and retrieve the value (project_id | undefined) for the filters

```
export const FilterList = (props: FilterListProps) => {
    const { label, icon, children, ...rest } = props;  <-- add 'onChange' or 'onSelectionChanged' 
    const translate = useTranslate();
    return (
        <Box {...rest}>
            <Box mt={2} display="flex" alignItems="center">
                <Box mr={1}>{icon}</Box>
                <Typography variant="overline">
                    {translate(label, { _: label })}
                </Typography>
            </Box>
            <List dense disablePadding>  <--- Maybe pass onChange/OnSelectionChanged properties down here?
                {children}
            </List>
        </Box>
    );
};
```

**Comment by slax57** [comment]
I'm not sure exactly how we could do this without significantly increasing the complexity of the component. I'm thinking of the _'pass onChange/OnSelectionChanged properties down here'_ part in particular.

Besides, I believe it is already doable in user-land by leveraging [useListContext](https://marmelab.com/react-admin/useListContext.html) to access the `filterValues`, and choose what `FilterListItem` to render accordingly.

If you are convinced there are use-cases not covered by this approach, and/or see a way to have `FilterList` support this feature without hurting the DX too much, then please elaborate.

**Comment by fzaninotto** [comment]
React-admin tries to offer easy-to-use solutions for common needs, and an easy way to use your components when it's not enough. But we can't (and won't) address all possible uses cases.

I believe what you ask (dependent filters / facets) isn't such a common need - especially because is actually covers various use cases (Does the order in which filters are clicked matter? How do you know which filters are applicable on the current data set? Do you need to reset the dependent filter once the master filter is removed?). 

Besides, as @slax57 pointed, it's doable in user land using `useListContext`.

So unfortunately, we won't support dependent filters in react-admin. Thanks for your report anyway!
