### ISSUE TITLE
How to set <SimpleFormIterator> to show one row initially

### ISSUE THREAD

**Issue by hs-dev-web** [marmelab/react-admin#8450]
on page first load there is no input shown, it only shows add button, what I want is to show one row because the system requires at least one record, how to do it?

**Comment by WiXSL** [comment]
As explained in the react-admin contributing guide, we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

Community support: Ask your question on StackOverFlow. This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
Professional support: If you're a React-Admin Enterprise Edition subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the Enterprise Edition, starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
