### ISSUE TITLE
 Error: Uncaught [TypeError: Cannot read property 'toLowerCase' of undefined] during tests

### ISSUE THREAD

**Issue by SujayPrabhu96** [marmelab/react-admin#8463]
**What you were expecting:**
- I am rendering a simple component wrapped inside `Create` tag and written tests using react-testing-library to check if the title has been rendered by referring to the documentation. I was expecting the test to pass.

**What happened instead:**
- Test case failed with error ` Error: Uncaught [TypeError: Cannot read property 'toLowerCase' of undefined]`

**Steps to reproduce:**
I am sharing demo repo link. You can clone it and run `yarn test`

**Related code:**

Demo repo link: https://github.com/SujayPrabhu96/react-admin-demo
Component to be tested: https://github.com/SujayPrabhu96/react-admin-demo/blob/main/src/admin/StandupShow.tsx
Test case: https://github.com/SujayPrabhu96/react-admin-demo/blob/main/src/admin/StandupShow.test.tsx

```
test("<StandupShow>", async () => {
    render(
        <AdminContext>
            <StandupShow />
        </AdminContext>
    );
    expect(screen.getByText("Create Standup")).toBeInTheDocument();
});
```

**Other information:**
- I have looked into the official documentation for writing tests: https://marmelab.com/react-admin/UnitTesting.html

**Environment**

* React-admin version: 4.6.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser:
* Stack trace (in case of a JS error):

**Comment by slax57** [comment]
Hi,

You are probably missing some context values, which are normally provided by react-admin in a complete app.
When writing tests, we often need to pass those values via context providers or via props.
I'd say you are probably missing the `resource` value here, but maybe others too.

Have a look at the way we write our internal tests to learn more.

In any case, I'm gonna have to close this issue. Indeed, as explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

If you need further help, you can use one of the channels below:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

Thank you for your understanding.
