### ISSUE TITLE
Fixed filters deeply merged to use it with object

### ISSUE THREAD

**Issue by groomain** [marmelab/react-admin#8476]
**Is your feature request related to a problem? Please describe.**
We are using react-admin with graphql.

Today we're filtering sometimes with subobject in our queries
```
{
    filter: {
        employee: {
             id: ....
        }
    }
}
```

if I want to fix the status, I use the filter props on the List component
ie: 

```
filter={ {
        employee: {
             status: "ENABLED"
        }
    }}
```

But if I do this I cannot specify the employee ID or anything else in the filter "employee".

I think it's because filter and current filters are not deeply merged. Just spread.
Cannot found where it's done in the code.

**Describe the solution you'd like**
Be able to specify an object as filter={} and still allow to filter on this object with something else.

**Describe alternatives you've considered**
Today we use filterDefaultValues because user still can edit filters in object with it.

**Additional context**
Hope it's clear enough!

**Comment by septentrion-730n** [comment]
Hi,

Could you do add a small demo using our [stackblitz template ](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=README.md) to clarify your request?

We would gladly welcome any help on this matter! 👍

**Comment by groomain** [comment]
Sorry don't really have a time to reproduce it. And don't really know how to do it on stackblitz :/

I'll see if I have the time to find where in the code filter is used to add a merge.

Thanks!

**Comment by baleato** [comment]
I belive this is because the list controller is using the spread syntax to combine the query filter and the permanent filter instead of deeply merging both filters. This results in a permanent filter like `{ employee: { status: "ENABLED" } }` not allowing you to additionaly filter by any other employee properties.

https://github.com/marmelab/react-admin/blob/1c22bbb10b9001ed3471df91d1a2c4a8bca95fae/packages/ra-core/src/controller/list/useListController.ts#L92-L94

I would also be interested in such a feature that allows for merging filters. Since lodash is already a dependency maybe using `filter: _merge({}, query.filter, filter)` could deliver this. @septentrion-730n, what's you opinion on this approach?

**Comment by fzaninotto** [comment]
This proposal hasn't received any attention from the community for quite some time, and we won't implement it in the near future. So I'm closing the issue. Feel free to contribute a PR implementing this feature, we'll look at closely.
