### ISSUE TITLE
Feature request: ability to customize default mutationMode

### ISSUE THREAD

**Issue by zenflow** [marmelab/react-admin#8506]
**Is your feature request related to a problem? Please describe.**
Yes actually. https://github.com/marmelab/react-admin/issues/8505
If that issue with undoable mutations was solved (undoable being the default mutationMode), I wouldn't really care about this feature (though it could still be generally useful).

**Describe the solution you'd like**
I'd like to be able to change the default mutationMode to optimistic (or pessimistic), so that when I want to change it globally, I don't need to specify it everywhere a mutation is made.

**Describe alternatives you've considered**
Change mutationMode in every place a mutation is made (not ideal)

**Additional context**
none

**Comment by slax57** [comment]
As explained in [the Architecture section of the React-Admin docs](https://marmelab.com/react-admin/Architecture.html#component-composition), RA encourages building your own variations of the core components instead of providing god-like components that configure their children.

Hence we encourage you to create custom versions of the RA components, like `Edit` or `DeleteButton`, or any other you need, that will set the `mutationMode` to optimistic (or pessimistic).
For this reason, I'm closing this issue as we won't address this feature request.
