### ISSUE TITLE
Ui Designs 4.0.7v

### ISSUE THREAD

**Issue by adnan1naeem** [marmelab/react-admin#8584]
<img width="1440" alt="Screenshot 2023-01-17 at 1 18 48 PM" src="https://user-images.githubusercontent.com/22443038/212888913-3b85edd3-507e-417c-8b4b-de70a24249ab.png">
<img width="1437" alt="Screenshot 2023-01-17 at 1 22 22 PM" src="https://user-images.githubusercontent.com/22443038/212888988-11d2da91-157f-4c9b-9a03-742bb5b06c9a.png">
Hey all i am facing an issue of ui designs in 4.0.7 version upgrade.I have more then 20 columns for a table in react admin which got distorted in 4.0.7 but works fine in 3.16.6.

Please let me know what is the work around for this issue

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
