### ISSUE TITLE
skip the login page and directly enter the home page

### ISSUE THREAD

**Issue by curisegong** [marmelab/react-admin#8621]
We want to log in with a third party, such as scanning the code github QR code, and then directly enter the system home page. But now there is a problem: after entering the system home page, click a menu, and the system will forcibly log out to the login interface, and I will get a session expiration, please re-link the error, what should I d

**Comment by slax57** [comment]
This is a duplicate of https://github.com/marmelab/react-admin/issues/8619 , and you are still not following the issue template nor following the contribution guide.

LAST WARNING: follow the [contribution rules](https://github.com/marmelab/react-admin/issues/8619#issuecomment-1415409669), otherwise we will block you from this repository.
