### ISSUE TITLE
Possibility to add a fallback checkbox component for `<DatagridRow>` when `selectable` prop is false

### ISSUE THREAD

**Issue by yanchesky** [marmelab/react-admin#8628]
**Is your feature request related to a problem? Please describe.**
`<DatagridRow>` component does not render a checkbox when the `selectable` prop is false. 

**Describe the solution you'd like**
I'd like to have an option to provide a custom component that will render in case `selectable` prop is false. 

**Describe alternatives you've considered**
I can create a custom `<DatagridRow>` for my own project which will implement this feature.

**Additional context**
Having such functionality would let us use `<Checkbox disabled>` for example. We could also easily provide a tooltip with a description of why the row is disabled for selection.

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion. That's an interesting use case. It makes me wonder if we shouldn't default to a disabled checkbox when `isRowSelectable` returns `false`, because the current UI is... confusing. 

![image](https://user-images.githubusercontent.com/99944/217322120-07e4e449-4f6f-4e23-a61d-2ac0596d4971.png)

I wonder what other users think about this. 

As for passing a custom checkbox component, I don't think we'll implement this, as it's not really simpler than using a custom `DatagridRow` and it's not a super common use case in my experience.

**Comment by WiXSL** [comment]
I agree, checkboxes of unelectable rows should be shown disabled instead of being hidden.
It is more visually consistent.

I've implemented this change in a PR, to be reviewed #8650

**Comment by fzaninotto** [comment]
#8650 is merged, so I'll close this PR. Thanks again for raising the issue. 

> As for passing a custom checkbox component, I don't think we'll implement this, as it's not really simpler than using a custom DatagridRow and it's not a super common use case in my experience.
