### ISSUE TITLE
defaultTheme.ts problem

### ISSUE THREAD

**Issue by STACKL0RD** [marmelab/react-admin#8729]
Hello, I work on react-admin, and I have a problem when I launch my project:
1st Error:
```
./node_modules/ra-ui-materialui/src/defaultTheme.ts 37:34
Module parse failed: Unexpected token (37:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         MuiTextField: {
|             defaultProps: {
>                 variant: 'filled' as const,
|                 margin: 'dense' as const,
|                 size: 'small' as const,
```
I tried to delete `as const` (I know this isn't a good solution but I tred), but a new problem appears:

2nd Error:
```
./node_modules/ra-ui-materialui/src/defaultTheme.ts 52:7
Module parse failed: Unexpected token (52:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> export interface RaThemeOptions extends ThemeOptions {
|     sidebar?: {
|         width?: number;
```

Have you an idea to resolve my problem?

**Environment**

* React-admin version: 4.0.0
* React version: 16.12.0
* Browser: Mozilla Firefox

**Comment by djhi** [comment]
Please follow the issue template

**Comment by STACKL0RD** [comment]
**What you were expecting:**
a functional project

**What happened instead:**
I work on react-admin, and I have a problem when I launch my project:

**Steps to reproduce:**
1st Error:
```
./node_modules/ra-ui-materialui/src/defaultTheme.ts 37:34
Module parse failed: Unexpected token (37:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         MuiTextField: {
|             defaultProps: {
>                 variant: 'filled' as const,
|                 margin: 'dense' as const,
|                 size: 'small' as const,
```
I tried to delete `as const` (I know this isn't a good solution but I tred), but a new problem appears:

2nd Error:
```
./node_modules/ra-ui-materialui/src/defaultTheme.ts 52:7
Module parse failed: Unexpected token (52:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> export interface RaThemeOptions extends ThemeOptions {
|     sidebar?: {
|         width?: number;
```

**Related code:**
see previous comment

**Other information:**
I tried to make a loader (webpack.config.js), without success.

```
const path = require('path');

module.exports = {
    mode: "development",
    devtool: "inline-source-map",
    entry: "./app.ts",
    output: {
      filename: './node_modules/ra-ui-materialui/src/defaultTheme.ts',
    },
    module: {
      rules: [
        {
          test: /\.(ts|tsx)$/,
          exclude: /node_modules/,
          use: [
            {
              loader: "babel-loader",
              options: {
                presets: [
                  "@babel/preset-env",
                  "@babel/preset-react",
                  "@babel/preset-typescript",
                ],
              },
            },
          ],
        },
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
        },
      ],
    },
  };
```

**Comment by slax57** [comment]
Hi,
It seems to me that this is not actually a bug report but a support request.

As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support requests, you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

Now, having a quick look at your `webpack.config.js` file make me realize you have no `ts-loader` in it, which is probably the source of your issue.
You may want to have a look at this file for a working example: https://github.com/marmelab/react-admin/blob/v4.8.0/examples/simple/webpack.config.js

In any case, I'll be closing this issue, and inviting you to ask your question in one of the support channels mentioned above if you need further help.
