### ISSUE TITLE
Has the idea of "fields" being copyable already been discussed?

### ISSUE THREAD

**Issue by Gabriel-Malenowitch** [marmelab/react-admin#8735]
**Is your feature request related to a problem? Please describe.**

We currently use a component to make fields copyable. The component passes a `cursor: pointer` style to `children` and accesses `children`'s `props` by getting `source` there, and `record` by context.
Ex:
```tsx
  <CopyChildrenField>
       <TextField source="test" />
  </CopyChildrenField>
```

**Describe the solution you'd like**
If it was a `prop`?
Ex:
```tsx
// Rather than:
<CopyChildrenField>
     <TextField source="test" />
</CopyChildrenField>

// Use than:
 <TextField source="test"  isCopyable/>
```
**Describe alternatives you've considered**

let's discuss : )

**Comment by slax57** [comment]
Hi, and thank you for your suggestion.
Although I agree that this would be a handy feature, one of our objectives is to keep react-admin small enough to avoid increasing the learning curve too much.
Unless there's a high demand for such a feature, since it's doable with pure React, I'd rather keep it user-land for now.
You can read more about this philosophy in our docs: https://marmelab.com/react-admin/Architecture.html#minimal-api-surface
Of course, I'm open to discussion as well :slightly_smiling_face: 
@djhi or @fzaninotto what do you think? Did you already come across such a need?

**Comment by viniciusbsneto** [comment]
Hello, @slax57! We're building such a field for our app. If you feel like this is a nice field component to be available at React Admin without going against its philosophy, we'd be up to open a PR.

**Comment by slax57** [comment]
Okay, so maybe this use-case is more common than I thought :sweat_smile: 
So yeah, @viniciusbsneto , we'd be happy to accept a PR implementing this feature :slightly_smiling_face: 
Remember to target it against the `next` branch :wink: 
Thank you guys so much!

**Comment by fzaninotto** [comment]
Wait, I'm -1 with this feature as it relies on child inspection, and this won't work in many cases. 

I think for these use cases, you should either use a userland solution as you explained, or an alternative datagrid that supports copying.

**Comment by lukascivil** [comment]
It would be a very important feature for the team here. React admin should be a swiss army knife for building admin panels.

**Comment by slax57** [comment]
Okay so let's settle down on this:
We won't include this component in react-admin's core, because it has to rely on child inspection, and this is something we want to avoid as much as possible.
However, if you guys are willing to share the code of your component, for instance as its own package, we would be happy to mention it in our docs!
So I'll close this feature request, and invite you to open a doc PR instead.
