### ISSUE TITLE
Make it possible to always display the sidebar menu - do not allow toggle it.

### ISSUE THREAD

**Issue by adriangarrote** [marmelab/react-admin#8786]
**Is your feature request related to a problem? Please describe.**
Make the menu more customizable by allowing to disable the capability of using the hamburguer menu for toggle the side bar menu, and make it always fit instead.  

**Describe the solution you'd like**
Make the menu more customizable by allowing to disable the capability of using the hamburguer menu for toggle the side bar menu, and make it always fit instead.  

**Describe alternatives you've considered**
Implementing a custom Appbar. 

**Additional context**

**Comment by slax57** [comment]
Hi, and thank you for your suggestion.
Since this is doable fairly easily in user-land, I'm not in favor of adding an option for this feature.
(you can have a look at [this recenlty merged PR](https://github.com/marmelab/react-admin/pull/8777) for inspiration)
Thanks for taking the time to open this feature request anyway!
