### ISSUE TITLE
Inconsistent width between text and autocomplete inputs

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#8796]
**What you were expecting:**

The text and autocomplete should have the same base width.

**What happened instead:**

The base width of the autocomplete input is smaller than the text input.

**Steps to reproduce:**

https://react-admin-storybook-mpmncf8xi-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-arrayinput--autocomplete-first

<details><summary>Details</summary>
<p>

![image](https://user-images.githubusercontent.com/1698357/229638373-ba0589f3-6aa3-43ac-9493-cbadc340ff8f.png)

</p>
</details> 

**Other information:**

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: from storybook
* Browser: Firefox
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
The problem comes from the browser. The following Stackblitz shows that even raw inputs have the same problem of unequal default width: https://stackblitz.com/edit/react-ts-fbuqu9?file=App.tsx

The differences in Chrome (similar differences appear in Firefox):

![image](https://github.com/marmelab/react-admin/assets/99944/fd076251-0a9a-41e5-aa0f-509293880b96)

IMHO, if this has to be fixed, it should be at the material-ui level. But I believe they chose not to address it (I think I have read an issue in their repo where they explain why they don't override the default input width but I can't find it there). 

@oliviertassinari , any insight?

**Comment by oliviertassinari** [comment]
We could consider making `fullWidth={true}` the default behavior. I see it's how a good number of libraries behave. It makes sense:

- https://getbootstrap.com/docs/5.3/forms/form-control/
- https://ant.design/components/input
- https://chakra-ui.com/docs/components/input/usage
- https://sancho-ui.com/components/form/#input
- https://baseweb.design/components/input/
- https://seek-oss.github.io/braid-design-system/components/TextField
- https://balance.reckon.com/package/text-input
- https://tailwindui.com/components/application-ui/forms/input-groups

**Comment by oliviertassinari** [comment]
> 
We could consider making fullWidth={true} the default behavior.

That would be a major change - perhaps too drastic. How about setting a sensible minWidth for all material-ui input components?


I think that this should be moved to https://github.com/mui/material-ui/issues/37310

**Comment by fzaninotto** [comment]
@soullivaneuh As seen in the above discussion, this is really a material-ui feature, so we won't override their behavior in react-admin. Besides, it's kind of doable in user land with a custom theme.

I'll close this issue. Thanks for your work anyway!
