### ISSUE TITLE
Layout theming issue because of nameless div

### ISSUE THREAD

**Issue by Nickman87** [marmelab/react-admin#8835]
I'm trying to get some custom styles up for the react-admin dashboard and everything is going pretty smoothly once I figured our the MUI theme structure and sx styling.

I do however end up with a styling issue when trying to get everything to stretch to 100% height (minimum) and I noticed that the CoreAdminRoutes component dops a single unnamed `div` into the react structure:
https://github.com/marmelab/react-admin/blob/60f0b6351242a10e63c3eb27fb3d63cb9fd97908/packages/ra-core/src/core/CoreAdminRoutes.tsx#L79
(using react-admin `4.9.2`)

Not sure if this has a practical use as the next component down is the Layout (or MyLayout in my case)?

![image](https://user-images.githubusercontent.com/870416/232040766-e7c9bb1c-985b-462c-8460-da5a9f8a3765.png)

**Comment by slax57** [comment]
Thanks for the report.
Maybe it could, even perhaps should, be removed, but this would be a BC.
Best way to fix this would be to add a new prop to provide a way to style this div, but this seems quite heavy because we would need to pass it all the way down from the `<Admin>` component.

For me the easiest fix would be to do it in user-land with something like

```tsx
<Box sx={{ '& div': { color: 'red' } }}>
  <Admin dataProvider={dataProvider}>
    <Resource name="posts" />
  </Admin>
</Box>
```

I'll leave this open as enhancement for now though, to see if it gets upvoted.

**Comment by fzaninotto** [comment]
I agree with @slax57, fixing it would be a BC, and this is doable in user land, so we don't need to do anything.
