### ISSUE TITLE
Multiple List with Tabs

### ISSUE THREAD

**Issue by tadstr** [marmelab/react-admin#8845]
**Is your feature request related to a problem? Please describe.**
Is there a way to create multiple List in a same item selected from the sidebar.

**Describe the solution you'd like**
a way to implement full React Admin datagrid with data fetched from API (react Query, axios, ...), not from the URL from <Resource /> name or DataProvider
![Untitled](https://user-images.githubusercontent.com/36992181/233308911-b6825dc7-d46f-4e95-b230-1ed04b86c7a9.png)

**Comment by slax57** [comment]
This really looks to me like a How To question and not a feature request.

Besides, requirements like the following really seem to go against the core concepts of RA IMO:
> a way to implement full React Admin datagrid with data fetched from API (react Query, axios, ...), not from the URL from name or DataProvider

As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
