### ISSUE TITLE
Disable the check that now results in an uncaught error in useEditController: Fetched record's id attribute must match the requested 'id'

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#8849]
**Is your feature request related to a problem? Please describe.**
A table trigger in my database alters the id of the record after updating it. That means that in the response the PATCH request returns the resource again, but with a different id then was used to update it.

When using the useEditController.ts I'm getting the following error when that happens:

> useEditController.ts:104 Uncaught Error: useEditController: Fetched record's id attribute (96c54f32...) must match the requested 'id' (67b1296a...)
 
**Describe the solution you'd like**
Removal of the check in useEditController that was introduced here https://github.com/marmelab/react-admin/commit/893130fe898066f970170c3d4c0106e498e74052.

That commit introduced the same kind of check in useEditController en useShowController. For the latter I think it always makes sense. But for the former, a niche case I admit, not necessary so.

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/465989/233636791-97d3042d-8c06-446d-af56-19b1fbc497d9.png">

**Describe alternatives you've considered**
If the benefit of having this check outweighs allowing for my niche use case, we could use some kind of mutationOption like disableIdCheck. The last workaround is to make a local copy of useEditController and change it for my needs, but I rather not do that.

**Additional context**
-

**Comment by slax57** [comment]
Hum I see...

I can't tell for sure if this check is absolutely needed or not, but since it's there since the earlier versions of react-admin v4, I'm afraid this assumption could have been made at other places in the code too, especially in the dataProvider hooks, when we optimistically update the react-query cache.
Hence I am not willing to take the risk to offer a way to remove it now, as it might create hidden bugs.

Besides, in my experience this is the first time I've heard of such a use-case, so I'm not sure it's common enough to justify an implementation in RA's core.

To me this use-case should be dealt with in user-land, by indeed making a local copy of `useEditController` and changing it for your needs.

However I'll keep this question open as I'd like to have @fzaninotto or @djhi 's opinion on this.

**Comment by WiXSL** [comment]
If it helps, this is the reason this code was introduced: #5530

**Comment by christiaanwesterbeek** [comment]
To summarize. A check was build into RA to signal an error when a backend **unintentional** returned a different id when **getting** a record, and the same check was also implemented for record updating. But the latter now prevents a **intentional** different id being returned by the backend when **updating** a record.

**Comment by fzaninotto** [comment]
I agree with @slax57: I think your use case is niche, and we don't have to support it. Besides, you can write your own Edit component without the check to support it, so I'll close the issue. 

Thanks for the report anyway!

**Comment by christiaanwesterbeek** [comment]
That's unfortunate, but thanks for considering. That leaves with me the choice to make a copy of useEditController and remove these lines.

https://github.com/marmelab/react-admin/blob/c98aa74ce97cdfcfaf9c075f6040b64f931e0345/packages/ra-core/src/controller/edit/useEditController.ts#L104-L108

**Comment by Dreamsorcerer** [comment]
I've encountered this too.

When using `mutationMode='pessimistic'`, everything still seems to work without a problem despite throwing the error. For example, if you use `redirect='show'` it successfully redirects to the new ID returned by the backend. Would be nice to be able to disable it, or atleast downgrade to a warning.

Curiously, when not using pessimistic mode, no error appears, yet this is the case where it may mess things up. So, it seems to me like the error is under the wrong conditions or something.

**Comment by christiaanwesterbeek** [comment]
I encountered the same problem in another use case that is less niche.

I have a ListWithEditInDrawer component. When a record in the list is clicked, a Mui Drawer opens with EditBase in it that takes the id from the url. It loads the record and populates the SimpleForm. Everything is working fine up until now.

When I click another record in the list, the error is also thrown. This is because EditBase now receives an new id prop, which is now a different value from id in the record context.

To fix this, I now also pass key={id} to EditBase so that it will be a new instance each time with no previous record context.

**Comment by slax57** [comment]
@christiaanwesterbeek Editing records in a Dialog, without leaving the List view, is something we officially support via the (Enterprise Edition) [EditDialog](https://marmelab.com/ra-enterprise/modules/ra-form-layout#createdialog-editdialog--showdialog) component. We never had this issue with this component.

However, re-reading the comments from this issue, and especially [this comment](https://github.com/marmelab/react-admin/issues/8849#issuecomment-1868599329) from @Dreamsorcerer makes me actually agree that this message could be downgraded to a warning to avoid blocking users that cannot do otherwise.

@fzaninotto @djhi may I request a 2nd thought on this?

**Comment by fzaninotto** [comment]
Converting the error to a warning puts us in an uncomfortable position. The optimistic update will fail and have unexpected consequences (probably leading to UI glitches / blinking), and the warning will say "yes it's broken, deal with it". I don't think that's a good DX. React-admin should either support or not support a use case. Being in the middle exposes us to more bug reports about a half-working feature. 

I repeat that we don't want to support the use case of a record update changing the id. If you need it, write your own Edit Controller.

Now, maybe I'm overstating the "unexpected consequences" of a broken optimistic update. But I also don't want to spend time testing it, as this isn't a use case we want to support. So if you're a contributor to react-admin, and you need this feature, you'll need to provide the proof yourself: open a proper PR converting the error to a warning and showing that it doesn't break anything, with lots of tests and comments. If such a proof is provided, we'll take a look at it, with no guarantee of merging.

**Comment by Dreamsorcerer** [comment]
> Now, maybe I'm overstating the "unexpected consequences" of a broken optimistic update.

As I mentioned in my comment, I'm using pessimistic updates which works fine despite this error being thrown (but, makes it rather annoying for tests where I need to ignore the error). When I change to optimistic updates, then things _do_ break a bit, but _there is no error_. This definitely seems to be the wrong way round with the current implementation.
