### ISSUE TITLE
Edit component for sub-routed nested resource

### ISSUE THREAD

**Issue by chattago2002** [marmelab/react-admin#8854]
I'm trying to use custom routes for nested resources. **Request** is a "real" resource as table on db whereas **Participants** is a "virtual" resource, it refers to **request_details** table.

I have the following:
```
<Admin dataProvider={dataProvider}>
    <Resource name="requests" list={RequestsList} create={NewRequest} edit={EditRequest} >
        <Route path=":reqID/participants" element={<ReqParticipantsList />} />
        <Route path=":reqID/participant/:partID" element={<ReqParticipantsEdit />} />
    </Resource>
</Admin>
```

When I go to /requests/11/participants the following code is loaded for **ReqParticipantsList** component and all is ok:
```
<ListBase resource="request_details">
```
but when I go to /requests/11/participant/205 and the code of **ReqParticipantsEdit** component contains
```
<EditBase resource="request_details">
```
I'm redirected to /request_details with an error (obviously).

In the **ReqParticipantsEdit** component I tried to use Edit, EditBase, ResourceContextProvider but nothing seems to work. If I use the simple paragraph to "log"
```
<p>{`Request ID: ${reqID}, Participant ID: ${partID}`}</p>
```
the 2 values are returned correctly (reqID and partID).

Where am I wrong?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
