### ISSUE TITLE
React admin tutorial, api does not send data

### ISSUE THREAD

**Issue by RetherSzu** [marmelab/react-admin#8858]
Hello everyone, I started the react-admin tutorial step by step, and when I add the resource to display the users, the api does not send any data

![image_2023-04-25_102649612](https://user-images.githubusercontent.com/60273111/234219115-7bd57ce3-d908-4050-957e-5a14915905b1.png)

The request to the api looks like this: 

```
https://jsonplaceholder.typicode.com/users?_end=10&_order=ASC&_sort=hours&_start=0&q=nico
```

When I remove the `q` parameter, it works, but how do I do it automatically?

```typescript
// in src/App.tsx
import { Admin, Resource, ListGuesser } from "react-admin";
import jsonServerProvider from "ra-data-json-server";

const dataProvider = jsonServerProvider("https://jsonplaceholder.typicode.com");

const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="users" list={ListGuesser} />
    </Admin>
);
export default App;
```

**Environment**

* React-admin version: 4.9.4
* React version: 18.2.0
* Browser: 111.0.5563.147

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by RetherSzu** [comment]
`we use the GitHub issues for bugs and feature requests only.` So it's not a bug if the react admin tutorial doesn't work?

**Comment by RetherSzu** [comment]
I just solved my problem by changing my browser, i was on opera
