### ISSUE TITLE
CloneButton fields and target props

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8930]
**Describe the solution you'd like**
It could be nice to have some extra customisation props on `<CloneButton>`.

`fields` or similar to provide a whitelist of which fields should be copied over.

`target` or similar to specify a different resource to copy the fields over to.

**Comment by slax57** [comment]
Hi, and thank you for your suggestion.

Since the `CloneButton` is actually a very simple component, I think there would be little added value to implement these new props, as opposed to simply make your own component.

If there is feedback from the community showing that there is a demand for such a feature, I might revise my answer, but so far I'm not in favor of adding this enhancement.

@fzaninotto @djhi did you have this use-case in the past?

**Comment by fzaninotto** [comment]
I agree with @slax57, I don't see a big added value in making a complex component for such a common need.
