### ISSUE TITLE
floating create button does not behave the same across browsers with wide data tables

### ISSUE THREAD

**Issue by dkocich** [marmelab/react-admin#9038]
**What you were expecting:**

- I use desktop datagrid / table which is very wide, I expect the same behaviour across mobile browsers but in the list view. I expect that the create button should stick to the bottom right corner (of the initial mobile zoom level) on both mobile operating systems and should float on top of the page content (or should less likely be away in the bottom - same behaviour across browsers). We have 70+ wide tables and I would like to know if there should be fix for that so it does not confuse users or it is preferred bypass this by adding lightweight mobile variant with less data and card view to all sections...

**What happened instead:**

- on android chrome, pixel 7 pro mobile and some other phones, the creation button first appears correctly while rendering but then the button is moved outside of view and is in the far away bottom right corner and user has to swipe far to find it 

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

I have example https://stackblitz.com/edit/github-xtcjre-zkgvtj?file=README.md / https://github.com/dkocich/github-xtcjre-zkgvtj where I removed mobile variant from PostList.tsx and deployed it to netlify so you can check on the android mobile phone yourself
https://main--loquacious-medovik-e8a6e2.netlify.app/#/posts

**Comment by dkocich** [comment]
android phone - i zommed out of initial page zoom to see the page overview with the button on the bottom right; with zoom locked, i would have to swipe there to search for the button somewhere in the white area
![Screenshot_20230621-175945](https://github.com/marmelab/react-admin/assets/6165660/414b9e0f-9a76-4383-b866-1159cdfa1d39)

**Comment by slax57** [comment]
Thanks for opening this issue.

I'm not sure how to qualify this.
From what I understand, the issue here is that the Datagrid is too wide and forces the main container to have an horizontal scrollbar, which it should not in most cases.
This won't happen when using an UI that complies better with mobile vertical displays, like a SimpleList.

IMO, the way to fix this would rather be to change the ListView to have a fixed width, and make its content scroll, instead of having the main container (the Layout) scroll.
For instance you could wrap your Datagrid inside a Box with a fixed width.

But I'm not sure if this is something we should, and can, fix on our side.

@fzaninotto @djhi what do you think.

**Comment by fzaninotto** [comment]
I agree, we shouldn't handle issues in mobile layouts that aren't optimized for mobile.
