### ISSUE TITLE
String error messages are not translated when using global validation

### ISSUE THREAD

**Issue by jm-masteos** [marmelab/react-admin#9084]
**What you were expecting:**

When rendering InputHelperText with props: 
```
{
error: 'my.translation.key'
touched: true
}
```
Then error message should be translated

**What happened instead:**

They are not translated (because translate() is not called in the component InputHelperText)

**Steps to reproduce:**

Use yupResolver(<schema>) as resolver in a Form component. Error message displayed in the InputHelperText should be translated, but they are not. Instead the translation key is displayed.

In the sandbox below: 
1 - In the form fill the field 'body' and let field 'post' empty. 
2 - Validate the form
3 - The error displayed in the helper text is not translated (the same key is translated and displayed juste above the form)

**Related code:**

https://stackblitz.com/edit/github-jywgwp?file=src%2Findex.tsx

**Other information:**
**Solution**
change the following in 'packages/ra-ui-materialui/src/input/InputHelperText.tsx' line 14

Change
```
    if (touched && error) {
        if ((error as ValidationErrorMessageWithArgs).message) {
            return <ValidationError error={error} />;
        }
        return <>{error}</>;
    }
```

Into
```
    if (touched && error) {
        if ((error as ValidationErrorMessageWithArgs).message) {
            return <ValidationError error={error} />;
        }
        return <>{translate(error)}</>;
    }
```

**Environment**

* React-admin version: 4.12
* Last version that did not exhibit the issue (if applicable): was working on 4.4 
* React version: 18.2
* Browser: all
* Stack trace (in case of a JS error): no error

**Comment by fzaninotto** [comment]
I'm not sure this is a bug. React-admin doesn't do the translation in InputHelperText, it does the translation before that.

For instance, when using per-input `validate`, react-admin translates error messages in `useInput`:

https://github.com/marmelab/react-admin/blob/de8fbaa3285714aab914e0e76cc369c09a817d3c/packages/ra-core/src/form/useInput.ts#L71-L78

There may be a problem with the form `validate` function, and server-side errors, but you'd have to build up a reproduction to prove it. 

When passing a `resolver` directly to the Form, we currently don't translate error messages by default, and I'm not sure we should. In my opinion, resolvers are a low level form API and we shouldn't interfere with it. 

In any case, when you pass an `error` prop to `InputHelperText`, it should already be translated. 

I'm changing the label of this issue to "needs more info" since I'd like a reproduction not of a `resolver`, but of a form `validate` or a server-side submission error.

**Comment by jm-masteos** [comment]
Hi @fzaninotto,

Please let me question this  :

> "In any case, when you pass an error prop to InputHelperText, it should already be translated."

As we see in the folloing code from ra-ui-materialui master 



[```typescript
export const InputHelperText = (props: InputHelperTextProps) => {
    const { helperText, touched, error } = props;
    const translate = useTranslate();

    if (touched && error) {
        if ((error as ValidationErrorMessageWithArgs).message) {
            return <ValidationError error={error} />;
        }
        return <>{error}</>;
    }

    if (helperText === false) {
        return null;
    }

    if (isValidElement(helperText)) {
        return helperText;
    }

    if (typeof helperText === 'string') {
        return <>{translate(helperText, { _: helperText })}</>;
    }
```](https://github.com/marmelab/react-admin/blob/de8fbaa3285714aab914e0e76cc369c09a817d3c/packages/ra-ui-materialui/src/input/InputHelperText.tsx#L10-L39)

**Comment by fzaninotto** [comment]
You're right, that's a regression. Thanks for the investigation!

Changing back to 'bug' label.
