### ISSUE TITLE
dataProvider() not working as expected 

### ISSUE THREAD

**Issue by AbsorbingInfo** [marmelab/react-admin#9093]
**What you were expecting:**

Instead of fetching get request from ' http://localhost:4000/service' it is redirecting my page to 'currentUrl/service'. can any one explain me what am i doing oncorrectly here?

**What happened instead:**

**Steps to reproduce:**

**Related code:**

```import { Admin, Resource } from 'react-admin';
import simpleRestProvider from 'ra-data-simple-rest';
import { ServiceList } from './AdminService';

export const AdminUsers = () => {
    const dataProvider=simpleRestProvider('http://localhost:4000');
  return (
    <Admin dataProvider={dataProvider}>
        <Resource name="service" list={ServiceList} />
    </Admin>
  )
}
``` 

* Preferably, a sandbox forked from 
  - https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)
  - https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple (v3)
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
