### ISSUE TITLE
How to initially hide some of these column when the list rendered

### ISSUE THREAD

**Issue by tauqeer-trailfive** [marmelab/react-admin#9214]
![image](https://github.com/marmelab/react-admin/assets/108520807/a26003a3-bcc6-4fa8-a43e-ea9493b3985f)

Is there any props to `List` or `DatagridConfigurable` component to hide some these columns of list and user can enable them according to their needs.

Here is the code that is use to show the list

```
<List
      filters={isSmall ? userFilters : undefined}
      sort={{ field: "createdAt", order: "DESC" }}
      perPage={10}
      aside={<InstrumentListAside />}
      actions={<PostListActions />}
    >
      {isXsmall ? (
        <MobileGrid />
      ) : (
        <DatagridConfigurable
          sx={{
            "& .column-groups": {
              md: { display: "none" },
              lg: { display: "table-cell" },
            },
          }}
        >
          <InstrumentLinkField />
          <TextField
            source="name"
            label="resources.musicalInstruments.fields.name"
          />
          <NumberField
            source="rank"
            label="resources.musicalInstruments.fields.Rank"
          />
          <DateField source="createdAt" label="Created At" showTime />
        </DatagridConfigurable>
      )}
    </List>
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
