### ISSUE TITLE
Set NumberInput min/max from validate

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#9227]
**Is your feature request related to a problem? Please describe.**
Currently, we can set min/max on NumberInput, and also validate with minValue/maxValue. Semantically, these indicate the same thing and there's no real reason you would want to set them differently.

**Describe the solution you'd like**
So, would it be possible to automatically set min/max when validate is already set? This would save us needing to special-case NumberInput to add these props in.

I'm not familiar with the implementation, so I realise there may be some technical limitation that makes it infeasible.

**Comment by slax57** [comment]
Thank you for your suggestion.

I'm personally not in favor of doing this, because then the native browser validation would take precedence, and hence display error with a different UI and different messages (even, possibly not translated the same way or with the same locale) than the one set in react-admin.

Hence this would lead to UI inconsistencies and could disturb users.

I think it's better to leave the choice to the developer.

@fzaninotto @djhi wdyt?

**Comment by fzaninotto** [comment]
I agree with @slax57, we won't do this in the core. In addition, you can always write your own NumberInput on top of react-admin's to do that in user land. So I'm closing this issue.
