### ISSUE TITLE
I need defaultSelection parameter to be added useRecordSelection hook

### ISSUE THREAD

**Issue by mtztkt** [marmelab/react-admin#9257]
**Is your feature request related to a problem? Please describe.**
I use useRecordSelection hook in my Datagrid component for managing selection. But i need to receive defaultSelection of grid and set. If this hook takes this argument optionally we can display defaultSelected elements

**Describe the solution you'd like**
<img width="1028" alt="image" src="https://github.com/marmelab/react-admin/assets/13540684/9953fb67-6301-49cb-8795-0ce85a3edd16">

**Comment by slax57** [comment]
Thank you for your suggestion. However I'm not sure I fully understand your use case.

Are calling `useRecordSelection` in a custom component? If so, where does the `defaultSelection` come from? Can't you instead call `select()` to set the selected ids?

If not, how do you intend to pass the `defaultSelection` to the component calling `useRecordSelection`?

In both cases, it would help to have a complete example showing what you are trying to achieve, so we can confirm this is the right way to do it.
Thanks.

**Comment by slax57** [comment]
It is still unclear to me why you need a custom Datagrid at all.

Is it to support the `defaultSelectedIds` prop? If so, where does this prop come from and why do you need it?
Or is it for another reason?

Also, it seems to me that the `toggleRecord` fn could be greatly simplified by using `toggle` provided by `useRecordSelection`.

Lastly, it would help to have a text version of the code, because the screenshot is cropped and I cannot see all props that are declared in `AuDataGrid`.

**Comment by fzaninotto** [comment]
No news for some time, closing.
