### ISSUE TITLE
https://marmelab.com/react-admin/doc/4.1/ToggleThemeButton.html

### ISSUE THREAD

**Issue by neps-in** [marmelab/react-admin#9287]
https://marmelab.com/react-admin/doc/4.1/ToggleThemeButton.html

This is NOT Found - broken link 

Pls fix

**Comment by fzaninotto** [comment]
The correct link is https://marmelab.com/react-admin/ToggleThemeButton.html

Could you tell us where you got this link from? 

We've removed the doc for older versions from our [documentation site](https://marmelab.com/react-admin/documentation.html), because keeping too many versions slows down the publication of doc fixes. Also, the deployment of the doc site often fails because the site is too big (we're using gh-pages). We cannot keep more than 10 past minor versions, which is already a lot. 

If you want to find the doc for older versions, you can still browse the react-admin repo at a particular tag (because the Markdown doc files are also versioned with the code). For instance, for react-admin 4.1: https://github.com/marmelab/react-admin/tree/v4.1.4/docs
