### ISSUE TITLE
`useUpdateMany` does not update cache with returned data in pessimistic update mode

### ISSUE THREAD

**Issue by jclangst** [marmelab/react-admin#9321]
**What you were expecting:**

`useUpdateMany` should match the behavior of `useUpdate` when using `mutationMode` `"pessimistic"`. In particular, it should update the cache with the _returned_ data, not the _calltime_ data.

Note the difference between `useUpdate` [here](https://github.com/marmelab/react-admin/blob/98ae9a4952117377fffb1208a892b320bb6cbf23/packages/ra-core/src/dataProvider/useUpdate.ts#L244) and `useUpdateMany` [here](https://github.com/marmelab/react-admin/blob/98ae9a4952117377fffb1208a892b320bb6cbf23/packages/ra-core/src/dataProvider/useUpdateMany.ts#L254C26-L254C26).

**What happened instead:**

`useUpdateMany` updates the cache with the `callTimeData` instead of the data actually returned from the API. This results in stale and/or incorrect data.

**Steps to reproduce:**

Use `useUpdateMany` and submit a data patch. Imagine your API server returns a computed field such as `updatedAt` on each resource indicating when updates are applied (in other words, this isn't sent in the request but is expected on the response). Notice that `updatedAt` does not get applied when using `useUpdateMany`, but does when using `useUpdate`.

**Other information:**

* React-admin version: `4.14.0`
* React version: `18.2.0`
* Browser: All

**Comment by slax57** [comment]
Hi, and thank you for this report.

As you can see in the [interface definitions for updateMany](https://marmelab.com/react-admin/DataProviderWriting.html#updatemany), `updateMany` only expects the updated ids as return value, not the full records.

Hence we cannot use the returned value to update the cache.

With the default settings for react-query, the full records should be refetched automatically when needed.
If this is still causing issues in your app, for instance because you use different settings, then you may need to invalidate the cache for the problematic queries manually with [`queryClient.invalidateQueries()`](https://tanstack.com/query/v3/docs/react/guides/query-invalidation).

Hope this helps.
