### ISSUE TITLE
Showing Label Text in Responsive on Buttons.

### ISSUE THREAD

**Issue by mustafasavul** [marmelab/react-admin#9366]
Greetings,
In react-admin, action buttons (MUI) take a text in the web view.
![image](https://github.com/marmelab/react-admin/assets/19707331/46057f03-c183-4b8d-9e97-054fe4c22b92)
In the mobile view, the text disappears and this text is removed from the DOM with JS.
![image](https://github.com/marmelab/react-admin/assets/19707331/731d5ad9-398b-4f09-9489-b5c6e8db138a)

I could not find props etc in the documentation about this. 
Is there a method to solve this without interfering with JS on mobile? i18 translate definition will be added here.

Mobile
![image](https://github.com/marmelab/react-admin/assets/19707331/0ab8ac26-84c8-48e1-a73d-52791b470d3b)

Web 
![image](https://github.com/marmelab/react-admin/assets/19707331/8972c3fc-1edc-4415-b5a2-a6d652986ef5)

Good works.

**Comment by adguernier** [comment]
Hello @mustafasavul, 

It's intended to hide the label on mobile to save space, and there are no props to change this behavior.

If you want to change this, you must create your own button according to your needs. You can take inspiration from the [`<ExportButton>` component](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/ExportButton.tsx) and from the [`<Button>` component](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/Button.tsx).

Since we won't fix it, I am closing this issue. Thanks.
