### ISSUE TITLE
OneToMany property : EditGuesser, ReferenceArrayInput and CheckboxGroupInput

### ISSUE THREAD

**Issue by ekergreis** [marmelab/react-admin#9485]
Hello,

I want to use a CheckboxGroupInput to modify a OneToMany property (account). 
I have code that works with an ArrayInput and many list, but I don't find it practical and would prefer to use checkboxes. 
I managed to display the list of checkboxes but the items are not pre-selected in EditGuesser.

Here is my code:
```
        <EditGuesser transform={AggregationTransform} actions={<EditActions />}>
            <ArrayInput source="account" label="Comptes">
                <SimpleFormIterator inline disableReordering fullWidth>
                    <ReferenceInput source="@id" reference="accounts">
                        <SelectInput optionText="name" fullWidth label="Compte"/>
                    </ReferenceInput>
                </SimpleFormIterator>
            </ArrayInput>

            <ReferenceArrayInput source="account.id" reference="accounts">
                <CheckboxGroupInput source="account.@id" label="Comptes" row={false} />
            </ReferenceArrayInput>
        </EditGuesser>
```

Thanks for your help

Regards

**Comment by ekergreis** [comment]
**What you were expecting:**
I want to use a CheckboxGroupInput to modify a OneToMany property (account).

**What happened instead:**
I managed to display the list of checkboxes but the items are not pre-selected in EditGuesser.

**Steps to reproduce:**
Use my code with a relation to collection accounts in my API : 

```
{
	"@context": "\/contexts\/Aggregation",
	"@id": "\/aggregations",
	"@type": "hydra:Collection",
	"hydra:totalItems": 1,
	"hydra:member": [
		{
			"@id": "\/aggregations\/1",
			"@type": "Aggregation",
			"id": 1,
			"name": "Veniam quisquam dolorem qui ea inventore.",
			"account": [
				{
					"@id": "\/accounts\/4",
					"@type": "Account",
					"id": 4,
					"bank": "\/banks\/2",
					"name": "Repudiandae est delectus ullam laudantium."
				},
				{
					"@id": "\/accounts\/2",
					"@type": "Account",
					"id": 2,
					"bank": "\/banks\/2",
					"name": "Veniam quisquam dolorem qui ea inventore."
				}
			]
		}
	]
}
```
Accounts api return : 
```
{
	"@context": "\/contexts\/Account",
	"@id": "\/accounts",
	"@type": "hydra:Collection",
	"hydra:totalItems": 2,
	"hydra:member": [
		{
			"@id": "\/accounts\/2",
			"@type": "Account",
			"id": 2,
			"bank": {
				"@id": "\/banks\/2",
				"@type": "Bank",
				"name": "Bank 2"
			},
			"name": "Veniam quisquam dolorem qui ea inventore.",
			"officialLabel": "Facilis enim repellat quae et maiores sint dicta.",
			"position": 4,
			"history": true
		},
		{
			"@id": "\/accounts\/4",
			"@type": "Account",
			"id": 4,
			"bank": {
				"@id": "\/banks\/2",
				"@type": "Bank",
				"name": "Bank 2"
			},
			"name": "Repudiandae est delectus ullam laudantium.",
			"officialLabel": "Aspernatur voluptatem repudiandae ullam incidunt.",
			"position": 97,
			"history": true
		}
	],
	"hydra:view": {
		"@id": "\/accounts?history=true",
		"@type": "hydra:PartialCollectionView"
	},
	"hydra:search": {
		"@type": "hydra:IriTemplate",
		"hydra:template": "\/accounts{?history}",
		"hydra:variableRepresentation": "BasicRepresentation",
		"hydra:mapping": [
			{
				"@type": "IriTemplateMapping",
				"variable": "history",
				"property": "history",
				"required": false
			}
		]
	}
}
```

**Related code:**
```
<EditGuesser transform={AggregationTransform} actions={<EditActions />}>
            <ArrayInput source="account" label="Comptes">
                <SimpleFormIterator inline disableReordering fullWidth>
                    <ReferenceInput source="@id" reference="accounts">
                        <SelectInput optionText="name" fullWidth label="Compte"/>
                    </ReferenceInput>
                </SimpleFormIterator>
            </ArrayInput>

            <ReferenceArrayInput source="account.id" reference="accounts">
                <CheckboxGroupInput source="account.@id" label="Comptes" row={false} />
            </ReferenceArrayInput>
</EditGuesser>
```
package.json react-admin version : 4.16.1 
```
{
  "name": "react-fin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@api-platform/admin": "^3.4.4",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^29.5.6",
    "@types/node": "^20.8.9",
    "@types/react": "^18.2.33",
    "@types/react-dom": "^18.2.14",
    "echarts": "^5.4.3",
    "echarts-for-react": "^3.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",
    "typescript": "^5.3.2",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by slax57** [comment]
Hi @ekergreis 

Thank you for providing this additional information.

However, it seems to me that your request is actually a support request and not a bug report (nor a feature request).

As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

Additionally, it seems that you are using Api Platform. You may also want to look for help in their repository: https://github.com/api-platform/api-platform

**Comment by ekergreis** [comment]
Thank you for the response.
It is indeed a support request; I just created a ticket on Stack Overflow.
I apologize for not noticing the mention on GitHub under 'Support question.

**Comment by slax57** [comment]
No worries. Thanks! :slightly_smiling_face:
