### ISSUE TITLE
Pin react-admin ra-* dependencies

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#9658]
**What you were expecting:**
That when I pin react-admin to a specific version it will only use the code in that release:
```
  "dependencies": {
    "react-admin": "4.16.7"
  }
```

**What happened instead:**
Because the dependencies on the subpackages are written as `"^4.16.7"`, it actually ends up using all the code from the latest release (given that the react-admin package itself contains almost no code and hasn't been changed in months).

**Proposed Solution:**
Change dependencies from `"^4.16.7"` to `"4.16.7"`. I see no reason someone would want to use a specific version of react-admin while using a newer version of one of the subpackages. Surely it makes more sense to ensure that all react-admin packages being used together are from the same release?

**Alternative:**
If this isn't accepted, then I'll have to manually add every subpackage into resolutions (and hope you don't add new ones in future), and then figure out how to do a grouped update in Dependabot to have them all upgraded together as one release.

**Comment by fzaninotto** [comment]
Thanks for your detailed suggestion.

Pinning dependencies to a specific version may solve your problem, but it creates others. Some third-party packages may have incompatible dependencies on the same subpackages, and this leads to duplicated packages. In a React application, this creates hard to debug problems (mostly due to React context). We've suffered from that in the past, in react-admin and in other open-source packages we maintain. 

We've already discussed hardening the dependencies from `^` to `~` (see #8952). As your suggestion is related, please continue the discussion on that other issue.

**Comment by Dreamsorcerer** [comment]
Right, I guess if you have 3rd-party components etc. that depend on subpackages, it could be an issue.

This is the solution I'll use then: https://github.com/aio-libs/aiohttp-admin/pull/860/files
