### ISSUE TITLE
Can not disable ra.action.clear_input_value in SelectInput

### ISSUE THREAD

**Issue by SilverHof** [marmelab/react-admin#9668]
I have a problem with https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/SelectInput.tsx

I want to disable this field
![image](https://github.com/marmelab/react-admin/assets/63652935/851114e1-b32d-44bd-bd83-32b046a17cc3)
How can I do it?

Case 1: `<SelectInput validate={....} />` 
Problem 1 - I dont want to validate this field

Case 2: `<SelectInput isRequired />` 
Problem - A star icon appears next to the label
![image](https://github.com/marmelab/react-admin/assets/63652935/81021f01-eb6f-4015-8199-92c2929dddc1)

The problem is here
![image](https://github.com/marmelab/react-admin/assets/63652935/dbf0d981-081f-40e6-b479-c022da42d124)

I think isRequired prop shouldn't be here, its like clearInputValue prop

**Comment by adguernier** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
