### ISSUE TITLE
useWatch on fields with required in edit is not working

### ISSUE THREAD

**Issue by gabifuse** [marmelab/react-admin#9683]
Hello!
I have 2 simple input fields that i want to allow only 1 of them, so if the first has value typed into it the second one should be disabled, and if the second one has value in it the first one should be disabled.

Ive tried using a few different methods including <FormDataConsumer> etc.

After investigating a little bit, i understood the best way to approach this is using useWatch, so i have the following code:

```
import { isNil } from 'lodash-es';
import * as React from 'react';
import { useEffect } from 'react';
import { Edit, SimpleForm, TextInput } from 'react-admin';
import { useWatch } from 'react-hook-form';

export const InnerTest = (): JSX.Element => {
	const data = useWatch({ name: ['dmsInsuranceType', 'dmsAccessoriesCode'] });

	useEffect(() => {
		console.log('data', data);
	}, [data]);

	return (
		<>
			<TextInput source="dmsInsuranceType" label="test1" required={isNil(data[1])} disabled={!isNil(data[1])} />
			<TextInput source="dmsAccessoriesCode" label="test2" required={isNil(data[0])} disabled={!isNil(data[0])} />
		</>
	);
};

export const TestEdit = (): JSX.Element => {
	return (
		<Edit>
			<SimpleForm>
				<InnerTest />
			</SimpleForm>
		</Edit>
	);
};
```

I have the same under Create where it works perfectly as expected, under the <Edit> for what ever reason if you load the entity with a value in the first field, remove it, type something to second field and remove focus from the field, the save button becomes disabled as if under the hood it thinks like nothing in the entity changed so it won't allow to submit the form.

FYI if i remove the disabled prop form either one of the TextInput it suddenly does work.

What is the correct approach here and what am i missing?

Thanks in advance,
Gabi.

**Comment by Nela62** [comment]
Hi Gabi, 

You are posting in the react-admin repository, not the react-hook-form one.

**Comment by adguernier** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
