### ISSUE TITLE
The "Blog" demo app doesn't work

### ISSUE THREAD

**Issue by firasrg** [marmelab/react-admin#9892]
I'm trying to see [the Blog demo](https://marmelab.com/react-admin/Demos.html#blog).

**What you were expecting:**
I'm expecting that the demo works fine as it's made by you.

**What happened instead:**
Blank page at start :
![image](https://github.com/marmelab/react-admin/assets/37019463/4813dcd8-f327-4537-a8fc-15bf138ba29c)

**Steps to reproduce:**
none

**Comment by fzaninotto** [comment]
I can't reproduce the problem: The demo does start (although after a good 30s). 

Can you please add mode details about your browser and OS?

**Comment by firasrg** [comment]
Thanks fot reply @fzaninotto. It seems the app in side doesn't work even in more than that delay seconds! However, even 30 seconds is too much. ive tried to reach it on stackblitz from Windows and smartphone and got same result

**Comment by fzaninotto** [comment]
Does https://codesandbox.io/p/devbox/github/marmelab/react-admin/tree/master/examples/simple work?

**Comment by firasrg** [comment]
oh it does ! in that case i'd suggest to put this working example instead in docs :)

**Comment by fzaninotto** [comment]
I suspect there has been a regression in Stackblitz lately, it didn't use to be this slow. 

We prefer Stackblitz over CodSandbox because CodeSandbox now drastically restricts the number of sandboxes you can make with a free plan. So many developers can't create a repro without paying, which is something we want to avoid.
