### ISSUE TITLE
Custom Save Button In TopToolbar inside Edit component

### ISSUE THREAD

**Issue by szabolcsveer** [marmelab/react-admin#9907]
e primarily use GitHub as an issue tracker; for usage and support questions, please use StackOverflow(https://stackoverflow.com/questions/tagged/react-admin using the tag `react-admin`) or the react-admin Discord Server(https://discord.gg/GeZF9sqh3N). Thanks! 😁.

Hi @fzaninotto 
I want to create a custom save button inside the TopToolbar component, but no matter how I approach the situation it just doesn't work, regardless of the usage of useSaveContext() save method explicitly on a Button element.

Can you point me to the right direction ?

here is a snippet:

```typescript
import SyncIcon from '@mui/icons-material/Sync';
import { IconButton } from '@mui/material';
import {
  Button,
  Edit,
  ExportButton,
  RadioButtonGroupInput,
  SimpleForm,
  TextInput,
  TopToolbar,
  useEditContext,
  useEditController,
  useSaveContext,
} from 'react-admin';
import styles from './CustomerEdit.module.scss';

const TopSave = () => {
  const { record, save } = useEditController();
  console.log('record', record);
  const saveHandler = async () => {
    if (save) {
      await save(record);
    }
  };

  return <Button variant="outlined" label="Save" onClick={saveHandler} />;
};

const CustomerEditActions = () => (
  <TopToolbar>
    <ExportButton variant="text" />
    <TopSave />
    <IconButton aria-label="Sync data">
      <SyncIcon color="primary" />
    </IconButton>
  </TopToolbar>
);

function CustomerEdit() {
  return (
    <Edit
      sx={{
        '& .RaEdit-card': {
          border: 'none',
          display: 'flex',
          justifyContent: 'center',
        },
      }}
      actions={<CustomerEditActions />}
    >
      <SimpleForm>
        <div className={styles.formContainer}>
          <div className={styles.title}>
            <h2>Person</h2>
            <RadioButtonGroupInput
              source="contactSalutation"
              choices={[
                { id: 'HERR', name: 'Herr' },
                { id: 'FRAU', name: 'Frau' },
              ]}
            />
          </div>
          <div className={styles.contactsGrid}>
            <TextInput source="navisionId" label="Kundennummer" size="medium" />
            <TextInput source="contactFirstName" label="Vorname" size="medium" />
            <TextInput source="nameAddition" label="Namenzusatz" size="medium" />
            <TextInput source="contactLastName" label="Nachname" size="medium" />
            <TextInput source="companyName" label="Firmen Name" size="medium" />
          </div>
          <div className={styles.title}>
            <h2>Kontakt</h2>
          </div>
          <div className={styles.contactsGrid}>
            <TextInput source="contactTelephone" label="telefonnummer" size="medium" />
            <TextInput source="invoiceEmail" label="Rechnungs E-Mail" size="medium" />
            <TextInput source="street" label="Adresse" size="medium" />
            <TextInput source="addressAddition" label="Adressezusatz" size="medium" />
            <TextInput source="zip" label="PLZ" size="medium" />
            <TextInput source="city" label="Stadt" size="medium" />
          </div>
        </div>
      </SimpleForm>
    </Edit>
  );
}

export default CustomerEdit;

```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by szabolcsveer** [comment]
Okay, I posted it on Stackoverflow
Answers are appreciated
